<?php
$title = "Supercomputing 2016 PMIx BoF slides";
$overview = "Slides from the PMIx BOF at SC'16";

$authors = "Ralph Castain, David Soltn";

$abstract = "Slides from the PMIx Community Meeting at SC'16.";

$presented = "<a href=\"http://sc16.supercomputing.org/\">" . "SC'16</a>,
November, 2016, in Salt Lake City, UT, USA";

$files[] = "PMIxBoF-2016.pdf";

$month = 11;
$day = 19;
$year = 2016;

$bibtex = "";
