<?php 
$title = "Open MPI: Goals, Concept, and Design of a Next Generation MPI Implementation";
$overview = "Presents an overview of the Open MPI project";

$authors = "Edgar Gabriel, Graham E. Fagg, George Bosilca, Thara Angskun,
Jack J. Dongarra, Jeffrey M. Squyres, Vishal Sahay, Prabhanjan Kambadur,
Brian Barrett, Andrew Lumsdaine, Ralph H. Castain, David J. Daniel, 
Richard L. Graham, Timothy S. Woodall";

$abstract = "A large number of MPI implementations are currently
available, each of which emphasize different aspects of
high-performance computing or are intended to solve a specific
research problem.  The result is a myriad of incompatible MPI
implementations, all of which require separate installation, and the
combination of which present significant logistical challenges for end
users.  Building upon prior research, and influenced by experience
gained from the code bases of the LAM/MPI, LA-MPI, and FT-MPI
projects, <em>Open MPI</em> is an all-new, production-quality MPI-2
implementation that is fundamentally centered around component
concepts.  Open MPI provides a unique combination of novel features
previously unavailable in an open-source, production-quality
implementation of MPI.  Its component architecture provides both a
stable platform for third-party research as well as enabling the
run-time composition of independent software add-ons.  This paper
presents a high-level overview the goals, design, and implementation
of Open MPI.";

$presented = "Euro PVM/MPI 2004, September, 2004, in Budapest, Hungary.";

$files[] = "euro-pvmmpi-2004-overview.ps";
$files[] = "euro-pvmmpi-2004-overview.pdf";

$month = 9;
$day = 20;
$year = 2004;

$bibtex = "@InProceedings{gabriel04:_open_mpi,
  author       = {Edgar Gabriel and Graham E. Fagg and George Bosilca
                  and Thara Angskun and Jack J. Dongarra and Jeffrey
                  M. Squyres and Vishal Sahay and Prabhanjan Kambadur
                  and Brian Barrett and Andrew Lumsdaine and Ralph
                  H. Castain and David J. Daniel and Richard L. Graham
                  and Timothy S. Woodall },
  title        = {Open {MPI}: Goals, Concept, and Design of a Next
                  Generation {MPI} Implementation},
  booktitle    = {Proceedings, 11th European PVM/MPI Users' Group
                  Meeting},
  year         = 2004,
  address      = {Budapest, Hungary},
  pages        = {97--104},
  month        = {September}
}";
