<?php
$title = "Supercomputing 2021 slides";
$overview = "Slides from the Open MPI State of the Union BOF at SC'21";

$authors = "George Bosilca, Jeff Squyres, Josh Hursey, Geoff Paulsen, Austen Lauria, Tomislav Janjusic, Howard Pritchard, Takafumi Nose";

$abstract = "Slides from the Open MPI State of the Union XIV Community
Meeting at SC'21.";

$presented = "<a href=\"http://sc21.supercomputing.org/\">" . "SC'21</a>,
November 16, 2021, via Zoom";

$files[] = "Open-MPI-SC21-BOF.pdf";

$month = 11;
$day = 16;
$year = 2021;

$bibtex = "";
