<?php
$topdir = "../../../..";
# Note that we must use the PHP "$$" indirection to assign to the
# "title" variable, because if we list "$ title" (without the space)
# in this file, Doxygen will replace it with a string title.
$ver = basename(getcwd());
$thwarting_doxygen_preprocessor = "title";
$$thwarting_doxygen_preprocessor = "Portable Hardware Locality (hwloc) Documentation: $ver";
$header_include_file = "$topdir/projects/hwloc/doc/$ver/www.open-mpi.org-css.inc";
include_once("$topdir/projects/hwloc/nav.inc");
include_once("$topdir/includes/header.inc");
include_once("$topdir/includes/code.inc");
?>
<!-- Generated by Doxygen 1.9.8 -->
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:d3d9a9a6595521f9666a5e94cc830dab83b65699&amp;dn=expat.txt MIT */
$(function() {
  initMenu('',false,false,'search.php','Search');
});
/* @license-end */
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-attribs">Data Fields</a>  </div>
  <div class="headertitle"><div class="title">hwloc_topology_misc_support Struct Reference<div class="ingroups"><a class="el" href="a00149.php">Topology Detection Configuration and Query</a></div></div></div>
</div><!--header-->
<div class="contents">

<p><code>#include &lt;<a class="el" href="a00071_source.php">hwloc.h</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a id="pub-attribs" name="pub-attribs"></a>
Data Fields</h2></td></tr>
<tr class="memitem:adf54a6dbe8e9dd5033dfe9c93df726c4" id="r_adf54a6dbe8e9dd5033dfe9c93df726c4"><td class="memItemLeft" align="right" valign="top">unsigned char&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="a00261.php#adf54a6dbe8e9dd5033dfe9c93df726c4">imported_support</a></td></tr>
<tr class="separator:adf54a6dbe8e9dd5033dfe9c93df726c4"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Flags describing miscellaneous features. </p>
</div><h2 class="groupheader">Field Documentation</h2>
<a id="adf54a6dbe8e9dd5033dfe9c93df726c4" name="adf54a6dbe8e9dd5033dfe9c93df726c4"></a>
<h2 class="memtitle"><span class="permalink"><a href="#adf54a6dbe8e9dd5033dfe9c93df726c4">&#9670;&#160;</a></span>imported_support</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">unsigned char hwloc_topology_misc_support::imported_support</td>
        </tr>
      </table>
</div><div class="memdoc">
<p>Support was imported when importing another topology, see <a class="el" href="a00149.php#ggada025d3ec20b4b420f8038d23d6e7bdead93e82b8668ee90e4f9354e201a2ed9c" title="Import support from the imported topology.">HWLOC_TOPOLOGY_FLAG_IMPORT_SUPPORT</a>. </p>

</div>
</div>
<hr/>The documentation for this struct was generated from the following file:<ul>
<li><a class="el" href="a00071_source.php">hwloc.h</a></li>
</ul>
</div><!-- contents -->
<?php
include_once("$topdir/includes/footer.inc");
