<? include("../../include/msg-header.inc"); ?>
<!-- received="Mon Aug 21 03:38:13 2006" -->
<!-- isoreceived="20060821073813" -->
<!-- sent="Mon, 21 Aug 2006 09:38:07 +0200" -->
<!-- isosent="20060821073807" -->
<!-- name="Ralf Wildenhues" -->
<!-- email="Ralf.Wildenhues_at_[hidden]" -->
<!-- subject="[OMPI devel] exit declaration in configure tests" -->
<!-- id="20060821073807.GD13341_at_iam.uni-bonn.de" -->
<!-- charset="us-ascii" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>From:</strong> Ralf Wildenhues (<em>Ralf.Wildenhues_at_[hidden]</em>)<br>
<strong>Date:</strong> 2006-08-21 03:38:07
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="1001.php">Adrian Knoth: "Re: [OMPI devel] A few notes on IPv6 status"</a>
<li><strong>Previous message:</strong> <a href="0999.php">Ralf Wildenhues: "Re: [OMPI devel] OpenMPI not conforming with the C90 spec?"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="1002.php">George Bosilca: "Re: [OMPI devel] exit declaration in configure tests"</a>
<li><strong>Reply:</strong> <a href="1002.php">George Bosilca: "Re: [OMPI devel] exit declaration in configure tests"</a>
<li><strong>Reply:</strong> <a href="1008.php">Brian Barrett: "Re: [OMPI devel] exit declaration in configure tests"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Revision 11268 makes me curious:
<br>
<p>|    M /trunk/config/ompi_setup_cxx.m4
<br>
| 
<br>
| Reorder the C++ compiler discovery stages. Check first the compiler vendor
<br>
| before checking if we are able to compile the test program. This is required
<br>
| for windows as the C++ conftest.c file generated by configure cannot be
<br>
| compiled with the Microsoft cl.exe compiler (because of the exit function
<br>
| prototype). So if we detect a vendor equal to microsoft we will assume
<br>
| that the compiler is correctly installed (which is true on Windows most
<br>
| of the time anyway).
<br>
<p>I believe to have killed all problematic exit cases from the OpenMPI
<br>
configury some time ago.  Did I miss any, or did the remaining ones
<br>
come from some other package (so we can fix that one)?  Which Autoconf
<br>
version was used (2.60 should not use any exit declarations itself any
<br>
more)?
<br>
<p>Cheers,
<br>
Ralf
<br>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="1001.php">Adrian Knoth: "Re: [OMPI devel] A few notes on IPv6 status"</a>
<li><strong>Previous message:</strong> <a href="0999.php">Ralf Wildenhues: "Re: [OMPI devel] OpenMPI not conforming with the C90 spec?"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="1002.php">George Bosilca: "Re: [OMPI devel] exit declaration in configure tests"</a>
<li><strong>Reply:</strong> <a href="1002.php">George Bosilca: "Re: [OMPI devel] exit declaration in configure tests"</a>
<li><strong>Reply:</strong> <a href="1008.php">Brian Barrett: "Re: [OMPI devel] exit declaration in configure tests"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
