<?php
$topdir = "../../..";
$title = "shmem_int_cswap(3) man page (version 3.1.1)";
$meta_desc = "Open MPI v3.1.1 man page: shmem_int_cswap(3)";

include_once("$topdir/doc/nav.inc");
include_once("$topdir/includes/header.inc");
?>
<p> <a href="../">&laquo; Return to documentation listing</a></p>
    <!-- manual page source format generated by PolyglotMan v3.2, -->
<!-- available at http://polyglotman.sourceforge.net/ -->

<body bgcolor='white'>
<a href='#toc'>Table of Contents</a><p>

<h2><a name='sect0' href='#toc0'>Name</a></h2>

<p> <i><i>shmem_int_cswap</i>(3)</i>, <i><i>shmem_int4_cswap</i>(3)</i>, <i><i>shmem_int8_cswap</i>(3)</i>,
<i><i>shmem_long_cswap</i>(3)</i>, <i><i>shmem_longlong_cswap</i>(3)</i> - Performs an atomic conditional
swap to a remote data object
<h2><a name='sect1' href='#toc1'>Synopsis</a></h2>

<p> C or C++: <br>
<pre>#include &lt;mpp/shmem.h&gt;
int shmem_int_cswap(int *target, int cond, int value, int pe);
long shmem_long_cswap(long *target, long cond, long value,
  int pe);
long long shmem_longlong_cswap(longlong *target,
  longlong cond, longlong value, int pe);
</pre> Fortran: <br>
<pre>INCLUDE "mpp/shmem.fh"
INTEGER pe
INTEGER(KIND=4) SHMEM_INT4_CSWAP
ires = SHMEM_INT4_CSWAP(target, cond, value, pe)
INTEGER(KIND=8) SHMEM_INT8_CSWAP
ires = SHMEM_INT8_CSWAP(target, cond, value, pe)
</pre>
<h2><a name='sect2' href='#toc2'>Description</a></h2>

<p> The conditional swap routines conditionally update a target
data object on an arbitrary processing element (PE) and return the prior
contents of the data object in one atomic operation. <p>
The arguments are as
follows:
<dl>

<dt>target </dt>
<dd>The remotely accessible integer data object to be updated
on the remote PE. If you are using C/C++, the type of target should match
that implied in the SYNOPSIS section. If you are using the Fortran compiler,
it must be of type integer with an element size of 4 bytes for SHMEM_INT4_ADD
and 8 bytes for SHMEM_INT8_ADD. </dd>

<dt>value </dt>
<dd>The value to be atomically added to
target. If you are using C/C++, the type of value should match that implied
in the SYNOPSIS section. If you are using Fortran, it must be of type integer
with an element size of target. </dd>

<dt>pe </dt>
<dd>An integer that indicates the PE number
upon which target is to be updated. If you are using Fortran, it must be
a default integer value. </dd>

<dt>target </dt>
<dd>The remotely accessible integer data object
to be updated on the remote PE. If you are using C/C++, the data type of
target should match that implied in the SYNOPSIS section. If you are using
Fortran, it must be of the following type: <blockquote></dd>

<dt><b>SHMEM_INT4_CSWAP</b>: 4-byte integer
</dt>
<dd></dd>

<dt><b>SHMEM_INT8_CSWAP</b>: 8-byte integer </dt>
<dd></dd>
</dl>
</blockquote>
<blockquote><p>
</blockquote>

<dl>

<dt>cond </dt>
<dd>cond is compared to the remote target
value. If cond and the remote target are equal, then value is swapped into
the remote target. Otherwise, the remote target is unchanged. In either case,
the old value of the remote target is returned as the function return value.
cond must be of the same data type as target. </dd>

<dt>value </dt>
<dd>The value to be atomically
written to the remote PE. value must be the same data type as target. </dd>

<dt>pe
</dt>
<dd>An integer that indicates the PE number upon which target is to be updated.
If you are using Fortran, it must be a default integer value. </dd>
</dl>
<p>

<h2><a name='sect3' href='#toc3'>Notes</a></h2>

<p> The
term remotely accessible is defined in <i><i>intro_shmem</i>(3)</i>.
<h2><a name='sect4' href='#toc4'>Return Values</a></h2>

<p> The
contents that had been in the target data object on the remote PE prior
to the conditional swap.
<h2><a name='sect5' href='#toc5'>Examples</a></h2>

<p> The following call ensures that the first
PE to execute the conditional swap will successfully write its PE number
to race_winner on PE 0. <br>
<pre>main()
{
  static int race_winner = -1;
  int oldval;
  shmem_init();
  oldval = shmem_int_cswap(&amp;race_winner, -1, shmem_my_pe(), 0);
  if (oldval == -1)
    printf("pe %d was first\n",shmem_my_pe());
}
</pre>
<h2><a name='sect6' href='#toc6'>See Also</a></h2>

<p> <i><i>intro_shmem</i>(3)</i>, <i><i>shmem_cache</i>(3)</i>, <i><i>shmem_swap</i>(3)</i> <p>

<hr><p>
<a name='toc'><b>Table of Contents</b></a><p>
<ul>
<li><a name='toc0' href='#sect0'>Name</a></li>
<li><a name='toc1' href='#sect1'>Synopsis</a></li>
<li><a name='toc2' href='#sect2'>Description</a></li>
<li><a name='toc3' href='#sect3'>Notes</a></li>
<li><a name='toc4' href='#sect4'>Return Values</a></li>
<li><a name='toc5' href='#sect5'>Examples</a></li>
<li><a name='toc6' href='#sect6'>See Also</a></li>
</ul>


<p> <a href="../">&laquo; Return to documentation listing</a></p>
<?php
include_once("$topdir/includes/footer.inc");
