<?php
$topdir = "../../..";
$title = "shmem_float_fetch(3) man page (version 3.1.6)";
$meta_desc = "Open MPI v3.1.6 man page: shmem_float_fetch(3)";

include_once("$topdir/doc/nav.inc");
include_once("$topdir/includes/header.inc");
?>
<p> <a href="../">&laquo; Return to documentation listing</a></p>
   <!-- manual page source format generated by PolyglotMan v3.2, -->
<!-- available at http://polyglotman.sourceforge.net/ -->

<body bgcolor='white'>
<a href='#toc'>Table of Contents</a><p>

<h2><a name='sect0' href='#toc0'>Name</a></h2>

<p> <i><i>shmem_int4_fetch</i>(3)</i>, <i><i>shmem_int8_fetch</i>(3)</i>, <i><i>shmem_int_fetch</i>(3)</i>, <i><i>shmem_long_fetch</i>(3)</i>,
<i><i>shmem_longlong_fetch</i>(3)</i> <i><i>shmem_double_fetch</i>(3)</i> <i><i>shmem_float_fetch</i>(3)</i> - Atomically
fetches the value of a remote data object
<h2><a name='sect1' href='#toc1'>Synopsis</a></h2>

<p> C or C++: <br>
<pre>#include &lt;mpp/shmem.h&gt;
int shmem_int_fetch(int *target, int pe);
long shmem_long_fetch(long *target, int pe);
long long shmem_longlong_fetch(long long *target, int pe);
double shmem_double_fetch(long long *target, int pe);
float  shmem_float_fetch(float *target, int pe);
</pre> Fortran: <br>
<pre>INCLUDE "mpp/shmem.fh"
INTEGER pe
INTEGER(KIND=4) SHMEM_INT4_FETCH, ires, target
ires = SHMEM_INT4_FETCH(target, pe)
INTEGER(KIND=8) SHMEM_INT8_FETCH, ires, target
ires = SHMEM_INT8_FETCH(target, pe)
REAL(KIND=4) SHMEM_INT4_FETCH, ires, target
ires = SHMEM_REAL4_FETCH(target, pe)
REAL(KIND=8) SHMEM_INT8_FETCH, ires, target
ires = SHMEM_REAL8_FETCH(target, pe)
</pre>
<h2><a name='sect2' href='#toc2'>Description</a></h2>

<p> The shmem_fetch functions perform an atomic fetch operation.
They return the contents of the <b>target</b> as an atomic operation.
<p> <p>
The arguments
are as follows:
<dl>

<dt>target </dt>
<dd>The remotely accessible data object to be fetched
from the remote PE. </dd>

<dt>pe </dt>
<dd>An integer that indicates the PE number from which
<i>target</i> is to be fetched. If you are using Fortran, it must be a default
integer value. </dd>
</dl>
<p>

<p>
<h2><a name='sect3' href='#toc3'>Return Values</a></h2>
The contents at the <i>target</i> address on the remote
PE.  The data type of the return value is the same as the the type of the
remote data object.
<p>
<h2><a name='sect4' href='#toc4'>See Also</a></h2>

<p> <i><i>intro_shmem</i>(3)</i>  <p>

<hr><p>
<a name='toc'><b>Table of Contents</b></a><p>
<ul>
<li><a name='toc0' href='#sect0'>Name</a></li>
<li><a name='toc1' href='#sect1'>Synopsis</a></li>
<li><a name='toc2' href='#sect2'>Description</a></li>
<li><a name='toc3' href='#sect3'>Return Values</a></li>
<li><a name='toc4' href='#sect4'>See Also</a></li>
</ul>


<p> <a href="../">&laquo; Return to documentation listing</a></p>
<?php
include_once("$topdir/includes/footer.inc");
