<?
$subject_val = "[OMPI users] MPI_File_read+MPI_BOTTOM crash on NFS ?";
include("../../include/msg-header.inc");
?>
<!-- received="Tue Jun 14 11:42:20 2016" -->
<!-- isoreceived="20160614154220" -->
<!-- sent="Tue, 14 Jun 2016 17:42:17 +0200" -->
<!-- isosent="20160614154217" -->
<!-- name="Nicolas Joly" -->
<!-- email="njoly_at_[hidden]" -->
<!-- subject="[OMPI users] MPI_File_read+MPI_BOTTOM crash on NFS ?" -->
<!-- id="20160614154217.GA9342_at_issan.sis.pasteur.fr" -->
<!-- charset="us-ascii" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> [OMPI users] MPI_File_read+MPI_BOTTOM crash on NFS ?<br>
<strong>From:</strong> Nicolas Joly (<em>njoly_at_[hidden]</em>)<br>
<strong>Date:</strong> 2016-06-14 11:42:17
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="29435.php">Ralph Castain: "Re: [OMPI users] runtime error in orte/loop_spawn test using OMPI 1.10.2"</a>
<li><strong>Previous message:</strong> <a href="29433.php">Gilles Gouaillardet: "Re: [OMPI users] scatter/gather, tcp, 3 nodes, homogeneous, # RAM"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="29476.php">Vincent Huber: "Re: [OMPI users] MPI_File_read+MPI_BOTTOM crash on NFS ?"</a>
<li><strong>Reply:</strong> <a href="29476.php">Vincent Huber: "Re: [OMPI users] MPI_File_read+MPI_BOTTOM crash on NFS ?"</a>
<li><strong>Reply:</strong> <a href="29494.php">Gilles Gouaillardet: "Re: [OMPI users] MPI_File_read+MPI_BOTTOM crash on NFS ?"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Hi,
<br>
<p>At work, i do have some mpi codes that make use of custom datatypes to
<br>
call MPI_File_read with MPI_BOTTOM ... It mostly works, except when
<br>
the underlying filesystem is NFS where if crash with SIGSEGV.
<br>
<p>The attached sample (code + data) works just fine with 1.10.1 on my
<br>
NetBSD/amd64 workstation using the UFS romio backend, but crash if
<br>
switched to NFS :
<br>
<p>njoly_at_issan [~]&gt; mpirun --version
<br>
mpirun (Open MPI) 1.10.1
<br>
njoly_at_issan [~]&gt; mpicc -g -Wall -o sample sample.c
<br>
njoly_at_issan [~]&gt; mpirun -n 2 ./sample ufs:data.txt
<br>
rank1 ... 111111111133333333335555555555
<br>
rank0 ... 000000000022222222224444444444
<br>
njoly_at_issan [~]&gt; mpirun -n 2 ./sample nfs:data.txt
<br>
[issan:20563] *** Process received signal ***
<br>
[issan:08879] *** Process received signal ***
<br>
[issan:20563] Signal: Segmentation fault (11)
<br>
[issan:20563] Signal code: Address not mapped (1)
<br>
[issan:20563] Failing at address: 0xffffffffb1309240
<br>
[issan:08879] Signal: Segmentation fault (11)
<br>
[issan:08879] Signal code: Address not mapped (1)
<br>
[issan:08879] Failing at address: 0xffffffff881b0420
<br>
[issan:08879] [ 0] [issan:20563] [ 0] 0x7dafb14a52b0 &lt;__sigtramp_siginfo_2&gt; at /usr/lib/libc.so.12
<br>
[issan:20563] *** End of error message ***
<br>
0x78b9886a52b0 &lt;__sigtramp_siginfo_2&gt; at /usr/lib/libc.so.12
<br>
[issan:08879] *** End of error message ***
<br>
--------------------------------------------------------------------------
<br>
mpirun noticed that process rank 0 with PID 20563 on node issan exited on signal 11 (Segmentation fault).
<br>
--------------------------------------------------------------------------
<br>
njoly_at_issan [~]&gt; gdb sample sample.core
<br>
GNU gdb (GDB) 7.10.1
<br>
[...]
<br>
Core was generated by `sample'.
<br>
Program terminated with signal SIGSEGV, Segmentation fault.
<br>
#0  0x000078b98871971f in memcpy () from /usr/lib/libc.so.12
<br>
[Current thread is 1 (LWP 1)]
<br>
(gdb) bt
<br>
#0  0x000078b98871971f in memcpy () from /usr/lib/libc.so.12
<br>
#1  0x000078b974010edf in ADIOI_NFS_ReadStrided () from /usr/pkg/lib/openmpi/mca_io_romio.so
<br>
#2  0x000078b97400bacf in MPIOI_File_read () from /usr/pkg/lib/openmpi/mca_io_romio.so
<br>
#3  0x000078b97400bc72 in mca_io_romio_dist_MPI_File_read () from /usr/pkg/lib/openmpi/mca_io_romio.so
<br>
#4  0x000078b988e72b38 in PMPI_File_read () from /usr/pkg/lib/libmpi.so.12
<br>
#5  0x00000000004013a4 in main (argc=2, argv=0x7f7fff7b0f00) at sample.c:63
<br>
<p>Thanks.
<br>
<p><pre>
-- 
Nicolas Joly
Cluster &amp; Computing Group
Biology IT Center
Institut Pasteur, Paris.


</pre>
<hr>
<ul>
<li>text/plain attachment: <a href="http://www.open-mpi.org/community/lists/users/att-29434/sample.c">sample.c</a>
</ul>
<!-- attachment="sample.c" -->
<hr>
<ul>
<li>text/plain attachment: <a href="http://www.open-mpi.org/community/lists/users/att-29434/data.txt">data.txt</a>
</ul>
<!-- attachment="data.txt" -->
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="29435.php">Ralph Castain: "Re: [OMPI users] runtime error in orte/loop_spawn test using OMPI 1.10.2"</a>
<li><strong>Previous message:</strong> <a href="29433.php">Gilles Gouaillardet: "Re: [OMPI users] scatter/gather, tcp, 3 nodes, homogeneous, # RAM"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="29476.php">Vincent Huber: "Re: [OMPI users] MPI_File_read+MPI_BOTTOM crash on NFS ?"</a>
<li><strong>Reply:</strong> <a href="29476.php">Vincent Huber: "Re: [OMPI users] MPI_File_read+MPI_BOTTOM crash on NFS ?"</a>
<li><strong>Reply:</strong> <a href="29494.php">Gilles Gouaillardet: "Re: [OMPI users] MPI_File_read+MPI_BOTTOM crash on NFS ?"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
