<?
$topdir = "/l/osl/www/www.open-mpi.org";
$topurl = "../../../../..";
$title = "Open MPI Announcements Mailing List Archives";
$lam_section = "open-mpi-announce-mail";

include_once("$topdir/includes/nav.inc");

$this_dir = "lists";
$base = $topurl;
include_once("$topdir/community/lists/ompi.inc");
include_once("$topdir/community/lists/plpa.inc");

include_once("$topdir/includes/header.inc");
?>
