<? include("../../include/msg-header.inc"); ?>
<!-- received="Thu May 24 12:13:52 2007" -->
<!-- isoreceived="20070524161352" -->
<!-- sent="Thu, 24 May 2007 12:13:42 -0400" -->
<!-- isosent="20070524161342" -->
<!-- name="Jeff Squyres" -->
<!-- email="jsquyres_at_[hidden]" -->
<!-- subject="Re: [MTT users] Few trunk results this morning?" -->
<!-- id="62DBBB03-91FB-4DD4-837A-ECAB6CB0EB18_at_cisco.com" -->
<!-- charset="US-ASCII" -->
<!-- inreplyto="OFD2363258.825906CD-ON872572E5.00587755-862572E5.0058AF1C_at_us.ibm.com" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>From:</strong> Jeff Squyres (<em>jsquyres_at_[hidden]</em>)<br>
<strong>Date:</strong> 2007-05-24 12:13:42
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="0308.php">Tim Mattox: "Re: [MTT users] Few trunk results this morning?"</a>
<li><strong>Previous message:</strong> <a href="0306.php">Sheldon D'mello: "Re: [MTT users] Few trunk results this morning?"</a>
<li><strong>In reply to:</strong> <a href="0306.php">Sheldon D'mello: "Re: [MTT users] Few trunk results this morning?"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="0308.php">Tim Mattox: "Re: [MTT users] Few trunk results this morning?"</a>
<li><strong>Reply:</strong> <a href="0308.php">Tim Mattox: "Re: [MTT users] Few trunk results this morning?"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Indiana: it looks like something went wrong with the tarball  
<br>
generation last night (note the zero-length files):
<br>
<p>[12:12] eddie:/l/osl/www/www.open-mpi.org/nightly/trunk % l
<br>
total 42468
<br>
drwxrwsr-x  3 jsquyres openmpi     4096 May 23 21:22 ./
<br>
drwxrwsr-x  7 jsquyres openmpi     4096 Apr 21 23:12 ../
<br>
-rw-rw-r--  1 jsquyres openmpi     1738 Aug 27  2006 index.php
<br>
-rw-r--r--  1 mpiteam  openmpi        0 May 23 21:22 latest_snapshot.txt
<br>
-rw-r--r--  1 mpiteam  openmpi        0 May 23 21:22 md5sums.txt
<br>
-rw-r--r--  1 mpiteam  projects 3919045 May 19 21:09  
<br>
openmpi-1.3a1r14701.tar.bz2
<br>
-rw-r--r--  1 mpiteam  projects 6903261 May 19 21:08  
<br>
openmpi-1.3a1r14701.tar.gz
<br>
-rw-r--r--  1 mpiteam  projects 3920829 May 20 21:09  
<br>
openmpi-1.3a1r14702.tar.bz2
<br>
-rw-r--r--  1 mpiteam  projects 6903903 May 20 21:09  
<br>
openmpi-1.3a1r14702.tar.gz
<br>
-rw-r--r--  1 mpiteam  projects 3928934 May 21 21:09  
<br>
openmpi-1.3a1r14715.tar.bz2
<br>
-rw-r--r--  1 mpiteam  projects 6915775 May 21 21:08  
<br>
openmpi-1.3a1r14715.tar.gz
<br>
-rw-r--r--  1 mpiteam  projects 3928720 May 22 21:09  
<br>
openmpi-1.3a1r14719.tar.bz2
<br>
-rw-r--r--  1 mpiteam  projects 6914181 May 22 21:09  
<br>
openmpi-1.3a1r14719.tar.gz
<br>
-rw-r--r--  1 mpiteam  openmpi        0 May 23 21:22  
<br>
openmpi-1.3a1r14743.tar.bz2
<br>
-rw-r--r--  1 mpiteam  openmpi        0 May 23 21:22  
<br>
openmpi-1.3a1r14743.tar.gz
<br>
-rw-r--r--  1 mpiteam  openmpi        0 May 23 21:22 sha1sums.txt
<br>
drwxrwsr-x  7 jsquyres openmpi     4096 May 24 11:54 .svn/
<br>
<p>What happened?
<br>
<p><p>On May 24, 2007, at 12:08 PM, Sheldon D'mello wrote:
<br>
<p><span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; Hi Ethan,
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; Yes, there is an error being generated by the wget command. Looks  
</span><br>
<span class="quotelev1">&gt; like the tarball does not exist.
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; Running command: wget -nv
</span><br>
<span class="quotelev1">&gt;    <a href="http://www.open-mpi.org/nightly/trunk/openmpi-.tar.gz">http://www.open-mpi.org/nightly/trunk/openmpi-.tar.gz</a>
</span><br>
<span class="quotelev1">&gt; OUT:<a href="http://www.open-mpi.org/nightly/trunk/openmpi-.tar.gz">http://www.open-mpi.org/nightly/trunk/openmpi-.tar.gz</a>:
</span><br>
<span class="quotelev1">&gt; OUT:11:05:16 ERROR 404: Not Found.
</span><br>
<span class="quotelev1">&gt; Command complete, exit status: 1
</span><br>
<span class="quotelev1">&gt; *** ERROR: Module aborted: MTT::MPI::Get::OMPI_Snapshot:Get: ***  
</span><br>
<span class="quotelev1">&gt; ERROR:
</span><br>
<span class="quotelev1">&gt;     Could not download tarball -- aborting
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; Regards,
</span><br>
<span class="quotelev1">&gt; Sheldon
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; sdmello_at_[hidden]
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; mtt-users-request_at_[hidden]
</span><br>
<span class="quotelev1">&gt; Sent by: mtt-users-bounces_at_[hidden]
</span><br>
<span class="quotelev1">&gt; 05/24/2007 11:00 AM
</span><br>
<span class="quotelev1">&gt; Please respond to
</span><br>
<span class="quotelev1">&gt; mtt-users_at_[hidden]
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; To
</span><br>
<span class="quotelev1">&gt; mtt-users_at_[hidden]
</span><br>
<span class="quotelev1">&gt; cc
</span><br>
<span class="quotelev1">&gt; Subject
</span><br>
<span class="quotelev1">&gt; mtt-users Digest, Vol 15, Issue 7
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; Send mtt-users mailing list submissions to
</span><br>
<span class="quotelev1">&gt;                 mtt-users_at_[hidden]
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; To subscribe or unsubscribe via the World Wide Web, visit
</span><br>
<span class="quotelev1">&gt;                 <a href="http://www.open-mpi.org/mailman/listinfo.cgi/mtt-users">http://www.open-mpi.org/mailman/listinfo.cgi/mtt-users</a>
</span><br>
<span class="quotelev1">&gt; or, via email, send a message with subject or body 'help' to
</span><br>
<span class="quotelev1">&gt;                 mtt-users-request_at_[hidden]
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; You can reach the person managing the list at
</span><br>
<span class="quotelev1">&gt;                 mtt-users-owner_at_[hidden]
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; When replying, please edit your Subject line so it is more specific
</span><br>
<span class="quotelev1">&gt; than &quot;Re: Contents of mtt-users digest...&quot;
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; Today's Topics:
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt;   1. Few trunk results this morning? (Ethan Mallove)
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; ----------------------------------------------------------------------
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; Message: 1
</span><br>
<span class="quotelev1">&gt; Date: Thu, 24 May 2007 11:52:23 -0400
</span><br>
<span class="quotelev1">&gt; From: Ethan Mallove &lt;ethan.mallove_at_[hidden]&gt;
</span><br>
<span class="quotelev1">&gt; Subject: [MTT users] Few trunk results this morning?
</span><br>
<span class="quotelev1">&gt; To: MTT users &lt;mtt-users_at_[hidden]&gt;
</span><br>
<span class="quotelev1">&gt; Message-ID: &lt;20070524155223.GJ6879_at_[hidden]&gt;
</span><br>
<span class="quotelev1">&gt; Content-Type: text/plain; charset=us-ascii
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; There's hardly any ompi-nightly-trunk results this morning
</span><br>
<span class="quotelev1">&gt; from *any* of the &quot;ompi-core-testers&quot;. Did something happen
</span><br>
<span class="quotelev1">&gt; with the tarball generator last night?
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; -Ethan
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; ------------------------------
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; _______________________________________________
</span><br>
<span class="quotelev1">&gt; mtt-users mailing list
</span><br>
<span class="quotelev1">&gt; mtt-users_at_[hidden]
</span><br>
<span class="quotelev1">&gt; <a href="http://www.open-mpi.org/mailman/listinfo.cgi/mtt-users">http://www.open-mpi.org/mailman/listinfo.cgi/mtt-users</a>
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; End of mtt-users Digest, Vol 15, Issue 7
</span><br>
<span class="quotelev1">&gt; ****************************************
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; _______________________________________________
</span><br>
<span class="quotelev1">&gt; mtt-users mailing list
</span><br>
<span class="quotelev1">&gt; mtt-users_at_[hidden]
</span><br>
<span class="quotelev1">&gt; <a href="http://www.open-mpi.org/mailman/listinfo.cgi/mtt-users">http://www.open-mpi.org/mailman/listinfo.cgi/mtt-users</a>
</span><br>
<p><p><pre>
-- 
Jeff Squyres
Cisco Systems
</pre>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="0308.php">Tim Mattox: "Re: [MTT users] Few trunk results this morning?"</a>
<li><strong>Previous message:</strong> <a href="0306.php">Sheldon D'mello: "Re: [MTT users] Few trunk results this morning?"</a>
<li><strong>In reply to:</strong> <a href="0306.php">Sheldon D'mello: "Re: [MTT users] Few trunk results this morning?"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="0308.php">Tim Mattox: "Re: [MTT users] Few trunk results this morning?"</a>
<li><strong>Reply:</strong> <a href="0308.php">Tim Mattox: "Re: [MTT users] Few trunk results this morning?"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
