<?php
$title = "Supercomputing 2018 slides";
$overview = "Slides from the Open MPI State of the Union BOF at SC'18";

$authors = "George Bosilca, Jeff Squyres, Edgar Gabriel, Josh Ladd";

$abstract = "Slides from the Open MPI State of the Union XII Community
Meeting at SC'18.";

$presented = "<a href=\"http://sc18.supercomputing.org/\">" . "SC'17</a>,
November 13, 2017, in Dallas, TX, USA";

$files[] = "Open-MPI-SC18-BOF.pdf";

$month = 11;
$day = 13;
$year = 2017;

$bibtex = "";
