<?
$subject_val = "[OMPI devel] issue with MPI_DISPLACEMENT_CURRENT and use mpi";
include("../../include/msg-header.inc");
?>
<!-- received="Thu Dec  3 23:52:21 2015" -->
<!-- isoreceived="20151204045221" -->
<!-- sent="Fri, 4 Dec 2015 13:52:24 +0900" -->
<!-- isosent="20151204045224" -->
<!-- name="Gilles Gouaillardet" -->
<!-- email="gilles_at_[hidden]" -->
<!-- subject="[OMPI devel] issue with MPI_DISPLACEMENT_CURRENT and use mpi" -->
<!-- id="56611C08.5040003_at_rist.or.jp" -->
<!-- charset="UTF-8" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> [OMPI devel] issue with MPI_DISPLACEMENT_CURRENT and use mpi<br>
<strong>From:</strong> Gilles Gouaillardet (<em>gilles_at_[hidden]</em>)<br>
<strong>Date:</strong> 2015-12-03 23:52:24
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="18402.php">Baldassari Caroline: "Re: [OMPI devel] Problem with the 1.8.8 version"</a>
<li><strong>Previous message:</strong> <a href="18400.php">Ralph Castain: "[OMPI devel] v1.10.2 release plans"</a>
<!-- nextthread="start" -->
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Jeff,
<br>
<p>the following program does not compile :
<br>
$ mpifort -c mpi_displacement_current_usempi.f90
<br>
mpi_displacement_current_usempi.f90:6:64:
<br>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&amp;     ,MPI_DATATYPE_NULL , &quot;native&quot;, MPI_INFO_NULL, ierr )
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1
<br>
Error: There is no specific subroutine for the generic 
<br>
&#226;&#128;&#152;mpi_file_set_view&#226;&#128;&#153; at (1)
<br>
<p>the root cause is MPI_DISPLACEMENT_CURRENT is defined as an integer 
<br>
instead of
<br>
integer(kind=MPI_ADDRESS_KIND)
<br>
<p>/* this is defined in ompi/include/mpif-io-constants.h generated by 
<br>
ompi/include/mpif-values.pl,
<br>
and this is all perl ... */
<br>
<p>could you please have a look ?
<br>
<p>Cheers,
<br>
<p>Gilles
<br>
<p>
<br><hr>
<ul>
<li>text/plain attachment: <a href="http://www.open-mpi.org/community/lists/devel/att-18401/mpi_displacement_current_usempi.f90">mpi_displacement_current_usempi.f90</a>
</ul>
<!-- attachment="mpi_displacement_current_usempi.f90" -->
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="18402.php">Baldassari Caroline: "Re: [OMPI devel] Problem with the 1.8.8 version"</a>
<li><strong>Previous message:</strong> <a href="18400.php">Ralph Castain: "[OMPI devel] v1.10.2 release plans"</a>
<!-- nextthread="start" -->
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
