<?php
$title = "Supercomputing 2015 slides";
$overview = "Slides from the Open MPI State of the Union BOF at SC'15";

$authors = "George Bosilca, Jeff Squyres, Nathan Hjelm";

$abstract = "Slides from the Open MPI State of the Union Community
Meeting at SC'15.";

$presented = "<a href=\"http://sc15.supercomputing.org/\">" . "SC'15</a>,
November, 2015, in Austin, TX, USA";

$files[] = "Open-MPI-SC15-BOF.pdf";

$month = 11;
$day = 18;
$year = 2015;

$bibtex = "";
