<?php
$title = "Supercomputing 2019 slides";
$overview = "Slides from the Open MPI State of the Union BOF at SC'19";

$authors = "George Bosilca, Jeff Squyres, Brian Barrett, Ralph Castain, Josh Hursey";

$abstract = "Slides from the Open MPI State of the Union XIII Community
Meeting at SC'19.";

$presented = "<a href=\"http://sc19.supercomputing.org/\">" . "SC'19</a>,
November 20, 2019, in Denver, CO, USA";

$files[] = "Open-MPI-SC19-BOF.pdf";

$month = 11;
$day = 20;
$year = 2019;

$bibtex = "";
