<?php 
$title = "Implementation of Open MPI on Red Storm";
$overview = "Presents an overview of Open MPI on the Red Storm platform.";

$authors = "Brian W. Barrett, Jeffrey M. Squyres, Andrew Lumsdaine";

$abstract = " The Open MPI project provides a high quality MPI
implementation available on a wide variety of platforms.  This
technical report describes the porting of Open MPI to the Cray Red
Storm platform (as well as the Cray XT3 platform).  While alpha
quality, the port already provides acceptable performance.  Remaining
porting work and future enhancements are also discussed.";

$presented = "Los Alamos Tech Report LA-UR-05-8307";

$files[] = "lanl-2005-red-storm.pdf";

$month = 10;
$day = 28;
$year = 2005;

$bibtex = "@TechReport{barrett05:_implem_open_mpi_red_storm,
  author       = {Brian W. Barrett and Jeffrey M. Squyres and Andrew Lumsdaine},
  title        = {Implementation of Open MPI on Red Storm},
  institution  = {Los Alamos National Laboratory},
  year         = 2005,
  number    = {LA-UR-05-8307},
  address   = {Los Alamos, New Mexico, USA},
  month     = {October}
}";

