<?
$subject_val = "[OMPI devel] setenv MPI_ROOT";
include("../../include/msg-header.inc");
?>
<!-- received="Tue Feb  8 08:50:17 2011" -->
<!-- isoreceived="20110208135017" -->
<!-- sent="Tue, 08 Feb 2011 14:52:15 +0100" -->
<!-- isosent="20110208135215" -->
<!-- name="Damien Guinier" -->
<!-- email="damien.guinier_at_[hidden]" -->
<!-- subject="[OMPI devel] setenv MPI_ROOT" -->
<!-- id="4D514A8F.6090709_at_bull.net" -->
<!-- charset="ISO-8859-1" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> [OMPI devel] setenv MPI_ROOT<br>
<strong>From:</strong> Damien Guinier (<em>damien.guinier_at_[hidden]</em>)<br>
<strong>Date:</strong> 2011-02-08 08:52:15
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="8966.php">George Bosilca: "Re: [OMPI devel] Hang for MPI_Ssend_init + MPI_Cancel"</a>
<li><strong>Previous message:</strong> <a href="8964.php">Tobias Hilbrich: "Re: [OMPI devel] Hang for MPI_Ssend_init + MPI_Cancel"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="8967.php">Jeff Squyres: "Re: [OMPI devel] setenv MPI_ROOT"</a>
<li><strong>Reply:</strong> <a href="8967.php">Jeff Squyres: "Re: [OMPI devel] setenv MPI_ROOT"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
hi all
<br>
<p>On v1.5 branch, can we add MPI_ROOT variable on:
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/%{shell_scripts_path}/%{shell_scripts_basename}.sh
<br>
and /%{shell_scripts_path}/%{shell_scripts_basename}.csh
<br>
with the value : MPI_ROOT=%{_prefix}
<br>
<p>The variable MPI_ROOT facilitate launch script creation. This variable 
<br>
is asked by customer who use BPS and LSF batch manager.
<br>
<p>thanks
<br>
<p>Damien Guinier
<br>
<p>-------------
<br>
<p>diff -r 486ca4bfca95 contrib/dist/linux/openmpi.spec
<br>
--- a/contrib/dist/linux/openmpi.spec   Mon Feb 07 15:40:31 2011 +0100
<br>
+++ b/contrib/dist/linux/openmpi.spec   Tue Feb 08 14:30:01 2011 +0100
<br>
@@ -514,6 +514,10 @@
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MANPATH=%{_mandir}:\${MANPATH}
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;export MANPATH
<br>
&nbsp;&nbsp;fi
<br>
+
<br>
+# MPI_ROOT
<br>
+MPI_ROOT=%{_prefix}
<br>
+export MPI_ROOT
<br>
&nbsp;&nbsp;EOF
<br>
&nbsp;&nbsp;cat &lt;&lt;EOF &gt; 
<br>
$RPM_BUILD_ROOT/%{shell_scripts_path}/%{shell_scripts_basename}.csh
<br>
&nbsp;&nbsp;# NOTE: This is an automatically-generated file!  (generated by the
<br>
@@ -542,6 +546,9 @@
<br>
&nbsp;&nbsp;else
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;setenv MANPATH %{_mandir}:
<br>
&nbsp;&nbsp;endif
<br>
+
<br>
+# MPI_ROOT
<br>
+setenv MPI_ROOT %{_prefix}
<br>
&nbsp;&nbsp;EOF
<br>
&nbsp;&nbsp;%endif
<br>
&nbsp;&nbsp;# End of shell_scripts if
<br>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="8966.php">George Bosilca: "Re: [OMPI devel] Hang for MPI_Ssend_init + MPI_Cancel"</a>
<li><strong>Previous message:</strong> <a href="8964.php">Tobias Hilbrich: "Re: [OMPI devel] Hang for MPI_Ssend_init + MPI_Cancel"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="8967.php">Jeff Squyres: "Re: [OMPI devel] setenv MPI_ROOT"</a>
<li><strong>Reply:</strong> <a href="8967.php">Jeff Squyres: "Re: [OMPI devel] setenv MPI_ROOT"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
