<?
$subject_val = "Re: [OMPI users] Cant build OpenMPI!";
include("../../include/msg-header.inc");
?>
<!-- received="Thu Jan 26 15:05:02 2012" -->
<!-- isoreceived="20120126200502" -->
<!-- sent="Thu, 26 Jan 2012 15:04:57 -0500" -->
<!-- isosent="20120126200457" -->
<!-- name="Jeff Squyres" -->
<!-- email="jsquyres_at_[hidden]" -->
<!-- subject="Re: [OMPI users] Cant build OpenMPI!" -->
<!-- id="4E1DA651-4FA2-4A91-803C-2DF1B895D9DC_at_cisco.com" -->
<!-- charset="windows-1252" -->
<!-- inreplyto="9A065633-D0E1-4092-9D2E-CFE4CA4D6500_at_cisco.com" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> Re: [OMPI users] Cant build OpenMPI!<br>
<strong>From:</strong> Jeff Squyres (<em>jsquyres_at_[hidden]</em>)<br>
<strong>Date:</strong> 2012-01-26 15:04:57
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="18281.php">David Akin: "[OMPI users] Strange recursive &quot;no&quot; error message when compiling 1.5 series with fault tolerance enabled"</a>
<li><strong>Previous message:</strong> <a href="18279.php">Ralph Castain: "Re: [OMPI users] How to determine MPI rank/process number local to a socket/node"</a>
<li><strong>In reply to:</strong> <a href="18259.php">Jeff Squyres: "Re: [OMPI users] Cant build OpenMPI!"</a>
<!-- nextthread="start" -->
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
To follow up for the web archives: We talked about this off-list.
<br>
<p>Upgrading to Open MPI 1.4.4 fixed the problem.  I'm assuming it was some bug in 1.4.2 that was fixed in 1.4.4.
<br>
<p><p>On Jan 24, 2012, at 2:13 PM, Jeff Squyres wrote:
<br>
<p><span class="quotelev1">&gt; One more thing to check: are you building on a networked filesystem, and the client on which you are building is not time synchronized with the file server?
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; If you are not building on a networked file system, or if you are building on a NFS and the time is NTP-synchronized between client and server, then please send everything listed here:
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt;    <a href="http://www.open-mpi.org/community/help/">http://www.open-mpi.org/community/help/</a>
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; On Jan 24, 2012, at 1:48 PM, devendra rai wrote:
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; Hello Jeff,
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; No. I did not run autogen.sh.  I just did the three steps that you showed.
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; Will log files be of any help? 
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; (Also, if the log files are not generated by just pipe'ing or tee'ing, please let me know).
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; Thanks a lot.
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; Best
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; Devendra
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; From: Jeff Squyres &lt;jsquyres_at_[hidden]&gt;
</span><br>
<span class="quotelev2">&gt;&gt; To: devendra rai &lt;rai.devendra_at_[hidden]&gt;; Open MPI Users &lt;users_at_[hidden]&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; Sent: Tuesday, 24 January 2012, 19:40
</span><br>
<span class="quotelev2">&gt;&gt; Subject: Re: [OMPI users] Cant build OpenMPI!
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; Did you try running autogen.sh?
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; You should not need to -- you should only need to:
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; ./configure ...
</span><br>
<span class="quotelev2">&gt;&gt; make all
</span><br>
<span class="quotelev2">&gt;&gt; make install
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; On Jan 24, 2012, at 1:38 PM, devendra rai wrote:
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; Hello All,
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; I am trying to build openMPI on a server (I do not have sudo on this server).
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; When running make, I get this error:
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../opal/include -I../../orte/include -I../../ompi/include -I../../opal/mca/paffinity/linux/plpa/src/libplpa -I../.. -I/usr/include -g -finline-functions -fno-strict-aliasing -pthread -fvisibility=hidden -MT dt_module.lo -MD -MP -MF .deps/dt_module.Tpo -c dt_module.c  -fPIC -DPIC -o .libs/dt_module.o
</span><br>
<span class="quotelev3">&gt;&gt;&gt; dt_module.c:177: error: expected expression before &#145;)&#146; token
</span><br>
<span class="quotelev3">&gt;&gt;&gt; dt_module.c:182: error: expected expression before &#145;)&#146; token
</span><br>
<span class="quotelev3">&gt;&gt;&gt; dt_module.c:187: error: expected expression before &#145;)&#146; token
</span><br>
<span class="quotelev3">&gt;&gt;&gt; dt_module.c:192: error: expected expression before &#145;)&#146; token
</span><br>
<span class="quotelev3">&gt;&gt;&gt; dt_module.c:203: error: expected expression before &#145;)&#146; token
</span><br>
<span class="quotelev3">&gt;&gt;&gt; dt_module.c:208: error: expected expression before &#145;)&#146; token
</span><br>
<span class="quotelev3">&gt;&gt;&gt; dt_module.c:219: error: expected expression before &#145;)&#146; token
</span><br>
<span class="quotelev3">&gt;&gt;&gt; dt_module.c:224: error: expected expression before &#145;)&#146; token
</span><br>
<span class="quotelev3">&gt;&gt;&gt; dt_module.c:229: error: expected expression before &#145;)&#146; token
</span><br>
<span class="quotelev3">&gt;&gt;&gt; dt_module.c:234: error: expected expression before &#145;)&#146; token
</span><br>
<span class="quotelev3">&gt;&gt;&gt; dt_module.c:250: error: expected expression before &#145;)&#146; token
</span><br>
<span class="quotelev3">&gt;&gt;&gt; make[2]: *** [dt_module.lo] Error 1
</span><br>
<span class="quotelev3">&gt;&gt;&gt; make[2]: Leaving directory `/home/raid/private/openmpi-1.4.2/ompi/datatype'
</span><br>
<span class="quotelev3">&gt;&gt;&gt; make[1]: *** [all-recursive] Error 1
</span><br>
<span class="quotelev3">&gt;&gt;&gt; make[1]: Leaving directory `/home/raid/private/openmpi-1.4.2/ompi'
</span><br>
<span class="quotelev3">&gt;&gt;&gt; make: *** [all-recursive] Error 1
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; Before this, I had some warnings:
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; WARNING: `aclocal-1.10' is missing on your system.  You should only need it if
</span><br>
<span class="quotelev3">&gt;&gt;&gt;         you modified `acinclude.m4' or `configure.in'.  You might want
</span><br>
<span class="quotelev3">&gt;&gt;&gt;         to install the `Automake' and `Perl' packages.  Grab them from
</span><br>
<span class="quotelev3">&gt;&gt;&gt;         any GNU archive site.
</span><br>
<span class="quotelev3">&gt;&gt;&gt; cd . &amp;&amp; /bin/bash /home/raid/private/openmpi-1.4.2/ompi/contrib/vt/vt/missing --run automake-1.10 --foreign 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; /home/raid/private/openmpi-1.4.2/ompi/contrib/vt/vt/missing: line 54: automake-1.10: command not found
</span><br>
<span class="quotelev3">&gt;&gt;&gt; WARNING: `automake-1.10' is missing on your system.  You should only need it if
</span><br>
<span class="quotelev3">&gt;&gt;&gt;         you modified `Makefile.am', `acinclude.m4' or `configure.in'.
</span><br>
<span class="quotelev3">&gt;&gt;&gt;         You might want to install the `Automake' and `Perl' packages.
</span><br>
<span class="quotelev3">&gt;&gt;&gt;         Grab them from any GNU archive site.
</span><br>
<span class="quotelev3">&gt;&gt;&gt; cd . &amp;&amp; /bin/bash /home/raid/private/openmpi-1.4.2/ompi/contrib/vt/vt/missing --run autoconf
</span><br>
<span class="quotelev3">&gt;&gt;&gt; aclocal.m4:16: warning: this file was generated for autoconf 2.63.
</span><br>
<span class="quotelev3">&gt;&gt;&gt; You have another version of autoconf.  It may work, but is not guaranteed to.
</span><br>
<span class="quotelev3">&gt;&gt;&gt; If you have problems, you may need to regenerate the build system entirely.
</span><br>
<span class="quotelev3">&gt;&gt;&gt; To do so, use the procedure documented by the package, typically `autoreconf'.
</span><br>
<span class="quotelev3">&gt;&gt;&gt; /bin/bash ./config.status --recheck
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; Is there any relationship? If not, what else am I missing?
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; Thanks a lot for pointers.
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; Best
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; Devendra
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; _______________________________________________
</span><br>
<span class="quotelev3">&gt;&gt;&gt; users mailing list
</span><br>
<span class="quotelev3">&gt;&gt;&gt; users_at_[hidden]
</span><br>
<span class="quotelev3">&gt;&gt;&gt; <a href="http://www.open-mpi.org/mailman/listinfo.cgi/users">http://www.open-mpi.org/mailman/listinfo.cgi/users</a>
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; -- 
</span><br>
<span class="quotelev2">&gt;&gt; Jeff Squyres
</span><br>
<span class="quotelev2">&gt;&gt; jsquyres_at_[hidden]
</span><br>
<span class="quotelev2">&gt;&gt; For corporate legal information go to:
</span><br>
<span class="quotelev2">&gt;&gt; <a href="http://www.cisco.com/web/about/doing_business/legal/cri/">http://www.cisco.com/web/about/doing_business/legal/cri/</a>
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; -- 
</span><br>
<span class="quotelev1">&gt; Jeff Squyres
</span><br>
<span class="quotelev1">&gt; jsquyres_at_[hidden]
</span><br>
<span class="quotelev1">&gt; For corporate legal information go to:
</span><br>
<span class="quotelev1">&gt; <a href="http://www.cisco.com/web/about/doing_business/legal/cri/">http://www.cisco.com/web/about/doing_business/legal/cri/</a>
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; _______________________________________________
</span><br>
<span class="quotelev1">&gt; users mailing list
</span><br>
<span class="quotelev1">&gt; users_at_[hidden]
</span><br>
<span class="quotelev1">&gt; <a href="http://www.open-mpi.org/mailman/listinfo.cgi/users">http://www.open-mpi.org/mailman/listinfo.cgi/users</a>
</span><br>
<p><p><pre>
-- 
Jeff Squyres
jsquyres_at_[hidden]
For corporate legal information go to:
<a href="http://www.cisco.com/web/about/doing_business/legal/cri/">http://www.cisco.com/web/about/doing_business/legal/cri/</a>
</pre>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="18281.php">David Akin: "[OMPI users] Strange recursive &quot;no&quot; error message when compiling 1.5 series with fault tolerance enabled"</a>
<li><strong>Previous message:</strong> <a href="18279.php">Ralph Castain: "Re: [OMPI users] How to determine MPI rank/process number local to a socket/node"</a>
<li><strong>In reply to:</strong> <a href="18259.php">Jeff Squyres: "Re: [OMPI users] Cant build OpenMPI!"</a>
<!-- nextthread="start" -->
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
