<?php
$title = "Supercomputing 2014 slides";
$overview = "Slides from the Open MPI State of the Union BOF at SC'14";

$authors = "George Bosilca, Jeff Squyres, Nathan Hjelm, Laust Brock-Nannestad";

$abstract = "Slides from the Open MPI State of the Union Community
Meeting at SC'14.";

$presented = "<a href=\"http://sc14.supercomputing.org/\">" . "SC'14</a>,
November, 2014, in New Orleans, LA, USA";

$files[] = "Open-MPI-SC14-BOF.pdf";

$month = 11;
$day = 19;
$year = 2014;

$bibtex = "";
