<? include("../../include/msg-header.inc"); ?>
<!-- received="Sun Oct 16 21:32:23 2005" -->
<!-- isoreceived="20051017023223" -->
<!-- sent="Sun, 16 Oct 2005 21:32:13 -0500" -->
<!-- isosent="20051017023213" -->
<!-- name="Brian Barrett" -->
<!-- email="brbarret_at_[hidden]" -->
<!-- subject="build system changes" -->
<!-- id="670D059D-CCED-4DEC-8A8D-EACE329305F9_at_open-mpi.org" -->
<!-- charset="US-ASCII" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>From:</strong> Brian Barrett (<em>brbarret_at_[hidden]</em>)<br>
<strong>Date:</strong> 2005-10-16 21:32:13
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="0450.php">Brian Barrett: "Re:  build system changes"</a>
<li><strong>Previous message:</strong> <a href="0448.php">Jeff Squyres: "Re:  porting guide?"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="0450.php">Brian Barrett: "Re:  build system changes"</a>
<li><strong>Reply:</strong> <a href="0450.php">Brian Barrett: "Re:  build system changes"</a>
<li><strong>Reply:</strong> <a href="0451.php">George Bosilca: "Re:  build system changes"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Hi all -
<br>
<p>I made yet another round of changes to the build system this  
<br>
weekend.  The goal was to improve the build time for Open MPI.  This  
<br>
improvement should offer speedups for autogen, configure, and build.   
<br>
I reduced the number of Makefiles produced by configure (and  
<br>
therefore the number of Makefile.in files generated by Automake), by  
<br>
using some interesting include features of Automake.  Rather than  
<br>
building support libraries in each directory, everything is directly  
<br>
folded into the project-level (opal,orte,ompi) library.  The  
<br>
advantage is faster build time.  The disadvantage is that you can no  
<br>
longer run &quot;make&quot; in ompi/proc (for instance).
<br>
<p>There is still one improvement along these lines that we can make.   
<br>
Currently, we create a Makefile in both &lt;project&gt;/mca/&lt;framework&gt; and  
<br>
&lt;project&gt;/mca/&lt;framework&gt;/base.  It should be possible to eliminate  
<br>
the one in base, reducing the number of Makefiles created even  
<br>
further.  But I ran out of time this weekend, so it's going to have  
<br>
to wait a bit.
<br>
<p>Brian
<br>
<p><p><pre>
-- 
   Brian Barrett
   Open MPI developer
   <a href="http://www.open-mpi.org/">http://www.open-mpi.org/</a>
</pre>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="0450.php">Brian Barrett: "Re:  build system changes"</a>
<li><strong>Previous message:</strong> <a href="0448.php">Jeff Squyres: "Re:  porting guide?"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="0450.php">Brian Barrett: "Re:  build system changes"</a>
<li><strong>Reply:</strong> <a href="0450.php">Brian Barrett: "Re:  build system changes"</a>
<li><strong>Reply:</strong> <a href="0451.php">George Bosilca: "Re:  build system changes"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
