<?php
$title = "Supercomputing 2015 PMIx BoF slides";
$overview = "Slides from the PMIx BOF at SC'15";

$authors = "Ralph Castain, Joshua Ladd, David Solt, Gary Brown";

$abstract = "Slides from the PMIx Community Meeting at SC'15.";

$presented = "<a href=\"http://sc15.supercomputing.org/\">" . "SC'15</a>,
November, 2015, in Austin, TX, USA";

$files[] = "PMIx-BoF.pdf";

$month = 11;
$day = 19;
$year = 2015;

$bibtex = "";
