<?php
$topdir = "../../..";
$title = "shmem_longlong_set(3) man page (version 3.0.6)";
$meta_desc = "Open MPI v3.0.6 man page: shmem_longlong_set(3)";

include_once("$topdir/doc/nav.inc");
include_once("$topdir/includes/header.inc");
?>
<p> <a href="../">&laquo; Return to documentation listing</a></p>
   <!-- manual page source format generated by PolyglotMan v3.2, -->
<!-- available at http://polyglotman.sourceforge.net/ -->

<body bgcolor='white'>
<a href='#toc'>Table of Contents</a><p>

<h2><a name='sect0' href='#toc0'>Name</a></h2>

<p> <i><i>shmem_double_set</i>(3)</i>, <i><i>shmem_float_set</i>(3)</i>, <i><i>shmem_int_set</i>(3)</i>, <i><i>shmem_long_set</i>(3)</i>,
<i><i>shmem_longlong_set</i>(3)</i> <i><i>shmem_int4_set</i>(3)</i>, <i><i>shmem_int8_set</i>(3)</i>, <i><i>shmem_real4_set</i>(3)</i>,
<i><i>shmem_real8_set</i>(3)</i>, - Atomically sets the value of a remote data object

<p>
<h2><a name='sect1' href='#toc1'>Synopsis</a></h2>

<p> C or C++: <br>
<pre>#include &lt;mpp/shmem.h&gt;
void shmem_double_set(double *target, double value, int pe);
void shmem_float_set(float *target, float value, int pe);
void shmem_int_set(int *target, int value, int pe);
void shmem_long_set(long *target, long value, int pe);
void shmem_longlong_set(long long *target, long long value, int pe);
</pre> Fortran: <br>
<pre>INCLUDE "mpp/shmem.fh"
INTEGER pe
CALL SHMEM_INT4_SET(target, value, pe)
CALL SHMEM_INT8_SET(target, value, pe)
CALL SHMEM_REAL4_SET(target, value, pe)
CALL SHMEM_REAL8_SET(target, value, pe)
</pre>
<h2><a name='sect2' href='#toc2'>Description</a></h2>

<p> The set routines write the <b>value</b> into the address <b>target</b> on
<b>pe</b> as an atomic operation. <p>
The arguments are as follows:
<dl>

<dt>target </dt>
<dd>The remotely
accessible data object to be set on the remote PE.  </dd>

<dt>value </dt>
<dd>The value to be
atomically written to the remote PE.  </dd>

<dt>pe </dt>
<dd>An integer that indicates the PE
number upon which target is to be updated. If you are using Fortran, it
must be a default integer value. </dd>
</dl>
<p>

<h2><a name='sect3' href='#toc3'>Return Values</a></h2>
NONE
<p>
<h2><a name='sect4' href='#toc4'>See Also</a></h2>

<p> <i><i>intro_shmem</i>(3)</i>

<p>  <p>

<hr><p>
<a name='toc'><b>Table of Contents</b></a><p>
<ul>
<li><a name='toc0' href='#sect0'>Name</a></li>
<li><a name='toc1' href='#sect1'>Synopsis</a></li>
<li><a name='toc2' href='#sect2'>Description</a></li>
<li><a name='toc3' href='#sect3'>Return Values</a></li>
<li><a name='toc4' href='#sect4'>See Also</a></li>
</ul>


<p> <a href="../">&laquo; Return to documentation listing</a></p>
<?php
include_once("$topdir/includes/footer.inc");
