<?php
$title = "Supercomputing 2006 slides";
$overview = "Slides from various presentations about Open MPI or by the Open MPI team members.";


$authors = "Brian Barrett, George Bosilca, Josh Hursey, Rainer Keller, Tim Mattox, Jeff Squyres";

$abstract = "Per request from many SC attendees, we are publishing 
our slides from various talks by Open MPI team members at SC.  The
talks are:

<ul>

<li> \"Heterogeneity and Open MPI\" presentation at the AIST booth by
Jeff Squyres and Rich Graham.</li>

<li> \"Open MPI Community Meeting\" BOF by Brian Barrett and Jeff
Squyres.</li>

<li> Booth slides from the Cisco show floor booth.</li>

<li> \"Extracting Internal Information from a Modular MPI Library\"
presentation at the Etnus booth by George Bosilca and Jeff
Squyres</li>

<li> \"Fault Tolerance in Open MPI\" presentation in the Indiana
University booth by Josh Hursey.</li>

<li> \"Open MPI: A Research Platform\" presentation in the Indiana
University booth by Tim Mattox.</li>

<li> \"Open MPI: What We've Done and Where We're Going\" presentation
in the Indiana University booth by Tim Mattox.</li>

<li> \"Why Open MPI?\" presentation in the Indiana University booth by
Tim Mattox.</li>

<li> \"Open MPI: Blending Academia and Industry\" presentation in the
Sun booth by Jeff Squyres.</li>

<li> \"Open MPI SC2006 Demo Description\" presentation in the Sun booth by
Rainer Keller.</li>

<li> \"Open MPI and InfiniBand\" presentation in the Mellanox booth by
Jeff Squyres.</li>

</ul>";

$presented = "<a href=\"http://sc06.supercomputing.org/\">" . "SC'06</a>,
November, 2006, in Tampa, Florida, USA";

$files[] = "aist-booth.pdf";
$files[] = "bof-ompi-community-meeting.pdf";
$files[] = "cisco-booth.pdf";
$files[] = "etnus-booth.pdf";
$files[] = "iu-booth-ft-in-ompi.pdf";
$files[] = "iu-booth-ompi-as-research-platform.pdf";
$files[] = "iu-booth-ompi-past-and-future.pdf";
$files[] = "iu-booth-why-ompi.pdf";
$files[] = "jsquyres-sun-booth.pdf";
$files[] = "rkeller-sun-booth.pdf";
$files[] = "mellanox-booth.pdf";

$month = 11;
$day = 13;
$year = 2006;

$bibtex = "";
