<?php
$title = "Supercomputing 2012 slides";
$overview = "Slides from the Open MPI State of the Union BOF at SC'12";

$authors = "George Bosilca, Jeff Squyres, Shinjii Sumimoto, Rolf vandeVaart";

$abstract = "Slides from the Open MPI State of the Union Community
Meeting at SC'12.";

$presented = "<a href=\"http://sc12.supercomputing.org/\">" . "SC'12</a>,
November, 2012, in Seattle, WA, USA";

$files[] = "Open-MPI-SC12-BOF.pdf";

$month = 11;
$day = 16;
$year = 2012;

$bibtex = "";
