<?
$subject_val = "Re: [hwloc-devel] BGQ empty topology with MPI";
include("../../include/msg-header.inc");
?>
<!-- received="Wed Mar 21 10:08:39 2012" -->
<!-- isoreceived="20120321140839" -->
<!-- sent="Wed, 21 Mar 2012 10:08:33 -0400" -->
<!-- isosent="20120321140833" -->
<!-- name="Daniel Ibanez" -->
<!-- email="dan.a.ibanez_at_[hidden]" -->
<!-- subject="Re: [hwloc-devel] BGQ empty topology with MPI" -->
<!-- id="CADcFuaZtN=4rwbM6B_U+6LpHvRCjtL_0t0kPoYyAGU5Jf5+qiQ_at_mail.gmail.com" -->
<!-- charset="UTF-8" -->
<!-- inreplyto="20120321073647.GQ5461_at_type.famille.thibault.fr" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> Re: [hwloc-devel] BGQ empty topology with MPI<br>
<strong>From:</strong> Daniel Ibanez (<em>dan.a.ibanez_at_[hidden]</em>)<br>
<strong>Date:</strong> 2012-03-21 10:08:33
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="2970.php">Daniel Ibanez: "Re: [hwloc-devel] BGQ empty topology with MPI"</a>
<li><strong>Previous message:</strong> <a href="2968.php">Samuel Thibault: "Re: [hwloc-devel] BGQ empty topology with MPI"</a>
<li><strong>In reply to:</strong> <a href="2968.php">Samuel Thibault: "Re: [hwloc-devel] BGQ empty topology with MPI"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="2970.php">Daniel Ibanez: "Re: [hwloc-devel] BGQ empty topology with MPI"</a>
<li><strong>Reply:</strong> <a href="2970.php">Daniel Ibanez: "Re: [hwloc-devel] BGQ empty topology with MPI"</a>
<li><strong>Reply:</strong> <a href="2974.php">Brice Goglin: "Re: [hwloc-devel] BGQ empty topology with MPI"</a>
<li><strong>Reply:</strong> <a href="2984.php">Christopher Samuel: "Re: [hwloc-devel] BGQ empty topology with MPI"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Attached is the stderr and stdout from lstopo compiled as you said.
<br>
I can't run hwloc-gather-topology.sh on the compute nodes
<br>
since its a script, but I can run it on the front end node.
<br>
<p>On Wed, Mar 21, 2012 at 3:36 AM, Samuel Thibault
<br>
&lt;samuel.thibault_at_[hidden]&gt;wrote:
<br>
<p><span class="quotelev1">&gt; Daniel Ibanez, le Wed 21 Mar 2012 03:37:25 +0100, a &#195;&#169;crit :
</span><br>
<span class="quotelev2">&gt; &gt; Please let me know if theres a hint of what could be causing it,
</span><br>
<span class="quotelev2">&gt; &gt; where to post, and what info to provide.
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; This is already the proper list.
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; Please attach the output of lstopo after having given the --enable-debug
</span><br>
<span class="quotelev1">&gt; option to ./configure and rebuilt completely, to get debugging
</span><br>
<span class="quotelev1">&gt; output. Also attach the /proc + /sys tarball generated by the installed
</span><br>
<span class="quotelev1">&gt; script hwloc-gather-topology.sh.
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; Samuel
</span><br>
<span class="quotelev1">&gt;
</span><br>
<p><p><p><pre>
-- 
Dan Ibanez


</pre>
<hr>
<ul>
<li>text/html attachment: <a href="http://www.open-mpi.org/community/lists/hwloc-devel/att-2969/attachment">attachment</a>
</ul>
<!-- attachment="attachment" -->
<hr>
<ul>
<li>application/octet-stream attachment: <a href="http://www.open-mpi.org/community/lists/hwloc-devel/att-2969/6581.error">6581.error</a>
</ul>
<!-- attachment="6581.error" -->
<hr>
<ul>
<li>application/octet-stream attachment: <a href="http://www.open-mpi.org/community/lists/hwloc-devel/att-2969/6581.output">6581.output</a>
</ul>
<!-- attachment="6581.output" -->
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="2970.php">Daniel Ibanez: "Re: [hwloc-devel] BGQ empty topology with MPI"</a>
<li><strong>Previous message:</strong> <a href="2968.php">Samuel Thibault: "Re: [hwloc-devel] BGQ empty topology with MPI"</a>
<li><strong>In reply to:</strong> <a href="2968.php">Samuel Thibault: "Re: [hwloc-devel] BGQ empty topology with MPI"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="2970.php">Daniel Ibanez: "Re: [hwloc-devel] BGQ empty topology with MPI"</a>
<li><strong>Reply:</strong> <a href="2970.php">Daniel Ibanez: "Re: [hwloc-devel] BGQ empty topology with MPI"</a>
<li><strong>Reply:</strong> <a href="2974.php">Brice Goglin: "Re: [hwloc-devel] BGQ empty topology with MPI"</a>
<li><strong>Reply:</strong> <a href="2984.php">Christopher Samuel: "Re: [hwloc-devel] BGQ empty topology with MPI"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
