<? include("../../include/msg-header.inc"); ?>
<!-- received="Fri Oct 20 15:36:00 2006" -->
<!-- isoreceived="20061020193600" -->
<!-- sent="Fri, 20 Oct 2006 15:35:50 -0400" -->
<!-- isosent="20061020193550" -->
<!-- name="Pak Lui" -->
<!-- email="Pak.Lui_at_[hidden]" -->
<!-- subject="Re: [OMPI devel] [GE users] OpenMPI 1.2 integration and dedicated MPI networks" -->
<!-- id="45392516.8050808_at_Sun.COM" -->
<!-- charset="ISO-8859-1" -->
<!-- inreplyto="45391912.4030601_at_cora.nwra.com" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>From:</strong> Pak Lui (<em>Pak.Lui_at_[hidden]</em>)<br>
<strong>Date:</strong> 2006-10-20 15:35:50
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="1132.php">Jeff Squyres: "Re: [OMPI devel] some stuff defined for Fortran but not for C"</a>
<li><strong>Previous message:</strong> <a href="1130.php">Lisandro Dalcin: "[OMPI devel] some stuff defined for Fortran but not for C"</a>
<li><strong>In reply to:</strong> <a href="1129.php">Orion Poplawski: "Re: [OMPI devel] [GE users] OpenMPI 1.2 integration and dedicated MPI networks"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="http://www.open-mpi.org/community/lists/devel/2006/11/1159.php">Orion Poplawski: "Re: [OMPI devel] [GE users] OpenMPI 1.2 integration and dedicated MPI networks"</a>
<li><strong>Reply:</strong> <a href="http://www.open-mpi.org/community/lists/devel/2006/11/1159.php">Orion Poplawski: "Re: [OMPI devel] [GE users] OpenMPI 1.2 integration and dedicated MPI networks"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Hi Orion,
<br>
<p>I wonder if you can try this:
<br>
<p>use the PE_HOSTFILE that is generated by the qsh -pe my_pe for tight 
<br>
integration, so the host names may be the ones without the &quot;x&quot;. But then 
<br>
in your mpirun command, specify the interfaces you would like to 
<br>
exclude, e.g. all except for the gigE interface. See if that works instead.
<br>
<p>-mca btl_tcp_if_exclude lo,all_my_non_gigE_if
<br>
<p>Orion Poplawski wrote:
<br>
<span class="quotelev1">&gt; Pak Lui wrote:
</span><br>
<span class="quotelev2">&gt;&gt; Hi Orion and Reuti,
</span><br>
<span class="quotelev2">&gt;&gt;
</span><br>
<span class="quotelev2">&gt;&gt; Let me see if I can understand the issue by breaking them down first:
</span><br>
<span class="quotelev2">&gt;&gt;
</span><br>
<span class="quotelev2">&gt;&gt; (1) First, I am curious to know why you would need to create a 
</span><br>
<span class="quotelev2">&gt;&gt; PE_HOSTFILE yourself, because that file is generated by SGE/N1GE when 
</span><br>
<span class="quotelev2">&gt;&gt; you specify you are running a parallel job under SGE/N1GE, by doing 
</span><br>
<span class="quotelev2">&gt;&gt; something like this with qsub/qsh/qrsh, etc:
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; In our setup (which I don't believe is very unique) the nodes are 
</span><br>
<span class="quotelev1">&gt; connected by two networks:  an &quot;admin&quot; network which allows for 
</span><br>
<span class="quotelev1">&gt; connections from outside the cluster and an &quot;MPI&quot; network that is a 
</span><br>
<span class="quotelev1">&gt; private GigE network connecting the nodes for MPI traffic:
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt;        +---------admin net (192.168.0.X)--------+
</span><br>
<span class="quotelev1">&gt;        |                           |            |
</span><br>
<span class="quotelev1">&gt; +-----------+                 +--------+    +--------+
</span><br>
<span class="quotelev1">&gt; | SGE Master|                 | coop00 |    | coop01 |
</span><br>
<span class="quotelev1">&gt; |           |                 | coop00x|    | coop01x|
</span><br>
<span class="quotelev1">&gt; +-----------+                 +--------+    +--------+
</span><br>
<span class="quotelev1">&gt;                                    |            |
</span><br>
<span class="quotelev1">&gt;                                    +------------+
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt;                                     MPI net (192.168.1.X)
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; So the &quot;x&quot; suffix names are the addresses on the MPI network.
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; Currently (loose integration), we create machines files like:
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; coop00x.cora.nwra.com cpu=2
</span><br>
<span class="quotelev1">&gt; coop01x.cora.nwra.com cpu=2
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; which makes the MPI traffic travel over the MPI network.  I'm trying to 
</span><br>
<span class="quotelev1">&gt; duplicate this under &quot;tight&quot; integration.
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev2">&gt;&gt;
</span><br>
<span class="quotelev2">&gt;&gt; (2) As for the following error message:
</span><br>
<span class="quotelev2">&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;  &gt; error: commlib error: access denied (client IP resolved to host name
</span><br>
<span class="quotelev3">&gt;&gt;  &gt; &quot;coop01x.cora.nwra.com&quot;. This is not identical to clients host name
</span><br>
<span class="quotelev3">&gt;&gt;  &gt; &quot;coop01.cora.nwra.com&quot;)
</span><br>
<span class="quotelev2">&gt;&gt;
</span><br>
<span class="quotelev2">&gt;&gt; As you mentioned in your setup, each node has 2 interfaces. And this 
</span><br>
<span class="quotelev2">&gt;&gt; message is an SGE error and it seems to tell you that SGE cannot 
</span><br>
<span class="quotelev2">&gt;&gt; resolve the host name.
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; No, it says that the IP resolved to &quot;coop01x.cora.nwra.com&quot;, but the 
</span><br>
<span class="quotelev1">&gt; machines' primary hostname is &quot;coop01.cora.nwra.com&quot;.
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev2">&gt;&gt;
</span><br>
<span class="quotelev2">&gt;&gt; (4) As for what you have mentioned here:
</span><br>
<span class="quotelev2">&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;  &gt; Now, looking at the OpenMPI gridengine code, it looks like it gets the
</span><br>
<span class="quotelev3">&gt;&gt;  &gt; node name from the first entry in the pe_hostfile, and never really 
</span><br>
<span class="quotelev2">&gt;&gt; uses
</span><br>
<span class="quotelev3">&gt;&gt;  &gt; the queue name for anything.
</span><br>
<span class="quotelev3">&gt;&gt;  &gt;
</span><br>
<span class="quotelev3">&gt;&gt;  &gt;          ptr = strtok_r(buf, &quot; \n&quot;, &amp;tok);
</span><br>
<span class="quotelev3">&gt;&gt;  &gt;          num = strtok_r(NULL, &quot; \n&quot;, &amp;tok);
</span><br>
<span class="quotelev3">&gt;&gt;  &gt;          queue = strtok_r(NULL, &quot; \n&quot;, &amp;tok);
</span><br>
<span class="quotelev3">&gt;&gt;  &gt;          arch = strtok_r(NULL, &quot; \n&quot;, &amp;tok);
</span><br>
<span class="quotelev3">&gt;&gt;  &gt; ...
</span><br>
<span class="quotelev3">&gt;&gt;  &gt;          node-&gt;node_name = strdup(ptr);
</span><br>
<span class="quotelev3">&gt;&gt;  &gt;          node-&gt;node_arch = strdup(arch);
</span><br>
<span class="quotelev3">&gt;&gt;  &gt;
</span><br>
<span class="quotelev3">&gt;&gt;  &gt; Perhaps it can be modified it uses the queue name hostname when doing
</span><br>
<span class="quotelev3">&gt;&gt;  &gt; SGE/qrsh calls, but the first hostname when doing MPI communication.
</span><br>
<span class="quotelev3">&gt;&gt;  &gt; Not really sure what the intent of the two fields in SGE's pe_hostfile
</span><br>
<span class="quotelev3">&gt;&gt;  &gt; is, or if OpenMPI can handle the idea of two hostnames for different
</span><br>
<span class="quotelev3">&gt;&gt;  &gt; purposes.
</span><br>
<span class="quotelev3">&gt;&gt;  &gt;
</span><br>
<span class="quotelev2">&gt;&gt;
</span><br>
<span class="quotelev2">&gt;&gt; Once it is in a parallel environment of SGE (e.g. when you have 
</span><br>
<span class="quotelev2">&gt;&gt; started a parallel job with &quot;qsh/qsub/qrsh -pe name_of_pe&quot;), in ORTE 
</span><br>
<span class="quotelev2">&gt;&gt; would use the -inherit flag of qrsh to tell qrsh to start a task in a 
</span><br>
<span class="quotelev2">&gt;&gt; already scheduled parallel job, therefore we cannot assign another 
</span><br>
<span class="quotelev2">&gt;&gt; queue to the job
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; I don't want to assign another queue to the job.  Assuming a pe_hostfile 
</span><br>
<span class="quotelev1">&gt; of:
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; coop01x.cora.nwra.com 2 coop.q_at_[hidden] &lt;NULL&gt;
</span><br>
<span class="quotelev1">&gt; coop00x.cora.nwra.com 2 coop.q_at_[hidden] &lt;NULL&gt;
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; I would like ORTE to use &quot;coop01.cora.nwra.com&quot; and 
</span><br>
<span class="quotelev1">&gt; &quot;coop00.cora.nwra.com&quot; (taken from the hostname parts of the queue 
</span><br>
<span class="quotelev1">&gt; names) for use with qrsh, and &quot;coop01x.cora.nwra.com&quot; and 
</span><br>
<span class="quotelev1">&gt; &quot;coop00x.cora.nwra.com&quot; as the hostnames to use for MPI traffic.
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; Again, this is just a stab at some way to hack what I want to achieve, 
</span><br>
<span class="quotelev1">&gt; which is SGE/admin traffic traveling over one network, and MPI traffic 
</span><br>
<span class="quotelev1">&gt; traveling over another.  I don't care how it is done.
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; Thanks!
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; - Orion
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<p><p><pre>
-- 
Thanks,
- Pak Lui
pak.lui_at_[hidden]
</pre>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="1132.php">Jeff Squyres: "Re: [OMPI devel] some stuff defined for Fortran but not for C"</a>
<li><strong>Previous message:</strong> <a href="1130.php">Lisandro Dalcin: "[OMPI devel] some stuff defined for Fortran but not for C"</a>
<li><strong>In reply to:</strong> <a href="1129.php">Orion Poplawski: "Re: [OMPI devel] [GE users] OpenMPI 1.2 integration and dedicated MPI networks"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="http://www.open-mpi.org/community/lists/devel/2006/11/1159.php">Orion Poplawski: "Re: [OMPI devel] [GE users] OpenMPI 1.2 integration and dedicated MPI networks"</a>
<li><strong>Reply:</strong> <a href="http://www.open-mpi.org/community/lists/devel/2006/11/1159.php">Orion Poplawski: "Re: [OMPI devel] [GE users] OpenMPI 1.2 integration and dedicated MPI networks"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
