<?php
$topdir = "../../../..";
# Note that we must use the PHP "$$" indirection to assign to the
# "title" variable, because if we list "$ title" (without the space)
# in this file, Doxygen will replace it with a string title.
$ver = basename(getcwd());
$thwarting_doxygen_preprocessor = "title";
$$thwarting_doxygen_preprocessor = "Portable Hardware Locality (hwloc) Documentation: $ver";
$header_include_file = "$topdir/projects/hwloc/doc/$ver/www.open-mpi.org-css.inc";

include_once("$topdir/projects/hwloc/nav.inc");
include_once("$topdir/includes/header.inc");
include_once("$topdir/includes/code.inc");
?>
<!-- Generated by Doxygen 1.7.4 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="pages.php"><span>Related&#160;Pages</span></a></li>
      <li class="current"><a href="modules.php"><span>Modules</span></a></li>
      <li><a href="annotated.php"><span>Data&#160;Structures</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="headertitle">
<div class="title">Modules</div>  </div>
</div>
<div class="contents">
<div class="textblock">Here is a list of all modules:</div><ul>
<li><a class="el" href="a00037.php">API version</a></li>
<li><a class="el" href="a00038.php">Topology context</a></li>
<li><a class="el" href="a00039.php">Object sets (hwloc_cpuset_t and hwloc_nodeset_t)</a></li>
<li><a class="el" href="a00040.php">Topology Object Types</a></li>
<li><a class="el" href="a00041.php">Topology Objects</a></li>
<li><a class="el" href="a00042.php">Create and Destroy Topologies</a></li>
<li><a class="el" href="a00043.php">Configure Topology Detection</a></li>
<li><a class="el" href="a00044.php">Tinker With Topologies.</a></li>
<li><a class="el" href="a00045.php">Get Some Topology Information</a></li>
<li><a class="el" href="a00046.php">Retrieve Objects</a></li>
<li><a class="el" href="a00047.php">Object/String Conversion</a></li>
<li><a class="el" href="a00048.php">CPU binding</a></li>
<li><a class="el" href="a00049.php">Memory binding</a></li>
<li><a class="el" href="a00050.php">Object Type Helpers</a></li>
<li><a class="el" href="a00051.php">Basic Traversal Helpers</a></li>
<li><a class="el" href="a00052.php">Finding Objects Inside a CPU set</a></li>
<li><a class="el" href="a00053.php">Finding a single Object covering at least CPU set</a></li>
<li><a class="el" href="a00054.php">Finding a set of similar Objects covering at least a CPU set</a></li>
<li><a class="el" href="a00055.php">Cache-specific Finding Helpers</a></li>
<li><a class="el" href="a00056.php">Advanced Traversal Helpers</a></li>
<li><a class="el" href="a00057.php">Binding Helpers</a></li>
<li><a class="el" href="a00058.php">Cpuset Helpers</a></li>
<li><a class="el" href="a00059.php">Nodeset Helpers</a></li>
<li><a class="el" href="a00060.php">Conversion between cpuset and nodeset</a></li>
<li><a class="el" href="a00061.php">Distances</a></li>
<li><a class="el" href="a00062.php">Advanced I/O object traversal helpers</a></li>
<li><a class="el" href="a00063.php">The bitmap API</a></li>
<li><a class="el" href="a00064.php">Helpers for manipulating glibc sched affinity</a></li>
<li><a class="el" href="a00065.php">Linux-only helpers</a></li>
<li><a class="el" href="a00066.php">Helpers for manipulating Linux libnuma unsigned long masks</a></li>
<li><a class="el" href="a00067.php">Helpers for manipulating Linux libnuma bitmask</a></li>
<li><a class="el" href="a00068.php">Helpers for manipulating Linux libnuma nodemask_t</a></li>
<li><a class="el" href="a00069.php">CUDA Driver API Specific Functions</a></li>
<li><a class="el" href="a00070.php">CUDA Runtime API Specific Functions</a></li>
<li><a class="el" href="a00071.php">OpenFabrics-Specific Functions</a></li>
<li><a class="el" href="a00072.php">Myrinet Express-Specific Functions</a></li>
</ul>
</div>
<?php
include_once("$topdir/includes/footer.inc");
