<?php
$topdir = "../../../..";
# Note that we must use the PHP "$$" indirection to assign to the
# "title" variable, because if we list "$ title" (without the space)
# in this file, Doxygen will replace it with a string title.
$ver = basename(getcwd());
$thwarting_doxygen_preprocessor = "title";
$$thwarting_doxygen_preprocessor = "Portable Hardware Locality (hwloc) Documentation: $ver";
$header_include_file = "$topdir/projects/hwloc/doc/$ver/www.open-mpi.org-css.inc";
include_once("$topdir/projects/hwloc/nav.inc");
include_once("$topdir/includes/header.inc");
include_once("$topdir/includes/code.inc");
?>
<!-- Generated by Doxygen 1.8.13 -->
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
$(function() {
  initMenu('',false,false,'search.php','Search');
});
</script>
<div id="main-nav"></div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#nested-classes">Data Structures</a> &#124;
<a href="#pub-attribs">Data Fields</a>  </div>
  <div class="headertitle">
<div class="title">hwloc_obj_memory_s Struct Reference<div class="ingroups"><a class="el" href="a00134.php">Object Structure and Attributes</a></div></div>  </div>
</div><!--header-->
<div class="contents">

<p><code>#include &lt;<a class="el" href="a00083_source.php">hwloc.h</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Data Structures</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">struct &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="a00182.php">hwloc_obj_memory_page_type_s</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-attribs"></a>
Data Fields</h2></td></tr>
<tr class="memitem:a8befd0b3f4f8b695cafed04b31f36a44"><td class="memItemLeft" align="right" valign="top">hwloc_uint64_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="a00178.php#a8befd0b3f4f8b695cafed04b31f36a44">total_memory</a></td></tr>
<tr class="separator:a8befd0b3f4f8b695cafed04b31f36a44"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aace044c7f3fd9dffe50202296bf1dc5a"><td class="memItemLeft" align="right" valign="top">hwloc_uint64_t&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="a00178.php#aace044c7f3fd9dffe50202296bf1dc5a">local_memory</a></td></tr>
<tr class="separator:aace044c7f3fd9dffe50202296bf1dc5a"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a208c27f4491077d7fb9ba5db8b29cb57"><td class="memItemLeft" align="right" valign="top">unsigned&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="a00178.php#a208c27f4491077d7fb9ba5db8b29cb57">page_types_len</a></td></tr>
<tr class="separator:a208c27f4491077d7fb9ba5db8b29cb57"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a865eba7b12b986d72dbe7a2cfd97c50d"><td class="memItemLeft" align="right" valign="top">struct <a class="el" href="a00182.php">hwloc_obj_memory_s::hwloc_obj_memory_page_type_s</a> *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="a00178.php#a865eba7b12b986d72dbe7a2cfd97c50d">page_types</a></td></tr>
<tr class="separator:a865eba7b12b986d72dbe7a2cfd97c50d"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Object memory. </p>
</div><h2 class="groupheader">Field Documentation</h2>
<a id="aace044c7f3fd9dffe50202296bf1dc5a"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aace044c7f3fd9dffe50202296bf1dc5a">&#9670;&nbsp;</a></span>local_memory</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">hwloc_uint64_t hwloc_obj_memory_s::local_memory</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Local memory (in bytes) </p>

</div>
</div>
<a id="a865eba7b12b986d72dbe7a2cfd97c50d"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a865eba7b12b986d72dbe7a2cfd97c50d">&#9670;&nbsp;</a></span>page_types</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">struct <a class="el" href="a00182.php">hwloc_obj_memory_s::hwloc_obj_memory_page_type_s</a> *  hwloc_obj_memory_s::page_types</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a208c27f4491077d7fb9ba5db8b29cb57"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a208c27f4491077d7fb9ba5db8b29cb57">&#9670;&nbsp;</a></span>page_types_len</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">unsigned hwloc_obj_memory_s::page_types_len</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Size of array <code>page_types</code>. </p>

</div>
</div>
<a id="a8befd0b3f4f8b695cafed04b31f36a44"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a8befd0b3f4f8b695cafed04b31f36a44">&#9670;&nbsp;</a></span>total_memory</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">hwloc_uint64_t hwloc_obj_memory_s::total_memory</td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Total memory (in bytes) in this object and its children. </p>

</div>
</div>
<hr/>The documentation for this struct was generated from the following file:<ul>
<li><a class="el" href="a00083_source.php">hwloc.h</a></li>
</ul>
</div><!-- contents -->
<?php
include_once("$topdir/includes/footer.inc");
