<?php
$topdir = "../../../..";
# Note that we must use the PHP "$$" indirection to assign to the
# "title" variable, because if we list "$ title" (without the space)
# in this file, Doxygen will replace it with a string title.
$ver = basename(getcwd());
$thwarting_doxygen_preprocessor = "title";
$$thwarting_doxygen_preprocessor = "Portable Hardware Locality (hwloc) Documentation: $ver";
$header_include_file = "$topdir/projects/hwloc/doc/$ver/www.open-mpi.org-css.inc";

include_once("$topdir/projects/hwloc/nav.inc");
include_once("$topdir/includes/header.inc");
include_once("$topdir/includes/code.inc");
?>
<!-- Generated by Doxygen 1.7.4 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="modules.php"><span>Modules</span></a></li>
      <li><a href="annotated.php"><span>Data&#160;Structures</span></a></li>
      <li><a href="files.php"><span>Files</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<div class="title">Myrinet Express-Specific Functions</div>  </div>
</div>
<div class="contents">
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="func-members"></a>
Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static inline int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="a00072.php#ga87f4746d0cad579ce4e86b98088f22a1">hwloc_mx_board_get_device_cpuset</a> (<a class="el" href="a00038.php#ga9d1e76ee15a7dee158b786c30b6a6e38">hwloc_topology_t</a> topology, unsigned id, <a class="el" href="a00039.php#ga4bbf39b68b6f568fb92739e7c0ea7801">hwloc_cpuset_t</a> set)</td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static inline int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="a00072.php#ga2ff7763b9c2c5975f9a2e3d638351535">hwloc_mx_endpoint_get_device_cpuset</a> (<a class="el" href="a00038.php#ga9d1e76ee15a7dee158b786c30b6a6e38">hwloc_topology_t</a> topology, mx_endpoint_t endpoint, <a class="el" href="a00039.php#ga4bbf39b68b6f568fb92739e7c0ea7801">hwloc_cpuset_t</a> set)</td></tr>
</table>
<hr/><h2>Function Documentation</h2>
<a class="anchor" id="ga87f4746d0cad579ce4e86b98088f22a1"></a><!-- doxytag: member="myriexpress.h::hwloc_mx_board_get_device_cpuset" ref="ga87f4746d0cad579ce4e86b98088f22a1" args="(hwloc_topology_t topology, unsigned id, hwloc_cpuset_t set)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">static inline int hwloc_mx_board_get_device_cpuset </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="a00038.php#ga9d1e76ee15a7dee158b786c30b6a6e38">hwloc_topology_t</a>&#160;</td>
          <td class="paramname"><em>topology</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">unsigned&#160;</td>
          <td class="paramname"><em>id</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="a00039.php#ga4bbf39b68b6f568fb92739e7c0ea7801">hwloc_cpuset_t</a>&#160;</td>
          <td class="paramname"><em>set</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Get the CPU set of logical processors that are physically close the MX board <code>id</code>. </p>
<p>For the given Myrinet Express board index <code>id</code>, read the OS-provided NUMA node and return the corresponding CPU set. </p>

</div>
</div>
<a class="anchor" id="ga2ff7763b9c2c5975f9a2e3d638351535"></a><!-- doxytag: member="myriexpress.h::hwloc_mx_endpoint_get_device_cpuset" ref="ga2ff7763b9c2c5975f9a2e3d638351535" args="(hwloc_topology_t topology, mx_endpoint_t endpoint, hwloc_cpuset_t set)" -->
<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">static inline int hwloc_mx_endpoint_get_device_cpuset </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="a00038.php#ga9d1e76ee15a7dee158b786c30b6a6e38">hwloc_topology_t</a>&#160;</td>
          <td class="paramname"><em>topology</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">mx_endpoint_t&#160;</td>
          <td class="paramname"><em>endpoint</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype"><a class="el" href="a00039.php#ga4bbf39b68b6f568fb92739e7c0ea7801">hwloc_cpuset_t</a>&#160;</td>
          <td class="paramname"><em>set</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td><code> [static]</code></td>
        </tr>
      </table>
</div>
<div class="memdoc">

<p>Get the CPU set of logical processors that are physically close to endpoint <code>endpoint</code>. </p>
<p>For the given Myrinet Express endpoint <code>endpoint</code>, read the OS-provided NUMA node and return the corresponding CPU set. </p>

</div>
</div>
</div>
<?php
include_once("$topdir/includes/footer.inc");
