<?php
include_once("$topdir/includes/nav.inc");

$this_dir = "orcm";
$this_nav[] = new Nav("Download v0.5 (preview)", "$topdir/software/orcm/v0.5/");
$this_nav[] = new Nav("Documentation", "https://github.com/open-mpi/orcm/wiki");
$this_nav[] = new Nav("License", "$topdir/projects/orcm/license.php");
$this_nav[] = new Nav("Mailing lists", "$topdir/community/lists/orcm.php");
$this_nav[] = new Nav("Bug tracking", "https://github.com/open-mpi/orcm/issues");
$this_nav[] = new Nav("GIT access", "https://github.com/open-mpi/orcm");
$this_nav[] = new Nav("Nightly snapshots", "$topdir/software/orcm/nightly/");
