<?php
$title = "TEG: A High-Performance, Scalable, Multi-Network Point-to-Point Communications Methodology";
$overview = "Overview and descrption of the point-to-point message passing design in Open MPI, focusing on the TEG PML component.";

$authors = "T.S. Woodall, R.L. Graham, R.H. Castain, D.J. Daniel,
M.W. Sukalski, G.E. Fagg, E. Gabriel, G. Bosilca, T. Angskun,
J.J. Dongarra, J.M. Squyres, V. Sahay, P. Kambadur, B. Barrett, A. Lumsdaine";

$abstract = "TEG is a new component-based methodology for
point-to-point messaging. Developed as part of the Open MPI project,
TEG provides a configurable fault-tolerant capability for
high-performance messaging that utilizes multi-network interfaces
where available. Initial performance comparisons with other MPI
implementations show comparable ping-pong latencies, but with
bandwidths up to 30% higher.";

$presented = "Euro PVM/MPI 2004, September, 2004, in Budapest, Hungary.";

$files[] = "euro-pvmmpi-2004-p2p.ps";
$files[] = "euro-pvmmpi-2004-p2p.pdf";

$month = 9;
$day = 20;
$year = 2004;

$bibtex = "@InProceedings{woodall04:_teg,
  author       = {T.S. Woodall and R.L. Graham and R.H. Castain and
                  D.J. Daniel and M.W. Sukalski and G.E. Fagg and
                  E. Gabriel and G. Bosilca and T. Angskun and
                  J.J. Dongarra and J.M. Squyres and V. Sahay and
                  P. Kambadur and B. Barrett and A. Lumsdaine},
  title        = {{TEG}: A High-Performance, Scalable, Multi-Network
                  Point-to-Point Communications Methodology},
  booktitle    = {Proceedings, 11th European PVM/MPI Users' Group
                  Meeting},
  year         = 2004,
  address      = {Budapest, Hungary},
  pages        = {303--310},
  month        = {September}
}";

