<?
$subject_val = "Re: [OMPI devel] 1.7.4rc2r30148 - static link failure on NetBSD";
include("../../include/msg-header.inc");
?>
<!-- received="Sat Jan 11 19:59:16 2014" -->
<!-- isoreceived="20140112005916" -->
<!-- sent="Sat, 11 Jan 2014 16:59:13 -0800" -->
<!-- isosent="20140112005913" -->
<!-- name="Paul Hargrove" -->
<!-- email="phhargrove_at_[hidden]" -->
<!-- subject="Re: [OMPI devel] 1.7.4rc2r30148 - static link failure on NetBSD" -->
<!-- id="CAAvDA17xYZdiG1qU2v0Qs-SHixGyd4Lse5Cxq=MV3z+N5qWJuQ_at_mail.gmail.com" -->
<!-- charset="ISO-8859-1" -->
<!-- inreplyto="CAAvDA16kod_ER4=Aj6Kce85B0zJ3ceVXSGjQSRaC1Q7-3sH-jA_at_mail.gmail.com" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> Re: [OMPI devel] 1.7.4rc2r30148 - static link failure on NetBSD<br>
<strong>From:</strong> Paul Hargrove (<em>phhargrove_at_[hidden]</em>)<br>
<strong>Date:</strong> 2014-01-11 19:59:13
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="13751.php">Paul Hargrove: "Re: [OMPI devel] Paul's testing summary"</a>
<li><strong>Previous message:</strong> <a href="13749.php">Paul Hargrove: "Re: [OMPI devel] Paul's testing summary"</a>
<li><strong>In reply to:</strong> <a href="13591.php">Paul Hargrove: "[OMPI devel] 1.7.4rc2r30148 - static link failure on NetBSD"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="13760.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] 1.7.4rc2r30148 - static link failure on NetBSD"</a>
<li><strong>Reply:</strong> <a href="13760.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] 1.7.4rc2r30148 - static link failure on NetBSD"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Digging through my emails I found an issue (in the email quoted below) that
<br>
I had forgotten about.
<br>
The basic issue is that NetBSD puts aio support in librt rather than libc,
<br>
but this is only visible when linking statically.
<br>
<p>Fortunately, NetBSD is one of the very few platforms on which I have
<br>
sufficiently new autotools to run autogen.pl.
<br>
The patch below resolves the problem for me.
<br>
However, I am not certain if/how this fits with OMPI's standard practices
<br>
with regards to configure tests.
<br>
<p>-Paul
<br>
<p>--- openmpi-1.9a1r30255/ompi/mca/fbtl/posix/configure.m4~       2014-01-11
<br>
15:53:19.000000000 -0800
<br>
+++ openmpi-1.9a1r30255/ompi/mca/fbtl/posix/configure.m4        2014-01-11
<br>
16:25:53.000000000 -0800
<br>
@@ -25,9 +25,11 @@
<br>
&nbsp;AC_DEFUN([MCA_ompi_fbtl_posix_CONFIG],[
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AC_CONFIG_FILES([ompi/mca/fbtl/posix/Makefile])
<br>
<p>+    fbtl_posix_happy=&quot;no&quot;
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AC_CHECK_HEADER([aio.h],
<br>
-                    [fbtl_posix_happy=&quot;yes&quot;],
<br>
-                    [fbtl_posix_happy=&quot;no&quot;])
<br>
+        [dnl NetBSD has aio_* in -lrt, usually in libc
<br>
+         OMPI_CHECK_FUNC_LIB([aio_write], [rt],
<br>
+             [fbtl_posix_happy=&quot;yes&quot;])])
<br>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;AS_IF([test &quot;$fbtl_posix_happy&quot; = &quot;yes&quot;],
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[$1],
<br>
<p><p><p>On Wed, Jan 8, 2014 at 11:22 AM, Paul Hargrove &lt;phhargrove_at_[hidden]&gt; wrote:
<br>
<p><span class="quotelev1">&gt; When I compile the current 1.7.4rc on NetBSD with no configure arguments,
</span><br>
<span class="quotelev1">&gt; I still get the &quot;make install&quot; failure that I have detailed in previous
</span><br>
<span class="quotelev1">&gt; emails.
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; HOWEVER, if I configure with &quot;--enable-static --disable-shared&quot; then I get
</span><br>
<span class="quotelev1">&gt; an earlier failure at build time (partial &quot;make V=1&quot; output shown below).
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; When linking otfmerge-mpi, the aio_* symbols from
</span><br>
<span class="quotelev1">&gt; libmpi.a(ompi/mca/fbtl/posix/fbtl_posix_ipwritev.o) are not resolved.
</span><br>
<span class="quotelev1">&gt;  According to the man pages on this system, those symbols reside in librt,
</span><br>
<span class="quotelev1">&gt; but there is no occurrence of &quot;-lrt&quot; in either the libtool command line or
</span><br>
<span class="quotelev1">&gt; the gcc command line generated by libtool.
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; NOTE, however, that this problem does NOT occur when building a default
</span><br>
<span class="quotelev1">&gt; shared library version despite ALSO lacking any explicit &quot;-lrt&quot; in the link
</span><br>
<span class="quotelev1">&gt; command.
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; -Paul
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; /bin/ksh ../../../libtool  --tag=CC    --mode=link gcc -DOTFMERGE_MPI
</span><br>
<span class="quotelev1">&gt;  -g -finline-functions -fno-strict-aliasing -pthread
</span><br>
<span class="quotelev1">&gt;  -L/home/phargrov/OMPI/openmpi-1.7-latest-netbsd6-amd64/BLD/ompi/contrib/vt/vt/../../../.libs
</span><br>
<span class="quotelev1">&gt; -o otfmerge-mpi otfmerge_mpi-handler.o  otfmerge_mpi-otfmerge.o
</span><br>
<span class="quotelev1">&gt; ../../../otflib/libopen-trace-format.la  ../../../otfauxlib/libotfaux.la-lmpi
</span><br>
<span class="quotelev1">&gt; libtool: link: gcc -DOTFMERGE_MPI -g -finline-functions
</span><br>
<span class="quotelev1">&gt; -fno-strict-aliasing -pthread -o otfmerge-mpi otfmerge_mpi-handler.o
</span><br>
<span class="quotelev1">&gt; otfmerge_mpi-otfmerge.o
</span><br>
<span class="quotelev1">&gt;  -L/home/phargrov/OMPI/openmpi-1.7-latest-netbsd6-amd64/BLD/ompi/contrib/vt/vt/../../../.libs
</span><br>
<span class="quotelev1">&gt; ../../../otflib/.libs/libopen-trace-format.a -lz
</span><br>
<span class="quotelev1">&gt; ../../../otfauxlib/.libs/libotfaux.a
</span><br>
<span class="quotelev1">&gt; /home/phargrov/OMPI/openmpi-1.7-latest-netbsd6-amd64/BLD/ompi/contrib/vt/vt/../../../.libs/libmpi.a
</span><br>
<span class="quotelev1">&gt; /home/phargrov/OMPI/openmpi-1.7-latest-netbsd6-amd64/BLD/orte/.libs/libopen-rte.a
</span><br>
<span class="quotelev1">&gt; /home/phargrov/OMPI/openmpi-1.7-latest-netbsd6-amd64/BLD/opal/.libs/libopen-pal.a
</span><br>
<span class="quotelev1">&gt; -lutil -lm -lpthread -pthread
</span><br>
<span class="quotelev1">&gt; /home/phargrov/OMPI/openmpi-1.7-latest-netbsd6-amd64/BLD/ompi/contrib/vt/vt/../../../.libs/libmpi.a(fbtl_posix_ipwritev.o):
</span><br>
<span class="quotelev1">&gt; In function `mca_fbtl_posix_ipwritev':
</span><br>
<span class="quotelev1">&gt; /home/phargrov/OMPI/openmpi-1.7-latest-netbsd6-amd64/openmpi-1.7-latest/ompi/mca/fbtl/posix/fbtl_posix_ipwritev.c:90:
</span><br>
<span class="quotelev1">&gt; undefined reference to `aio_write'
</span><br>
<span class="quotelev1">&gt; /home/phargrov/OMPI/openmpi-1.7-latest-netbsd6-amd64/openmpi-1.7-latest/ompi/mca/fbtl/posix/fbtl_posix_ipwritev.c:112:
</span><br>
<span class="quotelev1">&gt; undefined reference to `aio_write'
</span><br>
<span class="quotelev1">&gt; /home/phargrov/OMPI/openmpi-1.7-latest-netbsd6-amd64/openmpi-1.7-latest/ompi/mca/fbtl/posix/fbtl_posix_ipwritev.c:159:
</span><br>
<span class="quotelev1">&gt; undefined reference to `aio_write'
</span><br>
<span class="quotelev1">&gt; /home/phargrov/OMPI/openmpi-1.7-latest-netbsd6-amd64/openmpi-1.7-latest/ompi/mca/fbtl/posix/fbtl_posix_ipwritev.c:180:
</span><br>
<span class="quotelev1">&gt; undefined reference to `aio_write'
</span><br>
<span class="quotelev1">&gt; *** Error code 1
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; Stop.
</span><br>
<span class="quotelev1">&gt; make: stopped in
</span><br>
<span class="quotelev1">&gt; /home/phargrov/OMPI/openmpi-1.7-latest-netbsd6-amd64/BLD/ompi/contrib/vt/vt/extlib/otf/tools/otfmerge/mpi
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; --
</span><br>
<span class="quotelev1">&gt; Paul H. Hargrove                          PHHargrove_at_[hidden]
</span><br>
<span class="quotelev1">&gt; Future Technologies Group
</span><br>
<span class="quotelev1">&gt; Computer and Data Sciences Department     Tel: +1-510-495-2352
</span><br>
<span class="quotelev1">&gt; Lawrence Berkeley National Laboratory     Fax: +1-510-486-6900
</span><br>
<span class="quotelev1">&gt;
</span><br>
<p><p><p><pre>
-- 
Paul H. Hargrove                          PHHargrove_at_[hidden]
Future Technologies Group
Computer and Data Sciences Department     Tel: +1-510-495-2352
Lawrence Berkeley National Laboratory     Fax: +1-510-486-6900
</pre>
<hr>
<ul>
<li>text/html attachment: <a href="http://www.open-mpi.org/community/lists/devel/att-13750/attachment">attachment</a>
</ul>
<!-- attachment="attachment" -->
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="13751.php">Paul Hargrove: "Re: [OMPI devel] Paul's testing summary"</a>
<li><strong>Previous message:</strong> <a href="13749.php">Paul Hargrove: "Re: [OMPI devel] Paul's testing summary"</a>
<li><strong>In reply to:</strong> <a href="13591.php">Paul Hargrove: "[OMPI devel] 1.7.4rc2r30148 - static link failure on NetBSD"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="13760.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] 1.7.4rc2r30148 - static link failure on NetBSD"</a>
<li><strong>Reply:</strong> <a href="13760.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] 1.7.4rc2r30148 - static link failure on NetBSD"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
