<?
$subject_val = "Re: [OMPI devel] [EXTERNAL] Open MPI Configure Script";
include("../../include/msg-header.inc");
?>
<!-- received="Mon Jan 28 17:02:33 2013" -->
<!-- isoreceived="20130128220233" -->
<!-- sent="Mon, 28 Jan 2013 22:02:28 +0000" -->
<!-- isosent="20130128220228" -->
<!-- name="Jeff Squyres (jsquyres)" -->
<!-- email="jsquyres_at_[hidden]" -->
<!-- subject="Re: [OMPI devel] [EXTERNAL] Open MPI Configure Script" -->
<!-- id="EF66BBEB19BADC41AC8CCF5F684F07FC42CB9658_at_xmb-rcd-x01.cisco.com" -->
<!-- charset="iso-8859-1" -->
<!-- inreplyto="CAFUQeZ1+MhnNDergRz_8mUWdcb-k6-Z8cPso8dyphH_rtNAFaA_at_mail.gmail.com" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> Re: [OMPI devel] [EXTERNAL] Open MPI Configure Script<br>
<strong>From:</strong> Jeff Squyres (jsquyres) (<em>jsquyres_at_[hidden]</em>)<br>
<strong>Date:</strong> 2013-01-28 17:02:28
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="12038.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] Looking for a replacement call for repeated call	to MPI_IPROBE"</a>
<li><strong>Previous message:</strong> <a href="12036.php">David Beer: "Re: [OMPI devel] [EXTERNAL] Open MPI Configure Script"</a>
<li><strong>In reply to:</strong> <a href="12036.php">David Beer: "Re: [OMPI devel] [EXTERNAL] Open MPI Configure Script"</a>
<!-- nextthread="start" -->
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
You're basically telling your build system to use a C++ compiler as the linker when creating libtorque.  This probably does more-or-less what I suggested: rpath'ing in whatever dependencies you need such that when we link against libtorque, all of the (C++) dependencies that you need are automatically pulled along.
<br>
<p>Glad it got resolved!
<br>
<p><p>On Jan 28, 2013, at 4:55 PM, David Beer &lt;dbeer_at_[hidden]&gt;
<br>
&nbsp;wrote:
<br>
<p><span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; On Mon, Jan 28, 2013 at 12:14 PM, Barrett, Brian W &lt;bwbarre_at_[hidden]&gt; wrote:
</span><br>
<span class="quotelev1">&gt; On 1/28/13 11:54 AM, &quot;David Beer&quot; &lt;dbeer_at_[hidden]&gt; wrote:
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; checking for tm_init in -ltorque... no
</span><br>
<span class="quotelev1">&gt; configure: error: TM support requested but not found.  Aborting
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; Oddly enough, if you have already configured with an older version of TORQUE, you can build open-mpi with TORQUE 4.2 installed, so it can find the function definitions when compiling, its just for some reason it doesn't find them in the configure script. This is why I think that something in the configure script is assuming that libtorque was compiled with gcc.
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; Right, the configure output to stdout/stderr isn't very useful in diagnosing why a test failed.  The config.log file generated by configure will have much more information.
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; All,
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; Thanks for your help. I found a way to resolve this by changing OpenMPI's configure script, but then someone who knows a bit more about these things showed me that we can solve this by defining some more things on our end, namely adding:
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; +LT_LANG([C++])
</span><br>
<span class="quotelev1">&gt; +AC_SUBST([LIBTOOL_DEPS])
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; and 
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; +CCLD=&quot;$CXX&quot;
</span><br>
<span class="quotelev1">&gt; +AC_SUBST([CCLD])
</span><br>
<span class="quotelev1">&gt; +LIBTOOLFLAGS=&quot;--tag=CXX&quot;
</span><br>
<span class="quotelev1">&gt; +AC_SUBST([LIBTOOLFLAGS])
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; to our configure.ac and 
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; +LIBTOOL_DEPS = @LIBTOOL_DEPS@
</span><br>
<span class="quotelev1">&gt; +libtool: $(LIBTOOL_DEPS)
</span><br>
<span class="quotelev1">&gt; + $(SHELL) ./config.status --recheck
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; to our Makefile.am. I'm going to try to look some things up and see why this makes a difference, but I'm guessing that we previously had an incomplete definition that confused OpenMPI's configure script. Thanks for all of your help and I'm glad we could resolve this by fixing TORQUE.
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; -- 
</span><br>
<span class="quotelev1">&gt; David Beer | Senior Software Engineer
</span><br>
<span class="quotelev1">&gt; Adaptive Computing
</span><br>
<span class="quotelev1">&gt; _______________________________________________
</span><br>
<span class="quotelev1">&gt; devel mailing list
</span><br>
<span class="quotelev1">&gt; devel_at_[hidden]
</span><br>
<span class="quotelev1">&gt; <a href="http://www.open-mpi.org/mailman/listinfo.cgi/devel">http://www.open-mpi.org/mailman/listinfo.cgi/devel</a>
</span><br>
<p><p><pre>
-- 
Jeff Squyres
jsquyres_at_[hidden]
For corporate legal information go to: <a href="http://www.cisco.com/web/about/doing_business/legal/cri/">http://www.cisco.com/web/about/doing_business/legal/cri/</a>
</pre>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="12038.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] Looking for a replacement call for repeated call	to MPI_IPROBE"</a>
<li><strong>Previous message:</strong> <a href="12036.php">David Beer: "Re: [OMPI devel] [EXTERNAL] Open MPI Configure Script"</a>
<li><strong>In reply to:</strong> <a href="12036.php">David Beer: "Re: [OMPI devel] [EXTERNAL] Open MPI Configure Script"</a>
<!-- nextthread="start" -->
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
