<?
$subject_val = "Re: [OMPI devel] [EXTERNAL] Open MPI Configure Script";
include("../../include/msg-header.inc");
?>
<!-- received="Mon Jan 28 16:55:07 2013" -->
<!-- isoreceived="20130128215507" -->
<!-- sent="Mon, 28 Jan 2013 14:55:03 -0700" -->
<!-- isosent="20130128215503" -->
<!-- name="David Beer" -->
<!-- email="dbeer_at_[hidden]" -->
<!-- subject="Re: [OMPI devel] [EXTERNAL] Open MPI Configure Script" -->
<!-- id="CAFUQeZ1+MhnNDergRz_8mUWdcb-k6-Z8cPso8dyphH_rtNAFaA_at_mail.gmail.com" -->
<!-- charset="ISO-8859-1" -->
<!-- inreplyto="69A29AB53D57F54D81061A9E4E45B8FD317D7ED7_at_EXMB01.srn.sandia.gov" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> Re: [OMPI devel] [EXTERNAL] Open MPI Configure Script<br>
<strong>From:</strong> David Beer (<em>dbeer_at_[hidden]</em>)<br>
<strong>Date:</strong> 2013-01-28 16:55:03
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="12037.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] [EXTERNAL] Open MPI Configure Script"</a>
<li><strong>Previous message:</strong> <a href="12035.php">Steve Wise: "Re: [OMPI devel] openib unloaded before last mem dereg"</a>
<li><strong>In reply to:</strong> <a href="12027.php">Barrett, Brian W: "Re: [OMPI devel] [EXTERNAL] Open MPI Configure Script"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="12037.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] [EXTERNAL] Open MPI Configure Script"</a>
<li><strong>Reply:</strong> <a href="12037.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] [EXTERNAL] Open MPI Configure Script"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
On Mon, Jan 28, 2013 at 12:14 PM, Barrett, Brian W &lt;bwbarre_at_[hidden]&gt;wrote:
<br>
<p><span class="quotelev1">&gt; On 1/28/13 11:54 AM, &quot;David Beer&quot; &lt;dbeer_at_[hidden]&gt; wrote:
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; checking for tm_init in -ltorque... no
</span><br>
<span class="quotelev1">&gt; configure: error: TM support requested but not found.  Aborting
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; Oddly enough, if you have already configured with an older version of
</span><br>
<span class="quotelev1">&gt; TORQUE, you can build open-mpi with TORQUE 4.2 installed, so it can find
</span><br>
<span class="quotelev1">&gt; the function definitions when compiling, its just for some reason it
</span><br>
<span class="quotelev1">&gt; doesn't find them in the configure script. This is why I think that
</span><br>
<span class="quotelev1">&gt; something in the configure script is assuming that libtorque was compiled
</span><br>
<span class="quotelev1">&gt; with gcc.
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; Right, the configure output to stdout/stderr isn't very useful in
</span><br>
<span class="quotelev1">&gt; diagnosing why a test failed.  The config.log file generated by configure
</span><br>
<span class="quotelev1">&gt; will have much more information.
</span><br>
<span class="quotelev1">&gt;
</span><br>
<p>All,
<br>
<p>Thanks for your help. I found a way to resolve this by changing OpenMPI's
<br>
configure script, but then someone who knows a bit more about these things
<br>
showed me that we can solve this by defining some more things on our end,
<br>
namely adding:
<br>
<p>+LT_LANG([C++])
<br>
+AC_SUBST([LIBTOOL_DEPS])
<br>
<p>and
<br>
<p>+CCLD=&quot;$CXX&quot;
<br>
+AC_SUBST([CCLD])
<br>
+LIBTOOLFLAGS=&quot;--tag=CXX&quot;
<br>
+AC_SUBST([LIBTOOLFLAGS])
<br>
<p>to our configure.ac and
<br>
<p>+LIBTOOL_DEPS = @LIBTOOL_DEPS@
<br>
+libtool: $(LIBTOOL_DEPS)
<br>
+ $(SHELL) ./config.status --recheck
<br>
<p>to our Makefile.am. I'm going to try to look some things up and see why
<br>
this makes a difference, but I'm guessing that we previously had an
<br>
incomplete definition that confused OpenMPI's configure script. Thanks for
<br>
all of your help and I'm glad we could resolve this by fixing TORQUE.
<br>
<p><pre>
-- 
David Beer | Senior Software Engineer
Adaptive Computing
</pre>
<hr>
<ul>
<li>text/html attachment: <a href="http://www.open-mpi.org/community/lists/devel/att-12036/attachment">attachment</a>
</ul>
<!-- attachment="attachment" -->
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="12037.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] [EXTERNAL] Open MPI Configure Script"</a>
<li><strong>Previous message:</strong> <a href="12035.php">Steve Wise: "Re: [OMPI devel] openib unloaded before last mem dereg"</a>
<li><strong>In reply to:</strong> <a href="12027.php">Barrett, Brian W: "Re: [OMPI devel] [EXTERNAL] Open MPI Configure Script"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="12037.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] [EXTERNAL] Open MPI Configure Script"</a>
<li><strong>Reply:</strong> <a href="12037.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] [EXTERNAL] Open MPI Configure Script"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
