<?
$subject_val = "Re: [OMPI devel] vt compiler warnings and errors";
include("../../include/msg-header.inc");
?>
<!-- received="Tue Feb  5 10:36:44 2008" -->
<!-- isoreceived="20080205153644" -->
<!-- sent="Tue, 5 Feb 2008 16:38:28 +0100" -->
<!-- isosent="20080205153828" -->
<!-- name="Andreas Kn&#252;pfer" -->
<!-- email="andreas.knuepfer_at_[hidden]" -->
<!-- subject="Re: [OMPI devel] vt compiler warnings and errors" -->
<!-- id="200802051638.28990.andreas.knuepfer_at_tu-dresden.de" -->
<!-- charset="iso-8859-1" -->
<!-- inreplyto="297D3F07-C93D-45BE-87DD-82FB77D23601_at_cisco.com" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> Re: [OMPI devel] vt compiler warnings and errors<br>
<strong>From:</strong> Andreas Kn&#252;pfer (<em>andreas.knuepfer_at_[hidden]</em>)<br>
<strong>Date:</strong> 2008-02-05 10:38:28
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="3128.php">Brian W. Barrett: "Re: [OMPI devel] xensocket - callbacks through OPAL/libevent"</a>
<li><strong>Previous message:</strong> <a href="3126.php">Muhammad Atif: "[OMPI devel] xensocket - callbacks through OPAL/libevent"</a>
<li><strong>In reply to:</strong> <a href="3111.php">Jeff Squyres: "Re: [OMPI devel] vt compiler warnings and errors"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="3115.php">Tim Prins: "[OMPI devel] More VT warnings"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Hi Everbody,
<br>
<p>we discussed this issue here a lot. Indeed, we were putting the contents of 
<br>
the VampirTrace tarball to the trunk (via the vendor branch stuff).
<br>
<p>Then again, this is no virtue by itself, is it? So we agree to removing the 
<br>
configure scripts from the SVN and having it created by the autogen script.
<br>
This might resolve possible problems because of differing autoconf versions 
<br>
etc. 
<br>
<p>See/hear you at the telco, Andreas
<br>
<p><p>On Friday 01 February 2008, Jeff Squyres wrote:
<br>
<span class="quotelev1">&gt; On Feb 1, 2008, at 5:35 AM, Ralf Wildenhues wrote:
</span><br>
<span class="quotelev2">&gt; &gt; These files do not belong in SVN, they are generated by aclocal:
</span><br>
<span class="quotelev2">&gt; &gt;  ompi/contrib/vt/vt/extlib/otf/aclocal.m4
</span><br>
<span class="quotelev2">&gt; &gt;  ompi/contrib/vt/vt/aclocal.m4
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; I think both of these have their own configure scripts, meaning that
</span><br>
<span class="quotelev1">&gt; they were autoconfed/automaked/whatever before they were put into OMPI.
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; And in hindsight, this fits in with exactly what our original goal
</span><br>
<span class="quotelev1">&gt; was: take a VT tarball and dump it into OMPI's SVN.  Doh!
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; So I think the question still remains: can we hook VT's autoconf (et
</span><br>
<span class="quotelev1">&gt; al.) requirements into the top-level autogen.sh so that the trunk copy
</span><br>
<span class="quotelev1">&gt; of vt doesn't have configure/aclocal.m4/etc. and OMPI's top-level
</span><br>
<span class="quotelev1">&gt; autogen.sh will create them?
</span><br>
<p><p><p><pre>
-- 
Dipl. Math. Andreas Knuepfer, 
Center for Information Services and 
High Performance Computing (ZIH), TU Dresden, 
Willersbau A114, Zellescher Weg 12, 01062 Dresden
phone +49-351-463-38323, fax +49-351-463-37773

</pre>
<hr>
<ul>
<li>application/pgp-signature attachment: <a href="http://www.open-mpi.org/community/lists/devel/att-3127/signature.asc_">This is a digitally signed message part.</a>
</ul>
<!-- attachment="signature.asc_" -->
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="3128.php">Brian W. Barrett: "Re: [OMPI devel] xensocket - callbacks through OPAL/libevent"</a>
<li><strong>Previous message:</strong> <a href="3126.php">Muhammad Atif: "[OMPI devel] xensocket - callbacks through OPAL/libevent"</a>
<li><strong>In reply to:</strong> <a href="3111.php">Jeff Squyres: "Re: [OMPI devel] vt compiler warnings and errors"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="3115.php">Tim Prins: "[OMPI devel] More VT warnings"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
