<?php
$title = "Supercomputing 2025 slides";
$overview = "Slides from the Open MPI State of the Union BOF at SC'25";

$authors = "Howard Pritchard, George Bosilca, Aurelien Bouteiller, Thomas Naughton";

$abstract = "Slides from the Open MPI State of the Union XVII Community
Meeting at SC'25.";

$presented = "<a href=\"http://sc24.supercomputing.org/\">" . "SC'25</a>,
November 16, 2025, St. Louis , MO, USA";

$files[] = "Open-MPI-SC25-BOF.pdf";

$month = 11;
$day = 16;
$year = 2025;

$bibtex = "";
