<?php
$title = "ECP Community BOF Days: Open MPI State of the Union BOF 2021 slides";
$overview = "Slides from the Open MPI State of the Union BOF at during the ECP Community BOF Days event";

$authors = "George Bosilca, Jeff Squyres, Howard Pritchard, Joshua Ladd";

$abstract = "Slides from the Open MPI State of the Union XIII.5 Community
Meeting at ECP Community BOF Days 2021.";

$presented = "<a href=\"https://www.exascaleproject.org/event/ecp-community-bof-days-2021/\">ECP Community BOF Days 2021</a>,
March 30, 2021 (webinar)";

$files[] = "ompi-ecp-community-bofs-2021.pdf";

$month = 3;
$day = 30;
$year = 2021;

$bibtex = "";
