<?
$subject_val = "[OMPI users] cannot build 32-bit openmpi-1.7 on Linux";
include("../../include/msg-header.inc");
?>
<!-- received="Fri Apr  5 12:09:30 2013" -->
<!-- isoreceived="20130405160930" -->
<!-- sent="Fri, 5 Apr 2013 17:56:15 +0200 (CEST)" -->
<!-- isosent="20130405155615" -->
<!-- name="Siegmar Gross" -->
<!-- email="Siegmar.Gross_at_[hidden]" -->
<!-- subject="[OMPI users] cannot build 32-bit openmpi-1.7 on Linux" -->
<!-- id="201304051556.r35FuFQ2006433_at_tyr.informatik.hs-fulda.de" -->
<!-- charset="us-ascii" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> [OMPI users] cannot build 32-bit openmpi-1.7 on Linux<br>
<strong>From:</strong> Siegmar Gross (<em>Siegmar.Gross_at_[hidden]</em>)<br>
<strong>Date:</strong> 2013-04-05 11:56:15
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="21688.php">Paul Kapinos: "Re: [OMPI users] cannot build 32-bit openmpi-1.7 on Linux"</a>
<li><strong>Previous message:</strong> <a href="21686.php">Ralph Castain: "Re: [OMPI users] OpenMPI collective algorithm selection"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="21688.php">Paul Kapinos: "Re: [OMPI users] cannot build 32-bit openmpi-1.7 on Linux"</a>
<li><strong>Reply:</strong> <a href="21688.php">Paul Kapinos: "Re: [OMPI users] cannot build 32-bit openmpi-1.7 on Linux"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Hi
<br>
<p>today I tried to install openmpi-1.7 and got the following error
<br>
on my Linux system.
<br>
<p><p><p>openSuSE Linux 12.1, x86_64, Sun C 5.12, 32-bit version of openmpi
<br>
------------------------------------------------------------------
<br>
<p>linpc1 openmpi-1.7-Linux.x86_64.32_cc 103 tail log.make.Linux.x86_64.32_cc
<br>
Making all in mpi/fortran/use-mpi-f08
<br>
make[2]: Entering directory 
<br>
`/export2/src/openmpi-1.7/openmpi-1.7-Linux.x86_64.32_cc/ompi/mpi/fortran/use-mp
<br>
i-f08'
<br>
&nbsp;&nbsp;PPFC     mpi-f08-sizeof.lo
<br>
&nbsp;&nbsp;PPFC     mpi-f08.lo
<br>
&quot;../../../../../openmpi-1.7/ompi/mpi/fortran/use-mpi-f08/mpi-f08.F90&quot;, Line = 1, 
<br>
Column = 1: INTERNAL: Interrupt: Segmentation fault
<br>
make[2]: *** [mpi-f08.lo] Error 1
<br>
make[2]: Leaving directory 
<br>
`/export2/src/openmpi-1.7/openmpi-1.7-Linux.x86_64.32_cc/ompi/mpi/fortran/use-mp
<br>
i-f08'
<br>
make[1]: *** [all-recursive] Error 1
<br>
make[1]: Leaving directory 
<br>
`/export2/src/openmpi-1.7/openmpi-1.7-Linux.x86_64.32_cc/ompi'
<br>
make: *** [all-recursive] Error 1
<br>
<p><p><p>linpc1 openmpi-1.7-Linux.x86_64.32_cc 104 head config.log
<br>
This file contains any messages produced by compilers while
<br>
running configure, to aid debugging if configure makes a mistake.
<br>
<p>It was created by Open MPI configure 1.7, which was
<br>
generated by GNU Autoconf 2.69.  Invocation command line was
<br>
<p>&nbsp;&nbsp;$ ../openmpi-1.7/configure --prefix=/usr/local/openmpi-1.7_32_cc 
<br>
--with-jdk-bindir=/usr/local/jdk1.7.0_07-32/bin 
<br>
--with-jdk-headers=/usr/local/jdk1.7.0_07-32/include 
<br>
JAVA_HOME=/usr/local/jdk1.7.0_07-32 LDFLAGS=-m32 CC=cc CXX=CC FC=f95 CFLAGS=-m32 
<br>
CXXFLAGS=-m32 -library=stlport4 FCFLAGS=-m32 CPP=cpp CXXCPP=cpp CPPFLAGS= 
<br>
CXXCPPFLAGS= --enable-cxx-exceptions --enable-mpi-java --enable-heterogeneous 
<br>
--enable-opal-multi-threads --enable-mpi-thread-multiple --with-threads=posix 
<br>
--with-hwloc=internal --without-verbs --without-udapl --with-wrapper-cflags=-m32 
<br>
--enable-debug
<br>
<p>## --------- ##
<br>
## Platform. ##
<br>
<p><p><p>I could built an older version.
<br>
<p><p>linpc1 bin 108 ./ompi_info | more
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Package: Open MPI root_at_linpc1 Distribution
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Open MPI: 1.7rc9r28266
<br>
&nbsp;&nbsp;Open MPI repo revision: r28266
<br>
&nbsp;&nbsp;&nbsp;Open MPI release date: Mar 28, 2013 (nightly snapshot tarball)
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Open RTE: 1.7rc9r28266
<br>
&nbsp;&nbsp;Open RTE repo revision: r28266
<br>
&nbsp;&nbsp;&nbsp;Open RTE release date: Mar 28, 2013 (nightly snapshot tarball)
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;OPAL: 1.7rc9r28266
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;OPAL repo revision: r28266
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;OPAL release date: Mar 28, 2013 (nightly snapshot tarball)
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MPI API: 2.1
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ident string: 1.7rc9r28266
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Prefix: /usr/local/openmpi-1.7_32_cc
<br>
&nbsp;Configured architecture: x86_64-unknown-linux-gnu
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Configure host: linpc1
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Configured by: root
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Configured on: Thu Apr  4 09:18:23 CEST 2013
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Configure host: linpc1
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Built by: root
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Built on: Thu Apr  4 09:58:32 CEST 2013
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Built host: linpc1
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;C bindings: yes
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;C++ bindings: yes
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fort mpif.h: yes (all)
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fort use mpi: yes (full: ignore TKR)
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fort use mpi size: deprecated-ompi-info-value
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fort use mpi_f08: yes
<br>
&nbsp;Fort mpi_f08 compliance: The mpi_f08 module is available, but due to 
<br>
limitations in t
<br>
he f95 compiler, does not support the following: array subsections, ABSTRACT 
<br>
INTERFACE
<br>
&nbsp;function pointers, Fortran '08-specified ASYNCHRONOUS behavior, PROCEDUREs, 
<br>
direct pa
<br>
ssthru (where possible) to underlying Open MPI's C functionality
<br>
&nbsp;&nbsp;Fort mpi_f08 subarrays: no
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;C compiler: cc
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;C compiler absolute: /opt/solstudio12.3/bin/cc
<br>
&nbsp;&nbsp;C compiler family name: SUN
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;C compiler version: 0x5120
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;C++ compiler: CC
<br>
&nbsp;&nbsp;&nbsp;C++ compiler absolute: /opt/solstudio12.3/bin/CC
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fort compiler: f95
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fort compiler abs: /opt/solstudio12.3/bin/f95
<br>
...
<br>
<p><p><p>I can build a 64-bit version.
<br>
<p>tyr openmpi-1.7-Linux.x86_64.64_cc 212 grep INTERNAL log.*
<br>
tyr openmpi-1.7-Linux.x86_64.64_cc 213 
<br>
<p><p>I would be grateful, if somebody can fix the problem for the 32-bit
<br>
version. Thank you very much for any help in advance.
<br>
<p><p>Kind regards
<br>
<p>Siegmar
<br>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="21688.php">Paul Kapinos: "Re: [OMPI users] cannot build 32-bit openmpi-1.7 on Linux"</a>
<li><strong>Previous message:</strong> <a href="21686.php">Ralph Castain: "Re: [OMPI users] OpenMPI collective algorithm selection"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="21688.php">Paul Kapinos: "Re: [OMPI users] cannot build 32-bit openmpi-1.7 on Linux"</a>
<li><strong>Reply:</strong> <a href="21688.php">Paul Kapinos: "Re: [OMPI users] cannot build 32-bit openmpi-1.7 on Linux"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
