<?
$subject_val = "Re: [OMPI devel] orte_ns_base_select failed: returned value -1 instead of ORTE_SUCCESS";
include("../../include/msg-header.inc");
?>
<!-- received="Thu Jan 31 17:58:23 2008" -->
<!-- isoreceived="20080131225823" -->
<!-- sent="Thu, 31 Jan 2008 15:58:09 -0700" -->
<!-- isosent="20080131225809" -->
<!-- name="Ralph Castain" -->
<!-- email="rhc_at_[hidden]" -->
<!-- subject="Re: [OMPI devel] orte_ns_base_select failed: returned value -1 instead of ORTE_SUCCESS" -->
<!-- id="C3C7A091.442F%rhc_at_lanl.gov" -->
<!-- charset="ISO-8859-1" -->
<!-- inreplyto="C3C79F9B.4F5%rcastain_at_gmail.com" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> Re: [OMPI devel] orte_ns_base_select failed: returned value -1 instead of ORTE_SUCCESS<br>
<strong>From:</strong> Ralph Castain (<em>rhc_at_[hidden]</em>)<br>
<strong>Date:</strong> 2008-01-31 17:58:09
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="http://www.open-mpi.org/community/lists/devel/2008/02/3108.php">Andreas Knüpfer: "Re: [OMPI devel] vt compiler warnings and errors"</a>
<li><strong>Previous message:</strong> <a href="3106.php">Jeff Squyres: "Re: [OMPI devel] vt compiler warnings and errors"</a>
<li><strong>Maybe in reply to:</strong> <a href="3095.php">Aur&#233;lien Bouteiller: "[OMPI devel] orte_ns_base_select failed: returned value -1 instead of ORTE_SUCCESS"</a>
<!-- nextthread="start" -->
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Hmmm...well, my bad. There does indeed appear to be something funny going on
<br>
with Leopard. No idea what - it used to work fine. I haven't tested it in
<br>
awhile though - I've been test building regularly on Leopard, but running on
<br>
Tiger (I misspoke earlier).
<br>
<p>For now, I'm afraid you can't run on Leopard. Have to figure it out later
<br>
when I have more time.
<br>
<p>Ralph
<br>
<p><p><span class="quotelev1">&gt; ------ Forwarded Message
</span><br>
<span class="quotelev2">&gt;&gt; From: Aur&#233;lien Bouteiller &lt;bouteill_at_[hidden]&gt;
</span><br>
<span class="quotelev2">&gt;&gt; Reply-To: Open MPI Developers &lt;devel_at_[hidden]&gt;
</span><br>
<span class="quotelev2">&gt;&gt; Date: Thu, 31 Jan 2008 02:18:27 -0500
</span><br>
<span class="quotelev2">&gt;&gt; To: Open MPI Developers &lt;devel_at_[hidden]&gt;
</span><br>
<span class="quotelev2">&gt;&gt; Subject: Re: [OMPI devel] orte_ns_base_select failed: returned value -1
</span><br>
<span class="quotelev2">&gt;&gt; instead of ORTE_SUCCESS
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; I tried using a fresh trunk, same problem have occured.  Here is the
</span><br>
<span class="quotelev2">&gt;&gt; complete configure line. I am using libtool 1.5.22 from fink.
</span><br>
<span class="quotelev2">&gt;&gt; Otherwise everything is standard OS 10.5.
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt;    $ ../trunk/configure --prefix=/Users/bouteill/ompi/build --enable-
</span><br>
<span class="quotelev2">&gt;&gt; mpirun-prefix-by-default --disable-io-romio --enable-debug --enable-
</span><br>
<span class="quotelev2">&gt;&gt; picky --enable-mem-debug --enable-mem-profile --enable-visibility --
</span><br>
<span class="quotelev2">&gt;&gt; disable-dlopen --disable-shared --enable-static
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; The error message generated by abort contains garbage (line numbers do
</span><br>
<span class="quotelev2">&gt;&gt; not match anything in .c files and according to gdb the failure does
</span><br>
<span class="quotelev2">&gt;&gt; not occur during ns initialization). This looks like a heap corruption
</span><br>
<span class="quotelev2">&gt;&gt; or something as bad.
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; orterun (argc=4, argv=0xbffff81c) at ../../../../trunk/orte/tools/
</span><br>
<span class="quotelev2">&gt;&gt; orterun/orterun.c:529
</span><br>
<span class="quotelev2">&gt;&gt; 529     cb_states = ORTE_PROC_STATE_TERMINATED |
</span><br>
<span class="quotelev2">&gt;&gt; ORTE_PROC_STATE_AT_STG1;
</span><br>
<span class="quotelev2">&gt;&gt; (gdb) n
</span><br>
<span class="quotelev2">&gt;&gt; 530     rc = orte_rmgr.spawn_job(apps, num_apps, &amp;jobid, 0, NULL,
</span><br>
<span class="quotelev2">&gt;&gt; job_state_callback, cb_states, &amp;attributes);
</span><br>
<span class="quotelev2">&gt;&gt; (gdb) n
</span><br>
<span class="quotelev2">&gt;&gt; 531     while (NULL != (item = opal_list_remove_first(&amp;attributes)))
</span><br>
<span class="quotelev2">&gt;&gt; OBJ_RELEASE(item);
</span><br>
<span class="quotelev2">&gt;&gt; (gdb) n
</span><br>
<span class="quotelev2">&gt;&gt; ** Stepping over inlined function code. **
</span><br>
<span class="quotelev2">&gt;&gt; 532     OBJ_DESTRUCT(&amp;attributes);
</span><br>
<span class="quotelev2">&gt;&gt; (gdb) n
</span><br>
<span class="quotelev2">&gt;&gt; 534     if (orterun_globals.do_not_launch) {
</span><br>
<span class="quotelev2">&gt;&gt; (gdb) n
</span><br>
<span class="quotelev2">&gt;&gt; 539     OPAL_THREAD_LOCK(&amp;orterun_globals.lock);
</span><br>
<span class="quotelev2">&gt;&gt; (gdb) n
</span><br>
<span class="quotelev2">&gt;&gt; 541     if (ORTE_SUCCESS == rc) {
</span><br>
<span class="quotelev2">&gt;&gt; (gdb) n
</span><br>
<span class="quotelev2">&gt;&gt; 542         while (!orterun_globals.exit) {
</span><br>
<span class="quotelev2">&gt;&gt; (gdb) n
</span><br>
<span class="quotelev2">&gt;&gt; 543             opal_condition_wait(&amp;orterun_globals.cond,
</span><br>
<span class="quotelev2">&gt;&gt; (gdb) n
</span><br>
<span class="quotelev2">&gt;&gt; [grosse-pomme.local:77335] [NO-NAME] ORTE_ERROR_LOG: Bad parameter in
</span><br>
<span class="quotelev2">&gt;&gt; file /SourceCache/openmpi/openmpi-5/openmpi/orte/mca/oob/base/
</span><br>
<span class="quotelev2">&gt;&gt; oob_base_init.c at line 74
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; Aurelien
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; Le 30 janv. 08 &#224; 17:18, Ralph Castain a &#233;crit :
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; Are you running on the trunk, or an earlier release?
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; If the trunk, then I suspect you have a stale library hanging
</span><br>
<span class="quotelev3">&gt;&gt;&gt; around. I
</span><br>
<span class="quotelev3">&gt;&gt;&gt; build and run statically on Leopard regularly.
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; On 1/30/08 2:54 PM, &quot;Aur&#233;lien Bouteiller&quot; &lt;bouteill_at_[hidden]&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; wrote:
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; I get a runtime error in static build on Mac OS 10.5 (automake 1.10,
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; autoconf 2.60, gcc-apple-darwin 4.01, libtool 1.5.22).
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; The error does not occur in dso builds, and everything seems to work
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; fine on Linux.
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; Here is the error log.
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; ~/ompi$ mpirun -np 2 NetPIPE_3.6/NPmpi
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; [grosse-pomme.local:34247] [NO-NAME] ORTE_ERROR_LOG: Bad parameter in
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; file /SourceCache/openmpi/openmpi-5/openmpi/orte/mca/oob/base/
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; oob_base_init.c at line 74
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; [grosse-pomme.local:34247] [NO-NAME] ORTE_ERROR_LOG: Bad parameter in
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; file /SourceCache/openmpi/openmpi-5/openmpi/orte/mca/ns/proxy/
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; ns_proxy_component.c at line 222
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; [grosse-pomme.local:34247] [NO-NAME] ORTE_ERROR_LOG: Error in file /
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; SourceCache/openmpi/openmpi-5/openmpi/orte/runtime/orte_init_stage1.c
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; at line 230
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; --------------------------------------------------------------------------
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; It looks like orte_init failed for some reason; your parallel
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; process is
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; likely to abort.  There are many reasons that a parallel process can
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; fail during orte_init; some of which are due to configuration or
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; environment problems.  This failure appears to be an internal
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; failure;
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; here's some additional information (which may only be relevant to an
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; Open MPI developer):
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt;   orte_ns_base_select failed
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt;   --&gt; Returned value -1 instead of ORTE_SUCCESS
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; --------------------------------------------------------------------------
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; --------------------------------------------------------------------------
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; It looks like MPI_INIT failed for some reason; your parallel
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; process is
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; likely to abort.  There are many reasons that a parallel process can
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; fail during MPI_INIT; some of which are due to configuration or
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; environment
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; problems.  This failure appears to be an internal failure; here's
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; some
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; additional information (which may only be relevant to an Open MPI
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; developer):
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt;   ompi_mpi_init: orte_init_stage1 failed
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt;   --&gt; Returned &quot;Error&quot; (-1) instead of &quot;Success&quot; (0)
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; --------------------------------------------------------------------------
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; *** An error occurred in MPI_Init
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; *** before MPI was initialized
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; *** MPI_ERRORS_ARE_FATAL (goodbye)
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; --
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; Dr. Aur&#233;lien Bouteiller
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; Sr. Research Associate - Innovative Computing Laboratory
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; Suite 350, 1122 Volunteer Boulevard
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; Knoxville, TN 37996
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 865 974 6321
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; _______________________________________________
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; devel mailing list
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; devel_at_[hidden]
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; <a href="http://www.open-mpi.org/mailman/listinfo.cgi/devel">http://www.open-mpi.org/mailman/listinfo.cgi/devel</a>
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; _______________________________________________
</span><br>
<span class="quotelev3">&gt;&gt;&gt; devel mailing list
</span><br>
<span class="quotelev3">&gt;&gt;&gt; devel_at_[hidden]
</span><br>
<span class="quotelev3">&gt;&gt;&gt; <a href="http://www.open-mpi.org/mailman/listinfo.cgi/devel">http://www.open-mpi.org/mailman/listinfo.cgi/devel</a>
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; _______________________________________________
</span><br>
<span class="quotelev2">&gt;&gt; devel mailing list
</span><br>
<span class="quotelev2">&gt;&gt; devel_at_[hidden]
</span><br>
<span class="quotelev2">&gt;&gt; <a href="http://www.open-mpi.org/mailman/listinfo.cgi/devel">http://www.open-mpi.org/mailman/listinfo.cgi/devel</a>
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; ------ End of Forwarded Message
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; ------ End of Forwarded Message
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="http://www.open-mpi.org/community/lists/devel/2008/02/3108.php">Andreas Knüpfer: "Re: [OMPI devel] vt compiler warnings and errors"</a>
<li><strong>Previous message:</strong> <a href="3106.php">Jeff Squyres: "Re: [OMPI devel] vt compiler warnings and errors"</a>
<li><strong>Maybe in reply to:</strong> <a href="3095.php">Aur&#233;lien Bouteiller: "[OMPI devel] orte_ns_base_select failed: returned value -1 instead of ORTE_SUCCESS"</a>
<!-- nextthread="start" -->
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
