<?php
$title = "MPI Library and Low-Level Communication on the K computer";

$overview = "Description of the MPI library and low-level communication on the K computer";

$presented = "<a href=\"http://www.fujitsu.com/global/news/publications/periodicals/fstj/archives/vol48-3.html\">FUJITSU Scientific &amp; Technical Journal 2012-7 (Vol.48, No.3)</a>";

$authors = "Naoyuki Shida, Shinji Sumimoto, Atsuya Uno";

$abstract = "The key to raising application performance in a massively parallel system like the K computer is to increase the speed of communication between compute nodes. In the K computer, this inter-node communication is governed by the Message Passing Interface (MPI) communication library and low-level communication. This paper describes the implementation and performance of the MPI communication library, which exploits the new Tofu-interconnect architecture introduced in the K computer to enhance the performance of petascale applications, and low-level communication mechanism, which performs fine-grained control of the Tofu interconnect.";

$files[] = "mpi-library-and-low-level-communication-on-k.pdf";

$month = 7;
$day = 1;
$year = 2012;

$bibtex = " @Article{shida2012:mpi_kcomputer,
  author  = {Naoyuki Shida and Shinji Sumimoto and Atsuya Uno},
  title   = {{MPI} Library and Low-Level Communication on the {K computer}},
  journal = {FUJITSU Scientific \&amp; Technical Journal},
  month   = {July},
  year    = {2012},
  volume  = {48},
  number  = {3},
  pages   = {324--330}
}";
