<?php
$title = "Supercomputing 2011 slides";
$overview = "Slides from the Open MPI State of the Union BOF at SC'11";

$authors = "George Bosilca, Jeff Squyres, Shinjii Sumimoto, Rolf vandeVaart";

$abstract = "Slides from the Open MPI State of the Union Community
Meeting at SC'11.  Note that the \"feedback\" URL in the slides will
only work through the month of November, 2011.  If you have feedback
for the Open MPI team after this time, we encourage you to send it to
the general user's mailing list.";

$presented = "<a href=\"http://sc11.supercomputing.org/\">" . "SC'11</a>,
November, 2011, in Seattle, WA, USA";

$files[] = "Open-MPI-SC11-BOF-1up.pdf";
$files[] = "Open-MPI-SC11-BOF-2up.pdf";

$month = 11;
$day = 16;
$year = 2011;

$bibtex = "";
