<?php 
$title = "mpiJava 1.2: API Specification";
$overview = "Presents an overview of the mpiJava API used in Open MPI.";

$authors = "Bryan Carpenter, Geoffrey Fox, Sung-Hoon Ko and Sang Lim";

$abstract = " This document defines the API of mpiJava, a Java language binding for MPI 1.1. The document is not a standalone specification of the behavior of MPI--it is meant to be read in conjunction with the MPI standard document. Subsections are laid out in the same way as in the standard document, to allow cross-referencing. Where the mpiJava binding makes no significant change to a particular section of the standard document, we will just note here that there are no special issues for the Java binding. This does not mean that the corresponding section of the standard is irrelevant to the Java binding--it may mean it is 100% relevant! Where practical the API is modeled on the MPI C++ interface defined in the MPI standard version 2.0";

$files[] = "mpiJava-spec.pdf";

$presented = "Oct 1999";

$month = 10;
$year = 1999;
