<? include("../../include/msg-header.inc"); ?>
<!-- received="Thu May 18 04:08:39 2006" -->
<!-- isoreceived="20060518080839" -->
<!-- sent="Thu, 18 May 2006 10:08:26 +0200" -->
<!-- isosent="20060518080826" -->
<!-- name="Ralf Wildenhues" -->
<!-- email="Ralf.Wildenhues_at_[hidden]" -->
<!-- subject="[OMPI devel] tiny Fortran 90 nit" -->
<!-- id="20060518080826.GF10864_at_iam.uni-bonn.de" -->
<!-- charset="us-ascii" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>From:</strong> Ralf Wildenhues (<em>Ralf.Wildenhues_at_[hidden]</em>)<br>
<strong>Date:</strong> 2006-05-18 04:08:26
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="0884.php">Jeff Squyres \(jsquyres\): "Re: [OMPI devel] tiny Fortran 90 nit"</a>
<li><strong>Previous message:</strong> <a href="0882.php">Jeff Squyres \(jsquyres\): "Re: [OMPI devel] New bug tracker"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="0884.php">Jeff Squyres \(jsquyres\): "Re: [OMPI devel] tiny Fortran 90 nit"</a>
<li><strong>Maybe reply:</strong> <a href="0884.php">Jeff Squyres \(jsquyres\): "Re: [OMPI devel] tiny Fortran 90 nit"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Hi there,
<br>
<p>I currently need this patch to build the trunk, so that
<br>
attr_fn-f90-interfaces.h will be found in a VPATH build,
<br>
and distributed.  I don't know whether the header should
<br>
be installed, though -- in that case, this change needs
<br>
to be adjusted.
<br>
<p>Cheers,
<br>
Ralf
<br>
<p>Index: ompi/mpi/f90/Makefile.am
<br>
===================================================================
<br>
--- ompi/mpi/f90/Makefile.am	(revision 9962)
<br>
+++ ompi/mpi/f90/Makefile.am	(working copy)
<br>
@@ -50,7 +50,7 @@
<br>
&nbsp;
<br>
&nbsp;SUBDIRS = scripts
<br>
&nbsp;
<br>
-AM_FCFLAGS = -I$(top_builddir)/ompi/include $(OMPI_FC_MODULE_FLAG).
<br>
+AM_FCFLAGS = -I$(top_builddir)/ompi/include $(OMPI_FC_MODULE_FLAG). -I$(srcdir)
<br>
&nbsp;
<br>
&nbsp;# Override the default f90 rules because we have to insert
<br>
&nbsp;# $(FCFLAGS_f90) right before the source filename.  This is necessary
<br>
@@ -151,7 +151,7 @@
<br>
&nbsp;# distributed.  This file is always in the library, regardless of the
<br>
&nbsp;# size that we're building.
<br>
&nbsp;
<br>
-libmpi_f90_a_SOURCES = mpi.f90
<br>
+libmpi_f90_a_SOURCES = mpi.f90 attr_fn-f90-interfaces.h
<br>
&nbsp;
<br>
&nbsp;# These files are all generated by scripts in the scripts/ directory.
<br>
&nbsp;
<br>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="0884.php">Jeff Squyres \(jsquyres\): "Re: [OMPI devel] tiny Fortran 90 nit"</a>
<li><strong>Previous message:</strong> <a href="0882.php">Jeff Squyres \(jsquyres\): "Re: [OMPI devel] New bug tracker"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="0884.php">Jeff Squyres \(jsquyres\): "Re: [OMPI devel] tiny Fortran 90 nit"</a>
<li><strong>Maybe reply:</strong> <a href="0884.php">Jeff Squyres \(jsquyres\): "Re: [OMPI devel] tiny Fortran 90 nit"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
