<?php
$title = "HPC Controls: Vision to the Future";
$overview = "Slides from a presentation given at OMPI devel meeting and elsewhere";

$authors = "Ralph H. Castain";

$abstract = "Slides from a presentation given at OMPI devel meeting and elsewhere";

$presented = "<a href=\"https://github.com/open-mpi/ompi/wiki/Meeting-2015-06/\">" . "Devel'15</a>,
June, 2015, in San Jose, CA, USA";

$files[] = "HPCControlsFuture.pdf";

$month = 06;
$day = 24;
$year = 2015;

$bibtex = "";
