<?php
$title = "Open MPI Developer's Workshop";
$overview = "Slides from the Open MPI 2006 Developer's Workshop";

$authors = "Brian Barrett, George Bosilca, Rich Graham, Galen Shipman,
Tim Woodall, Jeff Squyres";

$abstract = "This week-long, hands-on workshop is being taught by the
Open MPI core development team.  The goal is to enable 3rd party
developers to extend and enhance the Open MPI code base, such as
hardware-specific functionality for particular networks or platforms.
A detailed analysis of how Open MPI works will be presented -- to
include significant time spent examining and discussing the code of
Open MPI itself.";

$presented = "April 17-20, 2006, Cisco Systems Campus, San Jose, CA,
USA.";

$month = 4;
$day = 17;
$year = 2006;

$bibtex = "";
$files = array();
