<?
$subject_val = "Re: [OMPI devel] [OMPI svn] svn:open-mpi r28456 - trunk";
include("../../include/msg-header.inc");
?>
<!-- received="Mon May  6 22:40:03 2013" -->
<!-- isoreceived="20130507024003" -->
<!-- sent="Mon, 6 May 2013 19:39:55 -0700" -->
<!-- isosent="20130507023955" -->
<!-- name="Ralph Castain" -->
<!-- email="rhc_at_[hidden]" -->
<!-- subject="Re: [OMPI devel] [OMPI svn] svn:open-mpi r28456 - trunk" -->
<!-- id="6AA86100-C35B-4401-B405-E9695346F70E_at_open-mpi.org" -->
<!-- charset="us-ascii" -->
<!-- inreplyto="20130506230519.15C0716027B_at_tiger.crest.iu.edu" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> Re: [OMPI devel] [OMPI svn] svn:open-mpi r28456 - trunk<br>
<strong>From:</strong> Ralph Castain (<em>rhc_at_[hidden]</em>)<br>
<strong>Date:</strong> 2013-05-06 22:39:55
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="12365.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] [OMPI svn] svn:open-mpi r28456 - trunk"</a>
<li><strong>Previous message:</strong> <a href="12363.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] June OMPI developer's meeting"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="12365.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] [OMPI svn] svn:open-mpi r28456 - trunk"</a>
<li><strong>Reply:</strong> <a href="12365.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] [OMPI svn] svn:open-mpi r28456 - trunk"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Could someone help me out a bit here:
<br>
<p>* I'm unaware of any mechanism for &quot;ignoring&quot; an entire framework. Was something added for that purpose?
<br>
<p>* What &quot;non-MCA&quot; projects are in our repository? Everything appears to be based on MCA plugins.
<br>
<p>* Looking at Trac, we eliminated all project/config directories when we did the OMPI-RTE abstraction. So what are we looping across at the end of autogen?
<br>
<p>Thanks
<br>
Ralph
<br>
<p><p>On May 6, 2013, at 4:05 PM, svn-commit-mailer_at_[hidden] wrote:
<br>
<p><span class="quotelev1">&gt; Author: naughtont (Thomas Naughton)
</span><br>
<span class="quotelev1">&gt; Date: 2013-05-06 19:05:18 EDT (Mon, 06 May 2013)
</span><br>
<span class="quotelev1">&gt; New Revision: 28456
</span><br>
<span class="quotelev1">&gt; URL: <a href="https://svn.open-mpi.org/trac/ompi/changeset/28456">https://svn.open-mpi.org/trac/ompi/changeset/28456</a>
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; Log:
</span><br>
<span class="quotelev1">&gt; Updates to autogen.pl:
</span><br>
<span class="quotelev1">&gt; +  Add ifdef guard to project's autogenerated &quot;frameworks.h&quot; header file,
</span><br>
<span class="quotelev1">&gt;   e.g., &quot;opal/inlude/opal/frameworks.h&quot; would have &quot;OPAL_FRAMEWORKS_H&quot;.
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; + Avoid adding &quot;ignored&quot; frameworks to the autogenerated &quot;frameworks.h&quot;
</span><br>
<span class="quotelev1">&gt;  header file.
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; + Avoid adding non-MCA projects to the autogenerated 'mca_project_list',
</span><br>
<span class="quotelev1">&gt;  which maintains existing support for &quot;projects&quot; with new MCA framework 
</span><br>
<span class="quotelev1">&gt;  enhancements.  Moves this down to mca_run_global().
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; + Add small loop at end to add projects with a &quot;config/&quot; subdir
</span><br>
<span class="quotelev1">&gt;  to the list of includes for 'autoreconf'.
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; Text files modified: 
</span><br>
<span class="quotelev1">&gt;   trunk/autogen.pl |    45 +++++++++++++++++++++++++++++---------- 
</span><br>
<span class="quotelev1">&gt;   1 files changed, 33 insertions(+), 12 deletions(-)
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; Modified: trunk/autogen.pl
</span><br>
<span class="quotelev1">&gt; ==============================================================================
</span><br>
<span class="quotelev1">&gt; --- trunk/autogen.pl	Mon May  6 18:00:45 2013	(r28455)
</span><br>
<span class="quotelev1">&gt; +++ trunk/autogen.pl	2013-05-06 19:05:18 EDT (Mon, 06 May 2013)	(r28456)
</span><br>
<span class="quotelev1">&gt; @@ -376,16 +376,22 @@
</span><br>
<span class="quotelev1">&gt;         }
</span><br>
<span class="quotelev1">&gt;     }
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; +    my $ifdef_string = uc &quot;${project}_FRAMEWORKS_H&quot;;
</span><br>
<span class="quotelev1">&gt;     open(FRAMEWORKS_OUT, &quot;&gt;$project/include/$project/frameworks.h&quot;);
</span><br>
<span class="quotelev1">&gt;     printf FRAMEWORKS_OUT &quot;%s&quot;, &quot;/*
</span><br>
<span class="quotelev1">&gt;  * This file is autogenerated by autogen.pl. Do not edit this file by hand.
</span><br>
<span class="quotelev1">&gt;  */
</span><br>
<span class="quotelev1">&gt; +#ifndef $ifdef_string
</span><br>
<span class="quotelev1">&gt; +#define $ifdef_string
</span><br>
<span class="quotelev1">&gt; +
</span><br>
<span class="quotelev1">&gt; #include &lt;opal/mca/base/mca_base_framework.h&gt;
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; $framework_decl_output
</span><br>
<span class="quotelev1">&gt; static mca_base_framework_t *${project}_frameworks[] = {
</span><br>
<span class="quotelev1">&gt; $framework_array_output    NULL
</span><br>
<span class="quotelev1">&gt; -};\n&quot;;
</span><br>
<span class="quotelev1">&gt; +};
</span><br>
<span class="quotelev1">&gt; +
</span><br>
<span class="quotelev1">&gt; +#endif /* $ifdef_string */\n\n&quot;;
</span><br>
<span class="quotelev1">&gt;     close(FRAMEWORKS_OUT);
</span><br>
<span class="quotelev1">&gt; }
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; @@ -447,6 +453,19 @@
</span><br>
<span class="quotelev1">&gt;     # Debugging output
</span><br>
<span class="quotelev1">&gt;     debug_dump($mca_found);
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; +    # Save (just) the list of MCA projects in the m4 file
</span><br>
<span class="quotelev1">&gt; +    my $str;
</span><br>
<span class="quotelev1">&gt; +    foreach my $p (@$projects) {
</span><br>
<span class="quotelev1">&gt; +        my $pname = $p-&gt;{name};
</span><br>
<span class="quotelev1">&gt; +        # Check if this project is an MCA project (contains MCA framework)
</span><br>
<span class="quotelev1">&gt; +        if (exists($mca_found-&gt;{$pname})) {
</span><br>
<span class="quotelev1">&gt; +            $str .= &quot;$p-&gt;{name}, &quot;;
</span><br>
<span class="quotelev1">&gt; +        }
</span><br>
<span class="quotelev1">&gt; +    }
</span><br>
<span class="quotelev1">&gt; +    $str =~ s/, $//;
</span><br>
<span class="quotelev1">&gt; +    $m4 .= &quot;\ndnl List of MCA projects found by autogen.pl
</span><br>
<span class="quotelev1">&gt; +m4_define([mca_project_list], [$str])\n&quot;;
</span><br>
<span class="quotelev1">&gt; +
</span><br>
<span class="quotelev1">&gt;     #-----------------------------------------------------------------------
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt;     $m4 .= &quot;\n$dnl_line
</span><br>
<span class="quotelev1">&gt; @@ -485,7 +504,14 @@
</span><br>
<span class="quotelev1">&gt;                 push(@tmp, $f)
</span><br>
<span class="quotelev1">&gt;                     if ($f ne &quot;common&quot;);
</span><br>
<span class="quotelev1">&gt;             }
</span><br>
<span class="quotelev1">&gt; -            @mykeys = @tmp;
</span><br>
<span class="quotelev1">&gt; +
</span><br>
<span class="quotelev1">&gt; +            # Then, check ignore status and prume ignored frameworks
</span><br>
<span class="quotelev1">&gt; +            @mykeys = ();
</span><br>
<span class="quotelev1">&gt; +            my $dir = &quot;$topdir/$pdir/mca&quot;;
</span><br>
<span class="quotelev1">&gt; +            foreach my $f (@tmp) {
</span><br>
<span class="quotelev1">&gt; +                push(@mykeys, $f)
</span><br>
<span class="quotelev1">&gt; +                    if (!ignored(&quot;$dir/$f&quot;));
</span><br>
<span class="quotelev1">&gt; +            }
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt;             foreach my $f (@mykeys) {
</span><br>
<span class="quotelev1">&gt;                 $frameworks_comma .= &quot;, $f&quot;;
</span><br>
<span class="quotelev1">&gt; @@ -1175,16 +1201,7 @@
</span><br>
<span class="quotelev1">&gt; push(@{$projects}, { name =&gt; &quot;ompi&quot;, dir =&gt; &quot;ompi&quot;, need_base =&gt; 1 })
</span><br>
<span class="quotelev1">&gt;     if (!$no_ompi_arg);
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; -# Save the list of projects in the m4 file
</span><br>
<span class="quotelev1">&gt; -my $str;
</span><br>
<span class="quotelev1">&gt; -foreach my $p (@$projects) {
</span><br>
<span class="quotelev1">&gt; -    $str .= &quot;$p-&gt;{name}, &quot;;
</span><br>
<span class="quotelev1">&gt; -}
</span><br>
<span class="quotelev1">&gt; -$str =~ s/, $//;
</span><br>
<span class="quotelev1">&gt; -$m4 .= &quot;dnl List of projects found by autogen.pl
</span><br>
<span class="quotelev1">&gt; -m4_define([mca_project_list], [$str])
</span><br>
<span class="quotelev1">&gt; -
</span><br>
<span class="quotelev1">&gt; -dnl Separate m4 define for each project\n&quot;;
</span><br>
<span class="quotelev1">&gt; +$m4 .= &quot;dnl Separate m4 define for each project\n&quot;;
</span><br>
<span class="quotelev1">&gt; foreach my $p (@$projects) {
</span><br>
<span class="quotelev1">&gt;     $m4 .= &quot;m4_define([project_$p-&gt;{name}], [1])\n&quot;;
</span><br>
<span class="quotelev1">&gt; }
</span><br>
<span class="quotelev1">&gt; @@ -1251,6 +1268,10 @@
</span><br>
<span class="quotelev1">&gt; verbose &quot;==&gt; Running autoreconf\n&quot;;
</span><br>
<span class="quotelev1">&gt; chdir(&quot;..&quot;);
</span><br>
<span class="quotelev1">&gt; my $cmd = &quot;autoreconf -ivf --warnings=all,no-obsolete,no-override -I config&quot;;
</span><br>
<span class="quotelev1">&gt; +foreach my $project (@{$projects}) {
</span><br>
<span class="quotelev1">&gt; +    $cmd .= &quot; -I $project-&gt;{dir}/config&quot;
</span><br>
<span class="quotelev1">&gt; +        if (-d &quot;$project-&gt;{dir}/config&quot;);
</span><br>
<span class="quotelev1">&gt; +}
</span><br>
<span class="quotelev1">&gt; safe_system($cmd);
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; #---------------------------------------------------------------------------
</span><br>
<span class="quotelev1">&gt; _______________________________________________
</span><br>
<span class="quotelev1">&gt; svn mailing list
</span><br>
<span class="quotelev1">&gt; svn_at_[hidden]
</span><br>
<span class="quotelev1">&gt; <a href="http://www.open-mpi.org/mailman/listinfo.cgi/svn">http://www.open-mpi.org/mailman/listinfo.cgi/svn</a>
</span><br>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="12365.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] [OMPI svn] svn:open-mpi r28456 - trunk"</a>
<li><strong>Previous message:</strong> <a href="12363.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] June OMPI developer's meeting"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="12365.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] [OMPI svn] svn:open-mpi r28456 - trunk"</a>
<li><strong>Reply:</strong> <a href="12365.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] [OMPI svn] svn:open-mpi r28456 - trunk"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
