<?php
$title = "Supercomputing 2017 PMIx BoF slides";
$overview = "Slides from the PMIx BOF at SC'17";

$authors = "Ralph Castain, Aurelien Bouteiller, Josh Hursey";

$abstract = "Slides from the PMIx Community Meeting at SC'17.";

$presented = "<a href=\"http://sc17.supercomputing.org/\">" . "SC'17</a>,
November, 2017, in Denver, CO, USA";

$files[] = "PMIxBoF-2017.pdf";

$month = 11;
$day = 16;
$year = 2017;

$bibtex = "";
