<?php
$topdir = "../../..";
$title = "pquery(1) man page (version 5.0.0rc2)";
$meta_desc = "Open MPI v5.0.0rc2 man page: pquery(1)";

include_once("$topdir/doc/nav.inc");
include_once("$topdir/includes/header.inc");
?>
<p> <a href="../">&laquo; Return to documentation listing</a></p>
  <!-- manual page source format generated by PolyglotMan v3.2, -->
<!-- available at http://polyglotman.sourceforge.net/ -->

<body bgcolor='white'>
<a href='#toc'>Table of Contents</a><p>

<h2><a name='sect0' href='#toc0'>Name</a></h2>
<p>
pquery - Request information from the system
<h2><a name='sect1' href='#toc1'>Synopsis</a></h2>
<br>
<pre>

</pre>
<h2><a name='sect2' href='#toc2'>C]pquery [ options ] [ keys ]R]Description</a></h2>
<p>
C]pqueryR] will request and output
the specified information. This requires that C]pqueryR] connect to an appropriate
server - the tool will automatically attempt to do so,
<dl>

<dt>but options are provided
</dt>
<dd>to assist its search or to direct it to a specific server. </dd>
</dl>
<p>
Keys passed to
C]pqueryR] may optionally include one or more qualifiers, with the individual
qualifiers delimited by semi-colons. For example: <br>
<pre>

</pre>
<h2><a name='sect3' href='#toc3'>C]PMIX_STORAGE_XFER_SIZE[PMIX_STORAGE_ID=lustre1,lustre2;PMIX_STORAGE_PATH=foo]R]Options</a></h2>
<p>
C]pqueryR]
supports the following options: <br>
<pre>

</pre>
<h2><a name='sect4' href='#toc4'>C]-h|--help                This help message-n|--nspace &lt;arg0&gt;       Specify server
nspace to connect to-p|--pid &lt;arg0&gt;          Specify server pid to connect to
  --system-server       Specifically connect to the system server   --system-server-first
Look for the system server first   --uri &lt;arg0&gt;          Specify URI of server
to connect to-v|--verbose             Be VerboseR]Authors</a></h2>
<p>
The OpenPMIx maintainers
[en]
<dl>

<dt>see <i>https://github.com/openpmix/openpmix</i> </dt>
<dd>or the file C]AUTHORSR]. </dd>
</dl>
<p>

<hr><p>
<a name='toc'><b>Table of Contents</b></a><p>
<ul>
<li><a name='toc0' href='#sect0'>Name</a></li>
<li><a name='toc1' href='#sect1'>Synopsis</a></li>
<li><a name='toc2' href='#sect2'>C]pquery [ options ] [ keys ]R]Description</a></li>
<li><a name='toc3' href='#sect3'>C]PMIX_STORAGE_XFER_SIZE[PMIX_STORAGE_ID=lustre1,lustre2;PMIX_STORAGE_PATH=foo]R]Options</a></li>
<li><a name='toc4' href='#sect4'>C]-h|--help                This help message-n|--nspace <arg0>       Specify server nspace to connect to-p|--pid <arg0>          Specify server pid to connect to   --system-server       Specifically connect to the system server   --system-server-first Look for the system server first   --uri <arg0>          Specify URI of server to connect to-v|--verbose             Be VerboseR]Authors</a></li>
</ul>


<p> <a href="../">&laquo; Return to documentation listing</a></p>
<?php
include_once("$topdir/includes/footer.inc");
