<?php
$topdir = "../../..";
$title = "pterm(1) man page (version 5.0.0rc1)";
$meta_desc = "Open MPI v5.0.0rc1 man page: pterm(1)";

include_once("$topdir/doc/nav.inc");
include_once("$topdir/includes/header.inc");
?>
<p> <a href="../">&laquo; Return to documentation listing</a></p>
  <!-- manual page source format generated by PolyglotMan v3.2, -->
<!-- available at http://polyglotman.sourceforge.net/ -->

<body bgcolor='white'>
<a href='#toc'>Table of Contents</a><p>

<h2><a name='sect0' href='#toc0'>Name</a></h2>
<p>
pterm - Terminate an instance of the PMIx Reference RTE (PRTE)
<h2><a name='sect1' href='#toc1'>Synopsis</a></h2>
<br>
<pre>

</pre>
<h2><a name='sect2' href='#toc2'>C]pterm JMS write some more hereR]Description</a></h2>
<p>
C]ptermR]
<dl>

<dt>terminates an instance
of the PMIx reference run time </dt>
<dd>environment (PRTE). </dd>
</dl>
<p>
JMS write more here
<h2><a name='sect3' href='#toc3'>Options</a></h2>
<p>
JMS
C]pterm --helpR] shows this: <br>
<pre>

</pre>
<h2><a name='sect4' href='#toc4'>C]pterm (PRTE) 2.0.0a1Usage: pterm [OPTION]...Terminate an instance of the PMIx
Reference RTE (PRTE)/*****      General Options      *****/-h|--help
                     This help message-v|--verbose
Be verbose-V|--version                         Print version and exit/*****
   DVM-Specific Options   *****/   --dvm-uri &lt;arg0&gt;                  Specify
the URI of the DVM master, or the name of the file (specified as
                              file:filename) that contains that info
--num-connect-retries             Max number of times to try to connect   --pid
&lt;arg0&gt;                      PID of the session-level daemon to which we should
connect   --system-server-first             First look for a system server
and connect to it if found   --system-server-only              Connect only
to a system-level server   --wait-to-connect                 Delay specified
number of seconds before trying to connectR]Authors</a></h2>
<p>
The PRTE maintainers
[en]
<dl>

<dt>see <i>https://github.com/openpmix/prte</i> or the </dt>
<dd>file C]AUTHORSR]. </dd>
</dl>
<p>

<hr><p>
<a name='toc'><b>Table of Contents</b></a><p>
<ul>
<li><a name='toc0' href='#sect0'>Name</a></li>
<li><a name='toc1' href='#sect1'>Synopsis</a></li>
<li><a name='toc2' href='#sect2'>C]pterm JMS write some more hereR]Description</a></li>
<li><a name='toc3' href='#sect3'>Options</a></li>
<li><a name='toc4' href='#sect4'>C]pterm (PRTE) 2.0.0a1Usage: pterm [OPTION]...Terminate an instance of the PMIx Reference RTE (PRTE)/*****      General Options      *****/-h|--help                            This help message-v|--verbose                         Be verbose-V|--version                         Print version and exit/*****    DVM-Specific Options   *****/   --dvm-uri <arg0>                  Specify the URI of the DVM master, or the name of the file (specified as                                     file:filename) that contains that info   --num-connect-retries             Max number of times to try to connect   --pid <arg0>                      PID of the session-level daemon to which we should connect   --system-server-first             First look for a system server and connect to it if found   --system-server-only              Connect only to a system-level server   --wait-to-connect                 Delay specified number of seconds before trying to connectR]Authors</a></li>
</ul>


<p> <a href="../">&laquo; Return to documentation listing</a></p>
<?php
include_once("$topdir/includes/footer.inc");
