<?
$subject_val = "[hwloc-users] hwloc error after upgrading from Centos 6.5 to Centos 7 on Supermicro with AMD Opteron 6344";
include("../../include/msg-header.inc");
?>
<!-- received="Wed Jan  6 22:10:03 2016" -->
<!-- isoreceived="20160107031003" -->
<!-- sent="Wed, 6 Jan 2016 22:10:00 -0500" -->
<!-- isosent="20160107031000" -->
<!-- name="David Winslow" -->
<!-- email="david.winslow_at_[hidden]" -->
<!-- subject="[hwloc-users] hwloc error after upgrading from Centos 6.5 to Centos 7 on Supermicro with AMD Opteron 6344" -->
<!-- id="20B0FB9A-D5C0-4A72-B7A7-143E9362CE07_at_serendipitynow.com" -->
<!-- charset="us-ascii" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> [hwloc-users] hwloc error after upgrading from Centos 6.5 to Centos 7 on Supermicro with AMD Opteron 6344<br>
<strong>From:</strong> David Winslow (<em>david.winslow_at_[hidden]</em>)<br>
<strong>Date:</strong> 2016-01-06 22:10:00
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="1239.php">Brice Goglin: "Re: [hwloc-users] [WARNING: A/V UNSCANNABLE] hwloc error after upgrading from Centos 6.5 to Centos 7 on Supermicro with AMD Opteron 6344"</a>
<li><strong>Previous message:</strong> <a href="1237.php">Brice Goglin: "Re: [hwloc-users] error from the operating system - Solaris 11.3 - SOLVED"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="1239.php">Brice Goglin: "Re: [hwloc-users] [WARNING: A/V UNSCANNABLE] hwloc error after upgrading from Centos 6.5 to Centos 7 on Supermicro with AMD Opteron 6344"</a>
<li><strong>Reply:</strong> <a href="1239.php">Brice Goglin: "Re: [hwloc-users] [WARNING: A/V UNSCANNABLE] hwloc error after upgrading from Centos 6.5 to Centos 7 on Supermicro with AMD Opteron 6344"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
I upgraded our servers from Centos 6.5 to Centos7.2. Since then, when I run mpirun I get the following error but the software continues to run and it appears to work fine.
<br>
<p>* hwloc 1.11.0rc3-git has encountered what looks like an error from the operating system.
<br>
*
<br>
* L3 (cpuset 0x000003f0) intersects with NUMANode (P#0 cpuset 0x0000003f) without inclusion!
<br>
* Error occurred in topology.c line 983
<br>
*
<br>
* The following FAQ entry in the hwloc documentation may help:
<br>
*   What should I do when hwloc reports &quot;operating system&quot; warnings?
<br>
* Otherwise please report this error message to the hwloc user's mailing list,
<br>
* along with the output+tarball generated by the hwloc-gather-topology script.
<br>
<p>I can replicate the error by simply running hwloc-info.
<br>
<p>The version of hwloc used with mpirun is 1.9. The version installed on the server that I ran is 1.7 that comes with Centos 7. They both give the error with minor differences shown below.
<br>
<p>With hwloc 1.7
<br>
* object (L3 cpuset 0x000003f0) intersection without inclusion!
<br>
* Error occurred in topology.c line 753
<br>
<p>With hwloc 1.9
<br>
* L3 (cpuset 0x000003f0) intersects with NUMANode (P#0 cpuset 0x0000003f) without inclusion!
<br>
* Error occurred in topology.c line 983
<br>
<p>The current kernel is 3.10.0-327.el7.x86_64. I&#226;&#128;&#153;ve tried updating the kernel to a minor release update and even tried to install kernel v4.4.3. None of the kernels worked. Again, hwloc works fine in Centos 6.5 with kernel 2.6.32-431.29.2.el6.x86_64.
<br>
<p>I&#226;&#128;&#153;ve attached the files generated by hwloc-gather-topology.sh.  I compared what this script says is the expected output to the actual output and, from what I can tell, they look the same. Maybe I&#226;&#128;&#153;m missing something after staring all day at the information.
<br>
<p>I did a clean install of the OS to perform the upgrade from 6.5.
<br>
<p>I&#226;&#128;&#153;ve attached the results of the hwloc-gather-topology.sh script. Any help will be greatly appreciated.
<br>
<p>


<br><p>
<p><p><p><p><hr>
<ul>
<li>application/octet-stream attachment: <a href="http://www.open-mpi.org/community/lists/hwloc-users/att-1238/myfile.output">myfile.output</a>
</ul>
<!-- attachment="myfile.output" -->
<hr>
<ul>
<li>application/x-bzip2 attachment: <a href="http://www.open-mpi.org/community/lists/hwloc-users/att-1238/myfile.tar.bz2">myfile.tar.bz2</a>
</ul>
<!-- attachment="myfile.tar.bz2" -->
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="1239.php">Brice Goglin: "Re: [hwloc-users] [WARNING: A/V UNSCANNABLE] hwloc error after upgrading from Centos 6.5 to Centos 7 on Supermicro with AMD Opteron 6344"</a>
<li><strong>Previous message:</strong> <a href="1237.php">Brice Goglin: "Re: [hwloc-users] error from the operating system - Solaris 11.3 - SOLVED"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="1239.php">Brice Goglin: "Re: [hwloc-users] [WARNING: A/V UNSCANNABLE] hwloc error after upgrading from Centos 6.5 to Centos 7 on Supermicro with AMD Opteron 6344"</a>
<li><strong>Reply:</strong> <a href="1239.php">Brice Goglin: "Re: [hwloc-users] [WARNING: A/V UNSCANNABLE] hwloc error after upgrading from Centos 6.5 to Centos 7 on Supermicro with AMD Opteron 6344"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
