<?php
$title = "Supercomputing 2017 slides";
$overview = "Slides from the Open MPI State of the Union BOF at SC'17";

$authors = "George Bosilca, Jeff Squyres, Josh Hursey, Gilles Gouaillardet, David Bernholdt";

$abstract = "Slides from the Open MPI State of the Union XI Community
Meeting at SC'17.";

$presented = "<a href=\"http://sc17.supercomputing.org/\">" . "SC'17</a>,
November, 2017, in Denver, CO, USA";

$files[] = "Open-MPI-SC17-BOF.pdf";

$month = 11;
$day = 15;
$year = 2017;

$bibtex = "";
