<?php
include_once("$topdir/includes/nav.inc");

$this_dir = "plpa";
$this_nav[] = new Nav("Download v1.3 (deprecated)", "$topdir/software/plpa/v1.3/");
$this_nav[] = new Nav("Download v1.2 (older)", "$topdir/software/plpa/v1.2/");
$this_nav[] = new Nav("Download v1.1 (older)", "$topdir/software/plpa/v1.1/");
$this_nav[] = new Nav("Download v1.0 (older)", "$topdir/software/plpa/v1.0/");
$this_nav[] = new Nav("License", "$topdir/projects/plpa/license.php");
$this_nav[] = new Nav("How does it work?", "$topdir/projects/plpa/overview.php");
$this_nav[] = new Nav("Mailing lists", "$topdir/community/lists/plpa.php");
$this_nav[] = new Nav("Subversion checkout", "$topdir/projects/plpa/svn.php");
