<? include("../../include/msg-header.inc"); ?>
<!-- received="Wed Feb 15 11:28:23 2006" -->
<!-- isoreceived="20060215162823" -->
<!-- sent="Wed, 15 Feb 2006 09:28:19 -0700" -->
<!-- isosent="20060215162819" -->
<!-- name="Xiaoning (David) Yang" -->
<!-- email="xyang_at_[hidden]" -->
<!-- subject="Re: [OMPI users] Installing OpenMPI on a solaris" -->
<!-- id="C018A4B3.8B8B%xyang_at_lanl.gov" -->
<!-- charset="US-ASCII" -->
<!-- inreplyto="393DA5BD-5CF9-46BD-96D3-510E55ABF3A3_at_open-mpi.org" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>From:</strong> Xiaoning (David) Yang (<em>xyang_at_[hidden]</em>)<br>
<strong>Date:</strong> 2006-02-15 11:28:19
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="0669.php">Edgar Gabriel: "Re: [OMPI users] Dynamic process question"</a>
<li><strong>Previous message:</strong> <a href="0667.php">Jeff Squyres: "Re: [OMPI users] [O-MPI users] Job fails with mpiP"</a>
<li><strong>In reply to:</strong> <a href="0664.php">Brian Barrett: "Re: [OMPI users] Installing OpenMPI on a solaris"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="http://www.open-mpi.org/community/lists/users/2006/06/1447.php">Eric Thibodeau: "Re: [OMPI users] Installing OpenMPI on a solaris"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Brian,
<br>
<p>Thank you for your help. I've asked our system administrator to install Open
<br>
MPI on a server. I hope she will succeed.
<br>
<p>David
<br>
<p>***** Correspondence *****
<br>
<p><p><p><span class="quotelev1">&gt; From: Brian Barrett &lt;brbarret_at_[hidden]&gt;
</span><br>
<span class="quotelev1">&gt; Reply-To: Open MPI Users &lt;users_at_[hidden]&gt;
</span><br>
<span class="quotelev1">&gt; Date: Tue, 14 Feb 2006 19:19:22 -0500
</span><br>
<span class="quotelev1">&gt; To: Open MPI Users &lt;users_at_[hidden]&gt;
</span><br>
<span class="quotelev1">&gt; Subject: Re: [OMPI users] Installing OpenMPI on a solaris
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; Can you send me the config.log file generated by Open MPI's
</span><br>
<span class="quotelev1">&gt; configure?  It should give some indication as to what is wrong.  If
</span><br>
<span class="quotelev1">&gt; you are on a Ultra Sparc machine (pretty much any machine built after
</span><br>
<span class="quotelev1">&gt; the Ultra 1), you might want to set the compiler flags to set the
</span><br>
<span class="quotelev1">&gt; default build mode to v8plus (aka 32 bit sparc v9).  The difference
</span><br>
<span class="quotelev1">&gt; between the default v8 assembly and the v8plus assembly is pretty
</span><br>
<span class="quotelev1">&gt; great in terms of performance.  Configuring Open MPI with something
</span><br>
<span class="quotelev1">&gt; like:
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt;    ./configure CFLAGS=&quot;-mv8plus&quot; CXXFLAGS=&quot;-mv8plus&quot; FFLAGS=&quot;-mv8plus&quot; \
</span><br>
<span class="quotelev1">&gt;          FCFLAGS=&quot;-mv8plus&quot; &lt;other options&gt;
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; should do the trick.
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; Brian
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; On Feb 14, 2006, at 3:48 PM, Xiaoning (David) Yang wrote:
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; Brian,
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; Thank you for your help. It turned out that my path pointed to an
</span><br>
<span class="quotelev2">&gt;&gt; older
</span><br>
<span class="quotelev2">&gt;&gt; version of gcc. After correcting that, I no longer get the same
</span><br>
<span class="quotelev2">&gt;&gt; error. But
</span><br>
<span class="quotelev2">&gt;&gt; now the error becomes, after I issued &quot;make all install&quot;,
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; ......
</span><br>
<span class="quotelev2">&gt;&gt; gcc -DHAVE_CONFIG_H -I. -I. -I../../include -I../../include -I../../
</span><br>
<span class="quotelev2">&gt;&gt; include
</span><br>
<span class="quotelev2">&gt;&gt; -I../.. -I../.. -I../../include -I../../opal -I../../orte -I../../ompi
</span><br>
<span class="quotelev2">&gt;&gt; -D_REENTRANT -O3 -DNDEBUG -fno-strict-aliasing -c req_test.c
</span><br>
<span class="quotelev2">&gt;&gt; -Wp,-MD,.deps/req_test.TPlo  -fPIC -DPIC -o .libs/req_test.o
</span><br>
<span class="quotelev2">&gt;&gt; /usr/ccs/bin/as: &quot;/var/tmp//cc5lFbCH.s&quot;, line 17: error: cannot use
</span><br>
<span class="quotelev2">&gt;&gt; v8plus
</span><br>
<span class="quotelev2">&gt;&gt; instructions in a non-v8plus target binary
</span><br>
<span class="quotelev2">&gt;&gt; /usr/ccs/bin/as: &quot;/var/tmp//cc5lFbCH.s&quot;, line 155: error: cannot
</span><br>
<span class="quotelev2">&gt;&gt; use v8plus
</span><br>
<span class="quotelev2">&gt;&gt; instructions in a non-v8plus target binary
</span><br>
<span class="quotelev2">&gt;&gt; *** Error code 1
</span><br>
<span class="quotelev2">&gt;&gt; make: Fatal error: Command failed for target `req_test.lo'
</span><br>
<span class="quotelev2">&gt;&gt; Current working directory /home/xyang/openmpi/openmpi-1.0.1/ompi/
</span><br>
<span class="quotelev2">&gt;&gt; request
</span><br>
<span class="quotelev2">&gt;&gt; *** Error code 1
</span><br>
<span class="quotelev2">&gt;&gt; make: Fatal error: Command failed for target `all-recursive'
</span><br>
<span class="quotelev2">&gt;&gt; Current working directory /home/xyang/openmpi/openmpi-1.0.1/ompi
</span><br>
<span class="quotelev2">&gt;&gt; *** Error code 1
</span><br>
<span class="quotelev2">&gt;&gt; make: Fatal error: Command failed for target `all-recursive'
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; Any clue what went wrong this time? Thanks a lot!
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; David
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; ***** Correspondence *****
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; From: Brian Barrett &lt;brbarret_at_[hidden]&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; Reply-To: Open MPI Users &lt;users_at_[hidden]&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; Date: Tue, 14 Feb 2006 13:54:21 -0500
</span><br>
<span class="quotelev3">&gt;&gt;&gt; To: Open MPI Users &lt;users_at_[hidden]&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; Subject: Re: [OMPI users] Installing OpenMPI on a solaris
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; On Feb 14, 2006, at 11:57 AM, Xiaoning (David) Yang wrote:
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; Thanks for the info. I tried to compile the simple code in your
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; email with
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 'c++ -c foo.c' and got the similar error. Does it mean that my
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; compiler was
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; not configured correctly? Thanks.
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; Yes, it points to a configuration issue with your C++ compiler.
</span><br>
<span class="quotelev3">&gt;&gt;&gt; Until that issue is resolved, it will be impossible to compile Open
</span><br>
<span class="quotelev3">&gt;&gt;&gt; MPI on that machine.
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; Brian
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; ***** Correspondence *****
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; From: Brian Barrett &lt;brbarret_at_[hidden]&gt;
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; Reply-To: Open MPI Users &lt;users_at_[hidden]&gt;
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; Date: Tue, 14 Feb 2006 08:48:49 -0500
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; To: Open MPI Users &lt;users_at_[hidden]&gt;
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; Subject: Re: [OMPI users] Installing OpenMPI on a solaris
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; On Feb 13, 2006, at 12:29 PM, Xiaoning (David) Yang wrote:
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt;&gt;&gt;&gt;&gt; I'm installing OpenMPI on a solaris system and got the following
</span><br>
<span class="quotelev2">&gt;&gt;&gt;&gt;&gt;&gt; error
</span><br>
<span class="quotelev2">&gt;&gt;&gt;&gt;&gt;&gt; message when running make:
</span><br>
<span class="quotelev2">&gt;&gt;&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt;&gt;&gt;&gt;&gt; /usr/local/lib/gcc-lib/sparc-sun-solaris2.6/2.95/../../../../
</span><br>
<span class="quotelev2">&gt;&gt;&gt;&gt;&gt;&gt; include/g++-3/s
</span><br>
<span class="quotelev2">&gt;&gt;&gt;&gt;&gt;&gt; tl_config.h:151: _G_config.h: No such file or directory
</span><br>
<span class="quotelev2">&gt;&gt;&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt;&gt;&gt;&gt;&gt; What does it mean and how to solve the problem. Thanks for any
</span><br>
<span class="quotelev2">&gt;&gt;&gt;&gt;&gt;&gt; help!
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; It is hard to tell without seeing the surrounding output, but it
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; appears that your C++ compiler is configured incorrectly and not
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; able
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; to compile STL code.  You might want to try building a simple
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; Hello,
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; World example using the IOStreams (like the one below) -- if that
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; doesn't work, you need to talk to your sysadmin or the supplier of
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; the GCC binaries you are using and figure out how to get simple
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; applications to compile.  If the simple example compiles, please
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; send
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; us the config.log from your Open MPI source tree and a bit more of
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; the output from make.
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; Thanks,
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; Brian
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; -- 
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt;    Brian Barrett
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt;    Open MPI developer
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt;    <a href="http://www.open-mpi.org/">http://www.open-mpi.org/</a>
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; #include &lt;iostream&gt;
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; int
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; main(int argc, char *argv[])
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; {
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt;      std::cout &lt;&lt; &quot;Hello, World&quot; &lt;&lt; std::endl;
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt;      return 0;
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; }
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; _______________________________________________
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; users mailing list
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; users_at_[hidden]
</span><br>
<span class="quotelev1">&gt;&gt;&gt;&gt;&gt; <a href="http://www.open-mpi.org/mailman/listinfo.cgi/users">http://www.open-mpi.org/mailman/listinfo.cgi/users</a>
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; _______________________________________________
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; users mailing list
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; users_at_[hidden]
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; <a href="http://www.open-mpi.org/mailman/listinfo.cgi/users">http://www.open-mpi.org/mailman/listinfo.cgi/users</a>
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; -- 
</span><br>
<span class="quotelev3">&gt;&gt;&gt;    Brian Barrett
</span><br>
<span class="quotelev3">&gt;&gt;&gt;    Open MPI developer
</span><br>
<span class="quotelev3">&gt;&gt;&gt;    <a href="http://www.open-mpi.org/">http://www.open-mpi.org/</a>
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; _______________________________________________
</span><br>
<span class="quotelev3">&gt;&gt;&gt; users mailing list
</span><br>
<span class="quotelev3">&gt;&gt;&gt; users_at_[hidden]
</span><br>
<span class="quotelev3">&gt;&gt;&gt; <a href="http://www.open-mpi.org/mailman/listinfo.cgi/users">http://www.open-mpi.org/mailman/listinfo.cgi/users</a>
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; _______________________________________________
</span><br>
<span class="quotelev2">&gt;&gt; users mailing list
</span><br>
<span class="quotelev2">&gt;&gt; users_at_[hidden]
</span><br>
<span class="quotelev2">&gt;&gt; <a href="http://www.open-mpi.org/mailman/listinfo.cgi/users">http://www.open-mpi.org/mailman/listinfo.cgi/users</a>
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; -- 
</span><br>
<span class="quotelev1">&gt;    Brian Barrett
</span><br>
<span class="quotelev1">&gt;    Open MPI developer
</span><br>
<span class="quotelev1">&gt;    <a href="http://www.open-mpi.org/">http://www.open-mpi.org/</a>
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; _______________________________________________
</span><br>
<span class="quotelev1">&gt; users mailing list
</span><br>
<span class="quotelev1">&gt; users_at_[hidden]
</span><br>
<span class="quotelev1">&gt; <a href="http://www.open-mpi.org/mailman/listinfo.cgi/users">http://www.open-mpi.org/mailman/listinfo.cgi/users</a>
</span><br>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="0669.php">Edgar Gabriel: "Re: [OMPI users] Dynamic process question"</a>
<li><strong>Previous message:</strong> <a href="0667.php">Jeff Squyres: "Re: [OMPI users] [O-MPI users] Job fails with mpiP"</a>
<li><strong>In reply to:</strong> <a href="0664.php">Brian Barrett: "Re: [OMPI users] Installing OpenMPI on a solaris"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="http://www.open-mpi.org/community/lists/users/2006/06/1447.php">Eric Thibodeau: "Re: [OMPI users] Installing OpenMPI on a solaris"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
