<?php

/////////////////////////////////////////////////////////////////////////

$q[] = "How do I discover the topology of an InfiniBand network?";

$anchor[] = "reader-ib-discover";

$a[] = "
There are a few tools involved in discovering the topology of an InfiniBand
network. The following [README] provides more information about this
process:<br>
<a href=\"https://github.com/open-mpi/netloc/blob/master/doc/README.infiniband\">README.infiniband</a>
";

/////////////////////////////////////////////////////////////////////////

