<?php

/////////////////////////////////////////////////////////////////////////

$q[] = "What if I have multiple networks?";

$anchor[] = "reader-multiple";

$a[] = "
It not uncommon to have a cluster with multiple networks. Often an Ethernet
network and another high-speed interconnect, or multiple of the same type of
network. In these situations you will need to run the netloc reader for each of
the networks in your system. The readers will produce network files for each
network type. The mapping mechanism will allow the netloc project to join these
networks together at specific server end points for that comprehensive view of
the HPC system topology.
";

/////////////////////////////////////////////////////////////////////////

