<?php

/////////////////////////////////////////////////////////////////////////

$q[] = "What are the netloc tools? How do I use them?";

$anchor[] = "tools-general";

$a[] = "
The netloc project creates a small collection of tools to help users collect 
and analyze the network topology. Each tool is listed below with a link to 
further documentation about how to use it properly.
<ul>
 <li> Network Readers
   <ul>
     <li><a href=\"https://github.com/open-mpi/netloc/blob/master/tools/reader_ib/README\"><tt>netloc_reader_ib</tt></a><br>
         Reader for InfiniBand Networks (see <a href=\"?category=reader_ib\">this FAQ</a> for more details)
     <li><a href=\"https://github.com/open-mpi/netloc/blob/master/tools/reader_of/README\"><tt>netloc_reader_of</tt></a><br>
         Reader for OpenFlow managed Ethernet Networks (see <a href=\"?category=reader_of\">this FAQ</a> for more details)
   </ul>
 <li><a href=\"https://github.com/open-mpi/netloc/blob/master/tools/lsnettopo/README\"><tt>lsnettopo</tt></a><br>
     A tool to display a textual representation of the network topology. It can also export the graph to some standard graph file formats.
 <li><tt>netloc_ib_extract_dats</tt><br>
     A tool to assist in the extraction of netloc data from raw InfiniBand data. (see <a href=\"?category=reader_ib\">this FAQ</a> for more details).
 <li><tt>netloc_ib_gather_raw</tt><br>
     A tool to assist in the gathering of raw InfiniBand data. (see <a href=\"?category=reader_ib\">this FAQ</a> for more details).
</ul>

";

/////////////////////////////////////////////////////////////////////////

