<?
$subject_val = "Re: [OMPI devel] Change compiler";
include("../../include/msg-header.inc");
?>
<!-- received="Mon Jul 18 16:17:04 2016" -->
<!-- isoreceived="20160718201704" -->
<!-- sent="Mon, 18 Jul 2016 13:16:34 -0700" -->
<!-- isosent="20160718201634" -->
<!-- name="Paul Hargrove" -->
<!-- email="phhargrove_at_[hidden]" -->
<!-- subject="Re: [OMPI devel] Change compiler" -->
<!-- id="CAAvDA16APzUP1C10BVWLMJ00A+C_6oQmX-oa_PcQibk=8BrwnA_at_mail.gmail.com" -->
<!-- charset="UTF-8" -->
<!-- inreplyto="D3B284C3.3781%emani1_at_llnl.gov" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> Re: [OMPI devel] Change compiler<br>
<strong>From:</strong> Paul Hargrove (<em>phhargrove_at_[hidden]</em>)<br>
<strong>Date:</strong> 2016-07-18 16:16:34
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="19237.php">Howard Pritchard: "[OMPI devel] tcp btl rendezvous performance question"</a>
<li><strong>Previous message:</strong> <a href="19235.php">Emani, Murali: "[OMPI devel] Change compiler"</a>
<li><strong>In reply to:</strong> <a href="19235.php">Emani, Murali: "[OMPI devel] Change compiler"</a>
<!-- nextthread="start" -->
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Murali,
<br>
<p>I typically configure with
<br>
&nbsp;&nbsp;&nbsp;CC=clang CXX=clang++
<br>
on the configure command line.
<br>
Editing of the files generated by configure (such as the Makefile) is not
<br>
advisable.
<br>
<p>-Paul
<br>
<p>On Mon, Jul 18, 2016 at 1:06 PM, Emani, Murali &lt;emani1_at_[hidden]&gt; wrote:
<br>
<p><span class="quotelev1">&gt; Hi all,
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; I would like to know if there is Clang support for OpenMPI codebase.
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; I am trying to change the underlying compiler from gcc to clang in
</span><br>
<span class="quotelev1">&gt; &#226;&#128;&#152;configure' and &#226;&#128;&#152;make all install&#226;&#128;&#153;, I changed these values in Makefile in
</span><br>
<span class="quotelev1">&gt; root dir and another one in config directory. The steps during &#226;&#128;&#152;configure&#226;&#128;&#153;
</span><br>
<span class="quotelev1">&gt; reflect gcc again instead of clang. Is this the right way or am I missing
</span><br>
<span class="quotelev1">&gt; something here ?
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; Is the wrapper compiler environment variable &#226;&#128;&#152;OMPI_CC&#226;&#128;&#153; intended to replace
</span><br>
<span class="quotelev1">&gt; the underlying compiler when compiling an MPI application.
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; &#226;&#128;&#148;
</span><br>
<span class="quotelev1">&gt; Murali
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; _______________________________________________
</span><br>
<span class="quotelev1">&gt; devel mailing list
</span><br>
<span class="quotelev1">&gt; devel_at_[hidden]
</span><br>
<span class="quotelev1">&gt; Subscription: <a href="https://www.open-mpi.org/mailman/listinfo.cgi/devel">https://www.open-mpi.org/mailman/listinfo.cgi/devel</a>
</span><br>
<span class="quotelev1">&gt; Link to this post:
</span><br>
<span class="quotelev1">&gt; <a href="http://www.open-mpi.org/community/lists/devel/2016/07/19235.php">http://www.open-mpi.org/community/lists/devel/2016/07/19235.php</a>
</span><br>
<span class="quotelev1">&gt;
</span><br>
<p><p><p><pre>
-- 
Paul H. Hargrove                          PHHargrove_at_[hidden]
Computer Languages &amp; Systems Software (CLaSS) Group
Computer Science Department               Tel: +1-510-495-2352
Lawrence Berkeley National Laboratory     Fax: +1-510-486-6900
</pre>
<hr>
<ul>
<li>text/html attachment: <a href="http://www.open-mpi.org/community/lists/devel/att-19236/attachment">attachment</a>
</ul>
<!-- attachment="attachment" -->
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="19237.php">Howard Pritchard: "[OMPI devel] tcp btl rendezvous performance question"</a>
<li><strong>Previous message:</strong> <a href="19235.php">Emani, Murali: "[OMPI devel] Change compiler"</a>
<li><strong>In reply to:</strong> <a href="19235.php">Emani, Murali: "[OMPI devel] Change compiler"</a>
<!-- nextthread="start" -->
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
