<?php
// Assume that $base has already been set

$this_nav[] = new Nav("hwloc announce archives",
                      "https://mail-archive.com/hwloc-announce@lists.open-mpi.org/");
$this_nav[] = new Nav("hwloc users archives",
                      "https://mail-archive.com/hwloc-users@lists.open-mpi.org/");
$this_nav[] = new Nav("hwloc devel archives",
                      "https://mail-archive.com/hwloc-devel@lists.open-mpi.org/");
