<?php
// Assume that $base has already been set

// This archive is empty
//$this_nav[] = new Nav("MTT announce archives", "$base/community/lists/mtt-announce/");
$this_nav[] = new Nav("MTT users archives",
                      "https://mail-archive.com/mtt-users@lists.open-mpi.org/");
$this_nav[] = new Nav("MTT developers archives",
                      "https://mail-archive.com/mtt-devel@lists.open-mpi.org/");
