<?php
// Assume that $base has already been set

$this_nav[] = new Nav("OMPI announce archives",
                      "https://www.mail-archive.com/announce@lists.open-mpi.org/");
$this_nav[] = new Nav("OMPI users archives",
                      "https://www.mail-archive.com/users@lists.open-mpi.org/");
$this_nav[] = new Nav("OMPI devel archives",
                      "https://www.mail-archive.com/devel@lists.open-mpi.org/");
