<?php
$title = "Open MPI and OpenIB: Past, Present, and Future";
$overview = "Talk presented at the OpenIB Workshop, 2006";

$authors = "Jeff Squyres, Tim Woodall, Shawn Hansen";

$abstract = "This talk provides an overview of the Open MPI project,
the current status of Open MPI's OpenIB support, some IB issues that
the Open MPI team has identified while deploying OpenIB in large-scale
clusters, and an invitation to an Open MPI Developer's Workshop,
hosted by Cisco Systems in San Jose, CA, in April 2006.";

$presented = "<a href=\"http://www.openfabrics.org/archives/spring2006sonoma.htm\">" . "OpenIB Workshop</a>, February 2006, in Sonoma, CA, USA";

$files[] = "Open-MPI-Sonoma.pdf";

$month = 2;
$day = 7;
$year = 2006;
