<?php

$title = "An Extensible Framework for Distributed Testing of MPI
Implementations";

$overview = "An overview of the MPI Testing Tool (MTT).";

$presented = "<a href=\"http://pvmmpi07.lri.fr/\">" .
"EuroPVM/MPI '07</a>, September 30th - October 3rd, 2007, Paris,
France.";

$authors = "Joshua Hursey, Ethan Mallove, Jeffrey M. Squyres, and
Andrew Lumsdaine";

$abstract = "Complex code bases require continual testing to ensure that
both new development and routine maintenance do not create unintended
side effects. Automation of regression testing is a common mechanism
to ensure consistency, accuracy, and repeatability of results. The
MPI Testing Tool (MTT) is a flexible framework specifically designed for
testing MPI implementations across multiple organizations and environments.
The MTT offers a unique combination of features not available
in any individual testing framework, including a built-in multiplicative
effect for creating and running tests, historical correctness and performance
analysis, and support for multiple cluster resource managers.";

$files[] = "euro-pvmmpi-2007-mtt.pdf";

$month = 9;
$day = 30;
$year = 2007;

$bibtex = "@InProceedings{hursey07:_exten_framew_for_distr_testin,
  author =	 {Joshua Hursey and Ethan Mallove and Jeffrey M. Squyres and Andrew Lumsdaine},
  title =	 {An Extensible Framework for Distributed Testing of MPI Implementations},
  booktitle =    {Proceedings, Euro PVM/MPI},
  year =         2007,
  address =      {Paris, France},
  month =        {October}
}";
