<?php
$title = "Open MPI version number scheme update";
$overview = "Slides descripting updates to how Open MPI will be version numbered and released";

$authors = "The Open MPI developer community";

$abstract = $overview;

#$presented = "<a href=\"http://sc14.supercomputing.org/\">" . "SC'14</a>,
#November, 2014, in New Orleans, LA, USA";

$files[] = "ompi-new-version-numbers-for-end-users.pdf";
$files[] = "ompi-new-version-numbers-for-end-users.pptx";

$month = 6;
$day = 23;
$year = 2015;

$bibtex = "";
