<?
$subject_val = "[OMPI users] Program hangs";
include("../../include/msg-header.inc");
?>
<!-- received="Thu Nov 19 20:50:22 2009" -->
<!-- isoreceived="20091120015022" -->
<!-- sent="Fri, 20 Nov 2009 09:50:17 +0800" -->
<!-- isosent="20091120015017" -->
<!-- name="Jiaye Li" -->
<!-- email="jameslipd_at_[hidden]" -->
<!-- subject="[OMPI users] Program hangs" -->
<!-- id="b5d787260911191750p5b5a28d8q301bd46cfab95ac4_at_mail.gmail.com" -->
<!-- charset="UTF-8" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> [OMPI users] Program hangs<br>
<strong>From:</strong> Jiaye Li (<em>jameslipd_at_[hidden]</em>)<br>
<strong>Date:</strong> 2009-11-19 20:50:17
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="11244.php">vasilis gkanis: "Re: [OMPI users] Program hangs"</a>
<li><strong>Previous message:</strong> <a href="11242.php">David Singleton: "Re: [OMPI users] exceedingly virtual memory consumption of MPI, environment if higher-setting &quot;ulimit -s&quot;"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="11244.php">vasilis gkanis: "Re: [OMPI users] Program hangs"</a>
<li><strong>Reply:</strong> <a href="11244.php">vasilis gkanis: "Re: [OMPI users] Program hangs"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Hello
<br>
<p>I installed openmpi-1.3.3 on my single node(cpu) intel 64bit quad-core
<br>
machine. The compiler info is:
<br>
<p><p>**************************************************************************************************************
<br>
intel-icc101018-10.1.018-1.i386
<br>
libgcc-4.4.0-4.i586
<br>
gcc-4.4.0-4.i586
<br>
gcc-gfortran-4.4.0-4.i586
<br>
gcc-c++-4.4.0-4.i586
<br>
intel-ifort101018-10.1.018-1.i386
<br>
<p>and the architecture is:
<br>
<p>processor    : 0
<br>
vendor_id    : GenuineIntel
<br>
cpu family    : 6
<br>
model        : 23
<br>
model name    : Intel(R) Core(TM)2 Quad CPU    Q9550  @ 2.83GHz
<br>
stepping    : 10
<br>
cpu MHz        : 2825.937
<br>
cache size    : 6144 KB
<br>
physical id    : 0
<br>
siblings    : 4
<br>
core id        : 0
<br>
cpu cores    : 4
<br>
apicid        : 0
<br>
initial apicid    : 0
<br>
fdiv_bug    : no
<br>
hlt_bug        : no
<br>
f00f_bug    : no
<br>
coma_bug    : no
<br>
fpu        : yes
<br>
fpu_exception    : yes
<br>
cpuid level    : 13
<br>
wp        : yes
<br>
flags        : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov
<br>
pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx lm constant_tsc
<br>
arch_perfmon pebs bts pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16
<br>
xtpr pdcm sse4_1 xsave lahf_lm tpr_shadow vnmi flexpriority
<br>
bogomips    : 5651.87
<br>
clflush size    : 64
<br>
power management:
<br>
<p>**************************************************************************************************************
<br>
<p>I compiled PWscf program with openmpi and tested the program. At the
<br>
beginning, the execution of  PW went on well, but after about 10 h, when the
<br>
program is going to finish. The program hang there, but the cpu time is
<br>
still occupied. (100% taken up by the program). There seems to be something
<br>
wrong, somewhere. Any ideas? Thank you in advance.
<br>
<p>This is the config.log of Ompi:
<br>
<p>**************************************************************************************************************
<br>
This file contains any messages produced by compilers while
<br>
running configure, to aid debugging if configure makes a mistake.
<br>
<p>It was created by Open MPI configure 1.3.3, which was
<br>
generated by GNU Autoconf 2.63.  Invocation command line was
<br>
<p>&nbsp;&nbsp;$ ./configure --prefix=/opt/openmpi-1.3.3 --disable-static CC=gcc FC=ifort
<br>
F77=ifort --enable-shared
<br>
<p>## --------- ##
<br>
## Platform. ##
<br>
## --------- ##
<br>
<p>hostname = localhost
<br>
uname -m = i686
<br>
uname -r = 2.6.29.4-167.fc11.i686.PAE
<br>
uname -s = Linux
<br>
uname -v = #1 SMP Wed May 27 17:28:22 EDT 2009
<br>
<p>/usr/bin/uname -p = unknown
<br>
/bin/uname -X     = unknown
<br>
<p>/bin/arch              = i686
<br>
/usr/bin/arch -k       = unknown
<br>
/usr/convex/getsysinfo = unknown
<br>
/usr/bin/hostinfo      = unknown
<br>
/bin/machine           = unknown
<br>
/usr/bin/oslevel       = unknown
<br>
/bin/universe          = unknown
<br>
<p>PATH: /home/jy/Download/XCrySDen-1.5.21-src-all
<br>
PATH: /home/jy/Download/XCrySDen-1.5.21-src-all
<br>
PATH: /home/jy/Download/XCrySDen-1.5.21-src-all
<br>
PATH: /home/jy/Download/XCrySDen-1.5.21-src-all
<br>
PATH: /home/jy/.wine/drive_c/windows
<br>
PATH: /home/jy/Download/XCrySDen-1.5.21-src
<br>
PATH: /home/jy/bin/vtstscripts
<br>
PATH: /opt/mpich2-1.2/bin
<br>
PATH: /opt/intel/fc/10.1.018/bin
<br>
PATH: /opt/intel/cc/10.1.018/bin
<br>
PATH: /usr/lib/qt-3.3/bin
<br>
PATH: /usr/kerberos/bin
<br>
PATH: /usr/lib/ccache
<br>
PATH: /usr/local/bin
<br>
PATH: /usr/bin
<br>
PATH: /bin
<br>
PATH: /usr/local/sbin
<br>
PATH: /usr/sbin
<br>
PATH: /sbin
<br>
PATH: /home/jy/Download/XCrySDen-1.5.21-src/scripts
<br>
PATH: /home/jy/Download/XCrySDen-1.5.21-src/util
<br>
PATH: /home/jy/Download/XCrySDen-1.5.21-src-all/scripts
<br>
PATH: /home/jy/Download/XCrySDen-1.5.21-src-all/util
<br>
PATH: /home/jy/Download/XCrySDen-1.5.21-src-all/scripts
<br>
PATH: /home/jy/Download/XCrySDen-1.5.21-src-all/util
<br>
PATH: /home/jy/bin
<br>
PATH: /home/jy/Download/XCrySDen-1.5.21-src-all/scripts
<br>
PATH: /home/jy/Download/XCrySDen-1.5.21-src-all/util
<br>
PATH: /home/jy/Download/XCrySDen-1.5.21-src-all/scripts
<br>
PATH: /home/jy/Download/XCrySDen-1.5.21-src-all/util
<br>
<p><p>## ----------- ##
<br>
## Core tests. ##
<br>
## ----------- ##
<br>
<p>configure:3424: checking for a BSD-compatible install
<br>
configure:3492: result: /usr/bin/install -c
<br>
configure:3503: checking whether build environment is sane
<br>
configure:3546: result: yes
<br>
configure:3571: checking for a thread-safe mkdir -p
<br>
configure:3610: result: /bin/mkdir -p
<br>
configure:3623: checking for gawk
<br>
configure:3639: found /usr/bin/gawk
<br>
configure:3650: result: gawk
<br>
configure:3661: checking whether make sets $(MAKE)
<br>
configure:3683: result: yes
<br>
configure:3853: checking how to create a ustar tar archive
<br>
configure:3866: tar --version
<br>
tar (GNU tar) 1.22
<br>
Copyright (C) 2009 Free Software Foundation, Inc.
<br>
License GPLv3+: GNU GPL version 3 or later &lt;<a href="http://gnu.org/licenses/gpl.html">http://gnu.org/licenses/gpl.html</a>
<br>
<span class="quotelev1">&gt;.
</span><br>
This is free software: you are free to change and redistribute it.
<br>
There is NO WARRANTY, to the extent permitted by law.
<br>
<p>.........
<br>
<p><p>configure: exit 0
<br>
<p><p>**************************************************************************************************************
<br>
<p><pre>
-- 
Sincerely yours
Jiaye Li
</pre>
<hr>
<ul>
<li>text/html attachment: <a href="http://www.open-mpi.org/community/lists/users/att-11243/attachment">attachment</a>
</ul>
<!-- attachment="attachment" -->
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="11244.php">vasilis gkanis: "Re: [OMPI users] Program hangs"</a>
<li><strong>Previous message:</strong> <a href="11242.php">David Singleton: "Re: [OMPI users] exceedingly virtual memory consumption of MPI, environment if higher-setting &quot;ulimit -s&quot;"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="11244.php">vasilis gkanis: "Re: [OMPI users] Program hangs"</a>
<li><strong>Reply:</strong> <a href="11244.php">vasilis gkanis: "Re: [OMPI users] Program hangs"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
