<?
$subject_val = "Re: [OMPI users] Intel compiled undefined reference errors (i.e.	mpi_reduce_)";
include("../../include/msg-header.inc");
?>
<!-- received="Mon Jun 24 14:22:06 2013" -->
<!-- isoreceived="20130624182206" -->
<!-- sent="Mon, 24 Jun 2013 18:21:53 +0000" -->
<!-- isosent="20130624182153" -->
<!-- name="Elken, Tom" -->
<!-- email="tom.elken_at_[hidden]" -->
<!-- subject="Re: [OMPI users] Intel compiled undefined reference errors (i.e.	mpi_reduce_)" -->
<!-- id="1182FB2B5679CE4B8BAD97725F014BB73281C390_at_FMSMSX104.amr.corp.intel.com" -->
<!-- charset="us-ascii" -->
<!-- inreplyto="CA+LevYKcVXcTXO97=m0RPtrPo=kQV4g94tQnadehOmtgbgPdqQ_at_mail.gmail.com" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> Re: [OMPI users] Intel compiled undefined reference errors (i.e.	mpi_reduce_)<br>
<strong>From:</strong> Elken, Tom (<em>tom.elken_at_[hidden]</em>)<br>
<strong>Date:</strong> 2013-06-24 14:21:53
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="22204.php">Jason Maldonis: "Re: [OMPI users] Intel compiled undefined reference errors (i.e. mpi_reduce_)"</a>
<li><strong>Previous message:</strong> <a href="22202.php">Jason Maldonis: "[OMPI users] Intel compiled undefined reference errors (i.e. mpi_reduce_)"</a>
<li><strong>In reply to:</strong> <a href="22202.php">Jason Maldonis: "[OMPI users] Intel compiled undefined reference errors (i.e. mpi_reduce_)"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="22204.php">Jason Maldonis: "Re: [OMPI users] Intel compiled undefined reference errors (i.e. mpi_reduce_)"</a>
<li><strong>Reply:</strong> <a href="22204.php">Jason Maldonis: "Re: [OMPI users] Intel compiled undefined reference errors (i.e. mpi_reduce_)"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
I saw a couple of issues noted below ...
<br>
<p><p>Now I am still getting some undefined reference errors. Namely:
<br>
[root_at_odie 060911_rmc_eam_gr_vk_t4]# make
<br>
ifort -g -debug all -check all -implicitnone -warn all -o rmc_test ran2.o globals.o read_inputs.o model.o rmc_functions.o scattering_factors.o fem1.o gr.o eam.o rmc_v_1_0.o  -L /export/apps/openmpi_intel_20130618/lib -lmpi
<br>
[Tom]
<br>
<span class="quotelev1">&gt;From your makefile below, this compile command is generated by your DEBUG target.  Fixes to the FC_DEBUG command noted below in your makefile...
</span><br>
<p>ifort: warning #10182: disabling optimization; runtime debug checks enabled
<br>
fem1.o: In function `fem':
<br>
/state/partition1/home/jjmaldonis/Jinwoo/2011/060911_rmc_eam_gr_vk_t4/fem1.f90:583: undefined reference to `mpi_reduce_'
<br>
/state/partition1/home/jjmaldonis/Jinwoo/2011/060911_rmc_eam_gr_vk_t4/fem1.f90:584: undefined reference to `mpi_reduce_'
<br>
fem1.o: In function `fem_update':
<br>
[Tom]  &lt;snip&gt;
<br>
<p>The above undefined reference errors are my problem.
<br>
<p>Below are my PATH and LD_LIBRARY_PATH variables, if they are of help.
<br>
echo $PATH
<br>
/usr/lib64/qt-3.3/bin:/state/partition1/apps/intel_20130618/composer_xe_2013.3.163/bin/intel64:/state/partition1/apps/intel_20130618/composer_xe_2013.3.163/mpirt/bin/intel64:/state/partition1/apps/intel_20130618/composer_xe_2013.3.163/bin/intel64:/state/partition1/apps/intel_20130618/composer_xe_2013.3.163/bin/intel64_mic:/state/partition1/apps/intel_20130618/composer_xe_2013.3.163/debugger/gui/intel64:/export/apps/intel_20130618/advisor_xe_2013/bin64:/export/apps/intel_20130618/inspector_xe_2013/bin64:/export/apps/intel_20130618/vtune_amplifier_xe_2013/bin64:/usr/local/bin:/bin:/usr/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/eclipse:/opt/ganglia/bin:/opt/ganglia/sbin:/usr/java/latest/bin:/opt/maven/bin:/export/apps/openmpi_intel_20130618/:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin:/opt/condor/bin:/opt/condor/sbin:/usr/local/samba/sbin:/opt/gridengine/bin/linux-x64:/export/apps/openmpi_intel_20130618/bin/:/usr/local/samba/sbin:/export/apps/openmpi_intel_20130618/bin/
<br>
[Tom]
<br>
You should try to get
<br>
/export/apps/openmpi_intel_20130618/bin
<br>
earlier in your path, ahead of this part:
<br>
/state/partition1/apps/intel_20130618/composer_xe_2013.3.163/mpirt/bin/intel64
<br>
which comes from the intel compilers 'compilervars.[c]sh' script and points to the Intel MPI run-time libraries (which you don't want, since you are using Open MPI).
<br>
Either that, or use a full path to your OpenMPI/Intel mpirun when you are ready to run the app., such as:
<br>
/export/apps/openmpi_intel_20130618/bin/mpirun .... ./rmc_test
<br>
<p>[Tom] &lt;snip&gt;
<br>
<p>Below I will paste my makefile, and attached are the compressed &quot;./configure ...&quot; and &quot;make all install&quot; command logs. Please let me know anything else that you need.
<br>
<p><p>#
<br>
# default makefile for ifort compiler with more or less
<br>
# appropriate options for debugging and high performance
<br>
#
<br>
<p># application name
<br>
APP = rmc_test
<br>
<p># list of source files
<br>
SRC = ran2.f90 globals.f90 read_inputs.f90 model.f90 rmc_functions.f90 scattering_factors.f90 fem1.f90 gr.f90 eam.f90 rmc_v_1_0.f90
<br>
<p># list of object files
<br>
OBJ = ran2.o globals.o read_inputs.o model.o rmc_functions.o scattering_factors.o fem1.o gr.o eam.o rmc_v_1_0.o
<br>
<p># define libraries needed by the linker
<br>
LIBS = -L /export/apps/openmpi_intel_20130618/lib -lmpi
<br>
[Tom]
<br>
Make this blank, so you will depend on 'mpif90' to provide the linking information:
<br>
LIBS =
<br>
<p><p># -rpath /state/partition1/apps/intel_20130618/composer_xe_2013.3.163/compiler/lib/
<br>
<p># compiler options for debugging
<br>
FC_DEBUG = ifort -g -debug all -check all -implicitnone -warn all
<br>
[Tom] You should make this more like your FC_OPT definition, using mpif90 rather than ifort, such as:
<br>
FC_DEBUG = mpif90 -g -debug all -check all -implicitnone -warn all
<br>
<p>[Tom] Cheers, Tom
<br>
<p># compiler options for optmized running
<br>
#FC_OPT = ifort -O3 -xO -ipo -no-prec-div -static
<br>
#FC_OPT = mpif90 -O3 -ipo -static
<br>
FC_OPT = mpif90 -O3
<br>
<p># build rules
<br>
<p>.SUFFIXES: .f90 .o
<br>
.f90.o:
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;${FC_DEBUG} -c $&lt;
<br>
<p>debug: ${OBJ}
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;${FC_DEBUG} -o ${APP} ${OBJ} ${LIBS}
<br>
<p>opt: ${SRC}
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;${FC_OPT} -o ${APP} ${SRC} ${LIBS}
<br>
<p>clean:
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rm -f *.mod *.o ${APP}
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ln -s /export/apps/openmpi_intel_20130618/lib/mpi.mod ./mpi.mod
<br>
<p><hr>
<ul>
<li>text/html attachment: <a href="http://www.open-mpi.org/community/lists/users/att-22203/attachment">attachment</a>
</ul>
<!-- attachment="attachment" -->
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="22204.php">Jason Maldonis: "Re: [OMPI users] Intel compiled undefined reference errors (i.e. mpi_reduce_)"</a>
<li><strong>Previous message:</strong> <a href="22202.php">Jason Maldonis: "[OMPI users] Intel compiled undefined reference errors (i.e. mpi_reduce_)"</a>
<li><strong>In reply to:</strong> <a href="22202.php">Jason Maldonis: "[OMPI users] Intel compiled undefined reference errors (i.e. mpi_reduce_)"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="22204.php">Jason Maldonis: "Re: [OMPI users] Intel compiled undefined reference errors (i.e. mpi_reduce_)"</a>
<li><strong>Reply:</strong> <a href="22204.php">Jason Maldonis: "Re: [OMPI users] Intel compiled undefined reference errors (i.e. mpi_reduce_)"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
