<?php

$titles[] = "What is MPI?  What is Open MPI?";

$a = "what-is-mpi";
$anchors[] = $a;

$durations[$a] = "20:18";

$base = "what-is-[open]-mpi";
$extras[$a][] = "$base-1up.pdf";
$extras[$a][] = "$base-2up.pdf";
$youtubes[$a] = "D0-xSWBGNAw";

$summaries[$a] = "Brief description of what MPI is, including a brief 
summary of the Open MPI Project.";

##########################################################################

$titles[] = "The ABCs of Open MPI: Decoding the Alphabet Soup of the Modern HPC Ecosystem (Part 1)";

$a = "abcs-of-open-mpi-part-1";
$anchors[] = $a;

$durations[$a] = "1:22:49";

$extras[$a][] = "easybuild_tech_talks_01_OpenMPI_part1_20200623.pdf";
$youtubes[$a] = "WpVbcYnFJmQ";

$summaries[$a] = "In conjunction with the EasyBuild community, Ralph
Castain and Jeff Squyres gave an online seminar about Open MPI in June
of 2020.  The general scope of the presentation was to demystify the
alphabet soup of the Open MPI ecosystem: the user-facing frameworks
and components, the 3rd party dependencies, etc.  This video is part 1
of that seminar.";

##########################################################################

$titles[] = "The ABCs of Open MPI: Decoding the Alphabet Soup of the Modern HPC Ecosystem (Part 2)";

$a = "abcs-of-open-mpi-part-2";
$anchors[] = $a;

$durations[$a] = "1:39:56";

$extras[$a][] = "easybuild_tech_talks_01_OpenMPI_part2_20200708.pdf";
$youtubes[$a] = "C4XfxUoSYQs";

$summaries[$a] = "In conjunction with the EasyBuild community, Ralph
Castain and Jeff Squyres gave an online seminar about Open MPI in June
of 2020.  The general scope of the presentation was to demystify the
alphabet soup of the Open MPI ecosystem: the user-facing frameworks
and components, the 3rd party dependencies, etc.  This video is part 2
of that seminar.";
