<?php

$titles[] = "What is MPI?  What is Open MPI?";

$a = "what-is-mpi";
$anchors[] = $a;

$durations[$a] = "20:18";

$base = "what-is-[open]-mpi";
$extras[$a][] = "$base-1up.pdf";
$extras[$a][] = "$base-2up.pdf";
$youtubes[$a] = "D0-xSWBGNAw";

$summaries[$a] = "Brief description of what MPI is, including a brief 
summary of the Open MPI Project.";

##########################################################################