<?php

$titles[] = "Open MPI: Overview/Architecture";

$a = "Cisco_JeffSquyres";
$anchors[] = $a;

$durations[$a] = "2:09:04";
$video_heights[$a] = 720;
$video_widths[$a] = 1280;

$base = "Cisco_JeffSquyres";
$extras[$a][] = "$base-1up.pdf";
$extras[$a][] = "$base-2up.pdf";
$youtubes[$a] = "4FoJmJslGxI";

$summaries[$a] = "Basic overview of Open MPI's architecture and general code base.

<strong><font color=\"red\">NOTE:</font></strong> These videos were
made in 2012.  While much of the architectural overview is still
relevant, many individual details have changed in Open MPI since then.
For example, the version number scheme cited in this video is no
longer used (<a
href=\"https://www.open-mpi.org/software/ompi/versions/\">see here for
a description of the current scheme</a>).  Just be aware that these
videos were a snapshot in time, and have a combination of both
architectural/high-level details and individual implementation
details, the specifics of which may have evolved over time.

A change was made to OMPI's library dependencies shortly after the vide was created - details of the linking hierarchy on slide 91 have been revised. Please see the slides in the accompanying pdf files for the new linking chart";

##########################################################################

$titles[] = "Open MPI Data Transfer";

$a = "Sandia_BrianBarrett";
$anchors[] = $a;

$durations[$a] = "2:09:33";
$video_heights[$a] = 720;
$video_widths[$a] = 1280;

$base = "Sandia_BrianBarrett";
$extras[$a][] = "$base-1up.pdf";
$extras[$a][] = "$base-2up.pdf";
$youtubes[$a] = "O8sTLRKM1Rs";

$summaries[$a] = "Detailed overview of the Open MPI data transfer system.

<strong><font color=\"red\">NOTE:</font></strong> These videos were
made in 2012.  While much of the architectural overview is still
relevant, many individual details have changed in Open MPI since then.
Just be aware that these videos were a snapshot in time, and have a
combination of both architectural/high-level details and individual
implementation details, the specifics of which may have evolved over
time.";

##########################################################################

$titles[] = "Scalable and Modular Parallel I/O for Open MPI";

$a = "Parallel_EdgarGabriel";
$anchors[] = $a;

$durations[$a] = "1:37:45";
$video_heights[$a] = 720;
$video_widths[$a] = 1280;

$base = "Parallel_EdgarGabriel";
$extras[$a][] = "$base-1up.pdf";
$extras[$a][] = "$base-2up.pdf";
$youtubes[$a] = "iMkE2_QGcTo";

$summaries[$a] = "Overview of parallel I/O in Open MPI.

<strong><font color=\"red\">NOTE:</font></strong> These videos were
made in 2012.  While much of the architectural overview is still
relevant, many individual details have changed in Open MPI since then.
Just be aware that these videos were a snapshot in time, and have a
combination of both architectural/high-level details and individual
implementation details, the specifics of which may have evolved over
time.";

##########################################################################

