<?php

$titles[] = "Basic Architecture and Tuning";

$a = "basic-arch-and-tuning";
$anchors[] = $a;

$durations[$a] = "13:36";
$video_heights[$a] = 480;
$video_widths[$a] = 640;

$base = "arch-and-tuning";
$notes[$a] = $quicktime;
$videos[$a] = "$base.mov";
$extras[$a][] = "$base-1up.pdf";
$extras[$a][] = "$base-2up.pdf";
$youtubes[$a] = "ZMeLtZWqVKo";

$summaries[$a] = "Describes the overall architecture of Open MPI and the 
basics of its run-time tuning capabilities.";

##########################################################################
