<?php
$title = "Open MPI for Cray XE/XK Systems";

$overview = "Open MPI for Cray XE/XK Systems";

$presented = "<a href=\"https://cug.org/1-conferences/CUG2012/\">" .
"Cray Users Group (CUG) '12</a>, April 29th - May 3rd, 2012, Stuttgart, Germany.";

$authors = "Manjunath Gorentla Venkata, Richard L. Graham, Nathan T. Hjelm, and Samuel K. Gutierrez";

$abstract = "Open MPI provides an implementation of the MPI standard supporting communications over a range of high-performance network interfaces. Recently, ORNL and LANL have collaborated on creating a port of Open MPI for Gemini, the network interface for Cray XE and XK systems. In this paper, we present our design and implementation of Open MPI's point-to-point and collective operations for Gemini, and techniques we employ to provide good scaling, and performance characteristics.";

$files[] = "cug_2012_open_mpi_for_cray_xe_xk.pdf";

$month = 4;
$day = 29;
$year = 2012;

$bibtex = "@article{60095403,
author = {Manjunath Gorentla Venkata and Richard L Graham and Nathan T Hjelm and Samuel K Gutierrez},
title = {Open MPI for Cray XE/XK Systems},
year = {2012},
masid = {60095403}
}";
