<? include("../../include/msg-header.inc"); ?>
<!-- received="Thu Jul 20 04:10:29 2006" -->
<!-- isoreceived="20060720081029" -->
<!-- sent="Thu, 20 Jul 2006 10:11:51 +0200" -->
<!-- isosent="20060720081151" -->
<!-- name="Adrian Knoth" -->
<!-- email="adi_at_[hidden]" -->
<!-- subject="Re: [OMPI devel] Building ompi occasionally touches the source files" -->
<!-- id="20060720081150.GX28805_at_drcomp.erfurt.thur.de" -->
<!-- charset="iso-8859-1" -->
<!-- inreplyto="20060717200505.GK28805_at_drcomp.erfurt.thur.de" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>From:</strong> Adrian Knoth (<em>adi_at_[hidden]</em>)<br>
<strong>Date:</strong> 2006-07-20 04:11:51
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="0977.php">Brian Barrett: "[OMPI devel] SVN breakage / new event library committed"</a>
<li><strong>Previous message:</strong> <a href="0975.php">Pierre: "Re: [OMPI devel] Problem compiling openmpi 1.1"</a>
<li><strong>In reply to:</strong> <a href="0971.php">Adrian Knoth: "[OMPI devel] Building ompi occasionally touches the source files"</a>
<!-- nextthread="start" -->
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
On Mon, Jul 17, 2006 at 10:05:05PM +0200, Adrian Knoth wrote:
<br>
<p>Hi,
<br>
<p><p><span class="quotelev1">&gt; The source is shared via svn, so it's for sure all are using the
</span><br>
<span class="quotelev1">&gt; same code.
</span><br>
<p><span class="quotelev1">&gt;  2. If compiling inside my directory layout, the build 
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt;     a) changes the following two files in trunk/src/
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; adi_at_ten:~/trunk/src$ svn st
</span><br>
<span class="quotelev1">&gt; M      opal/util/show_help_lex.c
</span><br>
<span class="quotelev1">&gt; M      opal/util/keyval/keyval_lex.c
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt;     b) fails to complete (see attachment), the errors are all
</span><br>
<span class="quotelev1">&gt;        related to lex.
</span><br>
<p>We've solved this bug and it is not OMPI-related.
<br>
<p>The long story:
<br>
<p>Whenever an .l-file is newer than its corresponding .c-file, it
<br>
is generated by a rule from our toplevel Makefile.
<br>
<p>svn changes the c/m-time, so flex is called, and probably due to
<br>
disabled autoconf-tools, this call is done with wrong parameters.
<br>
<p>The question why this behaviour was only seen on some of my
<br>
hosts is even weirder: The svn checkout generates timestamps.
<br>
If you checkout to an ext2/ext3-filesystem, everything works,
<br>
but the failing hosts all use xfs.
<br>
<p>We believe that xfs has a higher resolution for timestamps,
<br>
so the age of corresponding .l- and .c-files differ for
<br>
some value of a very small delta, thus forcing to rerun
<br>
flex and breaking the code.
<br>
<p>Our fix is quite simple: we touch the .c-files whenever there
<br>
are .c-files belonging to existing .l-files. Obviously, the
<br>
c-files are now &quot;newer&quot; and regeneration is prevented.
<br>
<p><p>Sorry for inconvenience.
<br>
<p><pre>
-- 
mail: adi_at_[hidden]  	<a href="http://adi.thur.de">http://adi.thur.de</a>	PGP: v2-key via keyserver
Idiot. Versager. Was f&#252;r Luschen laufen heutzutage eigentlich im Usenet 
herum?			(Felix von Leitner in de.alt.sysadmin.recovery)
</pre>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="0977.php">Brian Barrett: "[OMPI devel] SVN breakage / new event library committed"</a>
<li><strong>Previous message:</strong> <a href="0975.php">Pierre: "Re: [OMPI devel] Problem compiling openmpi 1.1"</a>
<li><strong>In reply to:</strong> <a href="0971.php">Adrian Knoth: "[OMPI devel] Building ompi occasionally touches the source files"</a>
<!-- nextthread="start" -->
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
