.\" Contributed by Dirk Eddelbuettel <edd@debian.org> under the BSD license
.TH OMPI_INFO 1 "June 2006" "Open MPI" "OPEN MPI COMMANDS"
.SH NAME
ompi_info - Information about the OpenMPI installation
.SH SYNOPSIS
.B ompi_info [options]
.SH DESCRIPTION
.PP
.B ompi_info
provides detailed information about the OpenMPI installation.
.SH OPTIONS
.B ompi_info
accepts the following options:
.TP 8
.I \-a|\-\-all 
Show all configuration options and MCA parameters
.TP 8
.I \-\-arch   
Show architecture Open MPI was compiled on
.TP 8
.I \-c|\-\-config
Show configuration options
.TP 8
.I \-gmca|\-\-gmca <arg0> <arg1>
Pass global MCA parameters that are applicable to all contexts (arg0 is the
parameter name; arg1 is the parameter value)
.TP 8
.I \-h|\-\-help
Show this help message
.TP 8
.I \-\-hostname
Show the hostname that Open MPI was configured and built on
.TP 8
.I \-\-internal
Show internal MCA parameters (not meant to be modified by users)
.TP 8
.I \-mca|\-\-mca <arg0> <arg1>
Pass context-specific MCA parameters; they are considered global if --gmca is
not used and only one context is specified (arg0 is the parameter name; arg1
is the parameter value) 
.TP 8
.I \-\-param <arg0> <arg1>
Show MCA parameters
.TP 8
.I \-\-parsable
Display output in parsable format
.I \-\-parseable
Synonym for --parsable
.TP 8
.I \-\-path <arg0>
Show paths that Open MPI was configured with
.TP 8
.I \-\-pretty
Display output in 'prettyprint' format (default)
.TP 8
.I \-v|\-\-version <arg0> <arg1>
Show version of Open MPI or a component
.SH AUTHORS
The OpenMPI maintainers -- see 
.I http://www.openmpi.org 
or the file
.IR AUTHORS .

This manual page was added by Dirk Eddelbuettel <edd@debian.org>, 
one of the Debian GNU/Linux maintainers for 
.BR OpenMPI , 
and may be used by others.
