.\" Contributed by Dirk Eddelbuettel <edd@debian.org> under the BSD license
.TH OPAL_WRAPPER 1 "June 2006" "Open MPI" "OPEN MPI COMMANDS"
.SH NAME
opal_wrapper - Internal OpenMPI wrapper command
.SH SYNOPSIS
.B opal_wrapper [options]
.SH DESCRIPTION
.PP
.B opal_wrapper
is not meant to be called directly, but is the backend called by the commands
.BR ortecc ,
.BR ortec++ ,
.BR opalcc ,
.BR opalc++ ,
.BR mpif90.openmpi ,
.BR mpif77.openmpi ,
.BR mpicxx.openmpi ,
.BR mpiCC.openmpi ,
.BR mpicc.openmpi and
.BR mpic++.openmpi .

.SH SEE ALSO
.BR ortecc (1),
.BR ortec++ (1),
.BR opalccc (1),
.BR mpif90.openmpi (1),
.BR mpif77.openmpi (1),
.BR mpicxx.openmpi (1),
.BR mpiCC.openmpi (1),
.BR mpicc.openmpi (1),
.BR mpic++.openmpi .
 and the website at
.IR http://www.openmpi.org .

.SH AUTHORS
The OpenMPI maintainers -- see 
.I http://www.openmpi.org 
or the file
.IR AUTHORS .

This manual page was added by Dirk Eddelbuettel <edd@debian.org>, 
one of the Debian GNU/Linux maintainers for 
.BR OpenMPI , 
and may be used by others.
