.\" Contributed by Dirk Eddelbuettel <edd@debian.org> under the BSD license
.TH ORTED 1 "June 2006" "Open MPI" "OPEN MPI COMMANDS"
.SH NAME
orted - Start an Open RTE Daemon
.SH SYNOPSIS
.B orted [options]
.SH DESCRIPTION
.PP
.B orted
starts an Open RTE daemon for the OpenMPI system.
.SH OPTIONS
.B orted
accepts the following options:
.TP 8
.I \-\-bootproxy <arg0>    
Run as boot proxy for <job-id>
.TP 8
.I \-d|\-\-debug
Debug the OpenRTE
.TP 8
.I \-d|\-\-spin
Have the 
.B orted 
spin until we can connect a debugger to it
.TP 8
.I \-\-debug-daemons
Enable debugging of OpenRTE daemons
.TP 8
.I \-\-debug-daemons-file  
Enable debugging of OpenRTE daemons, storing output in files
.TP 8
.I \-\-gprreplica <arg0>   
Registry contact information.
.TP 8
.I \-h|\-\-help
This help message
.TP 8
.I \-\-mpi-call-yield <arg0>
Have MPI (or similar) applications call yield when idle
.TP 8
.I \-\-name <arg0>
Set the orte process name
.TP 8
.I \-\-no-daemonize
Don't daemonize into the background
.TP 8
.I \-\-nodename <arg0>     
Node name as specified by host/resource description.
.TP 8
.I \-\-ns-nds <arg0>       
set sds/nds component to use for daemon (normally not needed)
.TP 8
.I \-\-nsreplica <arg0>
Name service contact information.
.TP 8
.I \-\-num_procs <arg0>
Set the number of process in this job
.TP 8
.I \-\-persistent
Remain alive after the application process completes
.TP 8
.I \-\-report-uri <arg0>   
Report this process' uri on indicated pipe
.TP 8
.I \-\-scope <arg0>
Set restrictions on who can connect to this universe
.TP 8
.I \-\-seed
Host replicas for the core universe services
.TP 8
.I \-\-set-sid
Direct the orted to separate from the current session
.TP 8
.I \-\-tmpdir <arg0>
Set the root for the session directory tree
.TP 8
.I \-\-universe <arg0>
Set the universe name as username@hostname:universe_name for this application 
.TP 8
.I \-\-vpid_start <arg0>   
Set the starting vpid for this job

.SH AUTHORS
The OpenMPI maintainers -- see 
.I http://www.openmpi.org 
or the file
.IR AUTHORS .

This manual page was added by Dirk Eddelbuettel <edd@debian.org>, 
one of the Debian GNU/Linux maintainers for 
.BR OpenMPI , 
and may be used by others.
