<?
$subject_val = "[OMPI users] openmpi-1.9a1r29303 neglects --with-wrapper-libs";
include("../../include/msg-header.inc");
?>
<!-- received="Tue Oct  1 03:24:48 2013" -->
<!-- isoreceived="20131001072448" -->
<!-- sent="Tue, 1 Oct 2013 09:18:06 +0200 (CEST)" -->
<!-- isosent="20131001071806" -->
<!-- name="Siegmar Gross" -->
<!-- email="Siegmar.Gross_at_[hidden]" -->
<!-- subject="[OMPI users] openmpi-1.9a1r29303 neglects --with-wrapper-libs" -->
<!-- id="201310010718.r917I6ZP019415_at_tyr.informatik.hs-fulda.de" -->
<!-- charset="us-ascii" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> [OMPI users] openmpi-1.9a1r29303 neglects --with-wrapper-libs<br>
<strong>From:</strong> Siegmar Gross (<em>Siegmar.Gross_at_[hidden]</em>)<br>
<strong>Date:</strong> 2013-10-01 03:18:06
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="22742.php">Damiano Natali: "Re: [OMPI users] non-functional mpif90 compiler"</a>
<li><strong>Previous message:</strong> <a href="22740.php">John Hearns: "Re: [OMPI users] line 60: echo: write error: No space left on device"</a>
<!-- nextthread="start" -->
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Hi,
<br>
<p>today I installed openmpi-1.9a1r29303 on Solaris 10 Sparc with
<br>
gcc-4.8.0. I used the following configuration command:
<br>
<p>tyr openmpi-1.9a1r29303-SunOS.sparc.64_gcc 64 head config.log
<br>
This file contains any messages produced by compilers while
<br>
running configure, to aid debugging if configure makes a mistake.
<br>
<p>It was created by Open MPI configure 1.9a1, which was
<br>
generated by GNU Autoconf 2.69.  Invocation command line was
<br>
<p>../openmpi-1.9a1r29303/configure \
<br>
&nbsp;&nbsp;--prefix=/usr/local/openmpi-1.9_64_gcc \
<br>
&nbsp;&nbsp;--libdir=/usr/local/openmpi-1.9_64_gcc/lib64 \
<br>
&nbsp;&nbsp;--with-jdk-bindir=/usr/local/jdk1.7.0_07/bin/sparcv9 \
<br>
&nbsp;&nbsp;--with-jdk-headers=/usr/local/jdk1.7.0_07/include \
<br>
&nbsp;&nbsp;JAVA_HOME=/usr/local/jdk1.7.0_07 \
<br>
&nbsp;&nbsp;LDFLAGS=-m64 \
<br>
&nbsp;&nbsp;-L/usr/local/gcc-4.8.0/lib/sparcv9 \
<br>
&nbsp;&nbsp;LIBS=-lgcc_s \
<br>
&nbsp;&nbsp;CC=gcc CXX=g++ FC=gfortran \
<br>
&nbsp;&nbsp;CFLAGS=-m64 CXXFLAGS=-m64 FCFLAGS=-m64 \
<br>
&nbsp;&nbsp;CPP=cpp CXXCPP=cpp CPPFLAGS= CXXCPPFLAGS= \
<br>
&nbsp;&nbsp;--enable-mpi-cxx \
<br>
&nbsp;&nbsp;--enable-cxx-exceptions \
<br>
&nbsp;&nbsp;--enable-mpi-java \
<br>
&nbsp;&nbsp;--enable-heterogeneous \
<br>
&nbsp;&nbsp;--enable-opal-multi-threads \
<br>
&nbsp;&nbsp;--enable-mpi-thread-multiple \
<br>
&nbsp;&nbsp;--with-threads=posix \
<br>
&nbsp;&nbsp;--with-hwloc=internal \
<br>
&nbsp;&nbsp;--without-verbs \
<br>
&nbsp;&nbsp;--without-udapl \
<br>
&nbsp;&nbsp;--without-sctp \
<br>
&nbsp;&nbsp;--with-wrapper-cflags=-std=c11 -m64 \
<br>
&nbsp;&nbsp;--with-wrapper-libs=-lgcc_s \
<br>
&nbsp;&nbsp;--enable-debug
<br>
...
<br>
<p><p>/export2/prog/SunOS_sparc/openmpi-1.9_64_gcc/bin/ompi_info | grep MPI:
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Open MPI: 1.9a1r29303
<br>
<p>/export2/prog/SunOS_sparc/openmpi-1.9_64_gcc/bin/mpicc -showme
<br>
gcc -I/usr/local/openmpi-1.9_64_gcc/include -fexceptions -pthread \
<br>
&nbsp;&nbsp;-std=c11 -m64 -Wl,-rpath -Wl,/usr/local/openmpi-1.9_64_gcc/lib64 \
<br>
&nbsp;&nbsp;-Wl,--enable-new-dtags -L/usr/local/openmpi-1.9_64_gcc/lib64 -lmpi
<br>
<p>The wrapper compiler doesn't contain &quot;-lgcc_s&quot;, which is necessary
<br>
to compile MPI programs on Solaris Sparc.
<br>
<p>tyr examples 72 /export2/prog/SunOS_sparc/openmpi-1.9_64_gcc/bin/mpicc hello_c.c 
<br>
/usr/local/openmpi-1.9_64_gcc/lib64/libmpi.so: undefined reference to `__muldc3_at_GCC_4.0.0'
<br>
/usr/local/openmpi-1.9_64_gcc/lib64/libmpi.so: undefined reference to `__mulsc3_at_GCC_4.0.0'
<br>
/usr/local/openmpi-1.9_64_gcc/lib64/libmpi.so: undefined reference to `__multc3_at_GCC_4.0.0'
<br>
collect2: error: ld returned 1 exit status
<br>
<p>tyr examples 73 /export2/prog/SunOS_sparc/openmpi-1.9_64_gcc/bin/mpicc hello_c.c -lgcc_s
<br>
tyr examples 74 
<br>
<p><p>The Javadoc documentation for the new Java API in Open MPI isn't
<br>
available. Is it necessary to do something special, so that it
<br>
will be built and installed?
<br>
<p>tyr examples 76 ls -l /export2/prog/SunOS_sparc/openmpi-1.9_64_gcc/share/
<br>
total 5
<br>
drwxr-xr-x 5 root root  512 Oct  1 08:50 man
<br>
drwxr-xr-x 3 root root 3072 Oct  1 08:52 openmpi
<br>
drwxr-xr-x 3 root root  512 Oct  1 08:51 vampirtrace
<br>
tyr examples 77 
<br>
<p><p>I would be grateful, if somebody can fix the problem with the
<br>
missing wrapper-lib. Thank you very much for any help in advance.
<br>
<p><p>Kind regards
<br>
<p>Siegmar
<br>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="22742.php">Damiano Natali: "Re: [OMPI users] non-functional mpif90 compiler"</a>
<li><strong>Previous message:</strong> <a href="22740.php">John Hearns: "Re: [OMPI users] line 60: echo: write error: No space left on device"</a>
<!-- nextthread="start" -->
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
