<?php
$title = "Supercomputing 2008 slides";
$overview = "Slides from various presentations about Open MPI or by the Open MPI team members.";

$authors = "George Bosilca, Joshua Hursey, Rainer Keller, Matthias Mueller, Jeff Squyres";

$abstract = 'Per request from many SC attendees, we are publishing 
our slides from various talks by Open MPI team members at SC.  The
talks are:

<ul>
<li> "Open MPI Community Meeting" BOF by Jeff Squyres, George Bosilca, and 
     Dave Montoya.</li>
<li> "Surviving in the Petascale World [and Beyond]" presentation in the
     Cisco booth by George Bosilca.</li>
<li> "MPI Implemnetation Health Assessment Through Multi-Institutional 
     Distributed Testing" presentation in the Cisco booth by Joshua
     Hursey.</li>
<li> "Open MPI: 10^15 Flops Can\'t Be Wrong" presentation in the Cisco
     booth by Jeff Squyres.</li>
<li> "Open MPI: Open Source + Innovation + Community = Petaflop" 
     presentations in the Mellanox and QLogic booths by Jeff Squyres.</li>
<li> "Performance Analysis with Open MPI and VampirTrace" presentation in
     the Cisco booth by Matthias Mueller.</li>
<li> "Memory Debugging for MPI-Applications in Open MPI" presentation in
     the Cisco booth by Rainer Keller.</li>
</ul>

Some talks contained animations which will not show in the PDFs below.
Other talks were originally presented in 16:9 format, and look a
little small in the PDFs.';

$presented = "<a href=\"http://sc08.supercomputing.org/\">" . "SC'08</a>,
November, 2008, in Austin, TX, USA";

$files[] = "bof-ompi-community-meeting-1up.pdf";
$files[] = "bof-ompi-community-meeting-2up.pdf";
$files[] = "gbosilca-cisco-booth-1up.pdf";
$files[] = "gbosilca-cisco-booth-2up.pdf";
$files[] = "jhursey-cisco-booth-1up.pdf";
$files[] = "jhursey-cisco-booth-2up.pdf";
$files[] = "jsquyres-cisco-booth-talk-1up.pdf";
$files[] = "jsquyres-cisco-booth-talk-2up.pdf";
$files[] = "jsquyres-other-booth-talk-1up.pdf";
$files[] = "jsquyres-other-booth-talk-2up.pdf";
$files[] = "mmueller-cisco-booth-1up.pdf";
$files[] = "mmueller-cisco-booth-2up.pdf";
$files[] = "rkeller-cisco-booth-1up.pdf";
$files[] = "rkeller-cisco-booth-2up.pdf";

$month = 11;
$day = 17;
$year = 2008;

$bibtex = "";
