<?
$subject_val = "Re: [OMPI devel] oshmem build failures";
include("../../include/msg-header.inc");
?>
<!-- received="Wed Oct 16 10:38:52 2013" -->
<!-- isoreceived="20131016143852" -->
<!-- sent="Wed, 16 Oct 2013 07:38:49 -0700" -->
<!-- isosent="20131016143849" -->
<!-- name="Ralph Castain" -->
<!-- email="rhc_at_[hidden]" -->
<!-- subject="Re: [OMPI devel] oshmem build failures" -->
<!-- id="B4D85807-3200-4313-BAEC-123C47E7EC27_at_open-mpi.org" -->
<!-- charset="us-ascii" -->
<!-- inreplyto="8E25A938F00ED34D90F8C49322FDF192AFA30E_at_xmb-rcd-x09.cisco.com" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> Re: [OMPI devel] oshmem build failures<br>
<strong>From:</strong> Ralph Castain (<em>rhc_at_[hidden]</em>)<br>
<strong>Date:</strong> 2013-10-16 10:38:49
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="13101.php">Jeff Squyres (jsquyres): "[OMPI devel] oshmem Fortran"</a>
<li><strong>Previous message:</strong> <a href="13099.php">David Goodell (dgoodell): "Re: [OMPI devel] oshmem build failures"</a>
<li><strong>In reply to:</strong> <a href="13099.php">David Goodell (dgoodell): "Re: [OMPI devel] oshmem build failures"</a>
<!-- nextthread="start" -->
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Yep, that was the problem! Fixed
<br>
<p>On Oct 16, 2013, at 7:30 AM, David Goodell (dgoodell) &lt;dgoodell_at_[hidden]&gt; wrote:
<br>
<p><span class="quotelev1">&gt; It's probably missing from a variable which has &quot;dist&quot; effects.  In ompi/include/ompi/Makefile.am this is &quot;$(headers)&quot;.
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; -Dave
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; On Oct 16, 2013, at 9:25 AM, Ralph Castain &lt;rhc_at_[hidden]&gt; wrote:
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; Weird - that file definitely exists - generated by autogen.
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; On Oct 16, 2013, at 7:23 AM, &quot;Jeff Squyres (jsquyres)&quot; &lt;jsquyres_at_[hidden]&gt; wrote:
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; Begin forwarded message:
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; From: MPI Team &lt;mpiteam_at_[hidden]&gt;
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; Subject: === CREATE FAILURE (trunk) ===
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; Date: October 16, 2013 10:18:14 AM EDT
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; To: &lt;testing_at_[hidden]&gt;
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; Reply-To: &lt;devel_at_[hidden]&gt;
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; ERROR: Command returned a non-zero exist status (trunk):
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt;    make distcheck
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; Start time: Wed Oct 16 09:59:02 EDT 2013
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; End time:   Wed Oct 16 10:18:13 EDT 2013
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; =======================================================================
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; [... previous lines snipped ...]
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CC       base/memheap_base_register.lo
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CC       base/memheap_base_mkey.lo
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CCLD     libmca_memheap.la
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; make[3]: Leaving directory `/home/mpiteam/openmpi/nightly-tarball-build-root/trunk/create-r29441/ompi/openmpi-1.9a1r29441/_build/oshmem/mca/memheap'
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; Making all in mca/scoll
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; make[3]: Entering directory `/home/mpiteam/openmpi/nightly-tarball-build-root/trunk/create-r29441/ompi/openmpi-1.9a1r29441/_build/oshmem/mca/scoll'
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CC       base/scoll_base_frame.lo
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CC       base/scoll_base_available.lo
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CC       base/scoll_base_select.lo
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CCLD     libmca_scoll.la
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; make[3]: Leaving directory `/home/mpiteam/openmpi/nightly-tarball-build-root/trunk/create-r29441/ompi/openmpi-1.9a1r29441/_build/oshmem/mca/scoll'
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; Making all in mca/spml
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; make[3]: Entering directory `/home/mpiteam/openmpi/nightly-tarball-build-root/trunk/create-r29441/ompi/openmpi-1.9a1r29441/_build/oshmem/mca/spml'
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CC       base/spml_base_frame.lo
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CC       base/spml_base_select.lo
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CC       base/spml_base_request.lo
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CC       base/spml_base_atomicreq.lo
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CC       base/spml_base_getreq.lo
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CC       base/spml_base_putreq.lo
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CC       base/spml_base.lo
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CCLD     libmca_spml.la
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; make[3]: Leaving directory `/home/mpiteam/openmpi/nightly-tarball-build-root/trunk/create-r29441/ompi/openmpi-1.9a1r29441/_build/oshmem/mca/spml'
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; Making all in .
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; make[3]: Entering directory `/home/mpiteam/openmpi/nightly-tarball-build-root/trunk/create-r29441/ompi/openmpi-1.9a1r29441/_build/oshmem'
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CC       op/op.lo
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CC       proc/proc.lo
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CC       proc/proc_group_cache.lo
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CC       request/request.lo
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CC       runtime/oshmem_shmem_init.lo
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CC       runtime/oshmem_shmem_finalize.lo
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CC       runtime/oshmem_shmem_abort.lo
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CC       runtime/oshmem_shmem_params.lo
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CC       runtime/oshmem_shmem_exchange.lo
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; CC       runtime/oshmem_info_support.lo
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; ../../oshmem/runtime/oshmem_info_support.c:14:46: error: oshmem/include/oshmem/frameworks.h: No such file or directory
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; ../../oshmem/runtime/oshmem_info_support.c: In function 'oshmem_info_register_types':
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; ../../oshmem/runtime/oshmem_info_support.c:36: error: 'oshmem_frameworks' undeclared (first use in this function)
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; ../../oshmem/runtime/oshmem_info_support.c:36: error: (Each undeclared identifier is reported only once
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; ../../oshmem/runtime/oshmem_info_support.c:36: error: for each function it appears in.)
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; ../../oshmem/runtime/oshmem_info_support.c: In function 'oshmem_info_register_framework_params':
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; ../../oshmem/runtime/oshmem_info_support.c:63: error: 'oshmem_frameworks' undeclared (first use in this function)
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; ../../oshmem/runtime/oshmem_info_support.c: In function 'oshmem_info_close_components':
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; ../../oshmem/runtime/oshmem_info_support.c:70: error: 'oshmem_frameworks' undeclared (first use in this function)
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; make[3]: *** [runtime/oshmem_info_support.lo] Error 1
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; make[3]: Leaving directory `/home/mpiteam/openmpi/nightly-tarball-build-root/trunk/create-r29441/ompi/openmpi-1.9a1r29441/_build/oshmem'
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; make[2]: *** [all-recursive] Error 1
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; make[2]: Leaving directory `/home/mpiteam/openmpi/nightly-tarball-build-root/trunk/create-r29441/ompi/openmpi-1.9a1r29441/_build/oshmem'
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; make[1]: *** [all-recursive] Error 1
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; make[1]: Leaving directory `/home/mpiteam/openmpi/nightly-tarball-build-root/trunk/create-r29441/ompi/openmpi-1.9a1r29441/_build'
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; make: *** [distcheck] Error 1
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; =======================================================================
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; 
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; Your friendly daemon,
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; Cyrador
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; _______________________________________________
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; testing mailing list
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; testing_at_[hidden]
</span><br>
<span class="quotelev4">&gt;&gt;&gt;&gt; <a href="http://www.open-mpi.org/mailman/listinfo.cgi/testing">http://www.open-mpi.org/mailman/listinfo.cgi/testing</a>
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; -- 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; Jeff Squyres
</span><br>
<span class="quotelev3">&gt;&gt;&gt; jsquyres_at_[hidden]
</span><br>
<span class="quotelev3">&gt;&gt;&gt; For corporate legal information go to: <a href="http://www.cisco.com/web/about/doing_business/legal/cri/">http://www.cisco.com/web/about/doing_business/legal/cri/</a>
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 
</span><br>
<span class="quotelev3">&gt;&gt;&gt; _______________________________________________
</span><br>
<span class="quotelev3">&gt;&gt;&gt; devel mailing list
</span><br>
<span class="quotelev3">&gt;&gt;&gt; devel_at_[hidden]
</span><br>
<span class="quotelev3">&gt;&gt;&gt; <a href="http://www.open-mpi.org/mailman/listinfo.cgi/devel">http://www.open-mpi.org/mailman/listinfo.cgi/devel</a>
</span><br>
<span class="quotelev2">&gt;&gt; 
</span><br>
<span class="quotelev2">&gt;&gt; _______________________________________________
</span><br>
<span class="quotelev2">&gt;&gt; devel mailing list
</span><br>
<span class="quotelev2">&gt;&gt; devel_at_[hidden]
</span><br>
<span class="quotelev2">&gt;&gt; <a href="http://www.open-mpi.org/mailman/listinfo.cgi/devel">http://www.open-mpi.org/mailman/listinfo.cgi/devel</a>
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<span class="quotelev1">&gt; _______________________________________________
</span><br>
<span class="quotelev1">&gt; devel mailing list
</span><br>
<span class="quotelev1">&gt; devel_at_[hidden]
</span><br>
<span class="quotelev1">&gt; <a href="http://www.open-mpi.org/mailman/listinfo.cgi/devel">http://www.open-mpi.org/mailman/listinfo.cgi/devel</a>
</span><br>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="13101.php">Jeff Squyres (jsquyres): "[OMPI devel] oshmem Fortran"</a>
<li><strong>Previous message:</strong> <a href="13099.php">David Goodell (dgoodell): "Re: [OMPI devel] oshmem build failures"</a>
<li><strong>In reply to:</strong> <a href="13099.php">David Goodell (dgoodell): "Re: [OMPI devel] oshmem build failures"</a>
<!-- nextthread="start" -->
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
