<?
$subject_val = "[OMPI devel] PathScale compiler ( ticket #1326 )";
include("../../include/msg-header.inc");
?>
<!-- received="Wed Jul 16 09:43:41 2008" -->
<!-- isoreceived="20080716134341" -->
<!-- sent="Wed, 16 Jul 2008 16:43:37 +0300" -->
<!-- isosent="20080716134337" -->
<!-- name="Lenny Verkhovsky" -->
<!-- email="lenny.verkhovsky_at_[hidden]" -->
<!-- subject="[OMPI devel] PathScale compiler ( ticket #1326 )" -->
<!-- id="453d39990807160643le04906anf4a476a2947da1d6_at_mail.gmail.com" -->
<!-- charset="ISO-8859-1" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> [OMPI devel] PathScale compiler ( ticket #1326 )<br>
<strong>From:</strong> Lenny Verkhovsky (<em>lenny.verkhovsky_at_[hidden]</em>)<br>
<strong>Date:</strong> 2008-07-16 09:43:37
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="4368.php">Don Kerr: "Re: [OMPI devel] IBCM error"</a>
<li><strong>Previous message:</strong> <a href="4366.php">Jeff Squyres: "Re: [OMPI devel] ompi_ignore dr pml?"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="4370.php">Jeff Squyres: "Re: [OMPI devel] PathScale compiler ( ticket #1326 )"</a>
<li><strong>Reply:</strong> <a href="4370.php">Jeff Squyres: "Re: [OMPI devel] PathScale compiler ( ticket #1326 )"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Hi, Jeff,
<br>
<p>I succeded to compile and run simple C++ app with PathScale 3.2 evaluation
<br>
version. look below.
<br>
<p>Maybe you had some installation / licence problems.
<br>
<p>I was in touch with Ben viz_at_[hidden] from PathScale support who helped
<br>
me with installation.
<br>
<p>#head config.log
<br>
This file contains any messages produced by compilers while
<br>
running configure, to aid debugging if configure makes a mistake.
<br>
It was created by Open MPI configure 1.4a1, which was
<br>
generated by GNU Autoconf 2.61. Invocation command line was
<br>
<p>&nbsp;&nbsp;$ ../configure --with-memory-manager=ptmalloc2 --with-openib
<br>
--prefix=/home/USERS/lenny/OMPI_COMP_PATH CC=pathcc CXX=pathCC FC=pathf90
<br>
F77=pathf90 F90=pathf90
<br>
<p>## --------- ##
<br>
## Platform. ##
<br>
<p>/home/USERS/lenny/OMPI_COMP_PATH/bin/mpiCC -o hello_c_plus hello++.cc
<br>
In file included from /usr/include/c++/4.1.2/backward/iostream.h:31,
<br>
&nbsp;&nbsp;from hello++.cc:34:
<br>
/usr/include/c++/4.1.2/backward/backward_warning.h:32:2: warning: #warning
<br>
This file includes at least one deprecated or antiquated header. Please
<br>
consider using one of the 32 headers found in section 17.4.1.2 of the C++
<br>
standard. Examples include substituting the &lt;X&gt; header for the &lt;X.h&gt; header
<br>
for C++ includes, or &lt;iostream&gt; instead of the deprecated header
<br>
&lt;iostream.h&gt;. To disable this warning use -Wno-deprecated.
<br>
<p>witch1:/home/USERS/lenny/TESTS/COMPILERS #
<br>
/home/USERS/lenny/OMPI_COMP_PATH/bin/mpirun -np 2 -H witch16,witch17
<br>
./hello_c_plus
<br>
Hello World! I am 0 of 2
<br>
Hello World! I am 1 of 2
<br>
<p><p>
<p>
<br><hr>
<ul>
<li>text/html attachment: <a href="http://www.open-mpi.org/community/lists/devel/att-4367/attachment">attachment</a>
</ul>
<!-- attachment="attachment" -->
<hr>
<ul>
<li>application/octet-stream attachment: <a href="http://www.open-mpi.org/community/lists/devel/att-4367/hello__.cc">hello__.cc</a>
</ul>
<!-- attachment="hello__.cc" -->
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="4368.php">Don Kerr: "Re: [OMPI devel] IBCM error"</a>
<li><strong>Previous message:</strong> <a href="4366.php">Jeff Squyres: "Re: [OMPI devel] ompi_ignore dr pml?"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="4370.php">Jeff Squyres: "Re: [OMPI devel] PathScale compiler ( ticket #1326 )"</a>
<li><strong>Reply:</strong> <a href="4370.php">Jeff Squyres: "Re: [OMPI devel] PathScale compiler ( ticket #1326 )"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
