<?
$subject_val = "Re: [hwloc-devel] xml file load incompatibilities";
include("../../include/msg-header.inc");
?>
<!-- received="Fri Sep 20 17:41:58 2013" -->
<!-- isoreceived="20130920214158" -->
<!-- sent="Fri, 20 Sep 2013 23:41:55 +0200" -->
<!-- isosent="20130920214155" -->
<!-- name="Brice Goglin" -->
<!-- email="Brice.Goglin_at_[hidden]" -->
<!-- subject="Re: [hwloc-devel] xml file load incompatibilities" -->
<!-- id="523CC123.60300_at_inria.fr" -->
<!-- charset="ISO-8859-1" -->
<!-- inreplyto="B8143CF1-1402-41A7-89C2-EE044496CE3B_at_open-mpi.org" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> Re: [hwloc-devel] xml file load incompatibilities<br>
<strong>From:</strong> Brice Goglin (<em>Brice.Goglin_at_[hidden]</em>)<br>
<strong>Date:</strong> 2013-09-20 17:41:55
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="3882.php">Ralph Castain: "Re: [hwloc-devel] xml file load incompatibilities"</a>
<li><strong>Previous message:</strong> <a href="3880.php">Ralph Castain: "[hwloc-devel] xml file load incompatibilities"</a>
<li><strong>In reply to:</strong> <a href="3880.php">Ralph Castain: "[hwloc-devel] xml file load incompatibilities"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="3882.php">Ralph Castain: "Re: [hwloc-devel] xml file load incompatibilities"</a>
<li><strong>Reply:</strong> <a href="3882.php">Ralph Castain: "Re: [hwloc-devel] xml file load incompatibilities"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Hello,
<br>
I don't see anything reason for such an incompatibility. But there are
<br>
many combinations, we can't test everything.
<br>
I can't reproduce that on my machines. Can you send the XML output of
<br>
both versions on one of your machines?
<br>
Brice
<br>
<p><p><p>Le 20/09/2013 23:32, Ralph Castain a &#233;crit :
<br>
<span class="quotelev1">&gt; Hi folks
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; I've run across a rather strange behavior. We have two branches in OMPI - the devel trunk (using hwloc v1.7.2) and our feature release series (using hwloc 1.5.2). I have found the following:
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; *the feature series can correctly load an xml file generated by lstopo of versions 1.5 or greater
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; * the devel series can correctly load an xml file generated by lstopo of versions 1.7 or greater, but not files generated by prior versions. In the latter case, I segfault as soon as I try to use the loaded topology.
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; Any ideas why the discrepancy? Can I at least detect the version used to create a file when loading it so I can error out instead of segfaulting?
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; Ralph
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; _______________________________________________
</span><br>
<span class="quotelev1">&gt; hwloc-devel mailing list
</span><br>
<span class="quotelev1">&gt; hwloc-devel_at_[hidden]
</span><br>
<span class="quotelev1">&gt; <a href="http://www.open-mpi.org/mailman/listinfo.cgi/hwloc-devel">http://www.open-mpi.org/mailman/listinfo.cgi/hwloc-devel</a>
</span><br>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="3882.php">Ralph Castain: "Re: [hwloc-devel] xml file load incompatibilities"</a>
<li><strong>Previous message:</strong> <a href="3880.php">Ralph Castain: "[hwloc-devel] xml file load incompatibilities"</a>
<li><strong>In reply to:</strong> <a href="3880.php">Ralph Castain: "[hwloc-devel] xml file load incompatibilities"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="3882.php">Ralph Castain: "Re: [hwloc-devel] xml file load incompatibilities"</a>
<li><strong>Reply:</strong> <a href="3882.php">Ralph Castain: "Re: [hwloc-devel] xml file load incompatibilities"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
