<?php
$title = "Supercomputing 2024 slides";
$overview = "Slides from the Open MPI State of the Union BOF at SC'24";

$authors = "George Bosilca, Edgar Gabriel, Tomislav Janjusic, Thomas Naughton, Luke Robinson";

$abstract = "Slides from the Open MPI State of the Union XVI Community
Meeting at SC'24.";

$presented = "<a href=\"http://sc24.supercomputing.org/\">" . "SC'24</a>,
November 17, 2024, Atlanta, GA, USA";

$files[] = "Open-MPI-SC24-BOF.pdf";

$month = 11;
$day = 17;
$year = 2024;

$bibtex = "";
