<?php
include_once("$topdir/includes/nav.inc");

$this_dir = "glassbottom";
$this_nav[] = new Nav("Download v1.0", "$topdir/software/glassbottom/v1.0/");
$this_nav[] = new Nav("Documentation", "https://github.com/open-mpi/glassbottom/wiki");
$this_nav[] = new Nav("License", "$topdir/projects/glassbottom/license.php");
$this_nav[] = new Nav("Mailing lists", "$topdir/community/lists/glassbottom.php");
$this_nav[] = new Nav("Bug tracking", "https://github.com/open-mpi/glassbottom/issues");
$this_nav[] = new Nav("Git access", "https://github.com/open-mpi/glassbottom");
$this_nav[] = new Nav("Nightly snapshots", "$topdir/software/glassbottom/nightly/");
