<?php
$topdir = "../../../..";
# Note that we must use the PHP "$$" indirection to assign to the
# "title" variable, because if we list "$ title" (without the space)
# in this file, Doxygen will replace it with a string title.
$ver = basename(getcwd());
$thwarting_doxygen_preprocessor = "title";
$$thwarting_doxygen_preprocessor = "Portable Hardware Locality (hwloc) Documentation: $ver";
$header_include_file = "$topdir/projects/hwloc/doc/$ver/www.open-mpi.org-css.inc";

include_once("$topdir/projects/hwloc/nav.inc");
include_once("$topdir/includes/header.inc");
include_once("$topdir/includes/code.inc");
?>
<!-- Generated by Doxygen 1.7.3 -->
  <div id="navrow1" class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Main&#160;Page</span></a></li>
      <li><a href="pages.php"><span>Related&#160;Pages</span></a></li>
      <li><a href="modules.php"><span>Modules</span></a></li>
      <li><a href="annotated.php"><span>Data&#160;Structures</span></a></li>
      <li class="current"><a href="files.php"><span>Files</span></a></li>
    </ul>
  </div>
  <div id="navrow2" class="tabs2">
    <ul class="tablist">
      <li><a href="files.php"><span>File&#160;List</span></a></li>
      <li><a href="globals.php"><span>Globals</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="summary">
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<h1>cudart.h File Reference</h1>  </div>
</div>
<div class="contents">

<p>Macros to help interaction between hwloc and the CUDA Runtime API.  
<a href="#_details">More...</a></p>
<div class="textblock"><code>#include &lt;hwloc.h&gt;</code><br/>
<code>#include &lt;hwloc/autogen/config.h&gt;</code><br/>
<code>#include &lt;hwloc/linux.h&gt;</code><br/>
<code>#include &lt;cuda_runtime_api.h&gt;</code><br/>
</div>
<p><a href="cudart_8h_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr><td colspan="2"><h2><a name="func-members"></a>
Functions</h2></td></tr>
<tr><td class="memItemLeft" align="right" valign="top">static inline int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="group__hwlocality__cudart.php#ga2daaf1dd1a9a7f11ccbc6821374120e9">hwloc_cudart_get_device_cpuset</a> (<a class="el" href="group__hwlocality__topology.php#ga9d1e76ee15a7dee158b786c30b6a6e38">hwloc_topology_t</a> topology , int device, <a class="el" href="group__hwlocality__sets.php#ga4bbf39b68b6f568fb92739e7c0ea7801">hwloc_cpuset_t</a> set)</td></tr>
<tr><td class="mdescLeft">&#160;</td><td class="mdescRight">Get the CPU set of logical processors that are physically close to device <code>cudevice</code>.  <a href="group__hwlocality__cudart.php#ga2daaf1dd1a9a7f11ccbc6821374120e9"></a><br/></td></tr>
</table>
<hr/><a name="_details"></a><h2>Detailed Description</h2>
<div class="textblock"><p>Macros to help interaction between hwloc and the CUDA Runtime API. </p>
<p>Applications that use both hwloc and the CUDA Runtime API may want to include this file so as to get topology information for CUDA devices. </p>
</div></div>
<?php
include_once("$topdir/includes/footer.inc");
