<?php
$title = "Supercomputing 2010 slides";
$overview = "Slides from various presentations about Open MPI or by the Open MPI team members";

$authors = "George Bosilca, Jeff Squyres, Brice Goglin";

$abstract = 'Per request from many SC attendees, we are publishing 
our slides from various talks by Open MPI team members at SC.  The
talks are:

<ul>
<li> "Open MPI Community Meeting" BOF by Jeff Squyres, George Bosilca, 
     and Brice Goglin.</li>
<li> "Open MPI: Collaborate to Innovate" presentation in the Cisco booth
     by Jeff Squyres.</li>
<li> MPI Forum BOF</li>
</ul>

Some talks contained animations which will not show in the PDFs below.
Other talks were originally presented in 16:9 format, and look a
little small in the PDFs.';

$presented = "<a href=\"http://sc10.supercomputing.org/\">" . "SC'10</a>,
November, 2009, in New Orleans, LA, USA";

$files[] = "ompi-bof-1up.pdf";
$files[] = "ompi-bof-2up.pdf";
$files[] = "jsquyres-cisco-booth.pdf";
$files[] = "Hursey-Cisco.pdf";
$files[] = "valgrind_openmpi.pdf";

#$files[] = "MPI_Forum_SC09_BOF-1up.pdf";
#$files[] = "MPI_Forum_SC09_BOF-2up.pdf";

$month = 11;
$day = 16;
$year = 2010;

$bibtex = "";
