<?
$topurl = "../../../../..";
$topdir = $topurl;
$title = "Open MPI Announcements Mailing List Archives";
$lam_section = "open-mpi-announce-mail";

include_once("$topdir/includes/nav.inc");

$this_dir = "lists";
$base = $topurl;
include_once("$topdir/community/lists/nav.inc");

include_once("$topdir/includes/header.inc");

$this_list = "announce";
include_once("$topdir/community/lists/frozen.inc");
?>
