<?php
$title = "Supercomputing 2016 slides";
$overview = "Slides from the Open MPI State of the Union BOF at SC'16";

$authors = "George Bosilca, Jeff Squyres, Nathan Hjelm, Perry Schmidt, Yossi Itigin, Ralph Castain";

$abstract = "Slides from the Open MPI State of the Union Community
Meeting at SC'16.";

$presented = "<a href=\"http://sc16.supercomputing.org/\">" . "SC'16</a>,
November, 2016, in Salt Lake City, USA";

$files[] = "Open-MPI-SC16-BOF.pdf";

$month = 11;
$day = 16;
$year = 2016;

$bibtex = "";
