<?php
$title = "Supercomputing 2023 slides";
$overview = "Slides from the Open MPI State of the Union BOF at SC'23";

$authors = "George Bosilca, Edgar Gabriel, Howard Pritchard, Tomislav Janjusic";

$abstract = "Slides from the Open MPI State of the Union XV Community
Meeting at SC'23.";

$presented = "<a href=\"http://sc21.supercomputing.org/\">" . "SC'23</a>,
November 15, 2023, Denver, CO, USA";

$files[] = "Open-MPI-SC23-BOF.pdf";

$month = 11;
$day = 15;
$year = 2024;

$bibtex = "";
