<?php
$title = "The Open Run-Time Enviroment (OpenRTE): A Transparent Multi-Cluster environment for High-Performance Computing";
$overview = "A description of the run-time environment (ORTE) sub-project in Open MPI";

$authors = "R. H. Castain, T. S. Woodall, D. J. Daniel, J. M. Squyres,
B. Barrett, G .E. Fagg";

$abstract = "The Open Run-Time Environment (OpenRTE) -- a spin-off
from the Open MPI project -- was developed to support distributed
high-performance computing applications operating in a heterogeneous
environment. The system transparently provides support for
interprocess communication, resource discovery and allocation, and
process launch across a variety of platforms. In addition, users can
launch their applications remotely from their desktop, disconnect from
them, and reconnect at a later time to monitor progress. This paper
will describe the capabilities of the OpenRTE system, describe its
architecture, and discuss future directions for the project.";

$presented = "<a href=\"http://www.pvmmpi05.unina2.it\">" .
"Euro PVM/MPI 2005</a>, September, 2005, in Sorrento, Italy";

$files[] = "euro-pvm-mpi-2005-orte.pdf";

$month = 9;
$day = 18;
$year = 2005;

$bibtex = "@InProceedings{castain05:_open_rte,
  author       = {R. H. Castain and T. S. Woodall and D. J. Daniel and
                  J. M. Squyres and B. Barrett and G .E. Fagg},
  title	       = {The Open Run-Time Environment (OpenRTE): A
                  Transparent Multi-Cluster Environment for
                  High-Performance Computing},
  booktitle    = {Proceedings, 12th European PVM/MPI Users' Group
                  Meeting},
  year	       = 2005,
  address      = {Sorrento, Italy},
  month	       = {September}
}";

