<?php
$title = "Supercomputing 2009 slides";
$overview = "Slides from various presentations about Open MPI or by the Open MPI team members";

$authors = "George Bosilca, Joshua Hursey, Jeff Squyres, Tim Mattox, Rich Graham";

$abstract = 'Per request from many SC attendees, we are publishing 
our slides from various talks by Open MPI team members at SC.  The
talks are:

<ul>
<li> "Open MPI Community Meeting" BOF by Jeff Squyres, and George Bosilca.</li>
<li> "A Transparent Process Migration Framework for Open MPI" presentation in
     the Cisco Systems, Inc. booth by Joshua Hursey.</li>
<li> "Open Source High Performance Computing with Open MPI" presentation
     in the Cisco Systems, Inc. booth by Jeff Squyres.</li>
<li> "High Performance Message Passing over generic Ethernet with Open-MX"
     presentation in the Cisco Systems, Inc. booth by Dr. Brice Goglin.</li>
<li> "Open MPI Tutorial" presentation in the Indiana University booth by 
     Joshua Hursey.</li>
<li> "OMPIO: A Modular Architecture for Parallel I/O" presentation in the
     Cisco Systems, Inc. booth by Dr. Edgar Gabriel.</li>
<li> "Tools to Analyze the Performance of Open MPI Programs" presentation
     in the Cisco Systems, Inc. booth by Jens Doleschal.</li>
<li> "A Resilient Runtime Environment for HPC and Internet Core Router
     Systems" presentation in the Cisco Systems, Inc. booth by Tim 
     Mattox.</li>
<li> "A Resilient Runtime Environment for HPC and Internet Core Router
     Systems" poster by Tim Mattox et al.</li>
<li> MPI Forum BOF</li>
</ul>

Some talks contained animations which will not show in the PDFs below.
Other talks were originally presented in 16:9 format, and look a
little small in the PDFs.';

$presented = "<a href=\"http://sc09.supercomputing.org/\">" . "SC'09</a>,
November, 2009, in Portland, OR, USA";

$files[] = "ompi-bof-1up.pdf";
$files[] = "ompi-bof-2up.pdf";
$files[] = "jjhursey-cisco-booth.pdf";
$files[] = "jsquyres-cisco-booth-1up.pdf";
$files[] = "jsquyres-cisco-booth-2up.pdf";
$files[] = "bgoglin-open-mx-cisco-booth.pdf";
$files[] = "jjhursey-iu-booth.pdf";
$files[] = "egabriel-parallel-io-cisco-booth.pdf";
$files[] = "jdoleschal-vt-cisco-booth.pdf";
$files[] = "ludd-cisco-booth-1up.pdf";
$files[] = "ludd-cisco-booth-2up.pdf";
$files[] = "ludd-poster.pdf";
$files[] = "MPI_Forum_SC09_BOF-1up.pdf";
$files[] = "MPI_Forum_SC09_BOF-2up.pdf";

$month = 11;
$day = 16;
$year = 2009;

$bibtex = "";
