<?php
$topdir = "../../../..";
# Note that we must use the PHP "$$" indirection to assign to the
# "title" variable, because if we list "$ title" (without the space)
# in this file, Doxygen will replace it with a string title.
$ver = basename(getcwd());
$thwarting_doxygen_preprocessor = "title";
$$thwarting_doxygen_preprocessor = "Portable Hardware Locality (hwloc) Documentation: $ver";
$header_include_file = "$topdir/projects/hwloc/doc/$ver/www.open-mpi.org-css.inc";
include_once("$topdir/projects/hwloc/nav.inc");
include_once("$topdir/includes/header.inc");
include_once("$topdir/includes/code.inc");
?>
<!-- Generated by Doxygen 1.8.18 -->
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',false,false,'search.php','Search');
});
/* @license-end */</script>
<div id="main-nav"></div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#nested-classes">Data Structures</a> &#124;
<a href="#pub-types">Public Types</a> &#124;
<a href="#pub-attribs">Data Fields</a>  </div>
  <div class="headertitle">
<div class="title">hwloc_location Struct Reference<div class="ingroups"><a class="el" href="a00178.php">Comparing memory node attributes for finding where to allocate on</a></div></div>  </div>
</div><!--header-->
<div class="contents">

<p><code>#include &lt;<a class="el" href="a00104_source.php">memattrs.h</a>&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Data Structures</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">union &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="a00284.php">hwloc_location_u</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-types"></a>
Public Types</h2></td></tr>
<tr class="memitem:a7efa5d659afc1e10bb0ae3a83d66ceea"><td class="memItemLeft" align="right" valign="top">enum &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="a00280.php#a7efa5d659afc1e10bb0ae3a83d66ceea">hwloc_location_type_e</a> { <a class="el" href="a00280.php#a7efa5d659afc1e10bb0ae3a83d66ceeaaa2e7fb101f183b3438599f16390961ef">HWLOC_LOCATION_TYPE_OBJECT</a> = 0, 
<a class="el" href="a00280.php#a7efa5d659afc1e10bb0ae3a83d66ceeaa0354078f9171bc68080a49c83b9dca9f">HWLOC_LOCATION_TYPE_CPUSET</a> = 1
 }</td></tr>
<tr class="separator:a7efa5d659afc1e10bb0ae3a83d66ceea"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-attribs"></a>
Data Fields</h2></td></tr>
<tr class="memitem:a7ec43ae76ccd9e44472e8256d0787e67"><td class="memItemLeft" align="right" valign="top">enum <a class="el" href="a00280.php#a7efa5d659afc1e10bb0ae3a83d66ceea">hwloc_location::hwloc_location_type_e</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="a00280.php#a7ec43ae76ccd9e44472e8256d0787e67">type</a></td></tr>
<tr class="separator:a7ec43ae76ccd9e44472e8256d0787e67"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a707a25a5b65177e4d081be49aa0777a2"><td class="memItemLeft" align="right" valign="top">union <a class="el" href="a00284.php">hwloc_location::hwloc_location_u</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="a00280.php#a707a25a5b65177e4d081be49aa0777a2">location</a></td></tr>
<tr class="separator:a707a25a5b65177e4d081be49aa0777a2"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Where to measure attributes from. </p>
</div><h2 class="groupheader">Member Enumeration Documentation</h2>
<a id="a7efa5d659afc1e10bb0ae3a83d66ceea"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a7efa5d659afc1e10bb0ae3a83d66ceea">&#9670;&nbsp;</a></span>hwloc_location_type_e</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">enum <a class="el" href="a00280.php#a7efa5d659afc1e10bb0ae3a83d66ceea">hwloc_location::hwloc_location_type_e</a></td>
        </tr>
      </table>
</div><div class="memdoc">

<p>Type of location. </p>
<table class="fieldtable">
<tr><th colspan="2">Enumerator</th></tr><tr><td class="fieldname"><a id="a7efa5d659afc1e10bb0ae3a83d66ceeaaa2e7fb101f183b3438599f16390961ef"></a>HWLOC_LOCATION_TYPE_OBJECT&#160;</td><td class="fielddoc"><p>Location is given as an object, in the location object union field. </p>
</td></tr>
<tr><td class="fieldname"><a id="a7efa5d659afc1e10bb0ae3a83d66ceeaa0354078f9171bc68080a49c83b9dca9f"></a>HWLOC_LOCATION_TYPE_CPUSET&#160;</td><td class="fielddoc"><p>Location is given as an cpuset, in the location cpuset union field. </p>
</td></tr>
</table>

</div>
</div>
<h2 class="groupheader">Field Documentation</h2>
<a id="a707a25a5b65177e4d081be49aa0777a2"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a707a25a5b65177e4d081be49aa0777a2">&#9670;&nbsp;</a></span>location</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">union <a class="el" href="a00284.php">hwloc_location::hwloc_location_u</a> hwloc_location::location</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a7ec43ae76ccd9e44472e8256d0787e67"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a7ec43ae76ccd9e44472e8256d0787e67">&#9670;&nbsp;</a></span>type</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">enum <a class="el" href="a00280.php#a7efa5d659afc1e10bb0ae3a83d66ceea">hwloc_location::hwloc_location_type_e</a> hwloc_location::type</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<hr/>The documentation for this struct was generated from the following file:<ul>
<li><a class="el" href="a00104_source.php">memattrs.h</a></li>
</ul>
</div><!-- contents -->
<?php
include_once("$topdir/includes/footer.inc");
