<?
$subject_val = "[OMPI devel] openib BTL problems with ORTE async changes";
include("../../include/msg-header.inc");
?>
<!-- received="Tue Sep  3 14:34:12 2013" -->
<!-- isoreceived="20130903183412" -->
<!-- sent="Tue, 3 Sep 2013 11:34:09 -0700" -->
<!-- isosent="20130903183409" -->
<!-- name="Rolf vandeVaart" -->
<!-- email="rvandevaart_at_[hidden]" -->
<!-- subject="[OMPI devel] openib BTL problems with ORTE async changes" -->
<!-- id="3AF945EBF4D3EC41AFE44EED9B0585F3600673C942_at_HQMAIL02.nvidia.com" -->
<!-- charset="us-ascii" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> [OMPI devel] openib BTL problems with ORTE async changes<br>
<strong>From:</strong> Rolf vandeVaart (<em>rvandevaart_at_[hidden]</em>)<br>
<strong>Date:</strong> 2013-09-03 14:34:09
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="12842.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] Possible OMPI 1.6.5 bug?  SEGV in malloc.c"</a>
<li><strong>Previous message:</strong> <a href="12840.php">Ralph Castain: "Re: [OMPI devel] Open-MPI build of NAMD launched from srun over 20% slowed than with mpirun"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="12843.php">Ralph Castain: "Re: [OMPI devel] openib BTL problems with ORTE async changes"</a>
<li><strong>Reply:</strong> <a href="12843.php">Ralph Castain: "Re: [OMPI devel] openib BTL problems with ORTE async changes"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
As mentioned in the weekly conference call, I am seeing some strange errors when using the openib BTL.  I have narrowed down the changeset that broke things to the ORTE async code.
<br>
<p><a href="https://svn.open-mpi.org/trac/ompi/changeset/29058">https://svn.open-mpi.org/trac/ompi/changeset/29058</a>  (and <a href="https://svn.open-mpi.org/trac/ompi/changeset/29061">https://svn.open-mpi.org/trac/ompi/changeset/29061</a> which was needed to fix compile errors)
<br>
<p>Changeset 29057 does not have these issues.  I do not have a very good characterization of the failures.  The failures are not consistent.  Sometimes they can pass.  Sometimes the stack trace can be different.  They seem to happen more with larger np, like np=4 and more.
<br>
<p>The first failure mode is a segmentation violation and it always seems to be that we are trying to pop something of a free list.  But the upper parts of the stack trace can vary.  This is with the trunk version 29061.
<br>
Ralph, any thoughts on where we go from here?
<br>
<p>[rolf_at_Fermi-Cluster src]$ mpirun -np 4 -host c0-0,c0-1,c0-3,c0-4 MPI_Irecv_comm_c
<br>
MPITEST info  (0): Starting:  MPI_Irecv_comm:
<br>
[compute-0-4:04752] *** Process received signal *** [compute-0-4:04752] Signal: Segmentation fault (11) [compute-0-4:04752] Signal code: Address not mapped (1) [compute-0-4:04752] Failing at address: 0x28
<br>
--------------------------------------------------------------------------
<br>
mpirun noticed that process rank 3 with PID 4752 on node c0-4 exited on signal 11 (Segmentation fault).
<br>
--------------------------------------------------------------------------
<br>
[rolf_at_Fermi-Cluster src]$ gdb MPI_Irecv_comm_c core.4752 GNU gdb Fedora (6.8-27.el5) Copyright (C) 2008 Free Software Foundation, Inc.
<br>
License GPLv3+: GNU GPL version 3 or later &lt;<a href="http://gnu.org/licenses/gpl.html">http://gnu.org/licenses/gpl.html</a>&gt;
<br>
Core was generated by `MPI_Irecv_comm_c'.
<br>
Program terminated with signal 11, Segmentation fault.
<br>
[New process 4753]
<br>
[New process 4756]
<br>
[New process 4755]
<br>
[New process 4754]
<br>
[New process 4752]
<br>
#0  0x00002aaaad6ecad6 in opal_atomic_lifo_pop (lifo=0x5996940) at ../../../../../opal/class/opal_atomic_lifo.h:111
<br>
111             lifo-&gt;opal_lifo_head = (opal_list_item_t*)item-&gt;opal_list_next;
<br>
(gdb) where
<br>
#0  0x00002aaaad6ecad6 in opal_atomic_lifo_pop (lifo=0x5996940) at ../../../../../opal/class/opal_atomic_lifo.h:111
<br>
#1  0x00002aaaad6ec5b4 in __ompi_free_list_wait_mt (fl=0x5996940, item=0x40ea8d50) at ../../../../../ompi/class/ompi_free_list.h:228
<br>
#2  0x00002aaaad6ec3f8 in post_recvs (ep=0x59f3120, qp=0, num_post=256) at ../../../../../ompi/mca/btl/openib/btl_openib_endpoint.h:361
<br>
#3  0x00002aaaad6ec1ae in mca_btl_openib_endpoint_post_rr_nolock (ep=0x59f3120, qp=0)
<br>
&nbsp;&nbsp;&nbsp;&nbsp;at ../../../../../ompi/mca/btl/openib/btl_openib_endpoint.h:405
<br>
#4  0x00002aaaad6ebfad in mca_btl_openib_endpoint_post_recvs (endpoint=0x59f3120)
<br>
&nbsp;&nbsp;&nbsp;&nbsp;at ../../../../../ompi/mca/btl/openib/btl_openib_endpoint.c:494
<br>
#5  0x00002aaaad6fe71c in qp_create_all (endpoint=0x59f3120) at ../../../../../ompi/mca/btl/openib/connect/btl_openib_connect_oob.c:432
<br>
#6  0x00002aaaad6fde2b in reply_start_connect (endpoint=0x59f3120, rem_info=0x40ea8ed0)
<br>
&nbsp;&nbsp;&nbsp;&nbsp;at ../../../../../ompi/mca/btl/openib/connect/btl_openib_connect_oob.c:245
<br>
#7  0x00002aaaad7006ae in rml_recv_cb (status=0, process_name=0x5b0bb90, buffer=0x40ea8f80, tag=102, cbdata=0x0)
<br>
&nbsp;&nbsp;&nbsp;&nbsp;at ../../../../../ompi/mca/btl/openib/connect/btl_openib_connect_oob.c:858
<br>
#8  0x00002ae802454601 in orte_rml_base_process_msg (fd=-1, flags=4, cbdata=0x5b0bac0)
<br>
&nbsp;&nbsp;&nbsp;&nbsp;at ../../../../orte/mca/rml/base/rml_base_msg_handlers.c:172
<br>
#9  0x00002ae8027164a1 in event_process_active_single_queue (base=0x58ac620, activeq=0x58aa5b0)
<br>
&nbsp;&nbsp;&nbsp;&nbsp;at ../../../../../../opal/mca/event/libevent2021/libevent/event.c:1367
<br>
#10 0x00002ae802716b24 in event_process_active (base=0x58ac620) at ../../../../../../opal/mca/event/libevent2021/libevent/event.c:1437
<br>
#11 0x00002ae80271715c in opal_libevent2021_event_base_loop (base=0x58ac620, flags=1)
<br>
&nbsp;&nbsp;&nbsp;&nbsp;at ../../../../../../opal/mca/event/libevent2021/libevent/event.c:1645
<br>
#12 0x00002ae8023e7465 in orte_progress_thread_engine (obj=0x2ae8026902c0) at ../../orte/runtime/orte_init.c:180
<br>
#13 0x0000003ab1e06367 in start_thread () from /lib64/libpthread.so.0
<br>
#14 0x0000003ab16d2f7d in clone () from /lib64/libc.so.6
<br>
(gdb)
<br>
<p><p>-----------------------------------------------------------------------------------
<br>
This email message is for the sole use of the intended recipient(s) and may contain
<br>
confidential information.  Any unauthorized review, use, disclosure or distribution
<br>
is prohibited.  If you are not the intended recipient, please contact the sender by
<br>
reply email and destroy all copies of the original message.
<br>
-----------------------------------------------------------------------------------
<br>
<p><hr>
<ul>
<li>text/html attachment: <a href="http://www.open-mpi.org/community/lists/devel/att-12841/attachment">attachment</a>
</ul>
<!-- attachment="attachment" -->
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="12842.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] Possible OMPI 1.6.5 bug?  SEGV in malloc.c"</a>
<li><strong>Previous message:</strong> <a href="12840.php">Ralph Castain: "Re: [OMPI devel] Open-MPI build of NAMD launched from srun over 20% slowed than with mpirun"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="12843.php">Ralph Castain: "Re: [OMPI devel] openib BTL problems with ORTE async changes"</a>
<li><strong>Reply:</strong> <a href="12843.php">Ralph Castain: "Re: [OMPI devel] openib BTL problems with ORTE async changes"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
