<?
$subject_val = "Re: [hwloc-users] Compiling hwloc into a static library on Windows and Linux";
include("../../include/msg-header.inc");
?>
<!-- received="Mon Jan  9 20:26:05 2012" -->
<!-- isoreceived="20120110012605" -->
<!-- sent="Tue, 10 Jan 2012 02:25:57 +0100" -->
<!-- isosent="20120110012557" -->
<!-- name="Samuel Thibault" -->
<!-- email="samuel.thibault_at_[hidden]" -->
<!-- subject="Re: [hwloc-users] Compiling hwloc into a static library on Windows and Linux" -->
<!-- id="20120110012557.GK4266_at_type.famille.thibault.fr" -->
<!-- charset="iso-8859-1" -->
<!-- inreplyto="1356968955.298000.1326157726292.JavaMail.root_at_zmbs4.inria.fr" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> Re: [hwloc-users] Compiling hwloc into a static library on Windows and Linux<br>
<strong>From:</strong> Samuel Thibault (<em>samuel.thibault_at_[hidden]</em>)<br>
<strong>Date:</strong> 2012-01-09 20:25:57
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="0500.php">Jeff Squyres: "Re: [hwloc-users] Compiling hwloc into a static library on Windows and Linux"</a>
<li><strong>Previous message:</strong> <a href="0498.php">Andrew Helwer: "[hwloc-users] Compiling hwloc into a static library on Windows and Linux"</a>
<li><strong>Maybe in reply to:</strong> <a href="0498.php">Andrew Helwer: "[hwloc-users] Compiling hwloc into a static library on Windows and Linux"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="0500.php">Jeff Squyres: "Re: [hwloc-users] Compiling hwloc into a static library on Windows and Linux"</a>
<li><strong>Reply:</strong> <a href="0500.php">Jeff Squyres: "Re: [hwloc-users] Compiling hwloc into a static library on Windows and Linux"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Andrew Helwer, le Tue 10 Jan 2012 02:08:46 +0100, a &#233;crit :
<br>
<span class="quotelev1">&gt; First of all, is Windows 64-bit supported? There is only a 32-bit release on
</span><br>
<span class="quotelev1">&gt; the downloads page.
</span><br>
<p>I have never tried to build a 64bit binary, but there is little reason
<br>
it should fail.
<br>
<p><span class="quotelev1">&gt; However, when I specify the --enable-embedded-mode flag in configure in Linux,
</span><br>
<span class="quotelev1">&gt; no libraries are built at all - the specified prefix directory contains only
</span><br>
<span class="quotelev1">&gt; empty directories.
</span><br>
<p>But the library is built, it's just not installed because projects often
<br>
prefer to link the library in, or something similar. If you want to
<br>
install libhwloc.a, simply fetch it from src/.libs/
<br>
<p><span class="quotelev1">&gt; I've managed to compile a working static library on Linux using the headers
</span><br>
<span class="quotelev1">&gt; generated by configure,
</span><br>
<p>I'm not sure to understand. Doesn't passing --enable-static to
<br>
./configure already generate a static library?
<br>
<p><span class="quotelev1">&gt; but am having a lot of difficulty doing the same on Windows - the
</span><br>
<span class="quotelev1">&gt; Visual Studio compiler runs into a lot of issues. Is there a simple
</span><br>
<span class="quotelev1">&gt; way to do this?
</span><br>
<p>I have to say I know basically nothing about what Visual Studio expects
<br>
from a static library.
<br>
<p>Samuel
<br>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="0500.php">Jeff Squyres: "Re: [hwloc-users] Compiling hwloc into a static library on Windows and Linux"</a>
<li><strong>Previous message:</strong> <a href="0498.php">Andrew Helwer: "[hwloc-users] Compiling hwloc into a static library on Windows and Linux"</a>
<li><strong>Maybe in reply to:</strong> <a href="0498.php">Andrew Helwer: "[hwloc-users] Compiling hwloc into a static library on Windows and Linux"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="0500.php">Jeff Squyres: "Re: [hwloc-users] Compiling hwloc into a static library on Windows and Linux"</a>
<li><strong>Reply:</strong> <a href="0500.php">Jeff Squyres: "Re: [hwloc-users] Compiling hwloc into a static library on Windows and Linux"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
