<?php
$title = "Supercomputing 2005 slides";
$overview = "Slides from various presentations about Open MPI or by the Open MPI team members.";

$authors = "Jeff Squyres, Tim Woodall, George Bosilca, Graham Fagg";

$abstract = "Per request from many SC attendees, we are publishing our
slides from various talks by Open MPI team members at SC.  There are
1-up and 6-up PDF versions of each.  The talks are:

<ul>
<li> Four mini-talks about Open MPI in the Indiana University booth:
     <ol>
     <li>Introduction and Overview of Open MPI<br/>
         Jeff Squyres (Indiana University)</li>
     <li>Advanced Point-to-Point Architecture in Open MPI<br/>
         Tim Woodall (Los Alamos National Laboratory)</li>
     <li>Datatypes, Fault Tolerance, and Other Cool Stuff in Open MPI<br/>
         George Bosilca (University of Tennessee)</li>
     <li>Tuning Collective Communication: Managing the choices<br/>
         Graham Fagg (University of Tennessee)</li>
     </ol>
</li>

<li> Open MPI summary presentation at the Eclipse parallel debugging
BOF (Jeff Squyres, Indiana University).</li>

<li> Open MPI summary presentation at the AIST booth (Jeff Squyres,
Indiana University).</li>

<li> \"Why MPI Makes You Scream!  And How Can We Improve Parallel
Debugging?\" BOF (Jeff Squyres, Indiana University)</li>
</ul>";

$presented = "<a href=\"http://sc05.supercomputing.org/\">" .
"SC'05</a>, November, 2005, in Seattle, Washington, USA";

$files[] = "iu-booth-slides-1up.pdf";
$files[] = "iu-booth-slides-6up.pdf";
$files[] = "eclipse-bof-1up.pdf";
$files[] = "eclipse-bof-6up.pdf";
$files[] = "aist-booth-1up.pdf";
$files[] = "aist-booth-6up.pdf";
$files[] = "debugging-bof-1up.pdf";
$files[] = "debugging-bof-6up.pdf";

$month = 11;
$day = 14;
$year = 2005;

$bibtex = "";
