<?
$subject_val = "[OMPI users] fortran90 and c++ wrappers don't work";
include("../../include/msg-header.inc");
?>
<!-- received="Thu Apr 17 00:56:01 2008" -->
<!-- isoreceived="20080417045601" -->
<!-- sent="Wed, 16 Apr 2008 21:55:57 -0700" -->
<!-- isosent="20080417045557" -->
<!-- name="Rodriguez, Jose" -->
<!-- email="jrodrig_at_[hidden]" -->
<!-- subject="[OMPI users] fortran90 and c++ wrappers don't work" -->
<!-- id="273EA81204953D4A911A18E8E2AF0000028F8ECA_at_santafe6.academic.ad.calstatela.edu" -->
<!-- charset="us-ascii" -->
<!-- inreplyto="273EA81204953D4A911A18E8E2AF0000028F8EC8_at_santafe6.academic.ad.calstatela.edu" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> [OMPI users] fortran90 and c++ wrappers don't work<br>
<strong>From:</strong> Rodriguez, Jose (<em>jrodrig_at_[hidden]</em>)<br>
<strong>Date:</strong> 2008-04-17 00:55:57
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="5407.php">Crni Gorac: "Re: [OMPI users] mpicc -showme:compile output (possible bug report)"</a>
<li><strong>Previous message:</strong> <a href="5405.php">Terry Frankcombe: "Re: [OMPI users] mpicc -showme:compile output (possible bug report)"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="5412.php">Jeff Squyres: "Re: [OMPI users] fortran90 and c++ wrappers don't work"</a>
<li><strong>Reply:</strong> <a href="5412.php">Jeff Squyres: "Re: [OMPI users] fortran90 and c++ wrappers don't work"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Dear OMPI users and builders:
<br>
<p>&nbsp;
<br>
<p>I recently installed the latest version of Open MPI (1.2.6) on my Mac
<br>
Pro, which has 2 dual-core Intel cpu's.
<br>
<p>On the plus side, I can successfully compile and run MPI codes written
<br>
both in fortran77 and in c on all 4 cores
<br>
<p>with the corresponding wrappers that the build created.  On the down
<br>
side, I can't compile the fortran90
<br>
<p>and the c++ versions of the sample `hello world' MPI programs.  Instead
<br>
I get
<br>
<p>&nbsp;
<br>
<p>&quot;.../mpi_examples jpr$ mpif90 hello_f90.f90
<br>
<p>&nbsp;fortcom: Error: hello_f90.f90, line 12: This module file was not
<br>
<p>&nbsp;generated by any release of this compiler.   [MPI]
<br>
<p>&nbsp;use mpi  --------^
<br>
<p>&nbsp;fortcom: Error: hello_f90.f90, line 17: This name does not have a type,
<br>
<p>&nbsp;and must have an explicit type.   [MPI_COMM_WORLD]
<br>
<p>&nbsp;call MPI_COMM_RANK(MPI_COMM_WORLD, rank, ierr)
<br>
-----------------------^  
<br>
<p>&nbsp;compilation aborted for hello_f90.f90 (code 1)&quot;
<br>
<p>&nbsp;
<br>
<p>and
<br>
<p>&nbsp;
<br>
<p>&quot;.../mpi_examples jpr$ mpicxx hello_cxx.cc
<br>
<p>&nbsp;ld64 warning: in /usr/local/lib/libstdc++.dylib, file is not of
<br>
required architecture
<br>
<p>&nbsp;ld64-62.1 failed: can't open file for writing&quot;.
<br>
<p>&nbsp;
<br>
<p>Does anyone know what's wrong here? I configured the build using all of
<br>
the latest Intel compilers:
<br>
<p>&nbsp;
<br>
<p>&quot;$ ./configure CC=icc CXX=icpc F77=ifort FC=ifort CFLAGS=-m64
<br>
<p>&nbsp;CXXFLAGS=-m64 FFLAGS=-m64 FCFLAGS=-m64 --with-mpi-f90-size=medium&quot;.
<br>
<p>&nbsp;
<br>
<p>Last, I'm running Mac OS Tiger (10.4.11) and Xcode 2.4.1. And apropos my
<br>
version of GCC, I have
<br>
<p>&nbsp;
<br>
<p>&quot;diana:~ jpr$ GCC
<br>
<p>&nbsp;i686-apple-darwin8-gcc-4.0.1: no input files&quot;.
<br>
<p>&nbsp;
<br>
<p>Any guidance would be greatly appreciated.
<br>
<p>&nbsp;
<br>
<p>Jose Rodriguez, Physics and Astronomy, California State University at
<br>
Los Angeles, April 16, 2008.
<br>
<p>&nbsp;
<br>
<p><p><hr>
<ul>
<li>text/html attachment: <a href="http://www.open-mpi.org/community/lists/users/att-5406/attachment">attachment</a>
</ul>
<!-- attachment="attachment" -->
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="5407.php">Crni Gorac: "Re: [OMPI users] mpicc -showme:compile output (possible bug report)"</a>
<li><strong>Previous message:</strong> <a href="5405.php">Terry Frankcombe: "Re: [OMPI users] mpicc -showme:compile output (possible bug report)"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="5412.php">Jeff Squyres: "Re: [OMPI users] fortran90 and c++ wrappers don't work"</a>
<li><strong>Reply:</strong> <a href="5412.php">Jeff Squyres: "Re: [OMPI users] fortran90 and c++ wrappers don't work"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
