<?php
$title = "Supercomputing 2013 slides";
$overview = "Slides from the Open MPI State of the Union BOF at SC'13";

$authors = "George Bosilca, Jeff Squyres, Brice Goglin, Mike Dubman";

$abstract = "Slides from the Open MPI State of the Union Community
Meeting at SC'13.";

$presented = "<a href=\"http://sc13.supercomputing.org/\">" . "SC'13</a>,
November, 2013, in Denver, CO, USA";

$files[] = "Open-MPI-SC13-BOF.pdf";

$month = 11;
$day = 19;
$year = 2013;

$bibtex = "";
