<?
$subject_val = "Re: [OMPI users] hdf5 build error using openmpi and Intel Fortran";
include("../../include/msg-header.inc");
?>
<!-- received="Wed Oct  6 10:07:26 2010" -->
<!-- isoreceived="20101006140726" -->
<!-- sent="Wed, 6 Oct 2010 16:07:21 +0200" -->
<!-- isosent="20101006140721" -->
<!-- name="G&#246;tz Waschk" -->
<!-- email="goetz.waschk_at_[hidden]" -->
<!-- subject="Re: [OMPI users] hdf5 build error using openmpi and Intel Fortran" -->
<!-- id="AANLkTikipDqbcHUDzcL-pVHqbCYWqc2JPFmb1Of2AeXh_at_mail.gmail.com" -->
<!-- charset="ISO-8859-1" -->
<!-- inreplyto="4CAC6ED6.3030106_at_aol.com" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> Re: [OMPI users] hdf5 build error using openmpi and Intel Fortran<br>
<strong>From:</strong> G&#246;tz Waschk (<em>goetz.waschk_at_[hidden]</em>)<br>
<strong>Date:</strong> 2010-10-06 10:07:21
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="14403.php">Andrei Fokau: "Re: [OMPI users] Shared memory"</a>
<li><strong>Previous message:</strong> <a href="14401.php">Tim Prince: "Re: [OMPI users] hdf5 build error using openmpi and Intel Fortran"</a>
<li><strong>In reply to:</strong> <a href="14401.php">Tim Prince: "Re: [OMPI users] hdf5 build error using openmpi and Intel Fortran"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="14404.php">Jeff Squyres: "Re: [OMPI users] hdf5 build error using openmpi and Intel Fortran"</a>
<li><strong>Reply:</strong> <a href="14404.php">Jeff Squyres: "Re: [OMPI users] hdf5 build error using openmpi and Intel Fortran"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
On Wed, Oct 6, 2010 at 2:43 PM, Tim Prince &lt;n8tm_at_[hidden]&gt; wrote:
<br>
<span class="quotelev2">&gt;&gt; libtool: link: mpif90 -shared &#160;.libs/H5f90global.o
</span><br>
<span class="quotelev2">&gt;&gt; .libs/H5fortran_types.o .libs/H5_ff.o .libs/H5Aff.o .libs/H5Dff.o
</span><br>
<span class="quotelev2">&gt;&gt; .libs/H5Eff.o .libs/H5Fff.o .libs/H5Gff.o .libs/H5Iff.o .libs/H5Lff.o
</span><br>
<span class="quotelev2">&gt;&gt; .libs/H5Off.o .libs/H5Pff.o .libs/H5Rff.o .libs/H5Sff.o .libs/H5Tff.o
</span><br>
<span class="quotelev2">&gt;&gt; .libs/H5Zff.o .libs/H5_DBLE_InterfaceInclude.o .libs/H5f90kit.o
</span><br>
<span class="quotelev2">&gt;&gt; .libs/H5_f.o .libs/H5Af.o .libs/H5Df.o .libs/H5Ef.o .libs/H5Ff.o
</span><br>
<span class="quotelev2">&gt;&gt; .libs/H5Gf.o .libs/H5If.o .libs/H5Lf.o .libs/H5Of.o .libs/H5Pf.o
</span><br>
<span class="quotelev2">&gt;&gt; .libs/H5Rf.o .libs/H5Sf.o .libs/H5Tf.o .libs/H5Zf.o .libs/H5FDmpiof.o
</span><br>
<span class="quotelev2">&gt;&gt; .libs/HDF5mpio.o .libs/H5FDmpioff.o &#160; &#160;-lmpi -lsz -lz -lm &#160;-m64
</span><br>
<span class="quotelev2">&gt;&gt; -mtune=generic -rpath=/usr/lib64/openmpi/1.4-icc/lib &#160; -soname
</span><br>
<span class="quotelev2">&gt;&gt; libhdf5_fortran.so.6 -o .libs/libhdf5_fortran.so.6.0.4
</span><br>
<span class="quotelev2">&gt;&gt; ifort: command line warning #10156: ignoring option '-r'; no argument
</span><br>
<span class="quotelev2">&gt;&gt; required
</span><br>
<span class="quotelev2">&gt;&gt; ifort: command line warning #10156: ignoring option '-s'; no argument
</span><br>
<span class="quotelev2">&gt;&gt; required
</span><br>
<span class="quotelev2">&gt;&gt; ld: libhdf5_fortran.so.6: No such file: No such file or directory
</span><br>
<span class="quotelev1">&gt; Do -Wl,-rpath and -Wl,-soname= work any better?
</span><br>
Yes, with these options, it build fine. But the command line is
<br>
generated by libtool, so how can I make libtool to use -Wl, in front
<br>
of the linker options? It seems to strip these from the command.
<br>
<p>Regards, G&#246;tz
<br>
<p><pre>
-- 
AL I:40: Do what thou wilt shall be the whole of the Law.
</pre>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="14403.php">Andrei Fokau: "Re: [OMPI users] Shared memory"</a>
<li><strong>Previous message:</strong> <a href="14401.php">Tim Prince: "Re: [OMPI users] hdf5 build error using openmpi and Intel Fortran"</a>
<li><strong>In reply to:</strong> <a href="14401.php">Tim Prince: "Re: [OMPI users] hdf5 build error using openmpi and Intel Fortran"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="14404.php">Jeff Squyres: "Re: [OMPI users] hdf5 build error using openmpi and Intel Fortran"</a>
<li><strong>Reply:</strong> <a href="14404.php">Jeff Squyres: "Re: [OMPI users] hdf5 build error using openmpi and Intel Fortran"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
