<?
$subject_val = "Re: [OMPI users] Problem with openmpi and infiniband";
include("../../include/msg-header.inc");
?>
<!-- received="Tue Dec 23 18:33:24 2008" -->
<!-- isoreceived="20081223233324" -->
<!-- sent="Tue, 23 Dec 2008 23:33:43 +0000" -->
<!-- isosent="20081223233343" -->
<!-- name="Biagio Lucini" -->
<!-- email="B.Lucini_at_[hidden]" -->
<!-- subject="Re: [OMPI users] Problem with openmpi and infiniband" -->
<!-- id="49517557.8020302_at_swansea.ac.uk" -->
<!-- charset="ISO-8859-1" -->
<!-- inreplyto="495166D9.2070107_at_web.de" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> Re: [OMPI users] Problem with openmpi and infiniband<br>
<strong>From:</strong> Biagio Lucini (<em>B.Lucini_at_[hidden]</em>)<br>
<strong>Date:</strong> 2008-12-23 18:33:43
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="7592.php">Sangamesh B: "Re: [OMPI users] mpiblast + openmpi + gridengine job faila to run"</a>
<li><strong>Previous message:</strong> <a href="7590.php">doriankrause: "Re: [OMPI users] Problem with openmpi and infiniband"</a>
<li><strong>In reply to:</strong> <a href="7590.php">doriankrause: "Re: [OMPI users] Problem with openmpi and infiniband"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="7593.php">Pavel Shamis (Pasha): "Re: [OMPI users] Problem with openmpi and infiniband"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Hi Dorian,
<br>
<p>thank you for your message.
<br>
<p>doriankrause wrote:
<br>
<p><span class="quotelev2">&gt;&gt;
</span><br>
<span class="quotelev2">&gt;&gt; The trouble is with an MPI code that runs fine with an openmpi 1.1.2 
</span><br>
<span class="quotelev2">&gt;&gt; library compiled without infiniband support (I have tested the 
</span><br>
<span class="quotelev2">&gt;&gt; scalability of the code up to 64 cores, the nodes are 4 or 8 cores, 
</span><br>
<span class="quotelev2">&gt;&gt; the results are exactly what I expect), but if I try to use a version 
</span><br>
<span class="quotelev2">&gt;&gt; compiled for infiniband, then only a subset of comunications (the ones 
</span><br>
<span class="quotelev2">&gt;&gt; connecting cores in the same node) are enabled, and because of this 
</span><br>
<span class="quotelev2">&gt;&gt; the program fails (gets stuck in a perennial waiting phase, in 
</span><br>
<span class="quotelev2">&gt;&gt; particular). This happens with any combination of compilers/library 
</span><br>
<span class="quotelev2">&gt;&gt; releases (1.1.2, 1.2.7, 1.2.8) I have tried. On other codes, and in 
</span><br>
<span class="quotelev2">&gt;&gt; particular on benchmarks downloaded from the net, openmpi over 
</span><br>
<span class="quotelev2">&gt;&gt; infiniband seems to work (I compared the latency with the tcp btl, so 
</span><br>
<span class="quotelev2">&gt;&gt; I am pretty sure that infiniband works). The two variables I kept 
</span><br>
<span class="quotelev2">&gt;&gt; fixed are SGE and the OFED module stack. I would like not to touch 
</span><br>
<span class="quotelev2">&gt;&gt; them, if possible, because the cluster seems to run fine for other 
</span><br>
<span class="quotelev2">&gt;&gt; purposes.
</span><br>
<p><span class="quotelev1">&gt; Does the problem only show up with openmpi? Did you tried to use mvapich 
</span><br>
<span class="quotelev1">&gt; (<a href="http://mvapich.cse.ohio-state.edu/">http://mvapich.cse.ohio-state.edu/</a>) to test whether it is a hardware or 
</span><br>
<span class="quotelev1">&gt; software problem? (I don't know any other open-source MPI implementation 
</span><br>
<span class="quotelev1">&gt; which supports infiniband)
</span><br>
<span class="quotelev1">&gt; 
</span><br>
<p>I have had bad experiences with mpich, on which mvapich is based. The 
<br>
short answer to your question is yes, and it did not work for other 
<br>
reasons (not even over ethernet). The interesting development today is 
<br>
that Intel MPI (which should be more or less mvapich2 if I am not wrong) 
<br>
seems to work (I will verify this also with mvapich2). This seems to 
<br>
point towards a problem with the OpenMPI libraries, but I have 
<br>
reservations: they seem to work for even complicated benchmarking tests 
<br>
(like the Intel Benchmark) AND I have troubles also with mpich, which I 
<br>
did not sort out. A possibility is that the problem is generated by the 
<br>
interaction MPI-SGE-my code. I would love if someone more experienced 
<br>
than me would give a look at the code (which unfortunately is fortran). 
<br>
I will try to trim down the over 4000 lines to a manageable proof of 
<br>
concept, if anyone is interested in following this up, but it is 
<br>
unlikely to happen before new year :-)
<br>
<p>Thanks again,
<br>
Biagio
<br>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="7592.php">Sangamesh B: "Re: [OMPI users] mpiblast + openmpi + gridengine job faila to run"</a>
<li><strong>Previous message:</strong> <a href="7590.php">doriankrause: "Re: [OMPI users] Problem with openmpi and infiniband"</a>
<li><strong>In reply to:</strong> <a href="7590.php">doriankrause: "Re: [OMPI users] Problem with openmpi and infiniband"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="7593.php">Pavel Shamis (Pasha): "Re: [OMPI users] Problem with openmpi and infiniband"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
