<?
$subject_val = "[OMPI devel] btl_openib.c:1200: mca_btl_openib_alloc: Assertion `qp != 255' failed";
include("../../include/msg-header.inc");
?>
<!-- received="Sat Jan 17 12:58:29 2015" -->
<!-- isoreceived="20150117175829" -->
<!-- sent="Sat, 17 Jan 2015 18:58:28 +0100" -->
<!-- isosent="20150117175828" -->
<!-- name="Adrian Reber" -->
<!-- email="adrian_at_[hidden]" -->
<!-- subject="[OMPI devel] btl_openib.c:1200: mca_btl_openib_alloc: Assertion `qp != 255' failed" -->
<!-- id="20150117175828.GM16124_at_lisas.de" -->
<!-- charset="us-ascii" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> [OMPI devel] btl_openib.c:1200: mca_btl_openib_alloc: Assertion `qp != 255' failed<br>
<strong>From:</strong> Adrian Reber (<em>adrian_at_[hidden]</em>)<br>
<strong>Date:</strong> 2015-01-17 12:58:28
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="16798.php">Gilles Gouaillardet: "Re: [OMPI devel] btl_openib.c:1200: mca_btl_openib_alloc: Assertion `qp != 255' failed"</a>
<li><strong>Previous message:</strong> <a href="16796.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] Open MPI 1.8: link problem when Fortran+C+Platform LSF"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="16798.php">Gilles Gouaillardet: "Re: [OMPI devel] btl_openib.c:1200: mca_btl_openib_alloc: Assertion `qp != 255' failed"</a>
<li><strong>Maybe reply:</strong> <a href="16798.php">Gilles Gouaillardet: "Re: [OMPI devel] btl_openib.c:1200: mca_btl_openib_alloc: Assertion `qp != 255' failed"</a>
<li><strong>Reply:</strong> <a href="16866.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] btl_openib.c:1200: mca_btl_openib_alloc: Assertion `qp	!= 255' failed"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
This time my bug report is not PSM related:
<br>
<p>I was able to reproduce the MTT error from <a href="http://mtt.open-mpi.org/index.php?do_redir=2228">http://mtt.open-mpi.org/index.php?do_redir=2228</a>
<br>
on my system with openmpi-dev-720-gf4693c9:
<br>
<p>mpi_test_suite: btl_openib.c:1200: mca_btl_openib_alloc: Assertion `qp != 255' failed.
<br>
[n050409:06796] *** Process received signal ***
<br>
[n050409:06796] Signal: Aborted (6)
<br>
[n050409:06796] Signal code:  (-6)
<br>
[n050409:06796] [ 0] /lib64/libpthread.so.0(+0xf710)[0x2b036d501710]
<br>
[n050409:06796] [ 1] /lib64/libc.so.6(gsignal+0x35)[0x2b036d741635]
<br>
[n050409:06796] [ 2] /lib64/libc.so.6(abort+0x175)[0x2b036d742e15]
<br>
[n050409:06796] [ 3] /lib64/libc.so.6(+0x2b75e)[0x2b036d73a75e]
<br>
[n050409:06796] [ 4] /lib64/libc.so.6(__assert_perror_fail+0x0)[0x2b036d73a820]
<br>
[n050409:06796] [ 5] /lustre/ws1/ws/adrian-mtt-0/ompi-install/lib/openmpi/mca_btl_openib.so(mca_btl_openib_alloc+0x77)[0x2b03730cf6d0]
<br>
[n050409:06796] [ 6] /lustre/ws1/ws/adrian-mtt-0/ompi-install/lib/openmpi/mca_btl_openib.so(mca_btl_openib_sendi+0x5e5)[0x2b03730d1ae9]
<br>
[n050409:06796] [ 7] /lustre/ws1/ws/adrian-mtt-0/ompi-install/lib/openmpi/mca_pml_ob1.so(+0xd407)[0x2b0373961407]
<br>
[n050409:06796] [ 8] /lustre/ws1/ws/adrian-mtt-0/ompi-install/lib/openmpi/mca_pml_ob1.so(+0xde45)[0x2b0373961e45]
<br>
[n050409:06796] [ 9] /lustre/ws1/ws/adrian-mtt-0/ompi-install/lib/openmpi/mca_pml_ob1.so(mca_pml_ob1_send+0x1ce)[0x2b0373962501]
<br>
[n050409:06796] [10] /lustre/ws1/ws/adrian-mtt-0/ompi-install/lib/libmpi.so.0(PMPI_Send+0x2b4)[0x2b036d20d1bb]
<br>
[n050409:06796] [11] mpi_test_suite[0x464424]
<br>
[n050409:06796] [12] mpi_test_suite[0x470304]
<br>
[n050409:06796] [13] mpi_test_suite[0x444a72]
<br>
[n050409:06796] [14] /lib64/libc.so.6(__libc_start_main+0xfd)[0x2b036d72dd5d]
<br>
[n050409:06796] [15] mpi_test_suite[0x4051a9]
<br>
[n050409:06796] *** End of error message ***
<br>
--------------------------------------------------------------------------
<br>
mpirun noticed that process rank 0 with PID 0 on node n050409 exited on signal 6 (Aborted).
<br>
--------------------------------------------------------------------------
<br>
<p>Core was generated by `mpi_test_suite -t p2p'.
<br>
Program terminated with signal 6, Aborted.
<br>
(gdb) bt
<br>
#0  0x00002b036d741635 in raise () from /lib64/libc.so.6
<br>
#1  0x00002b036d742d9d in abort () from /lib64/libc.so.6
<br>
#2  0x00002b036d73a75e in __assert_fail_base () from /lib64/libc.so.6
<br>
#3  0x00002b036d73a820 in __assert_fail () from /lib64/libc.so.6
<br>
#4  0x00002b03730cf6d0 in mca_btl_openib_alloc (btl=0x224e740, ep=0x22b66a0, order=255 '\377', size=73014, flags=3) at btl_openib.c:1200
<br>
#5  0x00002b03730d1ae9 in mca_btl_openib_sendi (btl=0x224e740, ep=0x22b66a0, convertor=0x7fff2c527bb0, header=0x7fff2c527cd0, header_size=14, payload_size=73000, order=255 '\377', flags=3, 
<br>
&nbsp;&nbsp;&nbsp;&nbsp;tag=65 'A', descriptor=0x7fff2c527ce8) at btl_openib.c:1829
<br>
#6  0x00002b0373961407 in mca_bml_base_sendi (bml_btl=0x2198850, convertor=0x7fff2c527bb0, header=0x7fff2c527cd0, header_size=14, payload_size=73000, order=255 '\377', flags=3, tag=65 'A', 
<br>
&nbsp;&nbsp;&nbsp;&nbsp;descriptor=0x7fff2c527ce8) at ../../../../ompi/mca/bml/bml.h:305
<br>
#7  0x00002b0373961e45 in mca_pml_ob1_send_inline (buf=0x2b7b760, count=1, datatype=0x2b97440, dst=1, tag=37, seqn=3639, dst_proc=0x21c2940, endpoint=0x22dff00, comm=0x6939e0) at pml_ob1_isend.c:107
<br>
#8  0x00002b0373962501 in mca_pml_ob1_send (buf=0x2b7b760, count=1, datatype=0x2b97440, dst=1, tag=37, sendmode=MCA_PML_BASE_SEND_STANDARD, comm=0x6939e0) at pml_ob1_isend.c:214
<br>
#9  0x00002b036d20d1bb in PMPI_Send (buf=0x2b7b760, count=1, type=0x2b97440, dest=1, tag=37, comm=0x6939e0) at psend.c:78
<br>
#10 0x0000000000464424 in tst_p2p_simple_ring_xsend_run (env=0x7fff2c528530) at p2p/tst_p2p_simple_ring_xsend.c:97
<br>
#11 0x0000000000470304 in tst_test_run_func (env=0x7fff2c528530) at tst_tests.c:1463
<br>
#12 0x0000000000444a72 in main (argc=3, argv=0x7fff2c5287f8) at mpi_test_suite.c:639
<br>
<p>This is with --enable-debug. Without --enable-debug I get a
<br>
segmentation fault, but not always. Using fewer cores it works most
<br>
of the time. With 32 cores on 4 nodes it happens almost
<br>
all the time. If it does not crash using fewer cores I get messages like:
<br>
<p>[n050409][[36216,1],1][btl_openib_xrc.c:58:mca_btl_openib_xrc_check_api] XRC error: bad XRC API (require XRC from OFED pre 3.12).
<br>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Adrian
<br>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="16798.php">Gilles Gouaillardet: "Re: [OMPI devel] btl_openib.c:1200: mca_btl_openib_alloc: Assertion `qp != 255' failed"</a>
<li><strong>Previous message:</strong> <a href="16796.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] Open MPI 1.8: link problem when Fortran+C+Platform LSF"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="16798.php">Gilles Gouaillardet: "Re: [OMPI devel] btl_openib.c:1200: mca_btl_openib_alloc: Assertion `qp != 255' failed"</a>
<li><strong>Maybe reply:</strong> <a href="16798.php">Gilles Gouaillardet: "Re: [OMPI devel] btl_openib.c:1200: mca_btl_openib_alloc: Assertion `qp != 255' failed"</a>
<li><strong>Reply:</strong> <a href="16866.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] btl_openib.c:1200: mca_btl_openib_alloc: Assertion `qp	!= 255' failed"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
