<?
$subject_val = "[OMPI devel] Git: open-mpi/ompi-tests branch master updated. c2134f3ed25d0b327f631365b6f5f60f4ef7140d";
include("../../include/msg-header.inc");
?>
<!-- received="Tue Sep 16 15:40:04 2014" -->
<!-- isoreceived="20140916194004" -->
<!-- sent="Tue, 16 Sep 2014 15:40:04 -0400 (EDT)" -->
<!-- isosent="20140916194004" -->
<!-- name="gitdub_at_[hidden]" -->
<!-- email="gitdub_at_[hidden]" -->
<!-- subject="[OMPI devel] Git: open-mpi/ompi-tests branch master updated. c2134f3ed25d0b327f631365b6f5f60f4ef7140d" -->
<!-- id="20140916194004.DE9B8265165_at_lion.crest.iu.edu" -->
<!-- charset="utf-8" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> [OMPI devel] Git: open-mpi/ompi-tests branch master updated. c2134f3ed25d0b327f631365b6f5f60f4ef7140d<br>
<strong>From:</strong> <a href="mailto:gitdub_at_[hidden]?Subject=Re:%20[OMPI%20devel]%20Git:%20open-mpi/ompi-tests%20branch%20master%20updated.%20c2134f3ed25d0b327f631365b6f5f60f4ef7140d"><em>gitdub_at_[hidden]</em></a><br>
<strong>Date:</strong> 2014-09-16 15:40:04
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="15850.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] ompi-tests SVN repo has been moved to Github"</a>
<li><strong>Previous message:</strong> <a href="15848.php">Ralph Castain: "Re: [OMPI devel] ompi-tests SVN repo has been moved to Github"</a>
<!-- nextthread="start" -->
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
This is an automated email from the git hooks/post-receive script. It was
<br>
generated because a ref change was pushed to the repository containing
<br>
the project &quot;open-mpi/ompi-tests&quot;.
<br>
<p>The branch, master has been updated
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;via  c2134f3ed25d0b327f631365b6f5f60f4ef7140d (commit)
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;from  cd84ff8722f2aee4107f7046592e12552bf38441 (commit)
<br>
<p>Those revisions listed above that are new to this repository have
<br>
not appeared on any other notification email; so we list those
<br>
revisions in full, below.
<br>
<p>- Log -----------------------------------------------------------------
<br>
<a href="https://github.com/open-mpi/ompi-tests/commit/c2134f3ed25d0b327f631365b6f5f60f4ef7140d">https://github.com/open-mpi/ompi-tests/commit/c2134f3ed25d0b327f631365b6f5f60f4ef7140d</a>
<br>
<p>commit c2134f3ed25d0b327f631365b6f5f60f4ef7140d
<br>
Author: Jeff Squyres &lt;jsquyres_at_[hidden]&gt;
<br>
Date:   Tue Sep 16 12:10:42 2014 -0700
<br>
<p>&nbsp;&nbsp;&nbsp;&nbsp;.gitignore: first version
<br>
<p>diff --git a/.gitignore b/.gitignore
<br>
new file mode 100644
<br>
index 0000000..8446664
<br>
--- /dev/null
<br>
+++ b/.gitignore
<br>
@@ -0,0 +1,935 @@
<br>
+.libs
<br>
+.deps
<br>
+.libs
<br>
+.svn
<br>
+*.la
<br>
+*.lo
<br>
+*.o
<br>
+*.so
<br>
+*.a
<br>
+.dirstamp
<br>
+*.dSYM
<br>
+*.S
<br>
+*.loT
<br>
+*.orig
<br>
+*.rej
<br>
+*.class
<br>
+*.xcscheme
<br>
+*.plist
<br>
+*~
<br>
+*\\#
<br>
+
<br>
+Makefile
<br>
+Makefile.in
<br>
+
<br>
+b_eff/b_eff.short
<br>
+b_eff/b_eff.tex
<br>
+b_eff/b_eff
<br>
+b_eff/b_eff.prot
<br>
+b_eff/b_eff.sum
<br>
+b_eff/b_eff.gps
<br>
+b_eff/b_eff.plot
<br>
+
<br>
+cxx-test-suite/configure
<br>
+cxx-test-suite/config.in
<br>
+cxx-test-suite/config.log
<br>
+cxx-test-suite/config.status
<br>
+cxx-test-suite/autom4te.cache
<br>
+cxx-test-suite/aclocal.m4
<br>
+cxx-test-suite/config/depcomp
<br>
+cxx-test-suite/config/missing
<br>
+cxx-test-suite/config/config.guess
<br>
+cxx-test-suite/config/config.sub
<br>
+cxx-test-suite/config/ltmain.sh
<br>
+cxx-test-suite/config/install-sh
<br>
+cxx-test-suite/src/mpi2c++_test
<br>
+cxx-test-suite/src/mpi2c++_dynamics_test
<br>
+cxx-test-suite/src/test_config.h
<br>
+cxx-test-suite/src/test_config.h.in
<br>
+cxx-test-suite/src/stamp-h1
<br>
+cxx-test-suite/src/connect
<br>
+
<br>
+ibm/aclocal.m4
<br>
+ibm/config.log
<br>
+ibm/config.status
<br>
+ibm/configure
<br>
+ibm/autom4te.cache
<br>
+ibm/libtool
<br>
+ibm/collective/allgather
<br>
+ibm/collective/allgatherv
<br>
+ibm/collective/allreduce
<br>
+ibm/collective/alltoall
<br>
+ibm/collective/alltoallvw_zero
<br>
+ibm/collective/alltoallv_somezeros
<br>
+ibm/collective/alltoallw
<br>
+ibm/collective/barrier
<br>
+ibm/collective/bcast
<br>
+ibm/collective/bcast_struct
<br>
+ibm/collective/exscan
<br>
+ibm/collective/gather
<br>
+ibm/collective/op
<br>
+ibm/collective/reduce
<br>
+ibm/collective/reduce_scatter
<br>
+ibm/collective/scan
<br>
+ibm/collective/scatter
<br>
+ibm/collective/struct_gatherv
<br>
+ibm/collective/*.log
<br>
+ibm/collective/*.trs
<br>
+ibm/collective/*.mod
<br>
+ibm/collective/reduce_scatter_in_place
<br>
+ibm/collective/reduce_big
<br>
+ibm/collective/reduce_loc
<br>
+ibm/collective/allreduce_in_place
<br>
+ibm/collective/allgather_in_place
<br>
+ibm/collective/scan_in_place
<br>
+ibm/collective/gatherv
<br>
+ibm/collective/reduce_in_place
<br>
+ibm/collective/gather_in_place
<br>
+ibm/collective/allgatherv_in_place
<br>
+ibm/collective/scatterv_in_place
<br>
+ibm/collective/gatherv_in_place
<br>
+ibm/collective/scatterv
<br>
+ibm/collective/scatter_in_place
<br>
+ibm/collective/exscan_in_place
<br>
+ibm/collective/reduce-complex-c
<br>
+ibm/collective/bcast_f08
<br>
+ibm/collective/ibcast_f08
<br>
+ibm/collective/ibarrier_f08
<br>
+ibm/collective/ibarrier_f90
<br>
+ibm/collective/reduce-complex
<br>
+ibm/collective/ibarrier
<br>
+ibm/collective/ibcast_f90
<br>
+ibm/collective/ibarrier_f
<br>
+ibm/collective/ibcast
<br>
+ibm/collective/ibcast_f
<br>
+ibm/collective/reduce_scatter_block
<br>
+ibm/collective/ireduce_in_place
<br>
+ibm/collective/ireduce_loc
<br>
+ibm/collective/igatherv_in_place
<br>
+ibm/collective/iallreduce_in_place
<br>
+ibm/collective/iscatterv
<br>
+ibm/collective/iscatter_in_place
<br>
+ibm/collective/iscatterv_in_place
<br>
+ibm/collective/ireduce-complex-c
<br>
+ibm/collective/ialltoall
<br>
+ibm/collective/ireduce
<br>
+ibm/collective/iscan
<br>
+ibm/collective/igatherv
<br>
+ibm/collective/ibcast_struct
<br>
+ibm/collective/iallreduce
<br>
+ibm/collective/igather_in_place
<br>
+ibm/collective/ireduce_scatter_block
<br>
+ibm/collective/igather
<br>
+ibm/collective/iallgatherv_in_place
<br>
+ibm/collective/ireduce_scatter
<br>
+ibm/collective/iallgather
<br>
+ibm/collective/iscan_in_place
<br>
+ibm/collective/ireduce_big
<br>
+ibm/collective/iallgatherv
<br>
+ibm/collective/iallgather_in_place
<br>
+ibm/collective/istruct_gatherv
<br>
+ibm/collective/ireduce_scatter_in_place
<br>
+ibm/collective/iscatter
<br>
+ibm/collective/alltoall_in_place
<br>
+ibm/collective/alltoallw_in_place
<br>
+ibm/collective/iexscan
<br>
+ibm/collective/iexscan_in_place
<br>
+ibm/collective/ineighbor_allgather
<br>
+ibm/collective/ineighbor_allgatherv
<br>
+ibm/collective/ineighbor_alltoall
<br>
+ibm/collective/ineighbor_alltoallv
<br>
+ibm/collective/ineighbor_alltoallw
<br>
+ibm/collective/neighbor_allgather
<br>
+ibm/collective/neighbor_allgatherv
<br>
+ibm/collective/neighbor_alltoall
<br>
+ibm/collective/neighbor_alltoallv
<br>
+ibm/collective/neighbor_alltoallw
<br>
+ibm/collective/op_mpifh
<br>
+ibm/collective/op_usempi
<br>
+ibm/collective/op_usempif08
<br>
+ibm/collective/optest.*
<br>
+ibm/collective/intercomm/allgather_inter
<br>
+ibm/collective/intercomm/allreduce_inter
<br>
+ibm/collective/intercomm/alltoall_inter
<br>
+ibm/collective/intercomm/alltoallv_inter
<br>
+ibm/collective/intercomm/alltoallw_inter
<br>
+ibm/collective/intercomm/barrier_inter
<br>
+ibm/collective/intercomm/bcast_inter
<br>
+ibm/collective/intercomm/gather_inter
<br>
+ibm/collective/intercomm/reduce_inter
<br>
+ibm/collective/intercomm/reduce_scatter_inter
<br>
+ibm/collective/intercomm/reduce_scatter_inter2
<br>
+ibm/collective/intercomm/scatter_inter
<br>
+ibm/collective/intercomm/scatterv_inter
<br>
+ibm/collective/intercomm/allgatherv_inter
<br>
+ibm/collective/intercomm/gatherv_inter
<br>
+ibm/collective/intercomm/iallgather_inter
<br>
+ibm/collective/intercomm/iallgatherv_inter
<br>
+ibm/collective/intercomm/iallreduce_inter
<br>
+ibm/collective/intercomm/ialltoall_inter
<br>
+ibm/collective/intercomm/ialltoallv_inter
<br>
+ibm/collective/intercomm/ialltoallw_inter
<br>
+ibm/collective/intercomm/ibarrier_inter
<br>
+ibm/collective/intercomm/ibcast_inter
<br>
+ibm/collective/intercomm/igather_inter
<br>
+ibm/collective/intercomm/igatherv_inter
<br>
+ibm/collective/intercomm/ireduce_inter
<br>
+ibm/collective/intercomm/ireduce_scatter_inter
<br>
+ibm/collective/intercomm/iscatter_inter
<br>
+ibm/collective/intercomm/iscatterv_inter
<br>
+ibm/collective/intercomm/*.log
<br>
+ibm/collective/intercomm/*.trs
<br>
+ibm/collective/self/*.trs
<br>
+ibm/collective/self/*.log
<br>
+ibm/collective/self/allgather
<br>
+ibm/collective/self/allgather_in_place
<br>
+ibm/collective/self/allgatherv
<br>
+ibm/collective/self/allgatherv_in_place
<br>
+ibm/collective/self/allreduce
<br>
+ibm/collective/self/allreduce_in_place
<br>
+ibm/collective/self/alltoall
<br>
+ibm/collective/self/alltoall_in_place
<br>
+ibm/collective/self/alltoallw
<br>
+ibm/collective/self/alltoallw_in_place
<br>
+ibm/collective/self/iallgather
<br>
+ibm/collective/self/iallgather_in_place
<br>
+ibm/collective/self/iallgatherv
<br>
+ibm/collective/self/iallgatherv_in_place
<br>
+ibm/collective/self/iallreduce
<br>
+ibm/collective/self/iallreduce_in_place
<br>
+ibm/collective/self/ialltoall
<br>
+ibm/collective/self/barrier
<br>
+ibm/collective/self/bcast
<br>
+ibm/collective/self/bcast_f08
<br>
+ibm/collective/self/bcast_struct
<br>
+ibm/collective/self/barrier
<br>
+ibm/collective/self/ibarrier
<br>
+ibm/collective/self/ibarrier_f
<br>
+ibm/collective/self/ibarrier_f08
<br>
+ibm/collective/self/ibarrier_f90
<br>
+ibm/collective/self/ibcast
<br>
+ibm/collective/self/ibcast_f
<br>
+ibm/collective/self/ibcast_f08
<br>
+ibm/collective/self/ibcast_f90
<br>
+ibm/collective/self/ibcast_struct
<br>
+ibm/communicator/attr
<br>
+ibm/communicator/comm_attr
<br>
+ibm/communicator/comm-self-attr-delete
<br>
+ibm/communicator/commdup
<br>
+ibm/communicator/commfree
<br>
+ibm/communicator/compare
<br>
+ibm/communicator/intercomm
<br>
+ibm/communicator/mpisplit
<br>
+ibm/communicator/self_atexit
<br>
+ibm/communicator/comm_get_name_cxx
<br>
+ibm/communicator/*.log
<br>
+ibm/communicator/*.trs
<br>
+ibm/communicator/attrsetget_mpifh
<br>
+ibm/communicator/attrsetget_usempi
<br>
+ibm/communicator/attrsetget_usempif08
<br>
+ibm/communicator/comm_dup_f
<br>
+ibm/communicator/libattrsetget.a
<br>
+ibm/communicator/comm_split_f
<br>
+ibm/communicator/comm_split_type
<br>
+ibm/communicator/multithreaded-get-set-attribute
<br>
+ibm/communicator/comm_idup
<br>
+ibm/communicator/comm_idup_mpifh
<br>
+ibm/communicator/comm_idup_usempi
<br>
+ibm/communicator/comm_idup_usempif08
<br>
+ibm/communicator/commdup_mpifh
<br>
+ibm/communicator/commdup_usempi
<br>
+ibm/communicator/commdup_usempif08
<br>
+ibm/communicator/commdup_with_info_mpifh
<br>
+ibm/communicator/commdup_with_info_usempi
<br>
+ibm/communicator/commdup_with_info_usempif08
<br>
+ibm/communicator/create_group
<br>
+ibm/communicator/create_group_mpifh
<br>
+ibm/communicator/create_group_usempi
<br>
+ibm/communicator/create_group_usempif08
<br>
+ibm/config/config.guess
<br>
+ibm/config/config.sub
<br>
+ibm/config/install-sh
<br>
+ibm/config/missing
<br>
+ibm/config/mkinstalldirs
<br>
+ibm/config/runtests.sh
<br>
+ibm/config/depcomp
<br>
+ibm/config/ltmain.sh
<br>
+ibm/config/ar-lib
<br>
+ibm/config/libtool.m4
<br>
+ibm/config/lt~obsolete.m4
<br>
+ibm/config/ltsugar.m4
<br>
+ibm/config/ltversion.m4
<br>
+ibm/config/ltoptions.m4
<br>
+ibm/config/test-driver
<br>
+ibm/datatype/bakstr
<br>
+ibm/datatype/bottom
<br>
+ibm/datatype/hindexed_block
<br>
+ibm/datatype/getel
<br>
+ibm/datatype/idx_null
<br>
+ibm/datatype/lbub
<br>
+ibm/datatype/lbub2
<br>
+ibm/datatype/loop
<br>
+ibm/datatype/nested-ddt
<br>
+ibm/datatype/paktest
<br>
+ibm/datatype/pptransp
<br>
+ibm/datatype/strangest1
<br>
+ibm/datatype/structsr
<br>
+ibm/datatype/structsr2
<br>
+ibm/datatype/transp
<br>
+ibm/datatype/transpa
<br>
+ibm/datatype/transp2
<br>
+ibm/datatype/transp3
<br>
+ibm/datatype/type_attr
<br>
+ibm/datatype/type_create_resized
<br>
+ibm/datatype/zero1
<br>
+ibm/datatype/zero2
<br>
+ibm/datatype/zero3
<br>
+ibm/datatype/zero5
<br>
+ibm/datatype/zero6
<br>
+ibm/datatype/datatype_cxx
<br>
+ibm/datatype/zeroblock
<br>
+ibm/datatype/fint2_f
<br>
+ibm/datatype/fint4_f
<br>
+ibm/datatype/fint8_f
<br>
+ibm/datatype/freal4_f
<br>
+ibm/datatype/freal8_f
<br>
+ibm/datatype/freal16_f
<br>
+ibm/datatype/*.log
<br>
+ibm/datatype/*.trs
<br>
+ibm/datatype/getel_x
<br>
+ibm/datatype/type_size_x
<br>
+ibm/dist-graph/*.log
<br>
+ibm/dist-graph/*.trs
<br>
+ibm/dist-graph/distgraph_test_1
<br>
+ibm/dist-graph/distgraph_test_2
<br>
+ibm/dist-graph/distgraph_test_3
<br>
+ibm/dist-graph/distgraph_test_4
<br>
+ibm/dynamic/spawn
<br>
+ibm/dynamic/spawn_with_env_vars
<br>
+ibm/dynamic/spawn_multiple
<br>
+ibm/dynamic/client_server
<br>
+ibm/dynamic/comm_join
<br>
+ibm/dynamic/loop_spawn
<br>
+ibm/dynamic/loop_child
<br>
+ibm/dynamic/no-disconnect
<br>
+ibm/dynamic/intercomm_create
<br>
+ibm/dynamic/*.log
<br>
+ibm/dynamic/*.trs
<br>
+ibm/environment/abort
<br>
+ibm/environment/attrs
<br>
+ibm/environment/err
<br>
+ibm/environment/final
<br>
+ibm/environment/finalized
<br>
+ibm/environment/init_thread
<br>
+ibm/environment/init_thread_funneled
<br>
+ibm/environment/init_thread_serialized
<br>
+ibm/environment/init_thread_multiple
<br>
+ibm/environment/initialized
<br>
+ibm/environment/is_thr_main
<br>
+ibm/environment/is_thr_main_mt
<br>
+ibm/environment/pcontrol
<br>
+ibm/environment/procname
<br>
+ibm/environment/query_thread
<br>
+ibm/environment/wtime
<br>
+ibm/environment/init_thread_cxx
<br>
+ibm/environment/is_thr_main_cxx
<br>
+ibm/environment/query_thread_cxx
<br>
+ibm/environment/*.log
<br>
+ibm/environment/*.trs
<br>
+ibm/group/compare
<br>
+ibm/group/group
<br>
+ibm/group/groupfree
<br>
+ibm/group/range
<br>
+ibm/group/*.log
<br>
+ibm/group/*.trs
<br>
+ibm/info/*.log
<br>
+ibm/info/*.trs
<br>
+ibm/info/00_create
<br>
+ibm/info/00_create_cxx
<br>
+ibm/info/10_set
<br>
+ibm/info/10_set_cxx
<br>
+ibm/info/20_delete
<br>
+ibm/info/20_delete_cxx
<br>
+ibm/info/30_get
<br>
+ibm/info/30_get_cxx
<br>
+ibm/info/40_getvaluelen
<br>
+ibm/info/40_getvaluelen_cxx
<br>
+ibm/info/50_getnkeys
<br>
+ibm/info/50_getnkeys_cxx
<br>
+ibm/info/60_info_env
<br>
+ibm/info/60_info_env_mpifh
<br>
+ibm/info/60_info_env_usempi
<br>
+ibm/info/60_info_env_usempif08
<br>
+ibm/info/comm_get_info
<br>
+ibm/info/comm_get_info_mpifh
<br>
+ibm/info/comm_get_info_usempi
<br>
+ibm/info/comm_get_info_usempif08
<br>
+ibm/info/comm_set_info
<br>
+ibm/info/comm_set_info_mpifh
<br>
+ibm/info/comm_set_info_usempi
<br>
+ibm/info/comm_set_info_usempif08
<br>
+ibm/io/*.log
<br>
+ibm/io/*.trs
<br>
+ibm/io/file_status_get_count
<br>
+ibm/io/file_status_get_count_f
<br>
+ibm/io/file_status_get_count_f08
<br>
+ibm/io/file_status_get_count_f90
<br>
+ibm/io/open_close
<br>
+ibm/io/open_close_mpifh
<br>
+ibm/io/open_close_usempi
<br>
+ibm/io/open_close_usempif08
<br>
+ibm/io/test.dat
<br>
+ibm/onesided/*.log
<br>
+ibm/onesided/*.trs
<br>
+ibm/onesided/c_create_info
<br>
+ibm/onesided/c_win_attr
<br>
+ibm/onesided/c_create
<br>
+ibm/onesided/c_lock_illegal
<br>
+ibm/onesided/c_fence_asserts
<br>
+ibm/onesided/c_fence_simple
<br>
+ibm/onesided/c_get
<br>
+ibm/onesided/c_get_big
<br>
+ibm/onesided/c_fence_put_1
<br>
+ibm/onesided/c_put
<br>
+ibm/onesided/c_put_big
<br>
+ibm/onesided/c_accumulate
<br>
+ibm/onesided/c_win_errhandler
<br>
+ibm/onesided/cxx_create
<br>
+ibm/onesided/c_create_disp
<br>
+ibm/onesided/cxx_create_info_half
<br>
+ibm/onesided/.gdb_history
<br>
+ibm/onesided/c_create_size
<br>
+ibm/onesided/c_accumulate_atomic
<br>
+ibm/onesided/cxx_create_info
<br>
+ibm/onesided/c_create_no_free
<br>
+ibm/onesided/cxx_create_disp
<br>
+ibm/onesided/cxx_win_attr
<br>
+ibm/onesided/cxx_get_group
<br>
+ibm/onesided/cxx_create_size
<br>
+ibm/onesided/cxx_simple_lock
<br>
+ibm/onesided/cxx_fence
<br>
+ibm/onesided/c_create_info_half
<br>
+ibm/onesided/cxx_simple_test
<br>
+ibm/onesided/cxx_win_name
<br>
+ibm/onesided/cxx_fence_get
<br>
+ibm/onesided/cxx_call_errhandler
<br>
+ibm/onesided/cxx_alloc
<br>
+ibm/onesided/ring_1sided_mpifh
<br>
+ibm/onesided/ring_1sided_sync_reg_mpifh
<br>
+ibm/onesided/ring_1sided_sync_reg_usempi
<br>
+ibm/onesided/ring_1sided_usempi
<br>
+ibm/onesided/ring_1sided_usempif08
<br>
+ibm/onesided/halo_1sided_put_alloc_mem_usempi
<br>
+ibm/onesided/halo_1sided_put_alloc_mem_usempif08
<br>
+ibm/onesided/c_fetch_and_op
<br>
+ibm/onesided/c_flush
<br>
+ibm/onesided/c_get_accumulate
<br>
+ibm/onesided/c_reqops
<br>
+ibm/onesided/c_win_shared
<br>
+ibm/onesided/c_win_shared_noncontig
<br>
+ibm/onesided/c_win_shared_noncontig_put
<br>
+ibm/onesided/c_fence_lock
<br>
+ibm/onesided/c_strided_acc_indexed
<br>
+ibm/onesided/c_strided_acc_onelock
<br>
+ibm/onesided/c_strided_acc_subarray
<br>
+ibm/onesided/c_strided_get_indexed
<br>
+ibm/onesided/c_strided_getacc_indexed
<br>
+ibm/onesided/c_strided_getacc_indexed_shared
<br>
+ibm/onesided/c_strided_putget_indexed
<br>
+ibm/onesided/c_strided_putget_indexed_shared
<br>
+ibm/onesided/c_transpose1
<br>
+ibm/onesided/c_transpose2
<br>
+ibm/onesided/c_transpose3
<br>
+ibm/onesided/c_transpose5
<br>
+ibm/onesided/c_transpose6
<br>
+ibm/onesided/c_transpose7
<br>
+ibm/onesided/win_allocate_shared
<br>
+ibm/onesided/win_allocate_shared_mpifh
<br>
+ibm/onesided/win_allocate_shared_usempi
<br>
+ibm/onesided/win_allocate_shared_usempif08
<br>
+ibm/onesided/win_allocate_shared2_mpifh
<br>
+ibm/onesided/win_allocate_shared2_usempi
<br>
+ibm/onesided/win_allocate_shared2_usempif08
<br>
+ibm/pt2pt/allocmem
<br>
+ibm/pt2pt/bsend
<br>
+ibm/pt2pt/bsend_free
<br>
+ibm/pt2pt/buffer
<br>
+ibm/pt2pt/free
<br>
+ibm/pt2pt/getcount
<br>
+ibm/pt2pt/interf
<br>
+ibm/pt2pt/iprobe
<br>
+ibm/pt2pt/isend
<br>
+ibm/pt2pt/probe
<br>
+ibm/pt2pt/rsend
<br>
+ibm/pt2pt/rsend2
<br>
+ibm/pt2pt/send
<br>
+ibm/pt2pt/send2
<br>
+ibm/pt2pt/sendrecv
<br>
+ibm/pt2pt/sendrecv_f
<br>
+ibm/pt2pt/sendrecv_rep
<br>
+ibm/pt2pt/seq
<br>
+ibm/pt2pt/ssend
<br>
+ibm/pt2pt/start
<br>
+ibm/pt2pt/startall
<br>
+ibm/pt2pt/test1
<br>
+ibm/pt2pt/test2
<br>
+ibm/pt2pt/test3
<br>
+ibm/pt2pt/testall
<br>
+ibm/pt2pt/testany
<br>
+ibm/pt2pt/testsome
<br>
+ibm/pt2pt/test_recv_init_null
<br>
+ibm/pt2pt/waitall
<br>
+ibm/pt2pt/waitany
<br>
+ibm/pt2pt/waitnull
<br>
+ibm/pt2pt/waitsome
<br>
+ibm/pt2pt/wildcard
<br>
+ibm/pt2pt/*.log
<br>
+ibm/pt2pt/*.trs
<br>
+ibm/pt2pt/mprobe
<br>
+ibm/pt2pt/mprobe_mpifh
<br>
+ibm/pt2pt/mprobe_usempi
<br>
+ibm/pt2pt/mprobe_usempif08
<br>
+ibm/pt2pt/mprobe-mpich
<br>
+ibm/pt2pt/improbe
<br>
+ibm/pt2pt/improbe_mpifh
<br>
+ibm/pt2pt/improbe_usempi
<br>
+ibm/pt2pt/improbe_usempif08
<br>
+ibm/pt2pt/testall_mpifh
<br>
+ibm/pt2pt/testall_usempi
<br>
+ibm/pt2pt/testall_usempif08
<br>
+ibm/pt2pt/testsome_mpifh
<br>
+ibm/pt2pt/testsome_usempi
<br>
+ibm/pt2pt/testsome_usempif08
<br>
+ibm/pt2pt/waitall_usempif08
<br>
+ibm/pt2pt/waitall_mpifh
<br>
+ibm/pt2pt/waitall_usempi
<br>
+ibm/pt2pt/waitsome_usempif08
<br>
+ibm/pt2pt/waitsome_mpifh
<br>
+ibm/pt2pt/waitsome_usempi
<br>
+ibm/pt2pt/allocmem_usempi
<br>
+ibm/pt2pt/allocmem_usempif08
<br>
+ibm/random/add_error_class
<br>
+ibm/random/alloc-mem
<br>
+ibm/random/attr-error-code
<br>
+ibm/random/ring_mmap
<br>
+ibm/random/ticket-1944-bcast-loop
<br>
+ibm/random/ticket-1944-test4
<br>
+ibm/random/ticket-1984-littlehang
<br>
+ibm/random/ticket-2014-basic-send-recv
<br>
+ibm/random/ticket-4507-reduce-scatter-comm
<br>
+ibm/random/reduce_local
<br>
+ibm/random/reduce_local_cxx
<br>
+ibm/random/reduce_local_f
<br>
+ibm/random/reduce_local_f90
<br>
+ibm/random/reduce_local_f08
<br>
+ibm/random/op_commutative
<br>
+ibm/random/op_commutative_cxx
<br>
+ibm/random/op_commutative_mpifh
<br>
+ibm/random/op_commutative_usempi
<br>
+ibm/random/op_commutative_usempif08
<br>
+ibm/random/mpi_peruse
<br>
+ibm/random/ompi-affinity-str
<br>
+ibm/random/*.mod
<br>
+ibm/random/*.log
<br>
+ibm/random/*.trs
<br>
+ibm/random/f_sync_reg_f08
<br>
+ibm/random/f_sync_reg_f
<br>
+ibm/random/f_sync_reg_f90
<br>
+ibm/random/handle_check_f08
<br>
+ibm/random/ticket-3956-datatype-leak
<br>
+ibm/random/ring_c
<br>
+ibm/random/ring_cxx
<br>
+ibm/random/ring_mpifh
<br>
+ibm/random/ring_usempi
<br>
+ibm/random/ring_usempif08
<br>
+ibm/random/geterrstr
<br>
+ibm/random/geterrstr_mpifh
<br>
+ibm/random/geterrstr_usempi
<br>
+ibm/random/geterrstr_usempif08
<br>
+ibm/random/many_to_one
<br>
+ibm/reporting/ompitest_config.h
<br>
+ibm/reporting/ompitest_config.h.in
<br>
+ibm/reporting/stamp-h
<br>
+ibm/reporting/stamp-h.in
<br>
+ibm/reporting/stamp-h1
<br>
+ibm/topology/cart
<br>
+ibm/topology/cart_map
<br>
+ibm/topology/cart_sub_zero
<br>
+ibm/topology/dimscreate
<br>
+ibm/topology/distgraph1
<br>
+ibm/topology/graph
<br>
+ibm/topology/sub
<br>
+ibm/topology/sub2
<br>
+ibm/topology/*.log
<br>
+ibm/topology/*.trs
<br>
+
<br>
+imb/src/IMB-EXT
<br>
+imb/src/IMB-MPI1
<br>
+imb/src/IMB-IO
<br>
+imb/src/exe_io
<br>
+imb/src/exe_ext
<br>
+imb/src/exe_mpi1
<br>
+
<br>
+intel_tests/src/*_c
<br>
+intel_tests/src/*_f
<br>
+
<br>
+iof/c_interactive
<br>
+iof/c_abort
<br>
+iof/c_hello
<br>
+iof/c_read_write
<br>
+iof/f77_interactive
<br>
+iof/f77_abort
<br>
+iof/f77_hello
<br>
+iof/f77_read_write
<br>
+iof/f90_interactive
<br>
+iof/f90_abort
<br>
+iof/f90_hello
<br>
+iof/f90_read_write
<br>
+iof/mpi.mod
<br>
+iof/data-*
<br>
+
<br>
+iu/ft/correctness/inflight
<br>
+iu/ft/correctness/progress
<br>
+iu/ft/correctness/quiet
<br>
+iu/ft/correctness/simple
<br>
+iu/ft/correctness/noop
<br>
+iu/ft/mgr-worker/mgr
<br>
+iu/ft/mgr-worker/worker
<br>
+iu/ft/perf/quiet
<br>
+iu/ft/perf/ring
<br>
+iu/ft/perf/noop
<br>
+iu/ft/perf/*.log
<br>
+iu/ft/perf/core.*
<br>
+iu/ft/perf/.archive
<br>
+iu/ft/perf/slurm-*
<br>
+iu/mtt/sif/etc/general/*-priv
<br>
+
<br>
+jeff-sun/t_size2
<br>
+jeff-sun/t_greqs
<br>
+jeff-sun/t_greqsf
<br>
+jeff-sun/t_commattrbugf
<br>
+jeff-sun/t_lookupname2
<br>
+jeff-sun/attr1
<br>
+jeff-sun/attr2
<br>
+jeff-sun/t_istruncate
<br>
+jeff-sun/att1-revised
<br>
+jeff-sun/t_typedup
<br>
+jeff-sun/mpi-handle-debug/simple
<br>
+jeff-sun/mpi-handle-debug/comm_test
<br>
+jeff-sun/mpi-handle-debug/comm_test_cxx
<br>
+jeff-sun/mpi-handle-debug/comm_test_f77
<br>
+
<br>
+latency/configure
<br>
+latency/config.log
<br>
+latency/config.status
<br>
+latency/Makefile.defs
<br>
+latency/autom4te.cache
<br>
+latency/include/lat_sys.h
<br>
+latency/include/latconfig.h
<br>
+
<br>
+llnl/IOR-2.9.0/src/C/IOR
<br>
+llnl/mdtest-1.7.1/mdtest
<br>
+llnl/simul-1.12/simul
<br>
+
<br>
+logp_mpi-1.4/logp_test
<br>
+logp_mpi-1.4/liblogp.a
<br>
+
<br>
+mellanox/IntelMPITEST-1.0/configure
<br>
+mellanox/IntelMPITEST-1.0/config.log
<br>
+mellanox/IntelMPITEST-1.0/config.status
<br>
+mellanox/IntelMPITEST-1.0/autom4te.cache
<br>
+mellanox/IntelMPITEST-1.0/Test/f90
<br>
+mellanox/IntelMPITEST-1.0/Test/testlist*_f90
<br>
+mellanox/IntelMPITEST-1.0/Test/summary.xml
<br>
+mellanox/IntelMPITEST-1.0/bin/f77tof90
<br>
+mellanox/IntelMPITEST-1.0/bin/Makefile.F.main
<br>
+mellanox/IntelMPITEST-1.0/bin/Makefile.F90.main
<br>
+mellanox/IntelMPITEST-1.0/bin/Makefile.c.main
<br>
+mellanox/IntelMPITEST-1.0/bin/Makefile.main
<br>
+mellanox/IntelMPITEST-1.0/bin/Makefile.master
<br>
+mellanox/IntelMPITEST-1.0/bin/mtest
<br>
+mellanox/IntelMPITEST-1.0/bin/mpitest
<br>
+mellanox/IntelMPITEST-1.0/bin/startjob.*
<br>
+mellanox/IntelMPITEST-1.0/include/f90options.h
<br>
+mellanox/IntelMPITEST-1.0/include/mpitest_cfgf90.h
<br>
+mellanox/IntelMPITEST-1.0/include/mpitestf90.h
<br>
+mellanox/IntelMPITEST-1.0/include/externalf90.h
<br>
+mellanox/IntelMPITEST-1.0/include/foptions.h
<br>
+mellanox/IntelMPITEST-1.0/lib/*.log
<br>
+mellanox/IntelMPITEST-1.0/lib/work.pcl
<br>
+mellanox/IntelMPITEST-1.0/lib/work.pc
<br>
+
<br>
+mpi2basic_tests/dyncomm/dyncomm_spawn_mult_son1
<br>
+mpi2basic_tests/dyncomm/dyncomm_spawn_mult_son2
<br>
+mpi2basic_tests/dyncomm/dyncomm_spawn_son
<br>
+mpi2basic_tests/dyncomm/dyncomm_spawn_father
<br>
+mpi2basic_tests/dyncomm/dyncomm_spawn_mult_father
<br>
+
<br>
+mpi_test_suite/.directory
<br>
+mpi_test_suite/aclocal.m4
<br>
+mpi_test_suite/autom4te.cache
<br>
+mpi_test_suite/configure
<br>
+mpi_test_suite/config.h
<br>
+mpi_test_suite/config.h.in
<br>
+mpi_test_suite/config.log
<br>
+mpi_test_suite/config.status
<br>
+mpi_test_suite/mpi_test_suite
<br>
+
<br>
+nbcbench/nbcbench
<br>
+nbcbench/NBCBench-0.9.2/config.log
<br>
+nbcbench/NBCBench-0.9.2/config.status
<br>
+nbcbench/NBCBench-0.9.2/stamp-h1
<br>
+nbcbench/NBCBench-0.9.2/nbcbench
<br>
+nbcbench/NBCBench-0.9.2/autom4te.cache
<br>
+nbcbench/NBCBench-0.9.2/libtool
<br>
+nbcbench/NBCBench-0.9.2/aclocal.m4
<br>
+nbcbench/libnbc-0.8.2/libnbc.a
<br>
+
<br>
+occ/Decision/*_ompi
<br>
+occ/Tests/*_ompi
<br>
+occ/bin/*_ompi
<br>
+occ/doc/*.aux
<br>
+occ/doc/*.bbl
<br>
+occ/doc/*.blg
<br>
+occ/doc/*.log
<br>
+occ/doc/*.idx
<br>
+occ/doc/*.toc
<br>
+
<br>
+ompi-java-tests/configure
<br>
+ompi-java-tests/config.log
<br>
+ompi-java-tests/config.status
<br>
+ompi-java-tests/autom4te.cache
<br>
+ompi-java-tests/config
<br>
+ompi-java-tests/aclocal.m4
<br>
+ompi-java-tests/reporting/OmpitestConfig.java
<br>
+
<br>
+onesided/configure
<br>
+onesided/config.status
<br>
+onesided/config.log
<br>
+onesided/config.guess
<br>
+onesided/config.sub
<br>
+onesided/aclocal.m4
<br>
+onesided/onesided_config.h
<br>
+onesided/onesided_config.h.in
<br>
+onesided/autom4te.cache
<br>
+onesided/missing
<br>
+onesided/depcomp
<br>
+onesided/install-sh
<br>
+onesided/ar-lib
<br>
+onesided/stamp-h1
<br>
+onesided/test_cs1
<br>
+onesided/test_put1
<br>
+onesided/t_winerror
<br>
+onesided/test_put4
<br>
+onesided/test_put5
<br>
+onesided/test_put6
<br>
+onesided/test_get1
<br>
+onesided/test_get2
<br>
+onesided/test_wincreate1
<br>
+onesided/test_get3
<br>
+onesided/test_acc1
<br>
+onesided/test_acc2
<br>
+onesided/test_acc3
<br>
+onesided/test_um_lock1
<br>
+onesided/test_start1
<br>
+onesided/test_start2
<br>
+onesided/test_cl1
<br>
+onesided/test_start3
<br>
+onesided/test_cl2
<br>
+onesided/test_um_mixed_put1
<br>
+onesided/t_win
<br>
+onesided/test_dan1
<br>
+onesided/t_winf
<br>
+onesided/t_f2c_c2f
<br>
+onesided/test_mt_put1
<br>
+onesided/test_mwin1
<br>
+onesided/t_winself
<br>
+onesided/t_winattrs
<br>
+onesided/test_lock1
<br>
+onesided/test_lock2
<br>
+onesided/test_lock3
<br>
+onesided/test_lock4
<br>
+onesided/test_lock5
<br>
+onesided/test_um_put1
<br>
+onesided/test_rma1
<br>
+onesided/tests
<br>
+onesided/t
<br>
+onesided/t_winattrsf
<br>
+onesided/test-driver
<br>
+
<br>
+openshmem-release-1.0d/examples/*.x
<br>
+openshmem-release-1.0d/feature_tests/C/*.x
<br>
+openshmem-release-1.0d/feature_tests/Fortran/accessibility/*.x
<br>
+openshmem-release-1.0d/feature_tests/Fortran/alloc/*.x
<br>
+openshmem-release-1.0d/feature_tests/Fortran/atomic/*.x
<br>
+openshmem-release-1.0d/feature_tests/Fortran/barrier/*.x
<br>
+openshmem-release-1.0d/feature_tests/Fortran/broadcast/*.x
<br>
+openshmem-release-1.0d/feature_tests/Fortran/collect/*.x
<br>
+openshmem-release-1.0d/feature_tests/Fortran/reductions/*.x
<br>
+openshmem-release-1.0d/feature_tests/Fortran/transfer/*.x
<br>
+openshmem-release-1.0d/performance_tests/micro_benchmarks/*.x
<br>
+
<br>
+orte/mpi_abort_0_last_c
<br>
+orte/mpi_read_stdin_c
<br>
+orte/mpi_abort_0_first_c
<br>
+orte/mpi_hostname_c
<br>
+orte/mpi_abort_all_c
<br>
+orte/fail/mpi_abort_0_first
<br>
+orte/fail/mpi_abort_0_last
<br>
+orte/fail/mpi_abort_all
<br>
+orte/fail/mpi_false
<br>
+orte/fail/mpi_segv
<br>
+orte/fail/mpi_exit77
<br>
+orte/pass/mpi_hostname
<br>
+orte/pass/mpi_noop
<br>
+orte/pass/mpi_sleep2
<br>
+orte/pass/mpi_sleep5
<br>
+
<br>
+osu/aclocal.m4
<br>
+osu/install-sh
<br>
+osu/config.status
<br>
+osu/config.log
<br>
+osu/depcomp
<br>
+osu/missing
<br>
+osu/configure
<br>
+osu/autom4te.cache
<br>
+osu/osu_reduce_scatter
<br>
+osu/osu_allreduce
<br>
+osu/osu_mbw_mr
<br>
+osu/osu_passive_get_latency
<br>
+osu/osu_alltoallv
<br>
+osu/osu_allgather
<br>
+osu/osu_passive_acc_latency
<br>
+osu/osu_gatherv
<br>
+osu/osu_scatterv
<br>
+osu/osu_latency_mt
<br>
+osu/osu_passive_put_latency
<br>
+osu/osu_passive_put_bw
<br>
+osu/osu_alltoall
<br>
+osu/osu_barrier
<br>
+osu/osu_allgatherv
<br>
+osu/osu_scatter
<br>
+osu/osu_passive_get_bw
<br>
+osu/osu_reduce
<br>
+osu/osu_multi_lat
<br>
+osu/osu_gather
<br>
+osu/osu_bcast
<br>
+osu/osu_acc_latency
<br>
+osu/osu_put_bw
<br>
+osu/osu_bw
<br>
+osu/osu_put_latency
<br>
+osu/osu_latency
<br>
+osu/osu_get_bw
<br>
+osu/osu_put_bibw
<br>
+osu/osu_bibw
<br>
+osu/osu_get_latency
<br>
+
<br>
+presta1.2/rma
<br>
+presta1.2/globalop
<br>
+presta1.2/laten
<br>
+presta1.2/allred
<br>
+presta1.2/com
<br>
+
<br>
+sandia/mpi_routecheck
<br>
+sandia/mt_send_recv
<br>
+
<br>
+simple/attr/configure
<br>
+simple/attr/aclocal.m4
<br>
+simple/attr/config.log
<br>
+simple/attr/config.status
<br>
+simple/attr/autom4te.cache
<br>
+simple/attr/attr_mpifh.f90
<br>
+simple/attr/attr_usempi.f90
<br>
+simple/attr/attr_usempif08.f90
<br>
+simple/attr/attr_mpifh
<br>
+simple/attr/attr_usempi
<br>
+simple/attr/attr_usempif08
<br>
+simple/attr/config/depcomp
<br>
+simple/attr/config/install-sh
<br>
+simple/attr/config/missing
<br>
+simple/basic/c/abort
<br>
+simple/basic/c/ring
<br>
+simple/basic/c/pack
<br>
+simple/basic/c/hello
<br>
+simple/basic/c/hello_null
<br>
+simple/basic/c/comm
<br>
+simple/basic/c/file_open
<br>
+simple/basic/c/type_struct
<br>
+simple/basic/c/no_op
<br>
+simple/basic/c/mpi_no_op
<br>
+simple/basic/c/grequest
<br>
+simple/basic/c/request_errors
<br>
+simple/basic/c/register_datarep
<br>
+simple/basic/c/reduce_local
<br>
+simple/basic/cxx/hello
<br>
+simple/basic/cxx/hello_null
<br>
+simple/basic/cxx/cxx_reduce
<br>
+simple/basic/cxx/grequest
<br>
+simple/basic/cxx/register_datarep
<br>
+simple/basic/cxx/reduce_local
<br>
+simple/basic/f77/hello
<br>
+simple/basic/f77/ring
<br>
+simple/basic/f77/ring_ignore
<br>
+simple/basic/f77/comm_name
<br>
+simple/basic/f77/register_datarep
<br>
+simple/basic/f77/ring_nonblocking
<br>
+simple/basic/f77/test_constants
<br>
+simple/basic/f77/reduce_local
<br>
+simple/basic/f90/ring
<br>
+simple/basic/f90/ring_ignore
<br>
+simple/basic/f90/hello
<br>
+simple/basic/f90/spawn
<br>
+simple/basic/f90/attr_f
<br>
+simple/basic/f90/statuses_ignore
<br>
+simple/basic/f90/gather
<br>
+simple/basic/f90/wtime
<br>
+simple/basic/f90/register_datarep
<br>
+simple/basic/f90/reduce_local
<br>
+simple/collective/allgather
<br>
+simple/collective/allgatherv
<br>
+simple/collective/allreduce
<br>
+simple/collective/alltoall
<br>
+simple/collective/alltoallw
<br>
+simple/collective/barrier
<br>
+simple/collective/bcast
<br>
+simple/collective/bcast_struct
<br>
+simple/collective/exscan
<br>
+simple/collective/gather
<br>
+simple/collective/gatherv
<br>
+simple/collective/op
<br>
+simple/collective/reduce
<br>
+simple/collective/reduce_scatter
<br>
+simple/collective/scan
<br>
+simple/collective/scatter
<br>
+simple/collective/struct_gatherv
<br>
+simple/errors/info_get_nthkey
<br>
+simple/errors/allgather-in-place
<br>
+simple/errors/scatter-in-place
<br>
+simple/errors/gather-in-place
<br>
+simple/file/file_open
<br>
+simple/file/file_iread
<br>
+simple/file/file_iwrite
<br>
+simple/file/multiwrite
<br>
+simple/file/romio
<br>
+simple/ping/mpi-ping
<br>
+simple/ping/mpi-ping-thread
<br>
+simple/ping/flood-gather
<br>
+simple/topology/graph_test
<br>
+simple/topology/cart_test
<br>
+
<br>
+sun/threads/mt_greqs
<br>
+sun/threads/mt_wincache
<br>
+sun/threads/mt_env
<br>
+sun/threads/mt_send
<br>
+sun/threads/mt_coll
<br>
+sun/threads/mt_group
<br>
+sun/threads/mt_rcvany
<br>
+sun/threads/mt_commcaching
<br>
+sun/threads/mt_sendrecv
<br>
+sun/threads/mt_start_compl
<br>
+sun/threads/mt_pt2pt2
<br>
+sun/threads/mt_misc
<br>
+sun/threads/mt_comm
<br>
+sun/threads/mt_win
<br>
+sun/threads/mt_f2c_c2f
<br>
+sun/threads/mt_send2
<br>
<p><p>-----------------------------------------------------------------------
<br>
<p>Summary of changes:
<br>
&nbsp;.gitignore | 935 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
<br>
&nbsp;1 file changed, 935 insertions(+)
<br>
&nbsp;create mode 100644 .gitignore
<br>
<p><p>hooks/post-receive
<br>
<pre>
-- 
open-mpi/ompi-tests
</pre>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="15850.php">Jeff Squyres (jsquyres): "Re: [OMPI devel] ompi-tests SVN repo has been moved to Github"</a>
<li><strong>Previous message:</strong> <a href="15848.php">Ralph Castain: "Re: [OMPI devel] ompi-tests SVN repo has been moved to Github"</a>
<!-- nextthread="start" -->
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
