<?php
$topdir = "../../..";
$title = "MPI_T_pvar_handle_alloc(3) man page (version 2.1.4)";
$meta_desc = "Open MPI v2.1.4 man page: MPI_T_PVAR_HANDLE_ALLOC(3)";

include_once("$topdir/doc/nav.inc");
include_once("$topdir/includes/header.inc");
?>
<p> <a href="../">&laquo; Return to documentation listing</a></p>
      <!-- manual page source format generated by PolyglotMan v3.2, -->
<!-- available at http://polyglotman.sourceforge.net/ -->

<body bgcolor='white'>
<a href='#toc'>Table of Contents</a><p>

<h2><a name='sect0' href='#toc0'>Name</a></h2>
<b>MPI_T_pvar_handle_alloc</b>, <b><a href="../man3/MPI_T_pvar_handle_free.3.php">MPI_T_pvar_handle_free</a></b> - Allocate/free
MPI performance variable handles
<h2><a name='sect1' href='#toc1'>Syntax</a></h2>

<h2><a name='sect2' href='#toc2'>C Syntax</a></h2>
<br>
<pre>#include &lt;mpi.h&gt;
int MPI_T_pvar_handle_alloc(int pvar_index, void *obj_handle,
                            MPI_T_pvar_handle *handle, int *count)
int <a href="../man3/MPI_T_pvar_handle_free.3.php">MPI_T_pvar_handle_free</a>(MPI_T_pvar_handle *handle)
DescriptionMPI_T_pvar_handle_alloc binds the performance variable specified
in pvar_index to the MPI object specified in obj_handle. If <a href="../man3/MPI_T_pvar_get_info.3.php">MPI_T_pvar_get_info</a>
returns MPI_T_BIND_NO_OBJECT as the binding for the variable the obj_handle
argument is ignored. The number of values represented by this performance
variable is returned in the count parameter.  <a href="../man3/MPI_T_pvar_handle_free.3.php">MPI_T_pvar_handle_free</a> frees
a handle allocated by MPI_T_pvar_handle_alloc and sets the handle argument
to MPI_T_PVAR_HANDLE_NULL.   ErrorsMPI_T_pvar_handle_alloc() will fail if:
[MPI_T_ERR_NOT_INITIALIZED] The MPI Tools interface not initialized [MPI_T_ERR_INVALID_INDEX]
The performance variable index is invalid [MPI_T_ERR_OUT_OF_HANDLES] No
more handles available <a href="../man3/MPI_T_pvar_handle_free.3.php">MPI_T_pvar_handle_free</a>() will fail if: [MPI_T_ERR_NOT_INITIALIZED]
The MPI Tools interface not initialized [MPI_T_ERR_INVALID_HANDLE] The
handle is invalid   See Also
<a href="../man3/MPI_T_pvar_get_info.3.php">MPI_T_pvar_get_info</a>

<p> <a href="../">&laquo; Return to documentation listing</a></p>
<?php
include_once("$topdir/includes/footer.inc");
