.\" Automatically generated by Pandoc 2.14.2
.\"
.TH "MPI_Graph_neighbors_count" "3" "" "2021-08-30" "Open MPI"
.hy
.SH Name
.PP
\f[C]MPI_Graph_neighbors_count\f[R] - Returns the number of neighbors of
a node associated with a graph topology.
.SH Syntax
.SS C Syntax
.IP
.nf
\f[C]
#include <mpi.h>

int MPI_Graph_neighbors_count(MPI_Comm comm, int rank,
    int *nneighbors)
\f[R]
.fi
.SS Fortran Syntax
.IP
.nf
\f[C]
USE MPI
! or the older form: INCLUDE \[aq]mpif.h\[aq]

MPI_GRAPH_NEIGHBORS_COUNT(COMM, RANK, NNEIGHBORS, IERROR)
    INTEGER COMM, RANK, NNEIGHBORS, IERROR
\f[R]
.fi
.SS Fortran 2008 Syntax
.IP
.nf
\f[C]
USE mpi_f08

MPI_Graph_neighbors_count(comm, rank, nneighbors, ierror)
    TYPE(MPI_Comm), INTENT(IN) :: comm
    INTEGER, INTENT(IN) :: rank
    INTEGER, INTENT(OUT) :: nneighbors
    INTEGER, OPTIONAL, INTENT(OUT) :: ierror
\f[R]
.fi
.SH Input Parameters
.IP \[bu] 2
\f[C]comm\f[R] : Communicator with graph topology (handle).
.IP \[bu] 2
\f[C]rank\f[R] : Rank of process in group of comm (integer).
.SH Output Parameters
.IP \[bu] 2
\f[C]nneighbors\f[R] : Number of neighbors of specified process
(integer).
.IP \[bu] 2
\f[C]IERROR\f[R] : Fortran only: Error status (integer).
.SH Description
.PP
\f[C]MPI_Graph_neighbors_count\f[R] and \f[C]MPI_Graph_neighbors\f[R]
provide adjacency information for a general, graph topology.
\f[C]MPI_Graph_neighbors_count\f[R] returns the number of neighbors for
the process signified by \f[C]rank\f[R].
.SH Errors
.PP
Almost all MPI routines return an error value; C routines as the value
of the function and Fortran routines in the last argument.
.PP
Before the error value is returned, the current MPI error handler is
called.
By default, this error handler aborts the MPI job, except for I/O
function errors.
The error handler may be changed with \f[C]MPI_Comm_set_errhandler\f[R];
the predefined error handler \f[C]MPI_ERRORS_RETURN\f[R] may be used to
cause error values to be returned.
Note that MPI does not guarantee that an MPI program can continue past
an error.
.SH See Also
.PP
\f[C]MPI_Graph_neighbors\f[R](3)
