<?php
$topdir = "../../..";
$title = "MPI_Comm_delete_attr(3) man page (version 5.0.0rc2)";
$meta_desc = "Open MPI v5.0.0rc2 man page: MPI_COMM_DELETE_ATTR(3)";

include_once("$topdir/doc/nav.inc");
include_once("$topdir/includes/header.inc");
?>
<p> <a href="../">&laquo; Return to documentation listing</a></p>
  <!-- manual page source format generated by PolyglotMan v3.2, -->
<!-- available at http://polyglotman.sourceforge.net/ -->

<body bgcolor='white'>
<a href='#toc'>Table of Contents</a><p>

<h2><a name='sect0' href='#toc0'>Name</a></h2>
<p>
C]MPI_Comm_delete_attrR] - Deletes attribute value associated with
a key.
<h2><a name='sect1' href='#toc1'>Syntax</a></h2>

<h3><a name='sect2' href='#toc2'>C Syntax</a></h3>
<br>
<pre>

</pre>
<h3><a name='sect3' href='#toc3'>C]#include &lt;mpi.h&gt;int MPI_Comm_delete_attr(MPI_Comm comm, int comm_keyval)R]Fortran
Syntax</a></h3>
<br>
<pre>

</pre>
<h3><a name='sect4' href='#toc4'>C]USE MPI! or the older form: INCLUDE [aq]mpif.h[aq]MPI_COMM_DELETE_ATTR(COMM,
COMM_KEYVAL, IERROR)    INTEGER COMM, COMM_KEYVAL, IERROR R]Fortran 2008
Syntax</a></h3>
<br>
<pre>

</pre>
<h3><a name='sect5' href='#toc5'>C]USE mpi_f08MPI_Comm_delete_attr(comm, comm_keyval, ierror)    TYPE(MPI_Comm),
INTENT(IN) :: comm    INTEGER, INTENT(IN) :: comm_keyval    INTEGER, OPTIONAL,
INTENT(OUT) :: ierrorR]Input/Output Parameter</a></h3>

<dl>

<dt>[bu]</dt>
<dd>C]commR] : Communicator
from which the attribute is deleted (handle). </dd>
</dl>

<h2><a name='sect6' href='#toc6'>Input Parameter</a></h2>

<dl>

<dt>[bu]</dt>
<dd>C]comm_keyvalR]
: Key value (integer). </dd>
</dl>

<h2><a name='sect7' href='#toc7'>Output Parameter</a></h2>

<dl>

<dt>[bu]</dt>
<dd>C]IERRORR] : Fortran only: Error
status (integer). </dd>
</dl>

<h2><a name='sect8' href='#toc8'>Description</a></h2>
<p>
C]MPI_Comm_delete_attrR] deletes an attribute
from cache by key. This function invokes the attribute delete function C]delete_fnR]
specified when the C]comm_keyvalR] was created. The call will fail if the
C]delete_fnR] function returns an error code other than C]MPI_SUCCESS.R]
Whenever a communicator is replicated using the function C]MPI_Comm_dupR],
all callback copy functions for attributes that are currently set are invoked
(in arbitrary order). Whenever a communicator is deleted using the function
C]MPI_Comm_freeR], all callback delete functions for attributes that are
currently set are invoked. This function is the same as C]MPI_Attr_deleteR]
but is needed to match the C]commR]unicator-specific functions introduced
in the MPI-2 standard. The use of C]MPI_Attr_deleteR] is deprecated.
<h2><a name='sect9' href='#toc9'>Notes</a></h2>
<p>
Note
that it is not defined by the MPI standard what happens if the C]delete_fnR]
callback invokes other MPI functions. In Open MPI, it is not valid for C]delete_fnR]
callbacks (or any of their children) to add or delete attributes on the
same object on which the C]delete_fnR] callback is being invoked.
<h2><a name='sect10' href='#toc10'>Errors</a></h2>
<p>
Almost
all MPI routines return an error value; C routines as the value of the
function and Fortran routines in the last argument. Before the error value
is returned, the current MPI error handler is called. By default, this error
handler aborts the MPI job, except for I/O function errors. The error handler
may be changed with C]MPI_Comm_set_errhandlerR]; the predefined error handler
C]MPI_ERRORS_RETURNR] may be used to cause error values to be returned.
Note that MPI does not guarantee that an MPI program can continue past
an error. <p>

<hr><p>
<a name='toc'><b>Table of Contents</b></a><p>
<ul>
<li><a name='toc0' href='#sect0'>Name</a></li>
<li><a name='toc1' href='#sect1'>Syntax</a></li>
<ul>
<li><a name='toc2' href='#sect2'>C Syntax</a></li>
<li><a name='toc3' href='#sect3'>C]#include <mpi.h>int MPI_Comm_delete_attr(MPI_Comm comm, int comm_keyval)R]Fortran Syntax</a></li>
<li><a name='toc4' href='#sect4'>C]USE MPI! or the older form: INCLUDE [aq]mpif.h[aq]MPI_COMM_DELETE_ATTR(COMM, COMM_KEYVAL, IERROR)    INTEGER COMM, COMM_KEYVAL, IERROR R]Fortran 2008 Syntax</a></li>
<li><a name='toc5' href='#sect5'>C]USE mpi_f08MPI_Comm_delete_attr(comm, comm_keyval, ierror)    TYPE(MPI_Comm), INTENT(IN) :: comm    INTEGER, INTENT(IN) :: comm_keyval    INTEGER, OPTIONAL, INTENT(OUT) :: ierrorR]Input/Output Parameter</a></li>
</ul>
<li><a name='toc6' href='#sect6'>Input Parameter</a></li>
<li><a name='toc7' href='#sect7'>Output Parameter</a></li>
<li><a name='toc8' href='#sect8'>Description</a></li>
<li><a name='toc9' href='#sect9'>Notes</a></li>
<li><a name='toc10' href='#sect10'>Errors</a></li>
</ul>


<p> <a href="../">&laquo; Return to documentation listing</a></p>
<?php
include_once("$topdir/includes/footer.inc");
