<?php
$topdir = "../../..";
$title = "MPI_Graph_get(3) man page (version 5.0.0rc2)";
$meta_desc = "Open MPI v5.0.0rc2 man page: MPI_GRAPH_GET(3)";

include_once("$topdir/doc/nav.inc");
include_once("$topdir/includes/header.inc");
?>
<p> <a href="../">&laquo; Return to documentation listing</a></p>
  <!-- manual page source format generated by PolyglotMan v3.2, -->
<!-- available at http://polyglotman.sourceforge.net/ -->

<body bgcolor='white'>
<a href='#toc'>Table of Contents</a><p>

<h2><a name='sect0' href='#toc0'>Name</a></h2>
<p>
C]MPI_Graph_getR] - Retrieves graph topology information associated
with a communicator.
<h2><a name='sect1' href='#toc1'>Syntax</a></h2>

<h3><a name='sect2' href='#toc2'>C Syntax</a></h3>
<br>
<pre>

</pre>
<h3><a name='sect3' href='#toc3'>C]#include &lt;mpi.h&gt;int MPI_Graph_get(MPI_Comm comm, int maxindex, int maxedges,
   int index[], int edges[])R]Fortran Syntax</a></h3>
<br>
<pre>

</pre>
<h3><a name='sect4' href='#toc4'>C]USE MPI! or the older form: INCLUDE [aq]mpif.h[aq]MPI_GRAPH_GET(COMM,
MAXINDEX, MAXEDGES, INDEX, EDGES, IERROR)    INTEGER COMM, MAXINDEX, MAXEDGES,
INDEX(*)    INTEGER EDGES(*), IERRORR]Fortran 2008 Syntax</a></h3>
<br>
<pre>

</pre>
<h2><a name='sect5' href='#toc5'>C]USE mpi_f08MPI_Graph_get(comm, maxindex, maxedges, index, edges, ierror)
   TYPE(MPI_Comm), INTENT(IN) :: comm    INTEGER, INTENT(IN) :: maxindex,
maxedges    INTEGER, INTENT(OUT) :: index(maxindex), edges(maxedges)
 INTEGER, OPTIONAL, INTENT(OUT) :: ierrorR]Input Parameters</a></h2>

<dl>

<dt>[bu]</dt>
<dd>C]commR]
: Communicator with graph structure (handle). </dd>

<dt>[bu]</dt>
<dd>C]maxindexR] : Length
of vector index in the calling program (integer). </dd>

<dt>[bu]</dt>
<dd>C]maxedgesR] : Length
of vector edges in the calling program (integer). </dd>
</dl>

<h2><a name='sect6' href='#toc6'>Output Parameters</a></h2>

<dl>

<dt>[bu]</dt>
<dd>C]indexR]
: Array of integers containing the graph structure (for details see the
definition of C]MPI_Graph_createR]). </dd>

<dt>[bu]</dt>
<dd>C]edgesR] : Array of integers containing
the graph structure. </dd>

<dt>[bu]</dt>
<dd>C]IERRORR] : Fortran only: Error status (integer).
</dd>
</dl>

<h2><a name='sect7' href='#toc7'>Description</a></h2>
<p>
Functions C]MPI_Graphdims_getR] and C]MPI_Graph_getR] retrieve
the graph-topology information that was associated with a communicator by
C]MPI_Graph_createR]. <p>
The information provided by C]MPI_Graphdims_getR]
can be used to dimension the vectors C]indexR] and C]edgesR] correctly
for a call to C]MPI_Graph_getR].
<h2><a name='sect8' href='#toc8'>Errors</a></h2>
<p>
Almost all MPI routines return an
error value; C routines as the value of the function and Fortran routines
in the last argument. <p>
Before the error value is returned, the current MPI
error handler is called. By default, this error handler aborts the MPI job,
except for I/O function errors. The error handler may be changed with C]MPI_Comm_set_errhandlerR];
the predefined error handler C]MPI_ERRORS_RETURNR] may be used to cause
error values to be returned. Note that MPI does not guarantee that an MPI
program can continue past an error.
<h2><a name='sect9' href='#toc9'>See Also</a></h2>
<p>
C]MPI_Graph_createR](3) C]MPI_Graphdims_getR](3)
<p>

<hr><p>
<a name='toc'><b>Table of Contents</b></a><p>
<ul>
<li><a name='toc0' href='#sect0'>Name</a></li>
<li><a name='toc1' href='#sect1'>Syntax</a></li>
<ul>
<li><a name='toc2' href='#sect2'>C Syntax</a></li>
<li><a name='toc3' href='#sect3'>C]#include <mpi.h>int MPI_Graph_get(MPI_Comm comm, int maxindex, int maxedges,    int index[], int edges[])R]Fortran Syntax</a></li>
<li><a name='toc4' href='#sect4'>C]USE MPI! or the older form: INCLUDE [aq]mpif.h[aq]MPI_GRAPH_GET(COMM, MAXINDEX, MAXEDGES, INDEX, EDGES, IERROR)    INTEGER COMM, MAXINDEX, MAXEDGES, INDEX(*)    INTEGER EDGES(*), IERRORR]Fortran 2008 Syntax</a></li>
</ul>
<li><a name='toc5' href='#sect5'>C]USE mpi_f08MPI_Graph_get(comm, maxindex, maxedges, index, edges, ierror)    TYPE(MPI_Comm), INTENT(IN) :: comm    INTEGER, INTENT(IN) :: maxindex, maxedges    INTEGER, INTENT(OUT) :: index(maxindex), edges(maxedges)    INTEGER, OPTIONAL, INTENT(OUT) :: ierrorR]Input Parameters</a></li>
<li><a name='toc6' href='#sect6'>Output Parameters</a></li>
<li><a name='toc7' href='#sect7'>Description</a></li>
<li><a name='toc8' href='#sect8'>Errors</a></li>
<li><a name='toc9' href='#sect9'>See Also</a></li>
</ul>


<p> <a href="../">&laquo; Return to documentation listing</a></p>
<?php
include_once("$topdir/includes/footer.inc");
