<?php
$topdir = "../../..";
$title = "MPI_File_write_ordered_end(3) man page (version 5.0.0rc2)";
$meta_desc = "Open MPI v5.0.0rc2 man page: MPI_FILE_WRITE_ORDERED_END(3)";

include_once("$topdir/doc/nav.inc");
include_once("$topdir/includes/header.inc");
?>
<p> <a href="../">&laquo; Return to documentation listing</a></p>
  <!-- manual page source format generated by PolyglotMan v3.2, -->
<!-- available at http://polyglotman.sourceforge.net/ -->

<body bgcolor='white'>
<a href='#toc'>Table of Contents</a><p>

<h2><a name='sect0' href='#toc0'>Name</a></h2>
<p>
C]MPI_File_write_ordered_endR] - Writes a file at a location specified
by a shared file pointer; ending part of a split collective routine (blocking).

<h2><a name='sect1' href='#toc1'>Syntax</a></h2>

<h3><a name='sect2' href='#toc2'>C Syntax</a></h3>
<br>
<pre>

</pre>
<h3><a name='sect3' href='#toc3'>C]#include &lt;mpi.h&gt;int MPI_File_write_ordered_end(MPI_File fh, const void *buf,
   MPI_Status *status)R]Fortran Syntax</a></h3>
<br>
<pre>

</pre>
<h3><a name='sect4' href='#toc4'>C]USE MPI! or the older form: INCLUDE [aq]mpif.h[aq]MPI_FILE_WRITE_ORDERED_END(FH,
BUF, STATUS, IERROR)    &lt;type&gt;  BUF(*)    INTEGER FH, STATUS(MPI_STATUS_SIZE),
IERRORR]Fortran 2008 Syntax</a></h3>
<br>
<pre>

</pre>
<h2><a name='sect5' href='#toc5'>C]USE mpi_f08MPI_File_write_ordered_end(fh, buf, status, ierror)    TYPE(MPI_File),
INTENT(IN) :: fh    TYPE(*), DIMENSION(..), INTENT(IN), ASYNCHRONOUS :: buf
   TYPE(MPI_Status) :: status    INTEGER, OPTIONAL, INTENT(OUT) :: ierrorR]Input/Output
Parameter</a></h2>

<dl>

<dt>[bu]</dt>
<dd>C]fhR] : File handle (handle). </dd>
</dl>

<h2><a name='sect6' href='#toc6'>Input Parameter</a></h2>

<dl>

<dt>[bu]</dt>
<dd>C]bufR] :
Initial address of buffer (choice). </dd>
</dl>

<h2><a name='sect7' href='#toc7'>Output Parameters</a></h2>

<dl>

<dt>[bu]</dt>
<dd>C]statusR] : Status
object (status). </dd>

<dt>[bu]</dt>
<dd>C]IERRORR] : Fortran only: Error status (integer). </dd>
</dl>

<h2><a name='sect8' href='#toc8'>Description</a></h2>
<p>
C]MPI_File_write_ordered_endR]
is the ending part of a split collective routine that must be called by
all processes in the communicator group associated with the file handle
C]fhR]. C]MPI_File_write_ordered_endR] returns the number of elements written
into the file associated with C]fhR] in C]statusR].
<h2><a name='sect9' href='#toc9'>Notes</a></h2>
<p>
All the nonblocking
collective routines for data access are [lq]split[rq] into two routines,
each with _begin or _end as a suffix. These split collective routines are
subject to the semantic rules described in Section 9.4.5 of the MPI-2 standard.

<h2><a name='sect10' href='#toc10'>Errors</a></h2>
<p>
Almost all MPI routines return an error value; C routines as the
value of the function and Fortran routines in the last argument. <p>
Before
the error value is returned, the current MPI error handler is called. For
MPI I/O function errors, the default error handler is set to C]MPI_ERRORS_RETURNR].
The error handler may be changed with C]MPI_File_set_errhandlerR]; the
predefined error handler C]MPI_ERRORS_ARE_FATALR] may be used to make I/O
errors fatal. Note that MPI does not guarantee that an MPI program can continue
past an error. <p>

<hr><p>
<a name='toc'><b>Table of Contents</b></a><p>
<ul>
<li><a name='toc0' href='#sect0'>Name</a></li>
<li><a name='toc1' href='#sect1'>Syntax</a></li>
<ul>
<li><a name='toc2' href='#sect2'>C Syntax</a></li>
<li><a name='toc3' href='#sect3'>C]#include <mpi.h>int MPI_File_write_ordered_end(MPI_File fh, const void *buf,    MPI_Status *status)R]Fortran Syntax</a></li>
<li><a name='toc4' href='#sect4'>C]USE MPI! or the older form: INCLUDE [aq]mpif.h[aq]MPI_FILE_WRITE_ORDERED_END(FH, BUF, STATUS, IERROR)    <type>  BUF(*)    INTEGER FH, STATUS(MPI_STATUS_SIZE), IERRORR]Fortran 2008 Syntax</a></li>
</ul>
<li><a name='toc5' href='#sect5'>C]USE mpi_f08MPI_File_write_ordered_end(fh, buf, status, ierror)    TYPE(MPI_File), INTENT(IN) :: fh    TYPE(*), DIMENSION(..), INTENT(IN), ASYNCHRONOUS :: buf    TYPE(MPI_Status) :: status    INTEGER, OPTIONAL, INTENT(OUT) :: ierrorR]Input/Output Parameter</a></li>
<li><a name='toc6' href='#sect6'>Input Parameter</a></li>
<li><a name='toc7' href='#sect7'>Output Parameters</a></li>
<li><a name='toc8' href='#sect8'>Description</a></li>
<li><a name='toc9' href='#sect9'>Notes</a></li>
<li><a name='toc10' href='#sect10'>Errors</a></li>
</ul>


<p> <a href="../">&laquo; Return to documentation listing</a></p>
<?php
include_once("$topdir/includes/footer.inc");
