<?php
$topdir = "../../..";
$title = "MPI_Get_count(3) man page (version 5.0.0rc2)";
$meta_desc = "Open MPI v5.0.0rc2 man page: MPI_GET_COUNT(3)";

include_once("$topdir/doc/nav.inc");
include_once("$topdir/includes/header.inc");
?>
<p> <a href="../">&laquo; Return to documentation listing</a></p>
  <!-- manual page source format generated by PolyglotMan v3.2, -->
<!-- available at http://polyglotman.sourceforge.net/ -->

<body bgcolor='white'>
<a href='#toc'>Table of Contents</a><p>

<h2><a name='sect0' href='#toc0'>Name</a></h2>
<p>
C]MPI_Get_countR] - Gets the number of top-level elements received.

<h2><a name='sect1' href='#toc1'>Syntax</a></h2>

<h3><a name='sect2' href='#toc2'>C Syntax</a></h3>
<br>
<pre>

</pre>
<h3><a name='sect3' href='#toc3'>C]#include &lt;mpi.h&gt;int MPI_Get_count(const MPI_Status *status, MPI_Datatype
datatype,    int *count)R]Fortran Syntax</a></h3>
<br>
<pre>

</pre>
<h3><a name='sect4' href='#toc4'>C]USE MPI! or the older form: INCLUDE [aq]mpif.h[aq]MPI_GET_COUNT(STATUS,
DATATYPE, COUNT, IERROR)    INTEGER STATUS(MPI_STATUS_SIZE), DATATYPE,
COUNT, IERRORR]Fortran 2008 Syntax</a></h3>
<br>
<pre>

</pre>
<h2><a name='sect5' href='#toc5'>C]USE mpi_f08MPI_Get_count(status, datatype, count, ierror)    TYPE(MPI_Status),
INTENT(IN) :: status    TYPE(MPI_Datatype), INTENT(IN) :: datatype    INTEGER,
INTENT(OUT) :: count    INTEGER, OPTIONAL, INTENT(OUT) :: ierrorR]Input
Parameters</a></h2>

<dl>

<dt>[bu]</dt>
<dd>C]statusR] : Return status of receive operation (status).
</dd>

<dt>[bu]</dt>
<dd>C]datatypeR] : Datatype of each receive buffer element (handle). </dd>
</dl>

<h2><a name='sect6' href='#toc6'>Output
Parameters</a></h2>

<dl>

<dt>[bu]</dt>
<dd>C]countR] : Number of received elements (integer). </dd>

<dt>[bu]</dt>
<dd>C]IERRORR]
: Fortran only: Error status (integer). </dd>
</dl>

<h2><a name='sect7' href='#toc7'>Description</a></h2>
<p>
Returns the number of
entries received. (We count entries, each of type C]datatypeR], not bytes.)
The C]datatypeR] argument should match the argument provided by the receive
call that set the C]statusR] variable. (As explained in Section 3.12.5 in
the MPI-1 Standard, [lq]Use of General Datatypes in Communication,[rq] C]MPI_Get_countR]
may, in certain situations, return the value C]MPI_UNDEFINEDR].) <p>
The C]datatypeR]
argument is passed to C]MPI_Get_countR] to improve performance. A message
might be received without counting the number of elements it contains,
and the C]countR] value is often not needed. Also, this allows the same
function to be used after a call to C]MPI_ProbeR].
<h2><a name='sect8' href='#toc8'>Notes</a></h2>
<p>
If the size of the
C]datatypeR] is zero, this routine will return a C]countR] of zero. If the
amount of data in C]statusR] is not an exact multiple of the size of C]datatypeR]
(so that C]countR] would not be integral), a C]countR] of C]MPI_UNDEFINEDR]
is returned instead.
<h2><a name='sect9' href='#toc9'>Errors</a></h2>
<p>
If the value to be returned is larger than can
fit into the C]countR] parameter, an C]MPI_ERR_TRUNCATER] error is raised.
<p>
Almost all MPI routines return an error value; C routines as the value
of the function and Fortran routines in the last argument. <p>
Before the error
value is returned, the current MPI error handler is called. By default,
this error handler aborts the MPI job, except for I/O function errors. The
error handler may be changed with C]MPI_Comm_set_errhandlerR]; the predefined
error handler C]MPI_ERRORS_RETURNR] may be used to cause error values to
be returned. Note that MPI does not guarantee that an MPI program can continue
past an error.
<h2><a name='sect10' href='#toc10'>See Also</a></h2>
<p>
C]MPI_Get_elementsR](3) <p>

<hr><p>
<a name='toc'><b>Table of Contents</b></a><p>
<ul>
<li><a name='toc0' href='#sect0'>Name</a></li>
<li><a name='toc1' href='#sect1'>Syntax</a></li>
<ul>
<li><a name='toc2' href='#sect2'>C Syntax</a></li>
<li><a name='toc3' href='#sect3'>C]#include <mpi.h>int MPI_Get_count(const MPI_Status *status, MPI_Datatype datatype,    int *count)R]Fortran Syntax</a></li>
<li><a name='toc4' href='#sect4'>C]USE MPI! or the older form: INCLUDE [aq]mpif.h[aq]MPI_GET_COUNT(STATUS, DATATYPE, COUNT, IERROR)    INTEGER STATUS(MPI_STATUS_SIZE), DATATYPE, COUNT, IERRORR]Fortran 2008 Syntax</a></li>
</ul>
<li><a name='toc5' href='#sect5'>C]USE mpi_f08MPI_Get_count(status, datatype, count, ierror)    TYPE(MPI_Status), INTENT(IN) :: status    TYPE(MPI_Datatype), INTENT(IN) :: datatype    INTEGER, INTENT(OUT) :: count    INTEGER, OPTIONAL, INTENT(OUT) :: ierrorR]Input Parameters</a></li>
<li><a name='toc6' href='#sect6'>Output Parameters</a></li>
<li><a name='toc7' href='#sect7'>Description</a></li>
<li><a name='toc8' href='#sect8'>Notes</a></li>
<li><a name='toc9' href='#sect9'>Errors</a></li>
<li><a name='toc10' href='#sect10'>See Also</a></li>
</ul>


<p> <a href="../">&laquo; Return to documentation listing</a></p>
<?php
include_once("$topdir/includes/footer.inc");
