<?php
$title = "The Architecture of Open Source Applications, volume 2";

$overview = "Chapter 15 presents an architectural overview of Open MPI.";

$presented = "<a href=\"http://www.aosabook.org/en/index.html\">
Book web site</a>";

$authors = "Jeffrey M. Squyres, edited by Amy Brown and Greg Wilson";

$abstract = "Chapter 15 presents an architectural overview of Open MPI.
Emphasis is placed on describing the structure of the Modular Component
Architecture and why it was designed the way it was.  This chapter
is excellent reading for those just starting a deep dive of the Open MPI
code base.

All proceeds from this books are donated to Amnesty International.";

$month = 4;
$day = 21;
$year = 2012;

$bibtex = "@InBook{squyres12:_archic_of_open_sourc_applic,
  author = 	 {Jeffrey M. Squyres},
  title = 	 {The Architecture of Open Source Applications},
  chapter = 	 15,
  publisher = 	 {Self published},
  year = 	 2012,
  volume = 	 {ii},
  month = 	 {April}
}";
