<? include("../../include/msg-header.inc"); ?>
<!-- received="Sat Apr  1 02:44:54 2006" -->
<!-- isoreceived="20060401074454" -->
<!-- sent="Sat, 1 Apr 2006 02:44:50 -0500" -->
<!-- isosent="20060401074450" -->
<!-- name="George Bosilca" -->
<!-- email="bosilca_at_[hidden]" -->
<!-- subject="Re: [OMPI users] MPI_Testsome with no requests" -->
<!-- id="13689357-BB16-4DD4-9975-F3A5C3CC391D_at_cs.utk.edu" -->
<!-- charset="US-ASCII" -->
<!-- inreplyto="C0530B79.25CD%tabrunn_at_sandia.gov" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>From:</strong> George Bosilca (<em>bosilca_at_[hidden]</em>)<br>
<strong>Date:</strong> 2006-04-01 02:44:50
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="0949.php">Prakash Velayutham: "[OMPI users] Open MPI and Torque error"</a>
<li><strong>Previous message:</strong> <a href="http://www.open-mpi.org/community/lists/users/2006/03/0947.php">Brunner, Thomas A.: "Re: [OMPI users] MPI_Testsome with no requests"</a>
<li><strong>In reply to:</strong> <a href="http://www.open-mpi.org/community/lists/users/2006/03/0947.php">Brunner, Thomas A.: "Re: [OMPI users] MPI_Testsome with no requests"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="0950.php">Brunner, Thomas A.: "Re: [OMPI users] MPI_Testsome with no requests"</a>
<li><strong>Reply:</strong> <a href="0950.php">Brunner, Thomas A.: "Re: [OMPI users] MPI_Testsome with no requests"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
There seems to be a sentence in the MPI standard about this case. The  
<br>
standard state:
<br>
<p>If there is no active handle in the list it returns outcount =  
<br>
MPI_UNDEFINED.
<br>
<p>Revision 9513 follow the standard.
<br>
<p>&nbsp;&nbsp;&nbsp;Thanks,
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;george.
<br>
<p><p>On Mar 31, 2006, at 6:38 PM, Brunner, Thomas A. wrote:
<br>
<p><span class="quotelev1">&gt; Compiling revision 9505 of the trunk and building my original test  
</span><br>
<span class="quotelev1">&gt; code now
</span><br>
<span class="quotelev1">&gt; core dumps.  I can run the test code with the Testsome line  
</span><br>
<span class="quotelev1">&gt; commented out.
</span><br>
<span class="quotelev1">&gt; Here is the output from a brief gdb session:
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; --------------------------------------------------------------
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; gdb a.out /cores/core.28141
</span><br>
<span class="quotelev1">&gt; GNU gdb 6.1-20040303 (Apple version gdb-437) (Sun Dec 25 08:31:29  
</span><br>
<span class="quotelev1">&gt; GMT 2005)
</span><br>
<span class="quotelev1">&gt; Copyright 2004 Free Software Foundation, Inc.
</span><br>
<span class="quotelev1">&gt; GDB is free software, covered by the GNU General Public License,  
</span><br>
<span class="quotelev1">&gt; and you are
</span><br>
<span class="quotelev1">&gt; welcome to change it and/or distribute copies of it under certain
</span><br>
<span class="quotelev1">&gt; conditions.
</span><br>
<span class="quotelev1">&gt; Type &quot;show copying&quot; to see the conditions.
</span><br>
<span class="quotelev1">&gt; There is absolutely no warranty for GDB.  Type &quot;show warranty&quot; for  
</span><br>
<span class="quotelev1">&gt; details.
</span><br>
<span class="quotelev1">&gt; This GDB was configured as &quot;powerpc-apple-darwin&quot;...Reading symbols  
</span><br>
<span class="quotelev1">&gt; for
</span><br>
<span class="quotelev1">&gt; shared libraries ..... done
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; Core was generated by `a.out'.
</span><br>
<span class="quotelev1">&gt; #0  0x010b2a90 in ?? ()
</span><br>
<span class="quotelev1">&gt; (gdb) bt
</span><br>
<span class="quotelev1">&gt; #0  0x010b2a90 in ?? ()
</span><br>
<span class="quotelev1">&gt; #1  0x010b2a3c in ?? ()
</span><br>
<span class="quotelev1">&gt; warning: Previous frame identical to this frame (corrupt stack?)
</span><br>
<span class="quotelev1">&gt; #2  0x00002c18 in grow_table (table=0x1, soft=3221222188, hard=0) at
</span><br>
<span class="quotelev1">&gt; class/ompi_pointer_array.c:352
</span><br>
<span class="quotelev1">&gt; (gdb) up
</span><br>
<span class="quotelev1">&gt; #1  0x010b2a3c in ?? ()
</span><br>
<span class="quotelev1">&gt; (gdb) up
</span><br>
<span class="quotelev1">&gt; #2  0x00002c18 in grow_table (table=0x1, soft=3221222188, hard=0) at
</span><br>
<span class="quotelev1">&gt; class/ompi_pointer_array.c:352
</span><br>
<span class="quotelev1">&gt; 352         if (table-&gt;size &gt;= OMPI_FORTRAN_HANDLE_MAX) {
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; ---------------------------------------------------------------
</span><br>
<span class="quotelev1">&gt; This is the output from the code.
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; Hello from processor 0 of 1
</span><br>
<span class="quotelev1">&gt; Signal:10 info.si_errno:0(Unknown error: 0) si_code:1(BUS_ADRALN)
</span><br>
<span class="quotelev1">&gt; Failing at addr:0x0
</span><br>
<span class="quotelev1">&gt; *** End of error message ***
</span><br>
<span class="quotelev1">&gt; ------------------------------------------------------------
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; Perhaps in the MPI_Wait* and MPI_Test* functions, if incount==0, then
</span><br>
<span class="quotelev1">&gt; *outcount should be set to zero and immediately return?  (Of course  
</span><br>
<span class="quotelev1">&gt; checking
</span><br>
<span class="quotelev1">&gt; that outcount !=0 too.)
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; Tom
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; On 3/31/06 1:35 PM, &quot;George Bosilca&quot; &lt;bosilca_at_[hidden]&gt; wrote:
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev2">&gt;&gt; When we're checking the arguments, we check for the request array to
</span><br>
<span class="quotelev2">&gt;&gt; not be NULL without looking to the number of requests. I think it
</span><br>
<span class="quotelev2">&gt;&gt; make sense, as I don't see why the user would call these functions
</span><br>
<span class="quotelev2">&gt;&gt; with 0 requests ... But, the other way around make sense too. As I
</span><br>
<span class="quotelev2">&gt;&gt; don't find anything in the MPI standard that stop the user doing that
</span><br>
<span class="quotelev2">&gt;&gt; I add the additional check to all MPI_Wait* and MPI_Test* functions.
</span><br>
<span class="quotelev2">&gt;&gt;
</span><br>
<span class="quotelev2">&gt;&gt; Please get the version from trunk after revision 9504.
</span><br>
<span class="quotelev2">&gt;&gt;
</span><br>
<span class="quotelev2">&gt;&gt;    Thanks,
</span><br>
<span class="quotelev2">&gt;&gt;      george.
</span><br>
<span class="quotelev2">&gt;&gt;
</span><br>
<span class="quotelev2">&gt;&gt; On Mar 31, 2006, at 2:56 PM, Brunner, Thomas A. wrote:
</span><br>
<span class="quotelev2">&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; I have an algorithm that collects information in a tree like manner
</span><br>
<span class="quotelev3">&gt;&gt;&gt; using
</span><br>
<span class="quotelev3">&gt;&gt;&gt; nonblocking communication.  Some nodes do not receive information
</span><br>
<span class="quotelev3">&gt;&gt;&gt; from other
</span><br>
<span class="quotelev3">&gt;&gt;&gt; nodes, so there are no outstanding requests on those nodes.  On all
</span><br>
<span class="quotelev3">&gt;&gt;&gt; processors, I check for the incoming messages using MPI_Testsome().
</span><br>
<span class="quotelev3">&gt;&gt;&gt; MPI_Testsome fails with OpenMPI, however if the request length is
</span><br>
<span class="quotelev3">&gt;&gt;&gt; zero.
</span><br>
<span class="quotelev3">&gt;&gt;&gt; Here is a code that can be run with only one processor that shows
</span><br>
<span class="quotelev3">&gt;&gt;&gt; the same
</span><br>
<span class="quotelev3">&gt;&gt;&gt; behavior:
</span><br>
<span class="quotelev3">&gt;&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; ///////////////////////////////////////////
</span><br>
<span class="quotelev3">&gt;&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; #include &quot;mpi.h&quot;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; #include &lt;stdio.h&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; int main( int argc, char *argv[])
</span><br>
<span class="quotelev3">&gt;&gt;&gt; {
</span><br>
<span class="quotelev3">&gt;&gt;&gt;     int myid, numprocs;
</span><br>
<span class="quotelev3">&gt;&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt;     MPI_Init(&amp;argc,&amp;argv);
</span><br>
<span class="quotelev3">&gt;&gt;&gt;     MPI_Comm_size(MPI_COMM_WORLD,&amp;numprocs);
</span><br>
<span class="quotelev3">&gt;&gt;&gt;     MPI_Comm_rank(MPI_COMM_WORLD,&amp;myid);
</span><br>
<span class="quotelev3">&gt;&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt;     printf(&quot;Hello from processor %i of %i\n&quot;, myid, numprocs);
</span><br>
<span class="quotelev3">&gt;&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt;     int size = 0;
</span><br>
<span class="quotelev3">&gt;&gt;&gt;     int num_done = 0;
</span><br>
<span class="quotelev3">&gt;&gt;&gt;     MPI_Status* stat = 0;
</span><br>
<span class="quotelev3">&gt;&gt;&gt;     MPI_Request* req = 0;
</span><br>
<span class="quotelev3">&gt;&gt;&gt;     int* done_indices = 0;
</span><br>
<span class="quotelev3">&gt;&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt;     MPI_Testsome( size, req, &amp;num_done, done_indices, stat);
</span><br>
<span class="quotelev3">&gt;&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt;     printf(&quot;Finalizing on processor %i of %i\n&quot;, myid, numprocs);
</span><br>
<span class="quotelev3">&gt;&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt;     MPI_Finalize();
</span><br>
<span class="quotelev3">&gt;&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt;     return 0;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; }
</span><br>
<span class="quotelev3">&gt;&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; /////////////////////////////////////////
</span><br>
<span class="quotelev3">&gt;&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; The output using OpenMPI is:
</span><br>
<span class="quotelev3">&gt;&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; Hello from processor 0 of 1
</span><br>
<span class="quotelev3">&gt;&gt;&gt; [mymachine:09115] *** An error occurred in MPI_Testsome
</span><br>
<span class="quotelev3">&gt;&gt;&gt; [mymachine:09115] *** on communicator MPI_COMM_WORLD
</span><br>
<span class="quotelev3">&gt;&gt;&gt; [mymachine:09115] *** MPI_ERR_REQUEST: invalid request
</span><br>
<span class="quotelev3">&gt;&gt;&gt; [mymachine:09115] *** MPI_ERRORS_ARE_FATAL (goodbye)
</span><br>
<span class="quotelev3">&gt;&gt;&gt; 1 process killed (possibly by Open MPI)
</span><br>
<span class="quotelev3">&gt;&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; Many other MPI implementations support this, and reading the
</span><br>
<span class="quotelev3">&gt;&gt;&gt; standard, it
</span><br>
<span class="quotelev3">&gt;&gt;&gt; seems like it should be OK.
</span><br>
<span class="quotelev3">&gt;&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; Thanks,
</span><br>
<span class="quotelev3">&gt;&gt;&gt; Tom
</span><br>
<span class="quotelev3">&gt;&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; &lt;config.log.bz2&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; &lt;testsome_test.out&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; &lt;testsome_test.c&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; &lt;ompi_info.out&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; _______________________________________________
</span><br>
<span class="quotelev3">&gt;&gt;&gt; users mailing list
</span><br>
<span class="quotelev3">&gt;&gt;&gt; users_at_[hidden]
</span><br>
<span class="quotelev3">&gt;&gt;&gt; <a href="http://www.open-mpi.org/mailman/listinfo.cgi/users">http://www.open-mpi.org/mailman/listinfo.cgi/users</a>
</span><br>
<span class="quotelev2">&gt;&gt;
</span><br>
<span class="quotelev2">&gt;&gt; _______________________________________________
</span><br>
<span class="quotelev2">&gt;&gt; users mailing list
</span><br>
<span class="quotelev2">&gt;&gt; users_at_[hidden]
</span><br>
<span class="quotelev2">&gt;&gt; <a href="http://www.open-mpi.org/mailman/listinfo.cgi/users">http://www.open-mpi.org/mailman/listinfo.cgi/users</a>
</span><br>
<span class="quotelev2">&gt;&gt;
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; _______________________________________________
</span><br>
<span class="quotelev1">&gt; users mailing list
</span><br>
<span class="quotelev1">&gt; users_at_[hidden]
</span><br>
<span class="quotelev1">&gt; <a href="http://www.open-mpi.org/mailman/listinfo.cgi/users">http://www.open-mpi.org/mailman/listinfo.cgi/users</a>
</span><br>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="0949.php">Prakash Velayutham: "[OMPI users] Open MPI and Torque error"</a>
<li><strong>Previous message:</strong> <a href="http://www.open-mpi.org/community/lists/users/2006/03/0947.php">Brunner, Thomas A.: "Re: [OMPI users] MPI_Testsome with no requests"</a>
<li><strong>In reply to:</strong> <a href="http://www.open-mpi.org/community/lists/users/2006/03/0947.php">Brunner, Thomas A.: "Re: [OMPI users] MPI_Testsome with no requests"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="0950.php">Brunner, Thomas A.: "Re: [OMPI users] MPI_Testsome with no requests"</a>
<li><strong>Reply:</strong> <a href="0950.php">Brunner, Thomas A.: "Re: [OMPI users] MPI_Testsome with no requests"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
