<?php
$topdir = "../../..";
$title = "ompi_info(1) man page (version 4.1.7)";
$meta_desc = "Open MPI v4.1.7 man page: ompi_info(1)";

include_once("$topdir/doc/nav.inc");
include_once("$topdir/includes/header.inc");
?>
<p> <a href="../">&laquo; Return to documentation listing</a></p>
    <!-- manual page source format generated by PolyglotMan v3.2, -->
<!-- available at http://polyglotman.sourceforge.net/ -->

<body bgcolor='white'>
<a href='#toc'>Table of Contents</a><p>

<h2><a name='sect0' href='#toc0'>Name</a></h2>
ompi_info - Display information about the Open MPI installation

<h2><a name='sect1' href='#toc1'>Synopsis</a></h2>
<b>ompi_info [options]</b>
<h2><a name='sect2' href='#toc2'>Description</a></h2>
<p>
<b>ompi_info</b> provides detailed
information about the Open MPI installation.  It can be useful for at least
three common scenarios: <p>
1. Checking local configuration and seeing how Open
MPI was installed. <p>
2. Submitting bug reports / help requests to the Open
MPI community (see <i>http://www.open-mpi.org/community/help/</i>) <p>
3. Seeing a list
of installed Open MPI plugins and querying what MCA parameters they support.
<p>
<b>NOTE:</b> <b>ompi_info</b> defaults to only showing a few MCA parameters by default
(i.e., level 1 parameters).  Use the <b>--level</b> option to enable showing more options
(see the LEVELS section for more information).
<h2><a name='sect3' href='#toc3'>Options</a></h2>
<b>ompi_info</b> accepts
the following options:
<dl>

<dt><i>-a|--all</i> </dt>
<dd>Show all configuration options and MCA parameters.
 Also changes the default MCA parameter level to 9, unless <i>--level</i> is also
specified. </dd>

<dt><i>--arch</i> </dt>
<dd>Show architecture on which Open MPI was compiled. </dd>

<dt><i>-c|--config</i>
</dt>
<dd>Show configuration options </dd>

<dt><i>-gmca|--gmca</i> &lt;param&gt; &lt;value&gt; </dt>
<dd>Pass global MCA parameters
that are applicable to all contexts. </dd>

<dt><i>-h|--help</i> </dt>
<dd>Shows help / usage message. </dd>

<dt><i>--hostname</i>
</dt>
<dd>Show the hostname on which Open MPI was configured and built. </dd>

<dt><i>--internal</i> </dt>
<dd>Show
internal MCA parameters (not meant to be modified by users). </dd>

<dt><i>--level</i> &lt;level&gt;
</dt>
<dd>Show only variables with at most this level (1-9). The default is 1 unless
--all is specified without --level, in which case the default is 9. See the
LEVELS section for more information. </dd>

<dt><i>-mca|--mca</i> &lt;param&gt; &lt;value&gt; </dt>
<dd>Pass context-specific
MCA parameters; they are considered global if --gmca is not used and only
one context is specified. </dd>

<dt><i>--param</i> &lt;type&gt; &lt;component&gt; </dt>
<dd>Show MCA parameters.  The
first parameter is the type of the component to display; the second parameter
is the specific component to display (or the keyword "all", meaning "display
all components of this type"). </dd>

<dt><i>-t|--type</i> </dt>
<dd>Show MCA parameters of the type specified
in the parameter. Accepts the following parameters: unsigned_int, unsigned_long,
unsigned_long_long, size_t, string, version_string, bool, double. By default
level is 1 unless it is specified with --level. </dd>

<dt><i>--parsable</i> </dt>
<dd>When used in conjunction
with other parameters, the output is displayed in a machine-parsable format
<i>--parseable</i> Synonym for --parsable </dd>

<dt><i>--path</i> &lt;type&gt; </dt>
<dd>Show paths that Open MPI was configured
with.  Accepts the following parameters: prefix, bindir, libdir, incdir,
pkglibdir, sysconfdir. </dd>

<dt><i>--pretty</i> </dt>
<dd>When used in conjunction with other parameters,
the output is displayed in &rsquo;prettyprint&rsquo; format (default) </dd>

<dt><i>--selected-only</i> </dt>
<dd>Show
only variables from selected components. </dd>

<dt><i>-V|--version</i> </dt>
<dd>Show version of Open MPI.
    </dd>
</dl>

<h2><a name='sect4' href='#toc4'>Levels</a></h2>
Open MPI has many, many run-time tunable parameters (called "MCA
parameters"), and usually only a handfull of them are useful to a given
user.   <p>
As such, Open MPI has divided these parameters up into nine distinct
levels, broken down into three categories, each with three sub-categories.
  <p>
Note that since each MCA parameter is accessible through the MPI_T control
variable API (introduced in MPI-3.0), these levels exactly correspond to
the nine MPI_T cvar levels.   <p>
The three categories are:
<dl>

<dt><b>End user</b> </dt>
<dd>Generally,
these are parameters that are required for correctness, meaning that a
user may need to set these just to get their MPI application to run correctly.
For example, BTL "if_include" and "if_exclude" parameters fit into this
category.  </dd>

<dt><b>Application tuner</b> </dt>
<dd>Generally, these are parameters that can be
used to tweak MPI application performance. This even includes parameters
that control resource exhaustion levels (e.g., number of free list entries,
size of buffers, etc.), and could be considered "correctness" parameters
if they&rsquo;re set too low. But, really -- they&rsquo;re tuning parameters.  </dd>

<dt><b>Open MPI developer</b>
</dt>
<dd>Parameters in this category either don&rsquo;t fit in the other two, or are specifically
intended for debugging / development of Open MPI itself.   </dd>
</dl>
<p>
And within each
category, there are three sub-categories:
<dl>

<dt><b>Basic</b> </dt>
<dd>This sub-category is for
parameters that everyone in this category will want to see -- even less-advanced
end users, application tuners, and new OMPI developers.  </dd>

<dt><b>Detailed</b> </dt>
<dd>This sub-category
is for parameters that are generally useful, but users probably won&rsquo;t need
to change them often.  </dd>

<dt><b>All</b> </dt>
<dd>This sub-category is for all other parameters.
Such parameters are likely fairly esoteric.   </dd>
</dl>
<p>
Combining the categories and
sub-categories, here&rsquo;s how Open MPI defines all nine levels:
<ol>
<li>Basic information
of interest to end users. </li><li>Detailed information of interest to end users.
</li><li>All remaining information of interest to end users. </li><li>Basic information required
for application tuners. </li><li>Detailed information required for application tuners.
</li><li>All remaining information required for application tuners. </li><li>Basic information
for Open MPI implementors. </li><li>Detailed information for Open MPI implementors.
</li><li>All remaining information for Open MPI implementors.   </li>
</ol>
<p>
By default, <b>ompi_info</b>
only shows level 1 MCA parameters.  To see more MCA parameters, use the
<b>--level</b> command line option.   <p>

<h2><a name='sect5' href='#toc5'>Examples</a></h2>

<dl>

<dt>ompi_info </dt>
<dd>Show the default output
of options and listing of installed components in a human-readable / prettyprint
format.   </dd>

<dt>ompi_info --parsable </dt>
<dd>Show the default output of options and listing
of installed components in a machine-parsable format.   </dd>

<dt>ompi_info --param btl
tcp </dt>
<dd>Show the level 1 MCA parameters of the "tcp" BTL component in a human-readable
/ prettyprint format.   </dd>

<dt>ompi_info --param btl tcp --level 6 </dt>
<dd>Show the level 1
through level 6 MCA parameters of the "tcp" BTL component in a human-readable
/ prettyprint format.   </dd>

<dt>ompi_info --param btl tcp --parsable </dt>
<dd>Show the level
1 MCA parameters of the "tcp" BTL component in a machine-parsable format.
  </dd>

<dt>ompi_info --type string --pretty-print --level 3 </dt>
<dd>Show the level 3 MCA parameters
of string type in a human-readable / prettyprint format.   </dd>

<dt>ompi_info --path
bindir </dt>
<dd>Show the "bindir" that Open MPI was configured with.   </dd>

<dt>ompi_info
--version </dt>
<dd>Show the version of Open MPI version numbers in a prettyprint format.
  </dd>

<dt>ompi_info --all </dt>
<dd>Show <i>all</i> information about the Open MPI installation, including
all components that can be found, all the MCA parameters that they support
(i.e., levels 1 through 9), versions of Open MPI and the components, etc.
     </dd>
</dl>

<h2><a name='sect6' href='#toc6'>Authors</a></h2>
The Open MPI maintainers -- see <i><i>http://www.openmpi.org/</i></i> or the
file <i>AUTHORS</i>. <p>
This manual page was originally contributed by Dirk Eddelbuettel
&lt;email-address-removed&gt;, one of the Debian GNU/Linux maintainers for Open MPI, and
may be used by others. <p>

<hr><p>
<a name='toc'><b>Table of Contents</b></a><p>
<ul>
<li><a name='toc0' href='#sect0'>Name</a></li>
<li><a name='toc1' href='#sect1'>Synopsis</a></li>
<li><a name='toc2' href='#sect2'>Description</a></li>
<li><a name='toc3' href='#sect3'>Options</a></li>
<li><a name='toc4' href='#sect4'>Levels</a></li>
<li><a name='toc5' href='#sect5'>Examples</a></li>
<li><a name='toc6' href='#sect6'>Authors</a></li>
</ul>


<p> <a href="../">&laquo; Return to documentation listing</a></p>
<?php
include_once("$topdir/includes/footer.inc");
