<?
$subject_val = "Re: [OMPI users] Configure and Build ok, but mpi module not recognized?";
include("../../include/msg-header.inc");
?>
<!-- received="Mon Sep 22 09:04:24 2008" -->
<!-- isoreceived="20080922130424" -->
<!-- sent="Mon, 22 Sep 2008 09:04:18 -0400" -->
<!-- isosent="20080922130418" -->
<!-- name="Jeff Squyres" -->
<!-- email="jsquyres_at_[hidden]" -->
<!-- subject="Re: [OMPI users] Configure and Build ok, but mpi module not recognized?" -->
<!-- id="2541C680-BCEB-45CB-90AF-1E730737FA7A_at_cisco.com" -->
<!-- charset="US-ASCII" -->
<!-- inreplyto="48535380809191551h68036208sb353c66b760b645_at_mail.gmail.com" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>Subject:</strong> Re: [OMPI users] Configure and Build ok, but mpi module not recognized?<br>
<strong>From:</strong> Jeff Squyres (<em>jsquyres_at_[hidden]</em>)<br>
<strong>Date:</strong> 2008-09-22 09:04:18
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="6651.php">Jeff Squyres: "Re: [OMPI users] conflict among differenv MPIs"</a>
<li><strong>Previous message:</strong> <a href="6649.php">Robert Kubrick: "Re: [OMPI users] conflict among differenv MPIs"</a>
<li><strong>In reply to:</strong> <a href="6631.php">Brian Harker: "[OMPI users] Configure and Build ok, but mpi module not recognized?"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="6652.php">Brian Harker: "Re: [OMPI users] Configure and Build ok, but mpi module not recognized?"</a>
<li><strong>Reply:</strong> <a href="6652.php">Brian Harker: "Re: [OMPI users] Configure and Build ok, but mpi module not recognized?"</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
On Sep 19, 2008, at 6:51 PM, Brian Harker wrote:
<br>
<p><span class="quotelev1">&gt; I have configured openMPI to work with the Intel C (icc) and C++
</span><br>
<span class="quotelev1">&gt; (icpc) compilers, as well as the Intel fortran (ifort) compiler, and
</span><br>
<span class="quotelev1">&gt; built all the single choice buffer fortran 90 bindings:
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; ./configure --prefix=$HOME/openmpi CC=icc CXX=icpc F77=ifort FC=ifort
</span><br>
<span class="quotelev1">&gt; --enable-mpi-f90 --with-mpi-f90-size=medium
</span><br>
<p>That all looks correct.
<br>
<p><span class="quotelev1">&gt; which works fine.  Ok.  Onto make all install.  Works fine too.  Now
</span><br>
<span class="quotelev1">&gt; when I try to compile the example hello_f90.f90 program, I get the
</span><br>
<span class="quotelev1">&gt; following error:
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev2">&gt;&gt; $HOME/openmpi/bin/mpif90 hello_f90.f90 -I$HOME/openmpi/include
</span><br>
<p>FWIW, you shouldn't need that -I, but that *probably* shouldn't be  
<br>
causing your problem here (note that OMPI's F90 module file is  
<br>
installed into $prefix/lib, not $prefix/include).
<br>
<p><span class="quotelev1">&gt; fortcom: Error: hello_f90.f90, line 12:  This module file was not
</span><br>
<span class="quotelev1">&gt; generated by any release of this compiler.    [MPI]
</span><br>
<span class="quotelev1">&gt;    use mpi
</span><br>
<span class="quotelev1">&gt; -----------^
</span><br>
<p>Two things to check:
<br>
<p>1. Are you using exactly the same ifort to build Open MPI as mpif90  
<br>
is?  I assume it is, but it's worth checking.  You can run the  
<br>
following to see exactly what mpif90 will execute:
<br>
<p>$HOME/openmpi/bin/mpif90 hello_f90.f90 -I$HOME/openmpi/include --showme
<br>
<p>And then run it yourself, ensuring that your $PATH is set to get the  
<br>
exact same ifort, etc.  I'm *guessing* that this is all correct, but  
<br>
it's worth checking.
<br>
<p>2. Check to see if there is another mpi.mod installed somewhere in the  
<br>
compiler search path that is not the mpi.mod that you expect.  For  
<br>
example, you might want to &quot;rm -rf $HOME/openmpi&quot; to ensure to have a  
<br>
100% clean Open MPI install.  And look elsewhere on the machine for  
<br>
mpi.mod that may be found in the compiler search patch before the Open  
<br>
MPI-installed mpi.mod is found.
<br>
<p><pre>
-- 
Jeff Squyres
Cisco Systems
</pre>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="6651.php">Jeff Squyres: "Re: [OMPI users] conflict among differenv MPIs"</a>
<li><strong>Previous message:</strong> <a href="6649.php">Robert Kubrick: "Re: [OMPI users] conflict among differenv MPIs"</a>
<li><strong>In reply to:</strong> <a href="6631.php">Brian Harker: "[OMPI users] Configure and Build ok, but mpi module not recognized?"</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="6652.php">Brian Harker: "Re: [OMPI users] Configure and Build ok, but mpi module not recognized?"</a>
<li><strong>Reply:</strong> <a href="6652.php">Brian Harker: "Re: [OMPI users] Configure and Build ok, but mpi module not recognized?"</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
