<? include("../../include/msg-header.inc"); ?>
<!-- received="Sun May 28 10:48:18 2006" -->
<!-- isoreceived="20060528144818" -->
<!-- sent="Sun, 28 May 2006 10:48:18 -0400" -->
<!-- isosent="20060528144818" -->
<!-- name="Justin Bronder" -->
<!-- email="jsbronder_at_[hidden]" -->
<!-- subject="[OMPI users] [PMX:VIRUS] Re: OpenMPI 1.0.3a1r10002 Fails to build with IBM XL Compilers." -->
<!-- id="4479B832.7060700_at_gmail.com" -->
<!-- charset="UTF-8" -->
<!-- inreplyto="6F078F41-7C85-4230-B33C-6C0038378D58_at_open-mpi.org" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>From:</strong> Justin Bronder (<em>jsbronder_at_[hidden]</em>)<br>
<strong>Date:</strong> 2006-05-28 10:48:18
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="1322.php">Francoise Roch: "[OMPI users] openmpi-1.1a7  on solaris10 opteron"</a>
<li><strong>Previous message:</strong> <a href="1320.php">Brian Barrett: "Re: [OMPI users] OpenMPI 1.0.3a1r10002 Fails to build with IBM XL Compilers."</a>
<li><strong>In reply to:</strong> <a href="1320.php">Brian Barrett: "Re: [OMPI users] OpenMPI 1.0.3a1r10002 Fails to build with IBM XL Compilers."</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="1331.php">Brian Barrett: "Re: [OMPI users] [PMX:VIRUS] Re: OpenMPI 1.0.3a1r10002 Fails to build with IBM XL Compilers."</a>
<li><strong>Reply:</strong> <a href="1331.php">Brian Barrett: "Re: [OMPI users] [PMX:VIRUS] Re: OpenMPI 1.0.3a1r10002 Fails to build with IBM XL Compilers."</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
Brian Barrett wrote:
<br>
<span class="quotelev1">&gt; On May 27, 2006, at 10:01 AM, Justin Bronder wrote:
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt;   
</span><br>
<span class="quotelev2">&gt;&gt; I've attached the required logs.  Essentially the problem seems to
</span><br>
<span class="quotelev2">&gt;&gt; be that the XL Compilers fail to recognize &quot;__asm__ __volatile__&quot; in
</span><br>
<span class="quotelev2">&gt;&gt; opal/include/sys/powerpc/atomic.h when building 64-bit.
</span><br>
<span class="quotelev2">&gt;&gt;
</span><br>
<span class="quotelev2">&gt;&gt; I've tried using various xlc wrappers such as gxlc and xlc_r to
</span><br>
<span class="quotelev2">&gt;&gt; no avail.  The current log uses xlc_r_64 which is just a one line
</span><br>
<span class="quotelev2">&gt;&gt; shell script forcing the -q64 option.
</span><br>
<span class="quotelev2">&gt;&gt;
</span><br>
<span class="quotelev2">&gt;&gt; The same works flawlessly with gcc-4.1.0.  I'm using the nightly
</span><br>
<span class="quotelev2">&gt;&gt; build in order to link with Torque's new shared libraries.
</span><br>
<span class="quotelev2">&gt;&gt;
</span><br>
<span class="quotelev2">&gt;&gt; Any help would be greatly appreciated.  For reference here are
</span><br>
<span class="quotelev2">&gt;&gt; a few other things that may provide more information.
</span><br>
<span class="quotelev2">&gt;&gt;     
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt; Can you send the config.log file generated by configure?  What else  
</span><br>
<span class="quotelev1">&gt; is in the xlc_r_64 shell script, other than the -q64 option?
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt;
</span><br>
<span class="quotelev1">&gt;   
</span><br>
I've attached the config.log, and here's what all of the *_64 scripts
<br>
look like.
<br>
<p><p>node42 openmpi-1.0.3a1r10002 # cat /opt/ibmcmp/vac/8.0/bin/xlc_r_64
<br>
#!/bin/sh
<br>
xlc_r -q64 &quot;$@&quot;
<br>
<p><p>Thanks,
<br>
<p><pre>
-- 
Justin Bronder
University of Maine, Orono
Advanced Computing Research Lab
20 Godfrey Dr
Orono, ME 04473
www.clusters.umaine.edu
Mathematics Department
425 Neville Hall
Orono, ME 04469


</pre>
<p>
WARNING: The virus scanner was unable to scan the next
<br>
attachment.  This attachment could possibly contain viruses
<br>
or other malicious programs.  The attachment could not be
<br>
scanned for the following reasons:
<br>
<p>The file was corrupt
<br>
<p>You are advised NOT to open this attachment unless you are
<br>
completely sure of its contents.  If in doubt, please
<br>
contact your system administrator.  
<br>
<p>The identifier for this message is 'k4SEmG3W018957'.
<br>
<p>The Management
<br>
PureMessage Admin &lt;sysadm_at_[hidden]&gt;
<br>
<p>
<br><p>
<p><hr>
<ul>
<li>application/gzip attachment: <a href="http://www.open-mpi.org/community/lists/users/att-1321/config.log.tar.gz">config.log.tar.gz</a>
</ul>
<!-- attachment="config.log.tar.gz" -->
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="1322.php">Francoise Roch: "[OMPI users] openmpi-1.1a7  on solaris10 opteron"</a>
<li><strong>Previous message:</strong> <a href="1320.php">Brian Barrett: "Re: [OMPI users] OpenMPI 1.0.3a1r10002 Fails to build with IBM XL Compilers."</a>
<li><strong>In reply to:</strong> <a href="1320.php">Brian Barrett: "Re: [OMPI users] OpenMPI 1.0.3a1r10002 Fails to build with IBM XL Compilers."</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="1331.php">Brian Barrett: "Re: [OMPI users] [PMX:VIRUS] Re: OpenMPI 1.0.3a1r10002 Fails to build with IBM XL Compilers."</a>
<li><strong>Reply:</strong> <a href="1331.php">Brian Barrett: "Re: [OMPI users] [PMX:VIRUS] Re: OpenMPI 1.0.3a1r10002 Fails to build with IBM XL Compilers."</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
