<? include("../../include/msg-header.inc"); ?>
<!-- received="Tue May 30 23:08:55 2006" -->
<!-- isoreceived="20060531030855" -->
<!-- sent="Tue, 30 May 2006 21:08:28 -0600" -->
<!-- isosent="20060531030828" -->
<!-- name="Brian Barrett" -->
<!-- email="brbarret_at_[hidden]" -->
<!-- subject="Re: [OMPI users] [PMX:VIRUS] Re: OpenMPI 1.0.3a1r10002 Fails to build with IBM XL Compilers." -->
<!-- id="1DE03290-009F-48C9-8344-C495EAFC5ED5_at_open-mpi.org" -->
<!-- charset="US-ASCII" -->
<!-- inreplyto="4479B832.7060700_at_gmail.com" -->
<!-- expires="-1" -->
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<p class="headers">
<strong>From:</strong> Brian Barrett (<em>brbarret_at_[hidden]</em>)<br>
<strong>Date:</strong> 2006-05-30 23:08:28
</p>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="1332.php">Brian Barrett: "Re: [OMPI users] Thread Safety"</a>
<li><strong>Previous message:</strong> <a href="1330.php">Brian Barrett: "Re: [OMPI users] Open MPI 1.0.2 and np &gt;=64"</a>
<li><strong>In reply to:</strong> <a href="1321.php">Justin Bronder: "[OMPI users] [PMX:VIRUS] Re: OpenMPI 1.0.3a1r10002 Fails to build with IBM XL Compilers."</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="1335.php">Justin Bronder: "Re: [OMPI users] [PMX:VIRUS] Re: OpenMPI 1.0.3a1r10002 Fails to build with IBM XL Compilers."</a>
<li><strong>Reply:</strong> <a href="1335.php">Justin Bronder: "Re: [OMPI users] [PMX:VIRUS] Re: OpenMPI 1.0.3a1r10002 Fails to build with IBM XL Compilers."</a>
<!-- reply="end" -->
</ul>
<hr>
<!-- body="start" -->
<p>
On May 28, 2006, at 8:48 AM, Justin Bronder wrote:
<br>
<p><span class="quotelev1">&gt; Brian Barrett wrote:
</span><br>
<span class="quotelev2">&gt;&gt; On May 27, 2006, at 10:01 AM, Justin Bronder wrote:
</span><br>
<span class="quotelev2">&gt;&gt;
</span><br>
<span class="quotelev2">&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; I've attached the required logs.  Essentially the problem seems to
</span><br>
<span class="quotelev3">&gt;&gt;&gt; be that the XL Compilers fail to recognize &quot;__asm__ __volatile__&quot; in
</span><br>
<span class="quotelev3">&gt;&gt;&gt; opal/include/sys/powerpc/atomic.h when building 64-bit.
</span><br>
<span class="quotelev3">&gt;&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; I've tried using various xlc wrappers such as gxlc and xlc_r to
</span><br>
<span class="quotelev3">&gt;&gt;&gt; no avail.  The current log uses xlc_r_64 which is just a one line
</span><br>
<span class="quotelev3">&gt;&gt;&gt; shell script forcing the -q64 option.
</span><br>
<span class="quotelev3">&gt;&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; The same works flawlessly with gcc-4.1.0.  I'm using the nightly
</span><br>
<span class="quotelev3">&gt;&gt;&gt; build in order to link with Torque's new shared libraries.
</span><br>
<span class="quotelev3">&gt;&gt;&gt;
</span><br>
<span class="quotelev3">&gt;&gt;&gt; Any help would be greatly appreciated.  For reference here are
</span><br>
<span class="quotelev3">&gt;&gt;&gt; a few other things that may provide more information.
</span><br>
<span class="quotelev3">&gt;&gt;&gt;
</span><br>
<span class="quotelev2">&gt;&gt;
</span><br>
<span class="quotelev2">&gt;&gt; Can you send the config.log file generated by configure?  What else
</span><br>
<span class="quotelev2">&gt;&gt; is in the xlc_r_64 shell script, other than the -q64 option?
</span><br>
<p><span class="quotelev1">&gt; I've attached the config.log, and here's what all of the *_64 scripts
</span><br>
<span class="quotelev1">&gt; look like.
</span><br>
<p>Can you try compiling without the -qkeyword=__volatile__?  It looks  
<br>
like XLC now has some support for GCC-style inline assembly, but it  
<br>
doesn't seem to be working in this case.  If that doesn't work, try  
<br>
setting CFLAGS and CXXFLAGS to include -qnokeyword=asm, which should  
<br>
disable GCC inline assembly entirely.  I don't have access to a linux  
<br>
cluster with the XL compilers, so I can't verify this.  But it should  
<br>
work.
<br>
<p>Brian
<br>
<p><p><pre>
-- 
   Brian Barrett
   Open MPI developer
   <a href="http://www.open-mpi.org/">http://www.open-mpi.org/</a>
</pre>
<!-- body="end" -->
<hr>
<ul class="links">
<!-- next="start" -->
<li><strong>Next message:</strong> <a href="1332.php">Brian Barrett: "Re: [OMPI users] Thread Safety"</a>
<li><strong>Previous message:</strong> <a href="1330.php">Brian Barrett: "Re: [OMPI users] Open MPI 1.0.2 and np &gt;=64"</a>
<li><strong>In reply to:</strong> <a href="1321.php">Justin Bronder: "[OMPI users] [PMX:VIRUS] Re: OpenMPI 1.0.3a1r10002 Fails to build with IBM XL Compilers."</a>
<!-- nextthread="start" -->
<li><strong>Next in thread:</strong> <a href="1335.php">Justin Bronder: "Re: [OMPI users] [PMX:VIRUS] Re: OpenMPI 1.0.3a1r10002 Fails to build with IBM XL Compilers."</a>
<li><strong>Reply:</strong> <a href="1335.php">Justin Bronder: "Re: [OMPI users] [PMX:VIRUS] Re: OpenMPI 1.0.3a1r10002 Fails to build with IBM XL Compilers."</a>
<!-- reply="end" -->
</ul>
<div class="center">
<table border="2" width="100%" class="links">
<tr>
<th><a href="date.php">Date view</a></th>
<th><a href="index.php">Thread view</a></th>
<th><a href="subject.php">Subject view</a></th>
<th><a href="author.php">Author view</a></th>
</tr>
</table>
</div>
<!-- trailer="footer" -->
<? include("../../include/msg-footer.inc") ?>
